### ISSUE TITLE
Consider `overlay-put` instead of `message`

### ISSUE THREAD

**Issue by protesilaos** [oantolin/embark#1]
Thank you @oantolin for making this package!

I think in terms of usability, it would be nice to have the feedback of `(message "Act on %s %s" kind embark--target)` as an overlay (which could be less verbose—perhaps as an option).

What I have in mind is the way recursive minibuffers show their depth level when `minibuffer-depth-indicate-mode` is enabled.  This offers you the chance to put the feedback outside the area of the minibuffer's input, which can make it feel less cluttered (especially if the indicator is just "Act"—again, if there is an option for that).

I believe this is the relevant code from `mb-depth.el`:

```elisp
(defun minibuffer-depth-setup ()
  "Set up a minibuffer for `minibuffer-depth-indicate-mode'.
The prompt should already have been inserted."
  (let ((depth (minibuffer-depth)))
    (when (> depth 1)
      (let ((pos (point-min)))
        (setq minibuffer-depth-overlay (make-overlay pos (1+ pos))))
      (overlay-put minibuffer-depth-overlay 'before-string
                   (if minibuffer-depth-indicator-function
                       (funcall minibuffer-depth-indicator-function depth)
                     (propertize (format "[%d]" depth) 'face 'highlight)))
      (overlay-put minibuffer-depth-overlay 'evaporate t))))
```

**Comment by oantolin** [comment]
Good idea! Will do.

**Comment by oantolin** [comment]
Done! I just put "<ACT>" at the beginning of the prompt, because I now think my previous message was way too long. Particularly with file names the prompt+entered text can be long enough to almost fill a line.

I put "<ACT>" at the beginning to cover up the depth indicator, in case people use it. Although the action literally takes place in a recursive minibuffer, I want it to feel like a "special minibuffer mode" instead.

Do you think "<ACT>" is OK? Would you suggest something else? Does it need to be configurable? (I feel a single short string is probable enough.)

**Comment by protesilaos** [comment]
Yes, this looks better!  If you ever feel like `propertize` is needed, a reasonable default is either `bold` or `highlight` (though it is fine right now).  The depth indicator uses the latter.

Regarding the customisation of the string: personally I would use "Act" anyway.  An option for this may not be needed.  Perhaps you could review it at a later point.

**Comment by oantolin** [comment]
I think I'd like to pick a single string and only make this configurable later on if someone requests it. So let's pick a string! When you say:

>  personally I would use "Act" anyway

do you mean you'd prefer that capitalization? The string is currently `<ACT>`. Are you proposing `<Act>` (or maybe `Act`) instead?

**Comment by protesilaos** [comment]
I think that if you use `propertize`, you should go with `Act` because you then benefit from the face attributes: there is no need to overdo it with the elements of differentiation/emphasis.

Otherwise keep it `<ACT>`: it already feels different from the minibuffer prompt.

I am fine either way.  For me the "act" (capitalisation-agnostic) overlay is good because it is concise and captures the essence of this tool, compared with the original wordy `message`.

**Comment by oantolin** [comment]
I decided to with propertized "Act" and I used highlight, to empasize this is a particular sort of recursive minibuffer. It looks more ... dignified? than `<ACT>`. (Although `<ACT>` would look cool on an old black and green CRT display.)

**Comment by protesilaos** [comment]
Thanks!
