### ISSUE TITLE
embark-act in normal buffer window only uses embark-general-map

### ISSUE THREAD

**Issue by bsag** [oantolin/embark#100]
First, thanks so much for Embark - I'm really getting into it!

With the recent changes, I've found that invoking `embark-act` in a file (whether on a symbol, url, region or whatever) only offers the actions for `embark-general-map`, not the relevant symbol, url or region versions of the map.

Using `embark-act` in the minibuffer offers the correct actions when I'm viewing files, buffers or bookmarks.

If it helps, I'm using selectrum, prescient, marginalia, consult and embark together within Doom Emacs (all the latest versions from MELPA at the time of this issue).

Here's my embark config (partially copied from recent examples here to get up to date integration with selectrum):

```elisp
(use-package! embark
  :after selectrum
  :bind (:map minibuffer-local-map
         ("C-o" . embark-act)
         ("C-S-o" . embark-act-noexit)
         :map embark-file-map
         ("j" . dired-jump)
         :map embark-buffer-map
         ("j" . dired-jump))
  :config
  (unbind-key "C-h" embark-meta-map)
  (add-to-list 'which-key-replacement-alist '((nil . "embark-") . (nil . "e-")))
  (add-hook 'embark-target-finders
            (defun selectrum-current-candidate+category ()
              (cons (selectrum--get-meta 'category)
                    (selectrum-get-current-candidate))))

  (add-hook 'embark-candidate-collectors
            (defun selectrum-current-candidates+category ()
              (when selectrum-active-p
                (cons (selectrum--get-meta 'category)
                      (selectrum-get-current-candidates
                       ;; Pass relative file names for dired.
                       minibuffer-completing-file-name)))))
  (add-hook 'embark-setup-hook 'selectrum-set-selected-candidate)
  (setq embark-action-indicator
        (lambda (map) (which-key--show-keymap "Embark" map nil nil 'no-paging)
          #'which-key--hide-popup-ignore-command)
        embark-become-indicator embark-action-indicator))
```

I also bind `embark-act` outside this to `s-.` for use outside the minibuffer, but I get the same results described here whether I use the binding or call it via `M-x embark-act`.

Thanks in advance for any help!

**Comment by oantolin** [comment]
I think the problem is just that you are missing a `(when selectrum-active-p` in the function you add to `embark-target-finders`. (You do have it in the other function.) Add it and see if that fixes the problem.

**Comment by bsag** [comment]
@oantolin Bingo! That worked perfectly. I'm embarrassed I didn't spot that - thanks for picking it up!
