### ISSUE TITLE
embark-act for buffers open in two windows

### ISSUE THREAD

**Issue by Vanarill** [oantolin/embark#102]
Dear developers,

While playing around with my display-buffer settings, I noticed some strange behaviour by embark-act when a certain buffer is open in two windows.

I am using embark of this commit:
`5332cbffb4f0409fd2f613bf75f670c295260e08`
and emacs version:
`;; (emacs-version t) GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0)
`

### Steps to reproduce:

Launch emacs:
`emacs -q
`

Switch to the scratch buffer.

Evaluate:
```
(require 'embark)
(define-key minibuffer-local-map (kbd "C-o") 'embark-act) ;; or any other key
```

Execute the following commands:
```
split-window-horizontally
other-window
```
Move the cursor to another location in the newly-focused window (the right one).

Use an embark-act action like insert:
`C-h f thing-at-point C-o i
`
(`thing-at point` is only there by example, for illustration)

You will then notice that the symbol is not inserted at the current cursor position, but at the cursor's position in the first window (the left one). (The same happens when one uses Selectrum.) 

This is not something of importance to me, as I almost never have the same buffer open in multiple windows, but I hope this bug report can be of some assistance and perhaps prevent future issues.

**Comment by oantolin** [comment]
Looks like I do need to save the target-window in addition to the target-buffer, and use the window if it is still live and still displays the target-buffer.

**Comment by minad** [comment]
Saving all the windows...

**Comment by oantolin** [comment]
Just so I don't forget: once I fix this I should update the embark-consult-preview stuff to use it.

**Comment by oantolin** [comment]
OK, @Vanarill, I'm now storing the target-window so that as long as it is still good (i.e., still live and still showing the target buffer), the same window is always used. In particular, since it starts out as being the selected window, the example you showed  now uses the correct window.
