### ISSUE TITLE
Extend support for next-error on exported/collected buffers

### ISSUE THREAD

**Issue by kljohann** [oantolin/embark#103]
It's very convenient when `next-error-last-buffer` is set (e.g. for `grep-mode` buffers) so that I can use `previous-error` / `next-error` from both within the grep buffer but also from a different buffer to jump to the previous/next match.

Do you think it would make sense to add similar support to `embark-collect-mode` in general? For example if I `embark-export`ed the results of `consult-line`, I could invoke `next-error` to display the `*Embark Collect*` buffer, move point to the next match and invoke the default action. (For obvious reasons this is already working for things that are exported to a `grep-mode` buffer, like `consult-git-grep`.)

I think it would have to be optional in order not to e.g. clobber up the `{previous,next}-error` action after exporting from `M-x`. Now that I am writing this up, maybe it's enough to use `embark-export-grep` for more completion types in `embark-exporters-alist` in my local configuration¹. But maybe a function similar to `{previous,next}-error` (but specific to embark, acting on the last collected buffer) would be useful in general?

¹: Well, at least `(consult-location . embark-export-grep)` does not work out of the box.

**Comment by oantolin** [comment]
Using next-error to run the default action is an interesting idea!

As for consult-location, yesterday an exporter to occur-mode was added. I didn't test but assumed that would support next-error automatically, as Exporting to grep-mode does.

**Comment by minad** [comment]
I think the idea is to only jump to the next line with next-error, not invoke the default action? I think next-error should not do special operations besides jumping.

**Comment by oantolin** [comment]
I thought @kljohann was proposing the default action behavior of next-error for collect buffers (what would "jumping" even mean in a general collect buffer?).

Then @kljohann also says that maybe instead it's enough to get export working in more cases where you want the traditional next-error behavior, which is why I mentioned the changes we made yesterday for the `consult-location` category.

**Comment by oantolin** [comment]
Oh, `next-error` doesn't seem to work in the occur mode buffer produced by exporting `consult-location` candidates.

**Comment by minad** [comment]
Oh, yes you are right! It will probably work well. Better than having a collect follow mode!

**Comment by oantolin** [comment]
The reason next-error isn't working in the exported occur-mode buffers is that I was supposed to put the `occur-match` property on the part of the string that is "a match". I guess I can just put it on the entire line.

Ideally for `consult-mark` and `consult-global-mark`, just the char at the mark should be considered the match.

And for `consult-line` it should something like "whatever the completion style highlights".

For `consult-outline` probably the entire line is fine.

**Comment by minad** [comment]
I think consult-mark and consult-global-mark are more "special cases" and not as widely used, my suggestion for those would also to use the entire line. Otherwise we would have to add some offset to the consult-location metadata or add one more marker for the line beginning.

In consult I am computing the position of the first matches using the completion style as you proposed. consult-outline and consult-line both use that when performing the jump.

**Comment by oantolin** [comment]
> I think consult-mark and consult-global-mark are more "special cases" and not as widely used, my suggestion for those would be to use the entire line. Otherwise we would have to add some offset to the consult-location metadata or add one more marker for the line beginning.

OK.

> In consult I am computing the position of the first matches using the completion style as you proposed. consult-outline and consult-line both use that when performing the jump.

But you do that lazily, right? At the time of the jump? I don't think you want to do it upfront for all candidates. I say we leave it at "entire line" for every case. I did that in this commit: 57961d0117f0e00e84861dc2daa816655f9a4503

**Comment by minad** [comment]
Yes, I just do it only when "looking up" the candidate (see :lookup of consult--read). This is called when doing preview or in the end when computing the result which should be returned by consult--read. My proposal would also be to just leave it on the whole line, at least for now!

**Comment by kljohann** [comment]
Indeed 974b4b2 from a functional point already achieves what I had in mind, thanks! :+1:

>  I thought @kljohann was proposing the default action behavior of next-error for collect buffers (what would "jumping" even mean in a general collect buffer?).

Exactly, I think `{previous,next}-error` should only ever be connected to "jumping" actions, so making them work for "occur"-style buffers should be enough. A separate but similar set of functions *might* be useful for exported "buffer" or "file" match sets (i.e. jump to next matching buffer/file), but that would probably be extra effort and I personally don't need it.

**Comment by oantolin** [comment]
Well, if the `{next,previous}-error` support for exported occur-mode buffers scratches your itch, and you think using those commands for actions that don't really feel like jumping to a location would be overstepping their purpose (@minad seems to agree and I think I do too), I propose we close this issue.

**Comment by kljohann** [comment]
Sure, thanks for the change. I guess it would be easy enough to make this configurable in the future if it's too intrusive for other users. But then again `next-error-last-buffer` is only set to the embark buffer after the first use of `{next,previous}-error` from that buffer, so it's probably fine.
