### ISSUE TITLE
Rename embark-consult-preview package

### ISSUE THREAD

**Issue by minad** [oantolin/embark#105]
I propose to rename embark-consult-preview to embark-consult and to move all the consult specifics to this package. For example the consult-location keymaps and consult-buffer keymaps. This would be cleaner and things would be better separated! The other option is to not go with a separate package, but since you already consider the preview worth its own package I would rather move the rest there too!

**Comment by oantolin** [comment]
I was thinking about that, but wasn't sure. How about renaming now, but waiting to move stuff out of Embark until this new package is on Melpa?

**Comment by minad** [comment]
That's a good idea! But I assume the package will get quickly into melpa if you ping one of the MELPA maintainers, since this is just a spin-off from the main embark package.

**Comment by oantolin** [comment]
I just realized I should add all the consult-specific code to `consult-embark`, there's no need to wait for that, I should only wait to delete it from embark.

**Comment by minad** [comment]
It seems there is already the embark-consult package on MELPA?

**Comment by oantolin** [comment]
Yes, it was approved (what in my time zone was) last night.

**Comment by oantolin** [comment]
I moved everything related to consult out of embark now.
