### ISSUE TITLE
embark-consult. el is basically undocumented

### ISSUE THREAD

**Issue by holgerschurig** [oantolin/embark#106]
Hi, as title says.

I've looked in the README.org, in the embark.texi. And while the file itself has a comment saying

> For now, it only provides access to Consult preview from
> auto-updating Embark Collect buffer that is associated to an active
> minibuffer for a Consult command

... I don't have the slightest idea what this means actually (e.g. for which workflow it is needed).

**Comment by minad** [comment]
This package is still in the making and will function as an integration package between consult and embark. Documentation will come. It will contain actions specific to consult commands (for example commands which set the consult-location completion category, like consult-line, consult-outline, consult-mark, consult-global-mark). Furthermore it contains support to trigger the Consult preview from the Embark collect buffers. Usually the Consult preview works automatically if triggered from the minibuffer if you are using default-completion, Icomplete or Selectrum. But it won't work if you scroll through the items in the Embark collect buffer, so this missing functionality is added here too.

**Comment by oantolin** [comment]
What @minad said. I wanted this on Melpa before removing anything from Embark, so as to not inconvenience Melpa users of Embark. That's why it's so preliminary.

For now, if you want a quick taste of the preview support, install Consult, run `consult-line`, when you've typed a little bit, run `embark-collect-live`, switch to the collect buffer and activate `embark-consult-preview-minor-mode`, then move around the collect buffer.

I like it so much I use `(add-hook 'embark-collect-mode-hook #'embark-consult-preview-minor-mode)` in my configuration.

**Comment by oantolin** [comment]
The consult stuff that was previously in embark has now been moved to embark-consult, and I added a bit more to the commentary.

**Comment by oantolin** [comment]
Is it better now, @holgerschurig? The consult preview functionality is described assuming you already know what consult previews are and what embark collect does. Maybe I could add pointers to the documentation of Consult and Embark.

**Comment by oantolin** [comment]
This problem has gotten much worse. I definitely need to write a README section specifically about embark-consult. It's on the TODO list. At least almost all of the behavior is DWIM, so I expect people to just feel better without knowing exactly why. 😆

**Comment by minad** [comment]
Well, I don't think there is much to be said about embark-consult. It is an integration package, you should install it if you want to use both embark and consult. It provides consult specific actions and importers.

**Comment by oantolin** [comment]
> It provides consult specific actions and exporters.

And a bunch of behavioral tweaks for consult commands when used as actions. I think it is worth documenting. The documentation would be short.

**Comment by minad** [comment]
Can this be closed thanks to https://github.com/oantolin/embark/issues/328?

**Comment by oantolin** [comment]
I think so. Maybe let's leave it open a bit to motivate me to update the package commentary. 😉

**Comment by minad** [comment]
@oantolin It seems to be okay to close this one, since it hasn't been updated for a long time.

**Comment by hmelman** [comment]
> I think experience has shown embark-consult is just intuitive integration that works as you'd expect. The mentions of the grep and occur export in Embark's main documentation seem to be all that really needs saying about embark-consult.

I agree, though I have one suggestion.  The embark README does make it clear that if you use consult you probably want to install embark-consult and how to do that with a good example.  But I think the section "Embark, Marginalia and Consult" should specifically mention or point to installing embark-consult to enable the described integration in case a reader just jumps directly to that section.

**Comment by oantolin** [comment]
I've revamped the Marginalia and Consult section of the manual so now `embark-consult` is much more documented (albeit in the Embark manual, not a manual of its own, but I think that's probably fine) and I explciitly say "If you use both Consult and Embark you should absolutely install the embark-consult" in the Consult section as @hmelman suggested.
