### ISSUE TITLE
Autoloading of embark-consult

### ISSUE THREAD

**Issue by minad** [oantolin/embark#108]
How do you intend to do this? What works? There are some autoload declarations but there are also these add-to-lists.

~~~ elisp
(with-eval-after-load 'consult
  (with-eval-after-load 'embark
    (require 'embark-consult)))
~~~

**Comment by oantolin** [comment]
Yeah I need to think about this. Maybe I'll put autoloads on all the functions added to lists, and on the code that adds them.

**Comment by oantolin** [comment]
Did this: 501fff203ebecc04025c4d475112de4214714a6d Not sure if that's the best approach.

**Comment by minad** [comment]
I don't think this will work since the lists are not yet available. You should autoload the variable definitions in embark.el too. But this is all very messy and I am not sure if it will work because of the order.

Probably it is better to remove any autoload stuff here and document that the package has to be used with use-package :after (embark consult)?

**Comment by oantolin** [comment]
The variable definitions in embark are OK, because in normal usage you always run some embark command first.

I think that if I wrap the code in embark-consult that adds values to embark lists in an `(with-eval-after-load 'embark ...)`, and autoload that it should be fine, no?

**Comment by oantolin** [comment]
I think I covered all the entry points now. 59133b3ab214a5e01e90c57abc3d5639de797fb6

I might still remove the autoload and just tell people to load it. 😄

**Comment by purcell** [comment]
Hmm, this is still broken. I pushed code to my unreasonably popular config repo to switch it to embark etc., only to find that startup now fails. Removing the autoload and telling people to load it sounds like a good plan.

I force-rebuilt the MELPA packages just to be sure.

**Comment by purcell** [comment]
Wait, no, hang on - I *think* it's okay. I still get failures in some of the Emacs versions, but can't quite see why. https://github.com/purcell/emacs.d/runs/1693597917

**Comment by minad** [comment]
@oantolin Is the autoloading of the keymap okay? Will this macro be expanded early? I don't like that you have autoloads everywhere. This seems brittle.

I would either use this:

~~~ elisp
(with-eval-after-load 'consult
  (with-eval-after-load 'embark
    (require 'embark-consult)))
~~~

Or this:

~~~ elisp
(use-package embark-consult
   :after (embark consult))
~~~

(Just to make sure, the use-package declaration I wrote ensures that embark-consult is lazily loaded after embark and consult, right?)

**Comment by oantolin** [comment]
@purcell I'm a litte surprised by the error, but my strategy definitely does not work in my setup either. If my first attempted use of embark-consult is running an action from consult-line, things don't get loaded in time.

> Removing the autoload and telling people to load it sounds like a good plan.

I'm going to do this.

**Comment by oantolin** [comment]
I think you are right, @minad. Both forms (the one using with-eval-after-load and the use-package declaration) are equivalent and do arrange for embark-consult to loaded once embark and consult are loaded. I'd going to recommend the use-package call in the readme.

**Comment by oantolin** [comment]
OK, I removed the autoloads and mentioned in a few places that users should arrange for the package to be loaded after consult and embark.

**Comment by minad** [comment]
Good! In this case I think this is the better strategy - we don't need fancy automatic autoloading in this case. I hope there won't be too many problems because of the integration package. But I suspect it will be a bit different in contrast to consult-selectrum/embark-selectrum/embark-ivy, since these immediately affect everyone who just wants to try out the packages quickly. In contrast, people who are looking for the whole thing and need embark-consult, are probably already more experienced and familiar with the packages.

**Comment by oantolin** [comment]
@purcell I just wanted to let you know I've removed all the autoloads and documented that users should arrange for the library to be loaded after consult and embark.

**Comment by purcell** [comment]
Awesome. I just have to say here that I am totally delighted with the consult + embark experience so far. Once I knew that I could replace the counsel-rg -> ivy-occur -> wgrep workflow I often used before, I was sold. So thanks to you, @minad and others for all your work on these libraries!

**Comment by minad** [comment]
Thank you, Steve! We are ourselves excited to see how well things fell into place. If you have useful suggestions or find any issues we are always eager to hear about it! We recently managed to get the consult-line -> occur-mode -> occur-edit-mode export working, it is like the small child of the consult-rg -> grep-mode -> wgrep workflow ;)

**Comment by oantolin** [comment]
That means a lot coming from you, @purcell, thank you! And let me just echo @minad in saying I'd love to hear any suggestions you might have.

**Comment by purcell** [comment]
Ooh, nice, I'll have to try that out too. I'm switching my config over, which is probably a little risky at this stage of development when things are still taking shape, but it should lead to many more users and feedback. :-)

**Comment by oantolin** [comment]
While the occur-mode export is certainly most useful with consult-line, it also works with consult-global-mark, and I think that has potential too! I can imagine putting marks in several buffers, and then editing them all at once.

**Comment by minad** [comment]
> Ooh, nice, I'll have to try that out too. I'm switching my config over, which is probably a little risky at this stage of development when things are still taking shape, but it should lead to many more users and feedback. :-)

Looking forward to it! From my perspective the current development status regarding the packages is as follows:

* Marginalia: Limited in scope, mostly done and very solid. Maybe more annotators will be added in the future, but I do not expect big changes. (One issue maybe, Emacs 28 introduces affixation functions, this is still a bit problematic)
* Consult: Basic functionality is solid. Maybe more commands will come in the future, but I hope that we are not blowing it up too much. There are not that many things on the wishlist. Maybe rough edges are expected around the more advanced features like async and preview, in particular since these feature need a bit of special casing for Selectrum and Icomplete, in the respective consult-selectrum/icomplete.el files.
* Embark: @oantolin put a lot of great work recently in this package and made some larger refactorings (live-collect/collect/completions buffer). But I feel the overall architecture has stabilized.
* Embark-Consult integration: @oantolin  recently sorted out many things, regarding grep-mode-export and occur-mode-export, but I think we got the basics alright now.
* Selectrum: From what I see this package already has some user base and is also pretty solid. Here I am expecting a few changes in the future, since the idea is that Selectrum will move closer to completing-read, putting less focus on its own API, maybe even renaming selectrum-read to selectrum--read in the end (cc @clemera).
* Orderless/Prescient: @purcell are you planning to use one of these? I am personally leaning to Orderless but both should work reasonably well.

I am sure, @oantolin and @clemera will also give you their perspective!

**Comment by purcell** [comment]
Thanks, that's a really helpful summary.

>     * Orderless/Prescient: @purcell are you planning to use one of these?

Both, I think. Perhaps I'm doing something wrong, but I cargo-culted some config that used orderless for completion-styles alongside prescient. The relevant chunk of my config is here: https://github.com/purcell/emacs.d/blob/master/lisp/init-selectrum.el

**Comment by minad** [comment]
> Both, I think. Perhaps I'm doing something wrong, but I cargo-culted some config that used orderless for completion-styles alongside prescient.

@clemera is using this combination. From what I've heard, it works well. Personally, I would love to see a downstripped Prescient which only focuses on the sorting and the persistence aspect, such that Prescient and Orderless don't compete against each other regarding the filtering.

> The relevant chunk of my config is here: https://github.com/purcell/emacs.d/blob/master/lisp/init-selectrum.el

I can take a look and give you a quick review over there.

**Comment by oantolin** [comment]
@clemera will be able to confirm, but I'm pretty sure that configuration will not actually use orderless for anything. (Well, if you turned off selectrum-mode you'd get orderless until you turned selectrum-mode back on.) The `selectrum-prescient-mode` will use prescient for both filtering and sorting.

It is possible to use orderless for filtering and prescient just for sorting, but I don't know the best way to set that up. I believe that setting this *after* turning on `selectrum-prescient-mode` would let you use orderless for filtering:

```elisp
(setq selectrum-refine-candidates-function #'orderless-filter)
(setq selectrum-highlight-candidates-function #'orderless-highlight-matches)
```
--------
On a different topic: what is this for? It looks a little funny.

```elisp
(global-set-key [remap execute-extended-command] nil)
(global-set-key [remap execute-extended-command] 'execute-extended-command)
```

**Comment by purcell** [comment]
Awesome, thanks! I probably don't really need orderless tbh, so don't worry about digging up more info for me.

Re. the rebinding stuff, for some reason I encountered an issue and unbinding the key fixed it. It could have been an issue with double-remapping given that I was switching from counsel etc., so there's a good chance I can drop that line now.

**Comment by minad** [comment]
> Awesome, thanks! I probably don't really need orderless tbh, so don't worry about digging up more info for me.

Yes, that's probably the cleaner solution. Use either orderless or prescient depending on your preference.

**Comment by oantolin** [comment]
> Awesome, thanks! I probably don't really need orderless tbh, so don't worry about digging up more info for me.

I think that if you are going to stick to default configurations, there is no strong reason to prefer orderless over prescient's filtering. Orderless becomes attractive when you use its style dispatchers to make up your own "query syntax".

**Comment by clemera** [comment]
@purcell Note that orderless filtering is much faster as it uses C functions for that. Prescient filtering is also nice and fast enough but still something you might want to know about.

**Comment by clemera** [comment]
@purcell To add some more perspective about Selectrum, there are still UI problems that need to get fixed and there are also some breaking changes ahead, as @minad mentioned `selectrum-read` will become a private function. I would have recommended to wait for the next stable release but it seems that ship has [sailed already](https://github.com/purcell/emacs.d/pull/766) ;)

**Comment by minad** [comment]
@clemera From my experience, the way you are already working on Selectrum keeps things pretty stable. There is not much breakage happening. I think you could just tag a release at any time. Maybe make it 3.1, 3.2, ... etc. And then 4.0 when you make selectrum-read private?

**Comment by clemera** [comment]
@minad Thanks, I plan to do that probably next week.

**Comment by purcell** [comment]
> I would have recommended to wait for the next stable release but it seems that ship has [sailed already](https://github.com/purcell/emacs.d/pull/766) ;)

Yeah, I'm keeping my config pretty minimal to avoid breakage, but I'm okay risking it. :-)
