### ISSUE TITLE
Want embark collect buffer selected after embark-collect-snapshot

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#109]
I have a single window in a frame.  I ran consult-line and used embark-act to do embark-collect-snapshot.  I had two windows with the bottom one having the embark-collect buffer, but the top (first) window was selected.  I'd like a way to have the embark-collect buffer selected automatically.  If not made the default behavior, maybe a user option, or describe how I could do this in a hook.

**Comment by oantolin** [comment]
You used embark-act, but embark-collect-snapshot can also be run directly or from embark-act-noexit, and we should pick a behavior that makes sense in all cases. Would it be reasonable that if you run embark-collect-snapshot in a non-exiting way, it's window is not immediately selected, but does get selected once you exit the minibuffer?

**Comment by oantolin** [comment]
After testing it, I think I like that behavior, specially for live collect buffers. ISo 'll select the windows once the minibuffer closes (but not before in the non-exiting case). And if someone doesn't like it, they can file an issue and we can discuss it then. d3219afbfc49f982f4193a69baa6e8733196dd0f

**Comment by hmelman** [comment]
Works for me.
