### ISSUE TITLE
Exit minibuffer and run command on target afterwards

### ISSUE THREAD

**Issue by clemera** [oantolin/embark#11]
`embark` executes actions before exiting the minibuffer. This has some downsides for example when I call `embark-describe-symbol` and exit the minibuffer afterwards the info page goes away because the recursive edit exits. Many times I want to execute an action like an exit command, that means exit the minibuffer and call the action with the previously selected target. One way to achieve this within the constraints of the minibuffer API is to write commands like this:

```elisp
(defun embark-info-emacs-command ()
  (interactive)
  (let ((node (embark-target)))
    (run-at-time 0 nil
                 (lambda ()
                   (Info-goto-emacs-command-node node))))
  (abort-recursive-edit))
```
I think this is useful enough to generalize it somehow in a command like `embark-exit-and-act` command. 

My current "vision" would be to keep the current behaviour via `embark-act` but
when called from `embark-exit-and-act` behave like the version above passing `embark-target` as the target argument (so it automatically works with `find-file-other-window` and such). So commands called from this new `embark-exit-and-act` command would have the requirement to accept the target as first argument.

What do you think?

**Comment by oantolin** [comment]
You are [not alone](https://github.com/oantolin/embark/issues/8#issuecomment-631247270)!

I had an implementation attempt already that basically never worked, so I took it out (e43b820).

I do want to add something like this, but haven't figured out the right way to do it yet. Thanks for the `run-at-time 0 nil` trick, I hadn't considered using something like that.

**Comment by oantolin** [comment]
OK! I think I managed to do it, your `run-at-time 0 nil` trick was invaluable, thanks! b6f552e

I had tried several other ways prior, some of which may actually work but were too complicated for me to get the details right. Lots of churn in the local repo, clean history here. ;)

In the end, I think `embark-exit-and-act` is more accurate than `embark-act-and-exit`, so I went with your original proposed name.

Please test! @karthink wanted this too, and @protesilaos has some custom commands that might be replaced by this.

**Comment by oantolin** [comment]
Oh, one other thing: `embark-act-and-exit` currently exits to top level. Should it exit just one minibuffer instead? Do we want both versions?

**Comment by karthink** [comment]
`embark-exit-and-act` works well. Do you have a use case for when it pops the minibuffer recursion stack instead of going to top-level?

Also, this is a suggestion, so feel free to ignore it: It takes a bit of customization to set `embark-ratify` on individual commands. On the other hand, a global switch `(defcustom embark-ratify-all)` isn't a good solution either since some actions (shell commands etc) always require input. Is there some way to design this better perhaps?

**Comment by karthink** [comment]
Maybe a list `embark-ratify-commands` that the user can add to? It essentially removes a `dolist` from the user's config adding the ratify property.

**Comment by oantolin** [comment]
> embark-exit-and-act works well.

Excellent. I'll wait to hear from @clemera and close this issue.

> Do you have a use case for when it pops the minibuffer recursion stack instead of going to top-level? My use pattern is to go to top-level almost always so my imagination is limited.

Same here. I'm happy with just top-level.

> Also, this is a suggestion, so feel free to ignore it: It takes a bit of customization to set embark-ratify on individual commands. On the other hand, a global switch (defcustom embark-ratify-all) isn't a good solution either since some actions (shell commands etc) always require input. Is there some way to design this better perhaps? Maybe a list embark-ratify-commands that the user can add to? It essentially removes a dolist from the user's config adding the ratify property.

There is an `embark-setup-hook` that applies to all commands that don't have a `embark-setup` property of their own (I renamed the cutesy `disembark`, and made the global hook "public", i.e., renamed it without double hyphen).

So if you want only a few commands ratified, you can leave `embark-setup-hook` at its default value of `nil` and set the `embark-setup` property to `embark-ratify` on the commands you want ratified.

If on the other hand you want almost all commands ratified, set `embark-setup-hook` to `embark-ratify` and then set the `embark-setup` property only on the commands you do not want ratified. Note that:

- `shell-command` and `async-shell-command` already have `embark-setup` properties (to insert a space before the filename and leave point at the beginning), so these need no further configuration!

- if you have nothing you actually want to do, you just want to avoid the global `embark-setup-hook`, then you can use `ignore` for the `embark-setup` property (very evocative, I feel).

So, for example, if you wanted everything ratified except for `shell-command` and `async-shell-command`, *all* you have to do is `(add-hook 'emark-setup-hook 'emark-ratify)`.

Is that good enough or would you still want a helper (which could be a variable or a function)?

**Comment by protesilaos** [comment]
> and @protesilaos has some custom commands that might be replaced by this.

Thanks!  Will update accordingly.  Just a note to self/others to check embark's wiki as well.

**Comment by clemera** [comment]
This works great, thank you! I'm also fine with `top-level`. 

One last thing is that usually after exit I would like to pass the argument right away like in my initial example. So far I only played around shortly with `embark` but after my experiments I think the commands where you would like to edit the argument afterwards in the minibuffer are in the minority?

**Comment by protesilaos** [comment]
> EDIT: Oh I just noticed you mentioned this above via (add-hook 'emark-setup-hook 'embark-ratify). But I still wonder if it would make sense to have this as default behaviour because I think this is probably the behaviour most users would expect?

Maybe we could compile a list of potentially 'destructive' commands (narrowly interpreted) and let those require a confirmation?

**Comment by oantolin** [comment]
> But I still wonder if it would make sense to have this as default behaviour because I think this is probably the behaviour most users would expect?

@clemera, maybe it is what most people would expect. I'll take your and @karthink's word for that. I have no problem at all with changing the default. I like visually confirming that the completion is the one I expected before pressing `RET`, but that can be my personal configuration: I don't intend to force my timidity on a devil-may-care majority!

> Maybe we could compile a list of potentially 'destructive' commands (narrowly interpreted) and let those require a confirmation?

Good idea, @protesilaos. Let's do that right now. But it's not just destructive commands, it's also commands like `shell-command` where the user need to type something extra at the prompt where the target is injected (in the case of `shell-command`: the command!).

And in the other direction, any command that prompts for more than one argument is safe, since you can cancel on the second argument even if the first was ratified.

So, of the actions in the keymaps I think I'd only put these on the list:

- `delete-file`
- `delete-directory`
- `shell-command`
- `async-shell-command`
- `kill-buffer`
- `embark-kill-buffer-and-window`

Maybe `package-delete`? But I don't think it's necessary: it's easy to reinstall a package you delete by mistake.

So, how does that list sound? Are there any other commands you want on the "danger list"? (They don't have to appear in `embark-*-maps`: we can still mark command as requiring confirmation even if we don't give them a binding.)

**Comment by protesilaos** [comment]
> So, how does that list sound? Are there any other commands you want on
> the "danger list"? (They don't have to appear in `embark-*-maps`: we
> can still mark command as requiring confirmation even if we don't give
> them a binding.)

How about `embark-shell-command-on-buffer`?  Or does it already inherit
from `shell-command`?

As for `package-delete` I am inclined to agree with you, though have no
strong preference about it.

**Comment by karthink** [comment]
Is the idea to set `embark-setup-hook` to `embark-ratify` for all commands except the above list? Or is it to change the behavior so that an empty `embark-setup-hook` implies no-confirm behavior?

By the way I think the term `embark-ratify` is a little confusing:

> Ratify \Rat"i*fy\: To approve and sanction; to make valid; to confirm; to establish; to settle.

This could be interpreted as "to approve or confirm" or as "to require approval or confirmation". e.g. to ratify as in sign off on a document explicitly.

**Comment by oantolin** [comment]
> How about `embark-shell-command-on-buffer`? Or does it already inherit from `shell-command`?

It doesn't inherit. I deemed it safe because by default it puts the output in a separate buffer, and with a `C-u` it does replace the buffer contents, but `undo` has your back.

**Comment by clemera** [comment]
I have nothing to add to this list, will it be a user option? I think that would be optimal because I like to live dangerously, at least inside Emacs ;) For `delete-file` I have `delete-by-moving-to-trash` set to non-nil.

**Comment by oantolin** [comment]
> By the way I think the term `embark-ratify` is a little confusing

Yes, it is. :( Any suggestions? How about very literally `embark-press-ret`?

**Comment by karthink** [comment]
> Is the idea to set `embark-setup-hook` to `embark-ratify` for all commands except the above list? Or is it to change the behavior so that an empty `embark-setup-hook` implies no-confirm behavior?

Either way this is a good solution, the only thing it requires the user to do is
```
(dolist (func '(f1 f2 f3 ...) nil)
  (put func 'embark-setup 'embark-ratify))
```
or something like that.

Some suggestions for embark ratify: (depending on what your default is)
`embark-confirm-p`, `embark-validate`, `embark-user-confirm`
OR
`embark-noconfirm`, `embark-go`, `embark-done`, `embark-auto`

There is probably some convention in Emacs for this that I'm not aware of.

**Comment by oantolin** [comment]
> Is the idea to set `embark-setup-hook` to `embark-ratify` for all commands except the above list? Or is it to change the behavior so that an empty `embark-setup-hook` implies no-confirm behavior?

The plan has happened (cfb4e24)! What I did was simply set `embark-setup-hook` to `embark-ratify`. This can of course be revisited.

> I have nothing to add to this list, will it be a user option?

I guess it could be. I kind of like the idea of using a property of the command, like `isearch` does with the `isearch-scroll` property, but maybe a list is better.

**Comment by clemera** [comment]
I don't know if it would be better but it would probably make it easier to configure. For properties users need to be aware of them (by reading the docs or code). And then they need a bit of Elisp skills to find all commands which have this properties and remove them.

**Comment by oantolin** [comment]
`isearch` is cool! I was just trying to be cool like `isearch`. :) But I don't have to be cool, I can make it a list.

Maybe this auto-press-RET vs wait-for-confirmation distinction is worth special-casing. Leave the setup-hooks for one-off things like `shell-command` inserting a space for you and leaving point at the beginning.

**Comment by clemera** [comment]
> isearch is cool! I was just trying to be cool like isearch. :) But I don't have to be cool, I can make it a list.

Hehe, I agree `isearch` is cool, although I try to avoid to look at the implementation if possible ;)

**Comment by clemera** [comment]
I once read an article about UI design but I can't find it to link it here. The idea was that instead of prompting users for confirmations just make it easy to undo actions. Many of are used to prompts like "Do you really want ...?". Just doing the action and making it easy undo unwanted actions is often more convenient. That's why I like  [resurrect](https://github.com/fbkante/resurrect) and `unbury-buffer`. Thinking about I should probably write an `untrash` command as well. 

BTW, thank you so much for this package it's such a great addition to the emacs ecosystem and if I understood correctly you came up with it in just a few days, brilliant!

**Comment by karthink** [comment]
> BTW, thank you so much for this package it's such a great addition to the emacs ecosystem and if I understood correctly you came up with it in just a few days, brilliant!

 +1 to this. All your packages are very good composable, mutually orthogonal extensions of Emacs' built in framework.

Plus I can't make any sense of `minibuffer.el`, so I'm glad someone else did the heavy lifting and I can just request features. :)

**Comment by oantolin** [comment]
Thank you for your kind words, @clemera and @karthink!

And... we're done with this issue! I've overhauled the configuration along the lines we discussed (commit ec210b0):

- The ratify/don't-ratify distinction is now called skip-edit/allow-edit.

- The skip/allow edit configuration is not related to hooks anymore, there are now variables `embark-allow-edit-default`, `embark-allow-edit-commands`, `embark-skip-edit-commands`, which see.
  
- The `embark-setup-hook` is no longer overriden by properties, but by a nice `embark-setup-overrides`, so you can see all the overrides in one place.
  
By the way, this comment was a pleasure to type with `embark`: I went `C-h v embark`, and inserted all the symbols from the completions buffer. :)

**Comment by oantolin** [comment]
I think this issue can be closed now. Please open a new issue if I missed anything.
