### ISSUE TITLE
Typo in embark-consult.el: cosult-buffer

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#110]
Look for `cosult-buffer` it appears once in a comment.

**Comment by hmelman** [comment]
Also: `that automatically previous the entry` should be "previews" not "previous".

**Comment by oantolin** [comment]
Thanks!

**Comment by iSeeU816** [comment]
It's not worth filing a new issue for it.
 
Currently line 59 of `embark-consult.el` file:

`;; If you don't want the minor mode automatically one and prefer to` should be "on".

Thanks!

**Comment by oantolin** [comment]
Thanks, @iSeeU816!
