### ISSUE TITLE
embark-consult report Error loading autoloads: (void-function embark-define-keymap)

### ISSUE THREAD

**Issue by stardiviner** [oantolin/embark#112]
When Emacs start, it soon report error:
```
Error loading autoloads: (void-function embark-define-keymap)
```
Here is my emacs config of embark:
```elisp
(use-package embark
  :ensure t
  :ensure selectrum
  :ensure embark-consult
  :bind (:map selectrum-minibuffer-map
              ("C-c C-o" . embark-export)
              ("C-c C-c" . embark-act)))
```

I tried to re-install these two packages. Still this error.
I guess `embark-consult` has not correctly generated autoload before embark `embark-define-keymap` loaded.

**Comment by oantolin** [comment]
That wasn't the only problem with the autoloads, and while I could have fixed that one, it seemed better to abandone the idea of autoloads in embark-consult. Now I'm recommending you arrange for it to be loaded after embark and consult, for example by using:

```elisp
(use-package embark-consult
  :ensure t
  :after (embark consult))
```

**Comment by oantolin** [comment]
See also #108.

**Comment by stardiviner** [comment]
Thanks @oantolin
