### ISSUE TITLE
[Question] How to add actions into any command?

### ISSUE THREAD

**Issue by TxGVNN** [oantolin/embark#113]
Hi. First, thanks for the great package.

I wonder how I can add action into a command? An example I want to add actions into `M-x projectile-switch-project`.
Instead of using projectile-find-file action by default, I want to use `ripgrep` or open a new term on the project when switching

I'm using counsel-projectile, that package has this feature and I can easy to customize it.
https://github.com/ericdanan/counsel-projectile/blob/06b03c1080d3ccc3fa9b9c41b1ccbcf13f058e4b/counsel-projectile.el#L1253-L1264

I'm trying to migrate from ivy/swiper/counsel to selectrum/embark/consult,... ecosystem

Thanks!

**Comment by oantolin** [comment]
Have you read the documentation about this topic? It's in the readme, in the [Defining actions for new categories of targets](https://github.com/oantolin/embark#defining-actions-for-new-categories-of-targets) section. Or you can read it in info:

```elisp
(info "(embark)Defining actions for new categories of targets")
```

If something isn't clear from the documentation, feel free to ask more questions right here in this issue.

**Comment by TxGVNN** [comment]
Oh, I missed it.
Sorry for my ignorance. I will try it. Thanks

**Comment by oantolin** [comment]
No problem, @TxGVNN! And as I said earlier, if something isn't clear, just ask here.
