### ISSUE TITLE
README info on embark-define-keymap seems outdated

### ISSUE THREAD

**Issue by mtreca** [oantolin/embark#119]
The section "Defining and configuring a keymap for tab actions" uses the following snippet for `embark define-keymap`:

```elisp
(embark-define-keymap embark-tab-actions
  "Keymap for actions for tab-bar tabs (when mentioned by name)."
  ("s" . tab-bar-select-tab-by-name)
  ("r" . tab-bar-rename-tab-by-name)
  ("k" . tab-bar-close-tab-by-name))
```

However, this results in an evaluation error. The following form works, though:

```elisp
(embark-define-keymap embark-tab-actions
  "Keymap for actions for tab-bar tabs (when mentioned by name)."
  ("s" tab-bar-select-tab-by-name)
  ("r" tab-bar-rename-tab-by-name)
  ("k" tab-bar-close-tab-by-name))
```

Did the macro change and this part was not updated, or am I doing something wrong?

**Comment by oantolin** [comment]
You're right, it's without the dot. Sorry about that.

**Comment by mtreca** [comment]
Thanks for the qucik reply and correction!
