### ISSUE TITLE
embark-consult: which consult commands should be bound in action and become maps?

### ISSUE THREAD

**Issue by minad** [oantolin/embark#122]
Idea by @astoff in https://github.com/minad/consult/pull/171/files#r560111176. The general-map is maybe too general?

**Comment by minad** [comment]
The same applies to consult-file-externally, which could be added to the file map. Through the embark-consult package we can provide such things nicely by default. Maybe there are even more useful consult commands which could be provided as actions by default?

**Comment by minad** [comment]
Maybe it is better to keep such things in the config?

~~~ diff
diff --git a/README.org b/README.org
index c8334b1..1605918 100644
--- a/README.org
+++ b/README.org
@@ -243 +243,3 @@ reasonable starting configuration:
-    ("C-S-a" . embark-act))              ; pick some comfortable binding
+    (("C-S-a" . embark-act) ;; pick some comfortable binding
+     :map embark-file-map
+     ("x" . consult-file-externally))) ;; if you use consult
~~~

**Comment by oantolin** [comment]
I forgot to add `consult-file-externally` to the file map! I definitely meant to: that function used to in Embark, if you recall, and I removed it to avoid duplication with Consult.

I may be confused about what `consult-isearch` does, I haven't been following it very closely. I thought it was for selecting a previous search string from isearch's history?

**Comment by oantolin** [comment]
The consult-embark package could also add a bunch of Consult commands to the become keymaps.

**Comment by minad** [comment]
> I may be confused about what consult-isearch does, I haven't been following it very closely. I thought it was for selecting a previous search string from isearch's history?

You can use it during isearch to change the search string or you can also use it to start a completely new search by either typing in a new string or by selecting from the history. This may make it useful for embark, to start a search. But the same applies to consult-line and other utilities. So maybe it is not really a good idea to add all these as actions.

**Comment by oantolin** [comment]
I have been using `consult-line` as an action a lot, but I use `M-g l` for it, instead of adding it to an Embark keymap. I guess I'll start using `consult-isearch` the same way.

We definitely shouldn't add too many of these to the general map. I worry about which-key users and don't want to overwhelm them with options, specially since we seem to recommend they use no paging. (I worry less about `embark-completing-read-prompter` users, since unlike which-key users, they can narrow). But maybe adding one, say consult-isearch, is reasonable.

**Comment by minad** [comment]
> I have been using consult-line as an action a lot, but I use M-g l for it, instead of adding it to an Embark keymap. I guess I'll start using consult-isearch the same way.

Agree, a dedicated binding works and is probably the better approach since it just works everywhere! Which keybinding do you propose for consult-isearch. I have M-s s right now in the example configure, but I am not super fond of it.

> We definitely shouldn't add too many of these to the general map. I worry about which-key users and don't want to overwhelm them with options, specially since we seem to recommend they use no paging. (I worry less about embark-completing-read-prompter users, since unlike which-key users, they can narrow). But maybe adding one, say consult-isearch, is reasonable.

Okay, let's keep the maps clean. But we still want to add a few of the consult commands to the become keymaps. We should carefully select those.

**Comment by astoff** [comment]
> We definitely shouldn't add too many of these to the general map.

`consult-isearch` should get a pass here, since isearch is exceptional in _not_ reading from the minibuffer. So, for Embark, binding it to `C-s` in the general map is the dwim solution!

Personally, I'm not going to bind `consult-isearch` globally; I'll rather access my search history via `C-s C-r`, exactly as in Swiper.

**Comment by astoff** [comment]
> I worry about which-key users

Is there maybe a symbol property to hide stuff from which-key?

**Comment by minad** [comment]
No symbol property as far as I know. It wouldn't make much sense to impose this on the user. But the user can configure which-key, replace entries, reformat and hide entries. Therefore cluttered which-key menus are not really a problem if someone cares about tuning this. Usually I remove commands from keymaps instead. For example in the help menu I removed some of the gnu propaganda, warranty and copying information. Probably I have lost the warranty.

**Comment by oantolin** [comment]
OK, let's not worry too much about which-key users then, they can tune the display if they wish. (But let's not go overboard either. 😛) By the way, is the no-paging really necessary? Paging seemed to work fine in my quick tests.

So lets bind `consult-file-externally` to `x` in the file map, and lets bind `consult-isearch` to `C-s`, but in which map? I guess the main contenders are the general map and the symbol map. Does anyone have a good use case for `consult-isearch` as an action which is not on the symbol at point?

What other consult commands should we bind in action maps? And in become maps?

**Comment by oantolin** [comment]
I guess isearch "feels" general even if we always use it on the symbol at point...

**Comment by minad** [comment]
Off topic, but I wonder about symbol at point again. Did you resolve the issue with non-elisp symbols such that they do not get the keymap cluttered with describe-symbol etc?

**Comment by astoff** [comment]
I guess it would be the _identifier_ map if not the general one. But since `<embark> C-s` just fails miserably if `C-s` is `isearch-forward`, I see no drawback in adding it to the general map.

**Comment by oantolin** [comment]
I think the issue was adequately resolved. @astoff never signed off on the strategy, but he didn't complain either. Now `(thing-at-point 'symbol)` is always a valid target. In major modes descending from Emacs Lisp it gets classified as `symbol`, in other programming major modes it gets classified as `identifier`, and in non-programming major modes, it gets classified again as `symbol`, but only if it actually has been interned.

As a little convenience, in org mode buffers if the target is starts and ends with `=` or starts and ends with `~`, those are assumed to be markup and stripped from the name. (In markdown mode this is not necessary because the backtick is not a symbol constituent.)

So above when I said I'd bind `C-s` for symbols, I also meant to include identifiers, I just forgot.

**Comment by minad** [comment]
> In major modes descending from Emacs Lisp it gets classified as symbol, in other programming major modes it gets classified as identifier, and in non-programming major modes, it gets classified again as symbol, but only if it actually has been interned before.

Ah perfect, the identifier target! This is a good solution. I had just forgotten that discussion. Thank you for reminding me again.

**Comment by oantolin** [comment]
I think it makes more sense to bind `C-s` in the general map, even if in the default configuration it is only used for symbols and identifiers. Users can add new "thing at point" targets, and might want to search for other occurrences of them.

**Comment by astoff** [comment]
> I think the issue was adequately resolved. @astoff never signed off on the strategy, but he didn't complain either.

Quem cala consente (the Spanish version of that must be fabulous).

**Comment by oantolin** [comment]
> Quem cala consente (the Spanish version of that must be fabulous).

I don't know about fabulous, but it is widely used, «El que calla, otorga».

**Comment by oantolin** [comment]
Huh. It's funny how I automatically switch from "..."  to «...» for Spanish. Do you guys do that with German quotes too?

**Comment by oantolin** [comment]
I'm very happy about this, because I often tried using `isearch` as an action only to be reminded it doesn't actually work. I really like using `query-replace` as an action too.

**Comment by astoff** [comment]
No, we do it American style. But I would call your style French, Germans do it »this way« or „this way“.

**Comment by oantolin** [comment]
> No, we do it American style. But I would call your style French, Germans do it »this way« or „this way“.

No, what I meant is do you find yourself using English quotes for English text and German quotes for German text, even if the German text is being quoted in the middle of an English conversation?

I knew about „this way“, but not about »this way«

**Comment by astoff** [comment]
Yes, I often do it when I need to throw some German in the middle of an
English sentence, but only if I want to give my message a funky vibe. Not
that there is anything funky about those quotes to the average German
speaker, but they do look very creative to me...

**Comment by oantolin** [comment]
I'll keep this issue open (and change the title) for further discussion of what consult commands `embark-consult` should bind.

**Comment by astoff** [comment]
I just realized there is an `isearch-edit-string` command with would work just as well as `consult-isearch` for Embark's purposes. 

@minad Since `isearch-consult` is a nearly drop-in replacement for `isearch-edit-string`, this suggests a binding for the former in `isearch-mode-map`, namely `M-e`.

**Comment by minad** [comment]
@astoff

> Since isearch-consult is a nearly drop-in replacement for isearch-edit-string, this suggests a binding for the former in isearch-mode-map, namely M-e.

What about setting the initial input to the current search string if a search is active such that it really becomes a drop-in replacement?

**Comment by astoff** [comment]
> I just realized there is an isearch-edit-string command with would work just as well as consult-isearch for Embark's purposes.

Maybe note quite: `isearch-edit-string` gives an error if Isearch has never been used in this Emacs session. After the first Isearch, it seems to always work fine.

**Comment by minad** [comment]
> Maybe note quite: isearch-edit-string gives an error if Isearch has never been used in this Emacs session. After the first Isearch, it seems to always work fine.

Well it does ot matter if isearch-edit-string is bad. If consult-isearch acts as a drop-in in the isearch-mode-map, we are good.

**Comment by oantolin** [comment]
Correct me if I'm wrong, but `consult-isearch` always seaches forward and `isearch-edit-string` searches in the direction of the last isearch.

**Comment by minad** [comment]
@oantolin See https://github.com/minad/consult/issues/184

**Comment by astoff** [comment]
> Correct me if I'm wrong, but [...] isearch-edit-string searches in the direction of the last isearch.

Probably, but just because isearch leaves it state as global variables. It's horrible, really. If you want Embark's `C-s` not to depend on Consult, I'd suggest a little function like this

``` elisp
(defun embark-isearch ()
  (interactive)
  (isearch-mode t nil nil nil 'isearch-symbol-regexp)
  ;; or just (isearch-mode t), to use the user's default mode
  (isearch-edit-string))
```

**Comment by oantolin** [comment]
Thanks @astoff, I decided to go with that in the embark package, and removed the bindings for consult-isearch in the embark-consult package, so that even people who don't use consult get a usable `C-s` (not that I expect many people that use embark but not consult, but this reduces a dependency for that functionality).

**Comment by minad** [comment]
We can still propose `consult-isearch` as an alternative command for this keybinding. However `consult-isearch` should be improved a bit more (https://github.com/minad/consult/issues/184).

**Comment by minad** [comment]
The search commands could be bound as actions with the option to allow editing of the search term. I would probably bind them under a prefix map:

* `c o` `consult-outline`
* `c i` `consult-imenu` or `consult-project-imenu`
* `c l` `consult-line`
* `c g` `consult-grep` 
* `c r` `consult-ripgrep`
* `c G` `consult-git-grep`
* `c f` `consult-find`
* `c L` `consult-locate`

Would it make sense to bind `C-s` (embark-isearch) to the region map to search for the marked region?

**Comment by oantolin** [comment]
I think discoverability is probably reason enough to include them, especially under a prefix where they don't really clutter up any lists. I actually use `consult-line` and `consult-imenu` as actions to search for the symbol at point pretty often. I did put them on the allow edit list as you suggest, but for `consult-imenu` and `consult-outline` I also have a setup hook that, when there is a unique match selects it and exits the minibuffer.

As for the region versions, I think I'd rather bring back a way to act on the region contents, even if you just get the general actions offered (but of course, you'd still be able to run any command). I don't know if you remember, but before there was an `embark-act-on-region-contents` bound to `RET` in `embark-region-map` that would rerun `embark-act` for you but instead of getting offered the region actions, you'd be offered actions appropriate for the region's _contents_. Back then the classifiers were still separate and I used them to classify the region's contents and pick the appropriate action map. I removed this when I unified target acquisition and classification.

**Comment by minad** [comment]
> I think discoverability is probably reason enough to include them.

Okay, sounds good. Maybe add even the version with the setup hook to embark-consult?

>  but before there was an embark-act-on-region-contents

No, I didn't remember this. Is it possible to add this `embark-act-on-region-contents` back in some non-intrusive form? But I consider this low priority, it was just a thought that this could be useful.

**Comment by oantolin** [comment]
> Okay, sounds good. Maybe add even the version with the setup hook to embark-consult?

OK, will do.

>  Is it possible to add this embark-act-on-region-contents back in some non-intrusive form? But I consider this low priority, it was just a thought that this could be useful.

I think so, I'll try something quick and if it doesn't work, just put this on the todo list.

**Comment by oantolin** [comment]
I added `embark-act-on-region-contents` again. dcddbe57fc2de46be955276db3e952450ba47d06

**Comment by oantolin** [comment]
I think I'll also add that prefix map with the Consult search commands to `embark-become-keymaps`, so those commands can easily become each other.

I like the prefix `c`, but it conflicts with a few things you might want for the thing at point:
- if it is a file name, `c` is `copy-file`,
- if it is a command, `c` is `Info-goto-emacs-command-node`,
- if it is a variable, `c` is `customize-set-variable`.

Maybe the `copy-file` overlap is fine, I don't think wanting to search for other occurrences of the the file name at point is that common.

The other two maybe I could rebind? `Info-goto-emacs-command-node` could be `I` for info (not `i`, because I don't want to shadow `embark-insert`).

The variable map currently has:
- `=`: `set-variable`
- `c`: `customize-set-variable`
- `C`: `customize-variable`

Maybe the last two could be `v` and `V` instead, or maybe even keep the `C` for `customize-variable` and just change `c` to `v`.

Alternatively, I could pick a different prefix for the Consult search commands.  Like `M-c`.

**Comment by minad** [comment]
I like u for customize. Then use C for consult?

**Comment by oantolin** [comment]
I think the setup hook that when the match is unique just goes there without further intervention from the user should only be used for `consult-outline`,  `consult-imenu` and `consult-project-imenu`. For the other commands if there is only one match for the thing at point, you are mostly likely on it!, and you will probably want to tweak the minibuffer input instead of the action sliently jumping to the current location, making it look like nothing happened!

**Comment by oantolin** [comment]
> I like u for customize. Marginalia also uses u. Then use C for consult?

Sure that seems fine. But I think I might change `Info-goto-emacs-command-node` to `I` anyway, since `c` is kind of a weird binding for that command.

**Comment by minad** [comment]
Sounds good. I would only bind consult-project-imenu and not consult-imenu. I am also proposing that in the consult example configuration. If the user prefers consult-imenu, it is easy to replace in the keymap.

**Comment by oantolin** [comment]
What does `consult-project-imenu` do if `consult-project-root-function` is nil? I found it confusing just now.

**Comment by oantolin** [comment]
Oh, if `consult-project-root-function` is nil it just gives you all buffer in the same major mode as the current one?

**Comment by minad** [comment]
I think it uses every buffer with the same mode. Maybe I should change it such that it falls back to consult-imenu and only shows the current buffer in that case. What do you think?

**Comment by oantolin** [comment]
This sounds like one of those personality tests: if `consult-project-root-function` is nil, an optimist says "all buffers in the current major mode are a single project!" and a pessimist says "the only buffer you can be sure is in the current project is the current buffer". 😆

**Comment by minad** [comment]
There is a third option - if no project root function is set just just the menus from all buffers since in that case everything is lost or show nothing at all :stuck_out_tongue_closed_eyes:

**Comment by oantolin** [comment]
I think I'm a pessimist, maybe it should fallback to `consult-imenu` if `consult-project-root-function` is nil. But also maybe `consult-project-root-function` should default to `vc-root-dir` or something in terms of `project-root`?

**Comment by minad** [comment]
> I think I'm a pessimist, maybe it should fallback to consult-imenu if consult-project-root-function is nil.

I will take a look at the code.

> But also maybe consult-project-root-function should default to vc-root-dir or something in terms of project-root?

@astoff suggested that in https://github.com/minad/consult/issues/167. I usually don't have vc loaded.

**Comment by oantolin** [comment]
I think maybe everything is fine as it is, I was just surprised by what happened when I ran `consult-project-imenu`, but I like that even with nil project root function it does something different than `consult-imenu`, something more global. And I can understand not wanting to load `vc`. It's easy enough for users to set the variable to `vc-root-dir`.

**Comment by minad** [comment]
It is okay to pessimize it, I guess that makes more sense. Also if the project root function returns nil, which is allowed. There is also consult--imenu-all-items in case someone wants to use a custom buffer filter.

**Comment by oantolin** [comment]
> I would only bind consult-project-imenu and not consult-imenu.

I was going to use `p` and `i` respectively. Do you really think it's better to bind only one of them?

**Comment by minad** [comment]
Maybe it is good to have consult-imenu at hand too if you want to get an Embark collect outline? If we have enough free keys let's just bind both.

**Comment by oantolin** [comment]
Maybe for the become maps its better to separate the async commands, because of the leading `#`, which you'd have to remove or add.

**Comment by oantolin** [comment]
OK, done with the search commands. I had to improve the support for prefix keys in the completing-read prompter first! 6bb4e5aef66c921ac722b6aa07745dc788ef5f6a

**Comment by oantolin** [comment]
Some other consult command should be added to some become keymaps. A bunch should go into the `file+buffer` map. I think maybe after adding those, this issue can be closed. Am I missing any other consult commands that need bindings in embark keymaps?

**Comment by minad** [comment]
I just wanted to check the consult submenu, but there is a problem - it does not update the which-key indicator. Do you have an idea on how to fix this? 

Regarding the become commands, I have not thought about these yet and I am not using become often. Nevertheless it is a nice feature. Maybe @protesilaos has some ideas on what should be bound? Probably there are more useful (also non-consult) actions we could add?

**Comment by protesilaos** [comment]
> Regarding the become commands, I have not thought about these yet and I am not using become often. Nevertheless it is a nice feature. Maybe @protesilaos has some ideas on what should be bound? 

I have been using become to switch between grep+find, buffers+recentf. Same for switching between consult-{line,outline,imenu}.  The implementation may still be refined though.

> Probably there are more useful (also non-consult) actions we could add?

My plan is to extend this principle for project.el commands for files, buffers, subdirs (my extension), grep.

There are other niches, such as my custom "insert bongo playlist" command that can become back and forth an "insert directory/URL/etc.".  I have not implemented those yet because I have been busy [further] refactoring my Emacs config (recently removed use-package and just extended diff-mode's font-lock).

**Comment by oantolin** [comment]
> I have been using become to switch between grep+find, buffers+recentf. Same for switching between consult-{line,outline,imenu}. The implementation may still be refined though.

The embark-consult package now adds consult-{line,outline,imenu} to the `embark-become-match-map`, under the prefix `C`.

**Comment by minad** [comment]
@protesilaos 

> I have been using become to switch between grep+find, buffers+recentf.

Unrelated, but since you mention buffers+recentf - I know you are not using `consult-buffer` since you dislike having multiple different candidate sources thrown together. Maybe you dislike that consult-buffer has been very ad-hoc? Still, I want to let you know that consult now has support for a better mechanism to merge candidates from different completion categories in a clean and fully configurable way. See https://github.com/minad/consult/blob/794e82d0306dc24aaf1612f982f724f28a02e3f2/consult.el#L2924 for the updated consult-buffer implementation. For such multi completions the consult-multi category is reported which works with Embark and Marginalia by dispatching to the individual category of the candidate under consideration.

**Comment by protesilaos** [comment]
> The embark-consult package now adds consult-{line,outline,imenu} to the embark-become-match-map, under the prefix C

Very well!  I have not updated anything the last few days.

> Unrelated, but since you mention buffers+recentf - I know you are not using consult-buffer since you dislike having multiple different candidate sources thrown together. Maybe you dislike that consult-buffer has been very ad-hoc? Still, I want to let you know that consult now has support for a better mechanism to merge candidates from different completion categories in a clean and fully configurable way. 

I noticed the commits in my feeds but I have not checked anything in depth yet (I read the commit logs before updating).  That granted, I have not been using consult-buffer thus far because it gives me too many false positives.  For example, I have a buffer "modus-themes.el", a directory "modus-themes", a recentf "modus-themes.html", one with org extension, another with .info...  Fundamentally, I need to make better use of the completion-category-overrides or something, though I have not looked into that for a long time---I should.

**Comment by minad** [comment]
@protesilaos Yes, having false positives is certainly the main problem with multi sources. If you figure something out I am eager to hear. But at least now it is possible to configure consult-buffer to the bits, remove sources add your own etc. And you can easily write your own commands based on consult--multi. I haven't done that yet - consult-buffer is the only multi command I am using. However I suspect it could be useful to write some project-specific menus where you throw together multiple common operations for quick access.

**Comment by protesilaos** [comment]
> @protesilaos Yes, having false positives is certainly the main problem with multi sources. If you figure something out I am eager to hear. But at least now it is possible to configure consult-buffer to the bits, remove sources add your own etc. And you can easily write your own commands based on consult--multi. I haven't done that yet - consult-buffer is the only multi command I am using. However I suspect it could be useful to write some project-specific menus where you throw together multiple common operations for quick access.

Good to know!  Will need to study it and give it a test.

**Comment by minad** [comment]
@oantolin I think this is finished. Only #139 is missing for accessibility.

**Comment by oantolin** [comment]
Yeah, I think you're right. I'll close this now.

By the way, I just reread the above exchange with @protesilaos and wanted to let you know that `consult-buffer` is growing on me, I think I might wind up using it as my main way to switch buffer and jump to bookmarks. It is less efficient than using `switch-to-buffer` and `bookmark-jump` for me, but only very slightly, and it's nice not to have to think about which command I need beforehand.

Also, I've turned on `recentf-mode` and whatever bad interaction it had with TRAMP years ago when I tried it for a couple of days seems to have been fixed. I do often try to switch to a buffer I recently killed, so it'll be nice to have the recent files too. I know lots of people have been using something like `helm-mini` for years, but I am very resistant to change for some things I have muscle-memory for, so I'm glad to see I might switch over this time.

I normally love automatic Consult previews, but I think for this particular case I might turn them off. In part it's that it's jarring that only buffers have a preview, though I understand and agree with the reasons for that.

**Comment by minad** [comment]
Note that you can overwrite the preview function 😆 

I could even factor them out from consult-buffer and consult-bookmark. They are local lambdas now. This would be better for reuse. But you can also just write your own consult--multi based command in ten lines or so.

Another option would be to make :preview part of the buffer sources such that we could enable it for more without doing any harm for people who dislike it since the sources can be modified easily.

Right now I have a distinction of source fields read by consult--multi vs additional fields read by the source consumer, eg in the case of consult--buffer the :open field. The :open action is not read by consult--multi. So maybe this field should really be called :buffer-open since it also receives a buffer specific display argument. And then there could be a :buffer-preview field.

At this point sources are of limited reusability since their preview and their action are tied to the command which is supposed to use them. In particular preview worries me a bit. If one would combine different source types their preview functions could interfere in weird ways.

**Comment by astoff** [comment]
> In part it's that it's jarring that only buffers have a preview

Please just don't add preview for unopened files! `counsel-switch-buffer` does that, and I think it's 1 of 2 unreasonable default settings in all of Ivy...

**Comment by minad** [comment]
> Please just don't add preview for unopened files! counsel-switch-buffer does that, and I think it's 1 of 2 unreasonable default settings in all of Ivy...

I agree regarding the defaults. But in consult it is now configurable, see https://github.com/minad/consult#multiple-sources.

~~~ elisp
(nconc consult--source-bookmark (list :state #'consult--bookmark-preview))
(nconc consult--source-file (list :state #'consult--file-preview))
(nconc consult--source-project-file (list :state #'consult--file-preview))
~~~

**Comment by minad** [comment]
I am not entirely consistent however, `consult-recent-file` previews by default and `consult-grep` also previews by default. Regarding `consult-recent-file` I could change it, but I don't think that anyone is actually using this command, it is just provided as a minimal fallback. `consult-grep` previews since in that case I actually care about the content, since I search content, so I think preview is justified.

**Comment by oantolin** [comment]
> Please just don't add preview for unopened files! `counsel-switch-buffer` does that, and I think it's 1 of 2 unreasonable default settings in all of Ivy...

@astoff I meant more in the opposite direction: buffers shouldn't be previewed (at least not automatically) either. It's weird that they are the only type in `consult-buffer` with a preview by default.

**Comment by minad** [comment]
@oantolin Well, I like the automatic preview and right now I am activating the preview everywhere also in order to showcase the feature. I think many people like it, including me. For recent files in consult-buffer it is obviously not a good option, since opening files can be very costly when additional modes are loaded etc. This is the compromise.

**Comment by oantolin** [comment]
I love the previews and want them automatic in every other case. But I think I might configure a preview key for consult-buffer specifically (I haven't yet.)

**Comment by astoff** [comment]
I think the way things work now is pretty reasonable, in particular the rationale for `consult-grep` to preview unopened files. As to the preview in `consult-buffer`, I think it's only useful on rare occasions, but then it's already there when I need it. I wouldn't use if if I had to remember a different key.

**Comment by oantolin** [comment]
New question on this topic: I just added `consult-buffer` to the `embark-become-file+buffer-map` bound to `C b`; should I bind it to `b` instead, overwriting the binding for `switch-to-buffer`. The idea is that maybe most people using the embark-consult package will be using `consult-buffer` instead of `switch-to-buffer`.

**Comment by minad** [comment]
Yes, b would be better I guess!

**Comment by minad** [comment]
We could bind consult-keep/focus-lines in the match map, maybe replacing keep and fush-lines

**Comment by oantolin** [comment]
We should bind them, but I'm a little unsure about replacing keep/flush-lines. Maybe `C f` and `C k` instead? (In fact maybe `C b` is fine for `consult-buffer` in the file+buffer map.) What if someone uses `keep-lines` by accident (maybe old muscle memory), and wants to switch to `consult-keep-lines`? That's inconvenient unless they both have (distinct) bindings in the become map.

**Comment by astoff** [comment]
Slightly on a tangent, since `keep-lines` doesn't have a global binding, but why is Consult's suggested config not done with remaps instead of replacing the mappings to their original versions? This may have some disadvantages, but it would make some of the things discussed in this issue just work out of the box.

**Comment by oantolin** [comment]
I was thinking even before your comment @astoff, that people that want to completely replace some built-in with a consult function will probably remap and then they get the non-`C`-prefixed binding anyway. So I don't have to worry about the remappers.

And binding the consult commands under the `C` prefix here actually helps the rest of the users, the ones that don't remap and maybe actually use both the built-in and a consult analogue: with separate bindings for the commands they can easily switch between them.

**Comment by minad** [comment]
@astoff I am not using remaps since I am not a fan of remaps, that's all. I am not using remaps in my config at all, I think. I like it better to be direct and more explicit. I think @oantolin's answer goes in the same direction. Users can always replace the bindings with remaps in case they prefer that style.
