### ISSUE TITLE
Problems with paths when acting on files from the completions buffer

### ISSUE THREAD

**Issue by oantolin** [oantolin/embark#13]
`embark-act` on files from the completion buffer:

1. `rename-file` in the completions buffer selects the file (with full path) correctly. However the prompt for the new name is always "~/", not the value of `default-directory` in the completions buffer.

2. `embark-insert` on a file inserts only the base name of the file. It should be appended with the `default-directory` in the completions buffer before insertion.

3. `embark-save` on a file name has the same behavior as `embark-insert`.

EDIT:

4. Same issue with `delete-file` and `delete-directory` when called using `embark-act` from the completions buffer. It looks for the base name of the file/directory in the default directory of the minibuffer instead of the completions buffer.

_Originally posted by @karthink in https://github.com/oantolin/embark/issues/3#issuecomment-631946208_

**Comment by oantolin** [comment]
OK, @karthink, I think fixed 2 & 3 with this commit 9cd01c5.

Then I wanted to fix 1, but in my testing I didn't see that issue. Did my fix for 2 & 3 accidentally fix 1 too?

**Comment by karthink** [comment]
2 & 3 are fixed. 1 is not, The prompt for the new name is still the minibuffer's value of `default-directory`, not the completions buffer's.

Additionally, 

4. Calling "I" (`embark-insert-relative-path`) through `find-file`, then `embark-exit-and-act` gives this error:

`ad-Advice-select-window: Wrong type argument: window-live-p, nil`

AND runs `find-file` on the file in question automatically the next time `find-file` is invoked. It's a weird bug.

**Comment by oantolin** [comment]
Whoops, I forgot about making the same change to `embark-insert-relative-path` the last time I changed `embark-insert`. Commit f62003e should fix 4 (as usual, please test). I'm working on 1.

**Comment by oantolin** [comment]
That's weird, I can't reproduce 1. For me the prompt for the new name starts in the directory of the files in the completions buffer.

**Comment by oantolin** [comment]
Does the problem you mentioned in 1 happen in `emacs -Q`?

**Comment by karthink** [comment]
Ok, issue 1 is not happening in `emacs -Q` or `emacs -q` any more. 

However it still happens in emacs with my config loaded. I'm investigating my minibuffer configuration to figure out what's tripping it up.

**Comment by oantolin** [comment]
I'll close this issue then, @karthink. If you figure out what part of your configuration causes this and you feel that embark should do something differently, let me know.
