### ISSUE TITLE
grep-setup-hook not called

### ISSUE THREAD

**Issue by jaor** [oantolin/embark#131]
Hi.  I'm on the latest embark and emacs master.  When i enter an exported collect buffer from, say, consult-ripgrep, the buffer is, as expected, in Grep mode.  However, it looks like grep-setup-hook hasn't been called, or at least it's had no effect.  In my case, that hook contains wgrep-setup, which, among other things, should be setting `C-c C-p`, but those bindings aren't there.  If i manually call wgrep-setup in the buffer, things seem to work.  Any ideas what might be causing this?

**Comment by oantolin** [comment]
That's odd. I call `grep-mode` and you think that would run the hook.

**Comment by oantolin** [comment]
Oh, I had not read carefully! I call `grep-mode`, which runs `grep-mode-hook`. I did not even know there existed a `grep-setup-hook`! Am I supposed to run that hook too? It seems `grep-mode` on its own doesn't run it. Is there a reason you put `wgrep-setup` in `grep-setup-hook` instead of `grep-mode-hook`?

**Comment by minad** [comment]
There is `grep-process-setup` which calls it, where a lot of weird stuff is going on. From what I see, it does not look like you should call it.

**Comment by jaor** [comment]
On Tue, Jan 26 2021, Omar Antolín Camarena wrote:

> Oh, I had not read carefully! I call grep-mode, which runs
> grep-mode-hook. I did not even know there existed a grep-setup-hook!
> Am I supposed to run that hook too? It seems grep-mode on its own
> doesn't run it. Is there a reason you put wgrep-setup in
> grep-setup-hook instead of grep-mode-hook?

no, i am not putting it in there, it's wgrep.el itself doing it, so
somehow wgrep thinks it'll get eventually called.  as @minad mentions,
these hooks seem to be called indirectly, perhaps as part of the
invocation of the grep process itself (so maybe it's being called in a
different buffer used when consult is collecting its candidates), but
i'm not sure either about the details.

if i call it manually in the embark export buffer, though, it seems to
work fine...

(with counsel-grep things seem to work, but i don't understand that code
well either)

**Comment by oantolin** [comment]
Well, I'd rather not run the `grep-setup-hook`, since that seems to be meant to be used by `grep-process-setup` and I am not running a grep *process* in `embark-export-grep`. Does just manually putting `wgrep-setup` in the `grep-mode-hook` work for you? Oh, or does that make `wgrep-setup` run twice in grep buffers created in the normal way by running `M-x grep`? You could just put it in `:after` advice on `embark-export-grep`.

**Comment by minad** [comment]
Maybe ask wgrep to change it? Or ask for the reason why the setup hook is used. Maybe it is used by accident?

**Comment by jaor** [comment]
On Tue, Jan 26 2021, Omar Antolín Camarena wrote:

> Well, I'd rather not run the grep-setup-hook, since that seems to be
> meant to be used by grep-process-setup and I am not running a grep
> process in embark-export-grep. Does just manually putting wgrep-setup
> in the grep-mode-hook work for you? Oh, or does that make wgrep-setup
> run twice in grep buffers created in the normal way by running M-x
> grep? You could just put it in :after advice on embark-export-grep.

both these things are possible (and work... the setup seems idempotent),
but `M-x grep` users are going to be surprised :) -- they don't have to
go through any additional loop to make wgrep work out of the box.
perhaps a mention in the docs for embark export, with the one-line
solution, is enough (i guess an embark-wgrep.el would be overkill?).

**Comment by oantolin** [comment]
I think I'll just call `wgrep-setup` myself if it exists. I already have some special code for `wgrep` anyway.

**Comment by oantolin** [comment]
So the exporter is now:

```elisp

(defvar wgrep-header/footer-parser)
(declare-function wgrep-setup "wgrep")

(defun embark-export-grep (lines)
  "Create a grep mode buffer listing LINES."
  (let ((buf (generate-new-buffer "*Embark Export Grep*")))
    (with-current-buffer buf
      (insert (propertize "Exported grep results:\n\n" 'wgrep-header t))
      (dolist (line lines) (insert line "\n"))
      (goto-char (point-min))
      (grep-mode)
      (setq-local wgrep-header/footer-parser #'ignore)
      (when (fboundp 'wgrep-setup) (wgrep-setup)))
    (switch-to-buffer buf)))
```

**Comment by oantolin** [comment]
I closed the issue with the idea that the real issue isn't that `grep-setup-hook` isn't called, but rather that `wgrep` didn't work out of the box with `embark-export-grep` the same way it does with `M-x grep`.

**Comment by jaor** [comment]
> I closed the issue with the idea that the real issue isn't that
> grep-setup-hook isn't called, but rather that wgrep didn't work out of
> the box with embark-export-grep the same way it does with M-x grep.

excellent.  thanks for the improvement!
