### ISSUE TITLE
consult-buffer default actions are broken

### ISSUE THREAD

**Issue by minad** [oantolin/embark#145]
Works when doing snapshots but not directly via embark-act, see discussion in https://github.com/oantolin/embark/commit/44907e210e68987fea2aa979fca2c930c8c83aca.

**Comment by oantolin** [comment]
Copying my remark from 44907e2:

From the snapshot the default action works precisely because those candidates are somehow missing the consult-multi property so they don't get refined. Try acting on the candidates in the snapshot buffer, you'll see you don't get the type-specific actions offered.

**Comment by oantolin** [comment]
Am I somehow stripping text properties when filling the embark collect buffer? I thought I wasn't.

**Comment by oantolin** [comment]
Maybe tabulated-list-mode strips properties.

**Comment by oantolin** [comment]
But it's a bad situation: either the default action works or you get type-specific actions offered but not both. If the `consult-multi` property is found, then the type refinement does occur and you get appropriate actions offered but the default action fails, and if the property is not present, then the prefix is not stripped and the default action works, but you only get offered `general` actions.

**Comment by minad** [comment]
>  Try acting on the candidates in the snapshot buffer, you'll see you don't get the type-specific actions offered.

Ouch,this should work :(

> From the snapshot the default action works precisely because those candidates are somehow missing the consult-multi property so they don't get refined. Try acting on the candidates in the snapshot buffer, you'll see you don't get the type-specific actions offered.

Okay, makes sense. Bugs interacting nicely :)

> But it's a bad situation: either the default action works or you get type-specific actions offered but not both. If the consult-multi property is found, then the type refinement does occur and you get appropriate actions offered but the default action fails, and if the property is not present, then the prefix is not stripped and the default action works, but you only get offered general actions.

Well, we just need the proper fix or rather two proper fixes:

1. Ensure that the collect buffer preserves the information such that all actions work
2. Fix the default action such that it works when the uniqueness prefix is present

**Comment by oantolin** [comment]
OK, the collect buffer *does* keep the text properties, but I was retrieving the candidates with the function `button-label` which uses `substring-no-properties` (and uses it without indices!, so it just removes the text properties).

**Comment by oantolin** [comment]
This is why I don't like relying on text properties: you never know when some innocent-looking function will strip them behind your back.

**Comment by minad** [comment]
Yes, one has to be careful. But for consult-multi and consult-location it is the right approach to attach metadata like this, I am convinced of that. The metadata is not lost at the boundary between Consult and Embark/Marginalia that's the crucial thing.

**Comment by oantolin** [comment]
It seems tab completing a candidate with default completion also strips some properties? If with default completion I run `consult-buffer`, type part of a candidate and press TAB to get the full candidate into the minibuffer, it does have the tofu character at the beginning and it is still invisible, but it doesn't have the `consult-multi` property, according to `C-u C-x =`. :(

**Comment by oantolin** [comment]
I wonder why tab completing keeps `invisible` and removes `consult-multi`.

**Comment by oantolin** [comment]
Ah, it doesn't preserve invisible either! You have a hack in consult to add it after the fact, right?

**Comment by minad** [comment]
Yes, this is the hack.

**Comment by oantolin** [comment]
So a quick experiment seems to indicate text-properties are not preserved by tab completing under default completion:

```elisp
(completing-read "Pick: " (list
                           (propertize "one"
                                       'prop "val"
                                       'display "two")
                           (concat "three" (propertize "(3)" 'invisible t))))
```

**Comment by minad** [comment]
Yes, tab completion does not preserve the properties, since it is like entering the candidate by hand. Does this break the way you are obtaining the currently selected candidate in Embark?

**Comment by oantolin** [comment]
> Yes, this is the hack.

Well, maybe it's worth extending the hack to add the `consult-multi` property. Otherwise use default-completionites won't get proper actions in `consult-buffer`.

**Comment by oantolin** [comment]
> Yes, tab completion does not preserve the properties, since it is like entering the candidate by hand. Does this break the way you are obtaining the currently selected candidate in Embark?

In a sense yes, for efficiency I first test (using `test-completion`) if the current minibuffer contents are a valid completion and only go through `completion-all-sorted-completions` if they are not. So if the user tab completes a candidates embark will use the minibuffer contents.

**Comment by oantolin** [comment]
I guess I could skip `test-completion` and always use `(car (completion-all-sorted-completions))`.

**Comment by minad** [comment]
> Well, maybe it's worth extending the hack to add the consult-multi property. Otherwise use default-completionites won't get proper actions in consult-buffer.

No, this does not sound right.

> In a sense yes, for efficiency I first test (using test-completion) if the current minibuffer contents are a valid completion and only go through completion-all-sorted-completions if they are not. So if the user tab completes a candidates embark will use the minibuffer contents.

Oh okay, can you please fix this, such that you always get the full candidate? I thought you already did it that way - I think we even talked about this? I think test-completion may still be good for efficiency? But since these Embark actions are a single operations the efficiency may not be a problem?

**Comment by minad** [comment]
Btw, why does it work in icomplete then? I think you use the same candidate extraction mechanism for default and icomplete? Or is icomplete just doing the right thing when tabbing?

**Comment by oantolin** [comment]
> Oh okay, can you please fix this, such that you always get the full candidate?

I do always get the full candidate, just ask `string-equal` if you don't believe me! 😉

But I get what you mean: always get it the slow way to ensure the text properties are preserved.

**Comment by minad** [comment]
Equality is a complicated topic I've heard - it seems this applies to Emacs strings too ;)

**Comment by oantolin** [comment]
> Btw, why does it work in icomplete then? I think you use the same candidate extraction mechanism for default and icomplete? Or is icomplete just doing the right thing when tabbing?

It doesn't work in icomplete either. To be clear what does work is tab completing candidates, that strips them of their properties, but if you don't have a full candidate in the minibuffer and you cycle through the completions, embark-act picks up the completion at the top of the cycle with text properties and all.

**Comment by oantolin** [comment]
Same with default completion. As long as what you have in the minibuffer is not already `string-equal` to a full candidate, then `embark-act` uses the top completion with text-properties and all. So just removing the optimization of checking if the minibuffer contents are a full candidate should fix this problem.

**Comment by minad** [comment]
Perfect, thanks!

**Comment by oantolin** [comment]
Oh, boy `(car (completion-all-sorted-completions))` isn't always the right thing. 😆 During tab cycling, that expression returns the *next* completion...

**Comment by minad** [comment]
I hope you don't have to search through all candidates - But even then this should still be a relatively quick thing. Now that you changed Embark such that you always get the full candidate including properties, I should probably also change Consult such that the function which obtains the candidate from the completion system does it in the same way (consult--completion-candidate-hook, consult--icomplete-candidate, consult--default-completion-candidate, consult--selectrum-candidate). But this would require me to update many commands... I think it should still be done in order to have this consistent with Embark.

**Comment by oantolin** [comment]
> Now that you changed Embark such that you always get the full candidate including properties

I haven't yet, because I haven't accepted that I might need to search for the minibuffer contents in the list of all completions.

**Comment by oantolin** [comment]
> Oh, boy `(car (completion-all-sorted-completions))` isn't always the right thing. 😆 During tab cycling, that expression returns the _next_ completion...

Wait, that can't be right, don't you use `car completion-all-sorted-completions` in `consult-icomplete--candidate`? Or is that function just wrong during tab cycling?

**Comment by minad** [comment]
> I haven't yet, because I haven't accepted that I might need to search for the minibuffer contents in the list of all completions.

I hope this is not necessary, but this is essentially what I usually do in these consult--read :lookup functions.

> Wait, that can't be right, don't you use car completion-all-sorted-completions in consult-icomplete--candidate? Or is that function just wrong during tab cycling?

Yes, this is what I am using - maybe it is wrong? I think you contributed that :)

**Comment by oantolin** [comment]
I think `consult--icomplete-candidate` *is* wrong during tab cycling, returning the next candidate rather than the current one. Embark does not have the same bug, because it uses `test-completion` first to see if the minibuffer contents are a valid candidate.

**Comment by minad** [comment]
Hmm, but preview works in icomplete-mode? I am confused now. Probably I am not "tab cycling" correctly.

**Comment by minad** [comment]
But since I am search through all the candidates in consult preview, you should simply do that too in Embark. I mean it works well and performant, I took care about this since I wanted to have a fast preview. I think I use `member` to find the correct list pair.

**Comment by oantolin** [comment]
> Hmm, but preview works in icomplete-mode? I am confused now. Probably I am not "tab cycling" correctly - In icomplete I can just use the arrows as in Selectrum?

Yes, you probably don't use tab cycling at all!  I don't mean icomplete's cycling with `icomplete-forward-completions` and `icomplete-backward-completions`. I mean using `minibuffer-complete` (normally bound to TAB in icomplete-mode and default-comp) with a non-nil value of `completion-cycle-threshold`. If you have fewer `completion-cycle-threshold` candidates, then TAB will insert the full text of a candidate and will mutate `completion-all-sorted-completions` so that the candidate just inserts is at the end, that way if you press TAB again, you cycle among the candidates.

**Comment by oantolin** [comment]
> In icomplete I can just use the arrows as in Selectrum?

You almost certainly bind them to `icomplete-{forward,backward}-completions`. Using those is cycling, but not tab cycling. The difference is that the full candidate is not inserted into the minibuffer.

**Comment by oantolin** [comment]
I'm confused: why would an overlay be any better than text properties here?

**Comment by minad** [comment]
I don't think it actually is. But when pressing TAB the prefix completes and seems to extend the invisible property to the new text. It is weird.

**Comment by minad** [comment]
Use consult-buffer with default completion, narrow to bookmarks, press TAB, enter some text which is invisible.

**Comment by oantolin** [comment]
Oh, I see, the change in unrelated to this discussion, but this discussion made you try TAB completion and then you noticed the invisiblity?

**Comment by oantolin** [comment]
Properties are sticky to the right by default, but this can be changed. I remember reading that in the manual once.

**Comment by minad** [comment]
Yes exactly.

**Comment by minad** [comment]
I was looking for such an extension flag, but didn't find it. I don't think it can be configured per property per string? For overlays you can tune the stickiness. However I could also remove the invisible properties in my tofu hack function again. But this would have more undesired effects.

**Comment by oantolin** [comment]
I think you can go back to the `invisible` text property, just use `'rear-nonsticky t` in addition to `'invisible t`.

**Comment by minad** [comment]
Great, linking here was the right idea ;) i will change it back then!

I searched for extend, advance etc. But tbh I didn't look good enough. I just went with what I thought would work.

**Comment by oantolin** [comment]
Or, to be more specific `'rear-nonsticky '(invisible)`, so you keep the rear-stickiness of other properties besides `invisible` at their default values. Actually probably `t` is better: you don't want the tofu to change any behavior of the text after it.

**Comment by oantolin** [comment]
It is kind of spooky to insert a consult-buffer candidate with TAB, backspace to erase what looks like all of the characters but secretely leaving the tofu undeleted, and then typing more text and nothing appears!

**Comment by oantolin** [comment]
The manual page is `(info "(Elisp)Sticky Properties")`, for future reference. I had to search for it again.

**Comment by oantolin** [comment]
Oh, no TAB cycling really screws things up!

As I said the way it works is that, if you have less than `completion-cycle-threshold` candidates (if that variable is `t` it counts as infinity), then `TAB` will:

- insert the first candidate, and
- mutate `completion-all-sorted-completions` to move the inserted candidate from the front to the end of the list.

That way repeated TABs will cycle through the candidates.

Unfortunately, when it put the inserted candidate at the end of `completion-all-sorted-completions` it removes the text properties!

Man, this is getting out of hand!

 If I really want text properties, I'll need to check if the minibuffer contents are a full candidate (because during tab cycling `(car (completion-all-sorted-completions))` is the next completion, not the current one), and if not use `(car (completion-all-sorted-completions))`; and in either case, look the result up in a fresh list from `(completion-all-completions ...)`, because only that list is guaranteed to have the text properties!

**Comment by oantolin** [comment]
Between this and `button-label` (and `completing-read` for that matter) stripping text properties, I'm starting to feel Emacs really doesn't want us using text properties this way.

**Comment by minad** [comment]
Yes, but I am retrieving the full candidate in my consult--read lookup functions by searching the candidate list as I already mentioned. Given this unholy step, I don't feel too bad about committing the additional sin of text properties.

Why is it not possible to directly call completion-all-completions on the minibuffer content? It sounds a bit complicated what you are proposing.

**Comment by minad** [comment]
Okay after rereading what you wrote:

> (STEP1) I'll need to check if the minibuffer contents are a full candidate (because during tab cycling (car (completion-all-sorted-completions)) is the next completion, not the current one), and if not use (car (completion-all-sorted-completions))

This you have to do anyways to get the correct candidate, right?

> (STEP2) look the result up in a fresh list from (completion-all-completions ...), because only that list is guaranteed to have the text properties!

This is the step necessary to regain the text properties, similar to my lookup. So it is kind of blaming the text properties a bit too much, text properties are really responsible only for this final step.

**Comment by oantolin** [comment]
I was writing a complicated explanation, but your comment above with the labeled (STEP1) and (STEP2) shows you don't need the explanation.

You are right that only STEP2 is because of the text properties, so maybe I shouldn't complain.

**Comment by minad** [comment]
Okay, I suggest we move on with this. I feel in Consult the problem is actually much uglier since I always have these :lookup functions everywhere, which disturbed me right from the start, but I didn't find a significantly better solution. In this case with the current candidate retrieval, I think the issue is so limited to these small get-current-candidate functions that I am not too worried about it. I mean these functions are already ugly because they are necessarily completion-system specific, so not much is to be lost.

While you fix this here I should also fix my candidate hooks for default completion/icomplete. Do you use a single one for both now? It somehow sounded like it since you also access the sorted completions. So I should probably remove consult--icomplete-candidate and fix consult--default-completion-candidate according to your STEP1. 

And if I decide to fix to work on https://github.com/minad/consult/issues/208, I should also add STEP2 on top. But I am still not sure - the benefits would be small since I still have to regenerate the full candidate after completing-read finished. At this point I could decide to just ignore the completing-read result and always go via the consult-completion-candidate-hook, but this sounds way too fragile and working against the API. Right now the candidate hook is only needed for preview which is an additional/optional feature on top.

**Comment by oantolin** [comment]
OK, so I've fixed targetting the minibuffer and the collect candidate at point so that text properties are preserved.

As consequence you do get correct type-specific actions for `consult-buffer` candidates whether in the minibuffer (which you did previously already unless you were using default completion and had used TAB to insert the candidate) or in an embark collect buffer.

As a result the default action is broken everywhere now. :D

**Comment by oantolin** [comment]
> Okay, I suggest we move on with this.

But this issue still remains: I fixed getting actions for the refined type, but the default action still fails because it wants the tofu. An incomplete work around would be to put `consult-buffer` on the allow edit list, and give it a setup hook override of `embark-consult-unique-match`. That would deal with all cases except when candidates from two different sources have the same name (I often have bookmarks and buffers with the same name, for example).

> I feel in Consult the problem is actually much uglier since I always have these :lookup functions everywhere, which disturbed me right from the start, but I didn't find a significantly better solution. In this case with the current candidate retrieval, I think the issue is so limited to these small get-current-candidate functions that I am not too worried about it. I mean these functions are already ugly because they are necessarily completion-system specific, so not much is to be lost.

I agree.

> While you fix this here I should also fix my candidate hooks for default completion/icomplete. Do you use a single one for both now? It somehow sounded like it since you also access the sorted completions. So I should probably remove consult--icomplete-candidate and fix consult--default-completion-candidate according to your STEP1.

I have *always* used a single one for default completion and icomplete, but I think in Consult you should use two separate ones. The one you have for default completion (which I believe I contributed), returns nil unless the minibuffer contents has a full candidate. That's nice because you don't get a preview until you actually have a full candidate in front of you. And then tab-cycling among candidates updates the preview nicely.

The function you have for icomplete does give the wrong answer during tab cycling. You could change it to `(if (test-completion ...) (minibuffer-contents) (car completion-all-sorted-completions))`.

> And if I decide to fix to work on minad/consult#208, I should also add STEP2 on top. But I am still not sure - the benefits would be small since I still have to regenerate the full candidate after completing-read finished. At this point I could decide to just ignore the completing-read result and always go via the consult-completion-candidate-hook, but this sounds way too fragile and working against the API. Right now the candidate hook is only needed for preview which is an additional/optional feature on top.

I think you shouldn't fix the text properties since the preview function doesn't need them.

**Comment by oantolin** [comment]
On second though you *should* use a single function for default completion and icomplete:

```elisp(defun consult--default/icomplete-completion-candidate ()
  "Return current candidate from default completion system or icomplete."
  (when (eq completing-read-function #'completing-read-default)
    (let ((cand (minibuffer-contents-no-properties)))
      (if (test-completion cand
                           minibuffer-completion-table
                           minibuffer-completion-predicate)
          cand
        (when completion-all-sorted-completions
          (car completion-all-sorted-completions))))))
```

(Not tested, but pretty sure it's right.)

**Comment by minad** [comment]
> But this issue still remains: I fixed getting actions for the refined type, but the default action still fails because it wants the tofu. An incomplete work around would be to put consult-buffer on the allow edit list, and give it a setup hook override of embark-consult-unique-match. That would deal with all cases except when candidates from two different sources have the same name (I often have bookmarks and buffers with the same name, for example).

Can we somehow special case this, such that the default action is not receiving the candidate with the stripped tofu. I think you proposed this before. This could turn out to be ugly, but I think it is also somehow logical. By transforming/dispatching candidates to the corresponding category from multi-category we remove some information. At this point the default action just does not apply anymore. What you could do - add the removed tofu as another text property to the candidate when removing the tofu in the transformer. Then the default action could look for this embark--tofu-prefix property and add it back. This could be done in an advice defined in embark-consult.el.

**Comment by minad** [comment]
Than you for the function, I will try if it works with both icomplete and default completion!

**Comment by oantolin** [comment]
The variable `completion-all-sorted-completions` is a cache for the function of the same name. The function I wrote relies on two things: (1) `icomplete` ensures the cache is up to date as you cycle through the candidates, (2) the cache is flushed after every non-tab-cycling change in the minibuffer contents. I'm sure about (1), a little less sure about (2), so some testing is in order.

Specifically I'd test with default completion, inserting a candidate with tab, and then modifying it with backspace and typing some other characters. The preview should not run until you have a full candidate again.

**Comment by oantolin** [comment]
> Can we somehow special case this, such that the default action is not receiving the candidate with the stripped tofu. I think you proposed this before. This could turn out to be ugly, but I think it is also somehow logical. By transforming/dispatching candidates to the corresponding category from multi-category we remove some information. At this point the default action just does not apply anymore. What you could do - add the removed tofu as another text property to the candidate when removing the tofu in the transformer. Then the default action could look for this embark--tofu-prefix property and add it back. This could be done in an advice defined in embark-consult.el.

That's exactly what I was planning to do. (Well, instead of storing the removed tofu I was thinking of storing the full thing, tofu and all.)

Another recent changes makes this a little awkward though. 😆 Before the default action was a little function called `embark-default-action`. I decided that it would look more informative in which-key if instead of `RET -> embark-default-action` you saw what the default action is, so now I bind `RET` directly to the command that opened the minibuffer.

This means that advice would have to be put on several consult commands, but I guess that's OK. Or I could back to the single function for all default actions...

**Comment by oantolin** [comment]
But either way, I'll fix it so the default action does get the full thing with tofu, and then I can get rid of `embark-consult-insert-line` and `embark-consult-save-line` and instead use a transformer for `consult-line`.

**Comment by minad** [comment]
> I decided that it would look more informative in which-key if instead of RET -> embark-default-action you saw what the default action is, so now I bind RET directly to the command that opened the minibuffer.

Yes, I love this!

**Comment by minad** [comment]
I added your fix in https://github.com/minad/consult/commit/19fbf25be4ad3aa09008e0825b1c7c1ed78c0f6b. It seems to work well with TAB cycling and also in icomplete.

**Comment by oantolin** [comment]
OK, this should be fixed now. I did exactly as you suggested: stored the tofu (not the whole candidate, I changed my mind) in a text property and insert from the embark setup hook for `consult-line`, `consult-isearch` and `consult-line`.

**Comment by oantolin** [comment]
The embark-consult package is pretty substantial now!

**Comment by minad** [comment]
Great! Do you see places where we could simplify things from the side of Consult in order to ease interfacing? A lot of the substance here comes from the occur export.

**Comment by minad** [comment]
I just tested it - and it seems to work flawlessly! Thank you!

**Comment by oantolin** [comment]
> Great! Do you see places where we could simplify things from the side of Consult in order to ease interfacing? A lot of the substance here comes from the occur export.

No, I don't see how Consult could help. As you say the occur export is a good chunk of the code, which is reasonable. And I also think we just wanted complex behavior for, say, `consult-line`and `consult-outline`:

- We wanted all actions on the candidates they produce, except the default action, to receive the lines without tofu.
- When those two are the default action we wanted them to go to the location immediately without waiting for the user to press RET.
- When those are used as actions on some random string that is not a full tofu-prefixed line, like the symbol at point, we want `consult-line` to keep the minibuffer open so people can scroll through the matches and maybe edit the string. Almost the same goes for `consult-outline`, except that if the match is unique we want `consult-outline` to just take you there without having to press `RET`.

It's fairly intricate behavior and I was happy to see that no advice was needed, it could be done with existing hooks in Embark.

**Comment by minad** [comment]
> And I also think we just wanted complex behavior for, say, consult-lineand consult-outline:

Agree.

> I was happy to see that no advice was needed, it could be done with existing hooks in Embark.

Agree, this is a good sign.

> It's fairly intricate behavior 

The only question in such cases is if it makes sense to take a step back and think about possible simplification - I mean removing behavior, removing special casing. But this dwim behavior we are having now seems reasonable. After some time, I will probably have forgotten what happens when, but Embark will continue to the right thing hopefully ;)

**Comment by minad** [comment]
Maybe one thing:

> When those are used as actions on some random string that is not a full tofu-prefixed line, like the symbol at point, we want consult-line to keep the minibuffer open so people can scroll through the matches and maybe edit the string. Almost the same goes for consult-outline, except that if the match is unique we want consult-outline to just take you there without having to press RET.

In Consult I am using consult-location for consult-line, consult-outline, consult-mark and consult-global-mark. Does it make sense to ensure that all of these work exactly the same? It is not obvious from the embark-consult code that this is the case. Ideally I wouldn't want to see these command names in the embark-consult code, only the category consult-location. And here you say that consult-outline is also special cased. I would probably prefer this to be consistent also in case I am adding more consult-location commands.

**Comment by oantolin** [comment]
Each bit of special behavior is done in a different hook function added to `embark-setup-overrides`, so you will find all of `consult-line`, `consult-outline`, `consult-mark` and `consult-global-mark` mentioned in `embark-consult` and see what special behavior they each get.

- They all get the tofu restoration for full candidates.
- That's all the special behavior `consult-mark` and `consult-global-mark` get, so by default they never keep their minibuffers open. This means you can't use them as actions to answer questions like: "are there any marks on lines which contain the symbol at point? (And if so, let me scroll through them with Consult's lovely previews!)". But I thought that usage was pretty esoteric. (It would be easy to enable it, just like for `consult-line`.)
- Then `consult-line` and `consult-outline` and all the async search commands get put on the allow edit list, so they keep their minibuffers open unless some other behavior autoaccepts the input.
- The async search commands get the async separator inserted at the beginning of the minibuffer input.
- `consult-line` and `consult-outline` do autoaccept the target under some circumstances, as I described above.

All of this is actually fairly readably gleaned from two embark variables after loading `embark-consult`. One is `embark-allow-edit-commands`, where you see the search commands will keep the minibuffer open by default, and the other is `embark-setup-overrides` which is:

```elisp
((consult-global-mark embark-consult-restore-prefix)
 (consult-mark embark-consult-restore-prefix)
 (consult-isearch embark-consult-restore-prefix)
 (consult-buffer embark-consult-restore-prefix)
 (consult-grep embark-consult-add-async-separator)
 (consult-ripgrep embark-consult-add-async-separator)
 (consult-git-grep embark-consult-add-async-separator)
 (consult-find embark-consult-add-async-separator)
 (consult-locate embark-consult-add-async-separator)
 (consult-line embark-consult-restore-prefix embark-consult-accept-tofu)
 (consult-project-imenu embark-consult-unique-match)
 (consult-imenu embark-consult-unique-match)
 (consult-outline embark-consult-restore-prefix embark-consult-accept-tofu embark-consult-unique-match)
 (async-shell-command embark--shell-prep)
 (shell-command embark--shell-prep)
 (eval-expression embark--eval-prep)
 (package-delete minibuffer-force-complete))
```

**Comment by oantolin** [comment]
So while the dwim behavior is a little long to fully specify, I think (1) it's very likely what you want, so people will use it without even thinking about it, (2) it's actually more or less discoverable even from the customize buffer.

**Comment by minad** [comment]
Okay, sounds good! Maybe add a link to this comment or even copy this comment to the source if is not already there ;)
I am totally happy with "perfect" dwim behavior as long as it is not working against me. My concern goes more in the direction of maintainability, if things will still be working after a while or if everything will become brittle after a while. But as long as we don't change the consult-location/consult-multi format and as long as I don't rename commands we are good. For each new command we have to add these overrides then. But I am not sure if we will even get more consult-location commands.
