### ISSUE TITLE
Handle unbound key presses

### ISSUE THREAD

**Issue by clemera** [oantolin/embark#15]
When using an unbound key in the transient map the transient map exits and the usually bound command gets executed. This also means that after such a mistyped key `embark--cleanup` doesn't run because `embark--target` is still set. This way you can end up in a state where you think you quitted `embark` but next time you open a minibuffer `embark--inject` does its thing.

I think any wrong pressed key should probably call a command like `embark-undefined` which would be like `embark-cancel` but showing an additional message to inform the user that the key is undefined. One way I can think of implementing this would be to use `[t]` to bind this command. This is a feature of keymaps to use this command as the default for any unbound key.

**Comment by clemera** [comment]
Looking into it seems adding the following as the last line to `embark-keymap` would do:

    (make-composed-keymap map '(keymap (t . embark-undefined)))

**Comment by oantolin** [comment]
The idea is that you can use any command as an embark a Rion, it doesn't need to be bound in an `embark-something-map`, or even bound at all: you can use `M-x some-command` as an action too.

I wouldn't want users to be limited to actions they had the foresight to bind in the `embark-something-maps`.

**Comment by clemera** [comment]
> The idea is that you can use any command as an embark action, it doesn't need to be bound in an embark-something-map, or even bound at all: you can use M-x some-command as an action too.

How would that work? Don't you need to write a special command to use it as an action?

**Comment by oantolin** [comment]
But there should be a visible indicator of whether an action is pending or not and an easy way to cancel it. I guess `embark-cancel` needs a binding not just in the transient map.

**Comment by clemera** [comment]
Okay I understand. But the "bug" is still a problem no?

**Comment by clemera** [comment]
I at least was bitten by that behaviour several times. I wouldn't like that to ever happen and that is more important to me than having the freedom to be able to use any command as an action adhoc which I don't see me doing. But you are free to disagree of course.

**Comment by oantolin** [comment]
What e, actly is the bug, though? Because injecting the target at the next available prompt is embark doing what it is supposed to do.

I guess if the indicator "Act" disappears before the injection, that's a bug. 

And if there is no way to cancel the action before it happens, that's a bug.

By the way, some people will probably *want* to limit themselves to actions in `embark-*-maps`. So it would be nice to add your `embark-undefined` command to embark, and tell people looking to curtail their own freedom voluntarily to bind it to t in `embark-general-map`.

**Comment by oantolin** [comment]
In fact, if it's less surprising, I wouldn't mind limiting action to embark-*-maps to be the default, as long as it is easy to configure the package for full freedom.

**Comment by oantolin** [comment]
So instead of a composed key map how about we just bind t to `embark-undefined` in `embark-general-map` and I can easily un bind it iny own configuration?

**Comment by clemera** [comment]
> What e, actly is the bug, though? 

For example if you invoke `find-file` and then `embark-exit-and-act` now press `q` which self inserts and you realize you messed up an instinctively press `C-g`. Now when you invoke `find-file` again it just opens the last selected file immediately.

> So it would be nice to add your embark-undefined command to embark, and tell people looking to curtail their own freedom voluntarily to bind it to t in embark-general-map

This only would work as long as they don't use prefix keys in the map because otherwise the `[t]` mapping wouldn't catch mistyped keys after a prefix I believe.

**Comment by clemera** [comment]
> So instead of a composed key map how about we just bind t to embark-undefined in embark-general-map and I can easily unbind it in my own configuration?

Otherwise this sounds good I have to test something and will report back.

**Comment by oantolin** [comment]
Mmh, I see, it would be nice if *any* `C-g` canceled the action.

**Comment by clemera** [comment]
I tested and binding in `embark-general-map` would not work with prefix keys:

    (define-key embark-general-map (kbd "C-c i") 'embark-insert)
    (define-key embark-general-map [t] 'embark-undefined)

Now if you type `C-c q` `embark-undefined` will not be called and you would have the same problem we talked about. I don't plan to use prefix keys in embark maps myself so I would be ok with this but this is something to be aware of.

**Comment by oantolin** [comment]
Does the composed key map approach catch prefix keys?

**Comment by clemera** [comment]
> Does the composed key map approach catch prefix keys?

Yes it does, because the `[t]` is defined in the parent which does not define any additional keybindings itself. So no prefix shadows it so to speak.

**Comment by clemera** [comment]
Oh wait apparently it doesn't work either.

**Comment by oantolin** [comment]
Oh, in that case let's say binding `embark-undefined` to t in `embark-general-map` is "good enough". :)

You know, I bet full freedom wouldn't be so bad if (1) `C-g` canceled the pending action too, (2) the "Act" indicator really stayed visible until the action was concluded.

**Comment by clemera** [comment]
I think I have found a way we can have both:

    (define-key embark-general-map [remap self-insert-command] 'embark-undefined)

I think this way you can still use any adhoc command as an action plus you won't be affected by the "bug" I was talking about. Prefix keys defined inside embark maps would still have this problem but I would be fine with that and I guess not many would like to use prefix keys inside them anyway.

**Comment by clemera** [comment]
BTW you said

> you can use M-x some-command as an action too.

and this doesn't work for me. Now I know why, I use `amx` and in the code you check for `execute-extended-command`. Could I convince you to you use `(string-match-p "M-x"` there, too? :)

**Comment by oantolin** [comment]
> `(define-key embark-general-map [remap self-insert-command] 'embark-undefined)`

This is great! To make sure I understand, you are proposing just adding this and considering the problem solved?

> Could I convince you to you use `(string-match-p "M-x"` there, too? :)

Sure thing.

**Comment by clemera** [comment]
> This is great! To make sure I understand, you are proposing just adding this and considering the problem solved?

Yup, as far I as you don't see any downsides. I currently don't. 

> Sure thing.

Nice thanks!

**Comment by clemera** [comment]
I like that solution if I mistype things I prefer to quit automatically but I would have felt a little bit worried if I really never would want the full freedom to execute any action adhoc ;)

**Comment by oantolin** [comment]
How about this version of `embark-undefined`?

```elisp
(defun embark-undefined ()
  "Cancel action and show an error message."
  (interactive)
  (ignore (embark-target))
  (user-error "Unknown embark action"))
```

**Comment by oantolin** [comment]
I'm mainly asking about signalling a user error, but I also changed the message. *I* like the gentle scolding in your message, but wouldn't feel comfortable leaving it in. :(

**Comment by clemera** [comment]
The message content was meant as a joke really :) I didn't expected you to leave it that way. I'm not sure about the user error. It makes more sense then a message but with selectrum the `minibuffer-message` is much less intrusive. The error message "blocks" the whole minibuffer but I believe this will be fixed in Emacs 27.

**Comment by oantolin** [comment]
I'm fine with just a message. By the way, in my testing it doesn't seem necessary to call `(embark--cleanup)` from `embark-undefined`. For me, the message (or user-error) flashes for a second and then you return to whatever you were doing in the minibuffer with the overlay gone.

Did you call it for the sake of Selectrum? Does Selectrum flash the message with the overlay still visible? (I have no problem with adding the `embark--cleanup` call, I just want to understand why you need it.)

**Comment by oantolin** [comment]
By the way, I'm really liking this remapping of self-insert-command. It seems exactly the right mix of safety and generality. Thanks for coming up with it.

**Comment by clemera** [comment]
If I use `minibuffer-message` the message is shown after the current input without flashing the whole minibuffer (also without selectrum in Emacs 26.3). With the cleanup before the message it looks a bit nicer because the embark overlay is already gone so this is the visual end state. Without the cleanup after the message disappears the prompt moves to the left when the embark overlay is cleaned up.

**Comment by clemera** [comment]
Hopefully the above is understandable otherwise I can make a gif.

**Comment by oantolin** [comment]
Got it.

**Comment by clemera** [comment]
Thank you very much!
