### ISSUE TITLE
Require at least Emacs 26.1?

### ISSUE THREAD

**Issue by minad** [oantolin/embark#151]
My stable Debian has 26.1, therefore I am using this as version bounds for Consult. But I am mostly using 27. Maybe also up the other packages, icomplete-vertical, orderless etc?

**Comment by oantolin** [comment]
Sure. I'm kidding myself with that 25.1 dependency.

**Comment by minad** [comment]
My plan is to drop 26 as soon as 28 is released and as soon as stable Debian has 27. It seems these popular Emacs distributions are already on their way to drop 26 support.
