### ISSUE TITLE
M-x embark-act RET M-x test-command RET runs in minibuffer with which-key

### ISSUE THREAD

**Issue by minad** [oantolin/embark#154]
I just checked again the issue I mentioned in #153. When the point is on a symbol, pressing `M-x embark-act RET M-x test-command RET`, the `test-command` is executed in the minibuffer. I am running 27.1 with which-key. The problem is the which-key indicator.

~~~ elisp
(defun test-command ()
  (interactive)
  (message "window=%s buffer=%s" (selected-window) (current-buffer)))

;; problem occurs only if the indicator is enabled!
;; (setq embark-action-indicator
;;       (lambda (map &rest _target) (which-key--show-keymap "Embark" map nil nil 'no-paging)
;;         #'which-key--hide-popup-ignore-command))
~~~

~~~
window=#<window 4 on  *Minibuf-0*> buffer= *Minibuf-0*
~~~

**Comment by oantolin** [comment]
Oh, boy. Unwanted interactions.

**Comment by oantolin** [comment]
This is odd: the indicator function is run before the action, and the action itself is wrapped in `with-selected-window`.

**Comment by minad** [comment]
Note that I only have this problem with M-x, not when invoking the predefined actions from the keymaps.

**Comment by oantolin** [comment]
Yeah, I know, it's very strange. I've been playing around with it.

**Comment by oantolin** [comment]
This seems to have been miraculously fixed by the recent indicator overhaul.
