### ISSUE TITLE
embark-act on symbol -> snapshot produces empty buffer

### ISSUE THREAD

**Issue by minad** [oantolin/embark#155]
Export says "no candidates", maybe snapshot could do the same?

**Comment by oantolin** [comment]
Well, there is technically a reason for collect being different from export in this regard, but maybe it's not a great reason and I should make collect also say "No candidates". The thing is that embark collect buffers have a working revert-buffer function, so even though there are currently no candidates, there might be some in the future.

**Comment by minad** [comment]
How does this revert-buffer functionality work? I think I've seen before that someone wondered about empty snapshot buffers. To me it feels like a bug therefore I asked, since I don't see much value in an empty buffer. But I also don't understand your revert buffer argument, so maybe I am missing the crucial detail :)

**Comment by oantolin** [comment]
> How does this revert-buffer functionality work?

The revert function checks if the buffer you called `embark-collect-*` from is still around, and if so, calls the candidate collectors again. The live updating functionality in `embark-collect-live` just calls `revert-buffer` after everything in the minibuffer, for example.

> To me it feels like a bug therefore I asked, since I don't see much value in an empty buffer.

You're right, there isn't much value! And making an empty buffer on the off chance that the user later adds some candidates and then reverts the collect buffer is probably unnecessary.

>  But I also don't understand your revert buffer argument, so maybe I am missing the crucial detail :)

Here's an example. Add a candidate collector for, I don't know, `defun`s:

```elisp
(defun collect-functions ()
  (when (derived-mode-p 'emacs-lisp-mode)
    (cons 'symbol
          (save-excursion
            (goto-char (point-min))
            (let (functions)
              (while (search-forward-regexp "^(defun \\(\\_<.*?\\_>\\)" nil t)
                (push (match-string 1) functions))
              (nreverse functions))))))

(add-to-list 'embark-candidate-collectors #'collect-functions)
```

Now, in an empty `emacs-lisp-mode` buffer run `embark-collect-snapshot`, to get an empty collect buffer. Next add some function definition to the empty `emacs-lisp-mode` buffer, switch to the collect buffer and press `g`. You'll now see the name of the function you just added.

**Comment by minad** [comment]
Okay makes sense! But if you have no buffer and no candidates, it would be better to not open a buffer. The question is what should happen on revert if there are no candidates left, then an empty buffer is justified I guess.

**Comment by oantolin** [comment]
Yeah, I agree, revert should be allowed to leave the buffer empty, but it should be non empty on initial creation.

**Comment by oantolin** [comment]
Maybe this "no initially empty collect buffers" should only apply to snapshot buffers. For example, if someone runs `embark-collect-live` with some gibberish in the minibuffer for which there are no completions, they might want to have the chance to fix the minibuffer input so that candidates appear later in the live collect buffer. Or if someone starts `embark-collect-live` for some consult async search command, it shouldn't refuse to collect just because the candidates haven't come in yet.

**Comment by oantolin** [comment]
I decided to show a message for empty collect buffers only in the snapshot case. 6d7e262a5db99ef6af9acc8c0bbe31494aae808d

**Comment by minad** [comment]
Yes exactly, I want this only for snapshot buffers!
