### ISSUE TITLE
How to customize action in *Embark Collect*?

### ISSUE THREAD

**Issue by BooAA** [oantolin/embark#157]
Sorry if this is duplicated or has been mentioned somewhere, I just can't find related information in README or Wiki.

When I press `RET` on the snapshot of `describe-function`, `*Help*` buffer is displayed in the same window. When I press `q` to quit that buffer, cursor is placed on the other window instead of the original one. For example:

Version: Emacs 28, master branch
OS: Debian/sid

1. `C-h f`, search `find-file`, 
2. calling `embark-act` and pressing `S` for snapshot

Original layout:
![embark1](https://user-images.githubusercontent.com/32809182/108222447-c4b05400-7173-11eb-9c1c-ef2a49a203b2.png)

After pressing `RET`, the `*Help*` buffer is displayed in the same window:
![embark2](https://user-images.githubusercontent.com/32809182/108223081-6172f180-7174-11eb-95d7-e06a4e65ee97.png)

`q` to quit, cursor is placed at the other window
![embark3](https://user-images.githubusercontent.com/32809182/108223337-ab5bd780-7174-11eb-8e29-2bc4f9f4efe7.png)

That's inconvenient IMO, it would be better to display `*Help*` at other window by default. I think this behavior is due to how `*Help*` is handled by the `display-buffer` mechanism but not Embark (i.e. I guess Embark simulate invoking command by keystroke and feed in the candidate as input, so the behavior is caused by command itself but not Embark) . If that's the case, how can I setup Embark using something like `describe-symbol-other-window` as action instead of just `describe-symbol`? I don't want to setup `display-buffer` since it will take effect globally and I just want to customize how Embark perform action locally.

I tried using `C-h k` to see what exactly is bound to `RET` in `*Embark Collect*`, but what I get is just `push-button`, so I have no idea how can I change this behavior.
 
BTW, I have tried using `windmove-display-default-keybindings` to temporarily override `display-buffer` action (like `M-S-<right>` to specify displaying at right) , windmove achieved this by using `display-buffer-overriding-action` API, so I assume it will work but in fact the behavior is weird, see below:

Original layout:
![embark1](https://user-images.githubusercontent.com/32809182/108222447-c4b05400-7173-11eb-9c1c-ef2a49a203b2.png)

press `M-S-<right>` first, then `RET`, `*Help*` is still in the same window. 

press `M-S-<down>`, then `RET`, `*Help*` is displayed at the bottom of the other window, and cursor is unchanged.
![embark4](https://user-images.githubusercontent.com/32809182/108229333-abf76c80-717a-11eb-84fd-8bac0d66379c.png)

I'm totally confused now, `embark-collect` is like a blackbox and I have no idea how to make it fit my need.

**Comment by oantolin** [comment]
I don't like this window behavior either. It didn't use to be like this, but now that all actions are run in the so-called target window, this is an unintended consequence. Maybe I should temporarily mark the window where you run the action as dedicated. I'll think about it a bit.

**Comment by oantolin** [comment]
I pushed a fix for this window behavior, that works by just temporarily marking the window in which you run the action as dedicated to its buffer (so, in your example, this tells `describe-symbol` that it can't use the window displaying the embark collect buffer). I tried a bunch of actions that mess with windows and think this behaved reasonably well in all cases, but I can easily have missed some edge case and the window behavior might require further tweaks (or full-blown configurability, which for now I'm hoping to avoid). Please test that fix to see if it satisfies you.

**Comment by BooAA** [comment]
Works for me. Thanks.

**Comment by jakanakaevangeli** [comment]
Sorry, but in quitting `embark-act`, same-window actions such as `find-file` or
`switch-to-buffer` don't use the same window any more.

Perhaps `set-window-dedicated-p` should only be set on windows displaying a
snapshot buffer, so it should perhaps be used in `embark--action-command` and
`embark-collect-choose` rather than in `embark--act`.

**Comment by oantolin** [comment]
Sorry, @jakanakaevangeli! I was under the impression I was harmlessly setting the minibuffer window to be dedicated in that case, but of course, by the time a quitting action runs, the minibuffer window is no longer the selected window, so I was actually marking as dedicated the window selected after the minibuffer exits! I've fixed it so the window temporarilt marked as dedicated is the one selected at the time you run `embark-act`. I think that is correct behavior, but please let me know if I screwed it up again. 45b3d93
