### ISSUE TITLE
embark-sorted-minibuffer-candidates is losing candidates

### ISSUE THREAD

**Issue by karthink** [oantolin/embark#159]
I replaced `embark-minibuffer-candidates` with `embark-sorted-minibuffer-candidates` in `embark-candidate-collectors` as I want my most used commands at the top of the completions list. But `embark-sorted-minibuffer-candidates` doesn't show any command I run in that session at all. That is, every time I make a choice from the set of offered completions, it disappears from the list on the next invocation of that command.

I tried to understand what's happening but couldn't figure it out. This seems like a problem with `completion--cache-all-sorted-completions` best I can tell.

**Comment by oantolin** [comment]
Oh, you mentioned this on reddit some time ago, right? I had forgotten. Thanks for opening this issue, so I don't lose track of this.

**Comment by oantolin** [comment]
Wow, this one is mysterious!

**Comment by oantolin** [comment]
When I said this problem was mysterious, what I really meant is that I am an idiot.

**Comment by oantolin** [comment]
Please test, @karthink!

**Comment by karthink** [comment]
Yup that works great. I'm following the MELPA package so I edited it by hand. That's one step closer to getting the best of `icomplete` and `embark`!
