### ISSUE TITLE
Execute code when exiting transient map

### ISSUE THREAD

**Issue by clemera** [oantolin/embark#16]
If you use `embark-act` with selectrum the candidate list shown in the minibuffer does not update (for example when renaming/deleting a file). An easy way to fix that for selectrum would be to set the transient exit function to something else (selectrum needs to get informed it needs to update the candidate list before the action gets executed because usually this only done on when the input changed). 

Currently you use a lambda for the exit function so I can't use advice. Could you use a named function so I can advice it? Or if you are OK with it even use a variable to bind the function to use, or maybe a hook? This way it would look less hackish in user configuration for selectrum users.

**Comment by clemera** [comment]
Here is what I currently use:

```elisp
(set-transient-map embark--keymap
                   #'embark--prefix-argument-p
                   (lambda ()
                     (setq selectrum--previous-input-string nil)
                     (setq embark--keymap nil)))
```

**Comment by clemera** [comment]
Maybe a cleaner way would be to be to introduce something like `embark-cleanup-hook`.

**Comment by clemera** [comment]
The above isn't optimal because it executes after every following command until `embark--cleanup` gets removed from `post-command-hook`.

**Comment by oantolin** [comment]
I'll make a hook, that seems nicest.

**Comment by clemera** [comment]
Great, thanks!

**Comment by oantolin** [comment]
Wait, rereading the issue I'm confused about something: if you want to update the candidate list (your examples were when deleting or renaming a file), don't you need to do that *after* the action is finished? I believe the transient keymap is removed *before* the action is run (right after the user types the keybinding, but before the binding is executed).

**Comment by clemera** [comment]
> I believe the transient keymap is removed before the action is run (right after the user types the keybinding, but before the binding is executed).

You are right the exit function runs before the action but that is ok. Selectrum checks `selectrum--previous-input-string` in post command hook. When you return from the recursive action call (which has it's own binding for `selectrum--previous-input-string`) the candidates get updated because `selectrum--previous-input-string` for that session is nil.

**Comment by karthink** [comment]
> If you use `embark-act` with selectrum the candidate list shown in the minibuffer does not update

This is also true of the completions buffer. Buffers killed via `embark-act` still remain in the completions list, for example.

**Comment by oantolin** [comment]
> This is also true of the completions buffer. Buffers killed via `embark-act` still remain in the completions list, for example.

I think this might be more trouble than its worth to address. We'd need a way to capture how you compute the list of candidates, not just a snapshot of the list of candidates. If the candidates came from a minibuffer, you'd need to record what command ran, which inputs were passed if any before coming to the minibuffer from which you run the completion, what input string was typed into the minibuffer and which completion styles were in effect at the time (maybe we can ignore the completion styles, assuming most people don't go around changing them all the time). If the candidates came from a completions buffer, you'd need all of that information for the minibuffer that created that completions buffer.

**Comment by oantolin** [comment]
> You are right the exit function runs before the action but that is ok.

I chose the
And thanks for explanation, I figure out it must be something like that, but only after asking you already.

**Comment by clemera** [comment]
Thank you!
