### ISSUE TITLE
Add support for affixation-function

### ISSUE THREAD

**Issue by minad** [oantolin/embark#169]
Should take precedence over the annotation-function.

**Comment by oantolin** [comment]
I won't do this until I can easily install an Emacs that has it. I'd be nervous to add a feature I am unable to test.

**Comment by minad** [comment]
Selectrum already has support and we provide affixation-functions it in Marginalia. But you are right that it is not without problems (https://github.com/minad/marginalia/issues/46). This issue is just to keep it in mind. It does not mean that we have to implement this soon.

**Comment by bdarcus** [comment]
How do these functions impact embark?

**Comment by oantolin** [comment]
They would only be used in embark collect list view, @bdarcus. The affixation function would be used instead of the annotation function to decorate targets. I guess maybe I'd make a 3 column list view: prefix, target, suffix.

**Comment by bdarcus** [comment]
OIC, so without you adding this support, it just means you'd only display the target?

**Comment by minad** [comment]
Oh you added support, thanks!
