### ISSUE TITLE
embark-default-action on command completions

### ISSUE THREAD

**Issue by karthink** [oantolin/embark#17]
`embark-default-action` doesn't DWIM with M-x. 

- M-x find-file
- (optional: call `embark-occur`)
- `embark-act` on target command (`find-file-other-window`, say)
- Call `embark-default-action`

Opens M-x again instead of running `find-file-other-window`.

Perhaps `embark-default-action` should run the thing at point instead on the completion category of `'command`?

**Comment by oantolin** [comment]
> Perhaps `embark-default-action` should run the thing at point instead on the completion category of `'command`?

I decided instead to allow injection into the `M-x` prompt when the command attempting injection is `embark-default-action` (or the directly bound version in the embark occur buffer).

**Comment by karthink** [comment]
Perhaps this should be controlled by `embark-setup-hook` / `embark-allow-edit-defaults` ?

**Comment by oantolin** [comment]
I'm sorry, I don't understand. I thought the change fixed this and it now does DWYM with M-x, but maybe I misunderstood what you meant all along?

**Comment by oantolin** [comment]
Hey, @karthink. Just  friendly nudge: are we done with this issue or do I still have something left to do? As far as I can tell `M-x` now works as you expected before filling the issue, but I'm worried I might be missing some subtlety.

**Comment by karthink** [comment]
`embark-default-action` is now working in a DWIM way when called using `embark-act`. When called using `embark-exit-and-act` (from the completions window), I get:

`Error running timer: (wrong-type-argument commandp nil)`

Tested on `emacs -Q`.

Of course, there is no reason to call `embark-exit-and-act` and then `embark-default-action` when it's the same as simply pressing RET, at least in the completions buffer and minibuffer.

**Comment by oantolin** [comment]
Thanks for reporting that bug! It should now be fixed (972dc5c). I'm closing this issue. As always, feel free to open a new one if I missed anything.
