### ISSUE TITLE
Error with ivy/counsel and using find-file from embark-act

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#170]
I tried using embark with ivy/counsel.  I particularly wanted to use support for files both in the minibuffer and in dired because I want to add file actions that are available in more than just the minibuffer.  However, in both the minibuffer and in dired if I use embark-act I see a the file menu and if I select find-file I get an error with this stack trace.

	Debugger entered--Lisp error: (wrong-type-argument stringp nil)
	  expand-file-name(nil "/Users/hmelman/elisp/")
	  ivy--call-cand(nil)
	  ivy-call()
	  ivy-read("Find file: " read-file-name-internal :matcher counsel--find-file-matcher :initial-input nil :action counsel-find-file-action :preselect nil :require-match confirm-after-completion :history file-name-history :keymap (keymap (remap keymap (undo . counsel-find-file-undo)) (67108960 lambda (&optional arg) "nil (`nil')" (interactive "p") (if (string= "" ivy-text) (execute-kbd-macro (kbd "M-o b")) (self-insert-command arg))) (96 . counsel-file-jump-from-find) (C-backspace . counsel-up-directory) (67108991 . counsel-up-directory)) :caller counsel-find-file)
	  counsel--find-file-1("Find file: " nil counsel-find-file-action counsel-find-file)
	  counsel-find-file()
	  funcall-interactively(counsel-find-file)
	  call-interactively(counsel-find-file nil nil)
	  command-execute(counsel-find-file)
	  #f(compiled-function () #<bytecode 0x1ffaaae8eaf1>)()
	  embark--act(counsel-find-file "hrm-python.el" t)
	  embark-act(nil)
	  funcall-interactively(embark-act nil)
	  call-interactively(embark-act nil nil)
	  command-execute(embark-act)

**Comment by oantolin** [comment]
Ivy has been updated since I last tested the integration, maybe they changed something. I'll look into it.

**Comment by oantolin** [comment]
I do see that error when using `find-file` as an action from dired, but not from the minibuffer. Maybe I need `counsel` to get the error from the minibuffer too.

**Comment by oantolin** [comment]
I wasn't letting one of Ivy's hooks run before exiting the minibuffer. I postponed the exiting until after Ivy's hook and things seem to work here now. So I hope the problem is fixed, though the fact that you also saw the problem in a case I didn't gives me pause.

Please test and let me know if it works for you now. (No rush, you can definitely wait until this last commit is on MELPA.)

**Comment by hmelman** [comment]
Thanks, will try it out.

**Comment by oantolin** [comment]
Great, thanks! (It's on MELPA now, by the way.)

**Comment by hmelman** [comment]
I tried it.  embark-act works fine in a dired buffer.  If I put point on a file and run embark-act and choose find-file, the file opens.  Great.

I tried it in a minibuffer using ivy-mode and it seems like the action is getting called not with the file but its directory.  So if I do M-x find-file, scroll down in ivy to some file, invoke embark-act and hit f to find-file, it runs but opens the file's directory.  If I use embark-act to choose load-file I get an error about loading a directory.

It's been a while since I used my ivy config, but I did try to just enable ivy and not counsel or ivy-rich and saw the same behavior.  I'm using latest of everything as found on melpa on Emacs 27.1 (mac port).

**Comment by oantolin** [comment]
I can't seem to reproduce that problem @hmelman, here file actions seem to be working fine with ivy. I'll try installing counsel (although you did say you see the same issue with just ivy).

Embark is supposed to work out of the box with Ivy now, so you should not have any integration code in your configuration. If you do have some integration code in your configuration the bug might be there.

**Comment by hmelman** [comment]
Ok, maybe I'm confused about ivy since I've been using selectrum for a while.  With ivy-mode, if I do find-file, I get a prompt, the current directory is in the input and am shown several filenames in the minibuffer.  If I use C-n and C-p to navigate those choices and hit RET, the highlighted file is opened.  If instead of hitting RET I invoke embark-act and then f (find-file), the highlighted file is not opened but the directory in the input is.

I have ivy and embark installed via package.el and I've commented out my configuration code and config with just `M-x ivy-mode` and `(global-set-key (kbd "s-/") 'embark-act)`. counsel is installed but `counsel-mode` variable is nil.  Same for ivy-rich.  There are a few ivy vars set in my custom file but they seem to be appearance stuff. I see both of these embark ivy functions in the hooks so that's getting loaded properly.

    (add-hook 'embark-target-finders #'embark-target-ivy-selection)
    (add-hook 'embark-candidate-collectors #'embark-ivy-candidates))

Can you describe exact steps you're trying so I can try them?

**Comment by oantolin** [comment]
Oh, I made the mistake of not testing in `emacs -q`. I can now reproduce the problem with these steps:

- `emacs -q`
- `M-x package-initialize`
- `M-: (global-set-key (kbd "s-/") 'embark-act)`
- Then `find-file` as you described.

And `embark-target-ivy-selection` is at the top of the list, and if called directly from the minibuffer (enable recursive minibuffers first, then use `M-: (embark-target-ivy-selection)` from within `find-file`) does return the correct answer. Mysterious.

**Comment by hmelman** [comment]
Cool.  Let me know if you need more info from me.

**Comment by oantolin** [comment]
It's weird: in my personal configuration where calling `find-file` as an action from the minibuffer does open the file, I still do see the directory-opening problem when using `find-file` as an action for a file at point in a regualr buffer.

**Comment by oantolin** [comment]
OK, I'm not too happy about that fix, but I believe it works. Please test it when you get the chance, @hmelman.

**Comment by hmelman** [comment]
Seems to work.  Thanks!
