### ISSUE TITLE
Add support for group-function

### ISSUE THREAD

**Issue by minad** [oantolin/embark#172]
I don't have a patch for Embark yet. You mentioned that collapsing would be interesting to have, is there some existing facility to be used for this, provided by tablist? Or was the idea to implement this by hand using 'invisible and creating a separate button?

**Comment by oantolin** [comment]
I don't tabulated-list-mode has anything to be used for this. Maybe tablist does (I think it probably doesn't either, but am not sure), but I don't want to depend on it. My plan was to use `invisible` and a button, as you suggest.

**Comment by minad** [comment]
Duplicate #389
