### ISSUE TITLE
Inconsistent results when called on a filename with spaces in dired

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#173]
In a dired buffer I put point on a filename containing space like so:

    -rw-r--r--   1 hmelman staff 8.7K Jan 15 19:57 Sculpt Snow.md

If I have point in the word Sculpt and invoke embark-act it finds the full pathname (I call embark-save and paste in another buffer).  However if I have point in the word Snow and do the same it just finds the word "Snow".  If I have point in the "md and do the same it just finds the word "md".

**Comment by oantolin** [comment]
Thanks for reporting! I was trusting ffap to do the right thing, but of course in dired we can do better. I changed it so it correctly gets the full file name anywhere on the line of a file in dired.

I am a little surprised that ffap only finds the file name when point is on the first word. I should test for file names in strings in programming buffers.

**Comment by hmelman** [comment]
Works! thanks.
