### ISSUE TITLE
Add a new category / type

### ISSUE THREAD

**Issue by ecraven** [oantolin/embark#174]
Sorry if this is an obvious question, but how do I add a new category? I add it to `embark-keymap-alist`, that part I think I understood, but how do I get emacs to provide the necessary metadata? For example, I'd like to add a metadata category of "password" for `M-x password-store-copy` and related functions. `completing-read` does not seem to take a category as a parameter. Where is this actually set?
Thanks for any help with this, embark is a great package!

**Comment by ecraven** [comment]
Do I assume correctly that I should set `marginalia-command-categories`to something like `((password-store-copy . password))` and then use `password` as a category in `embark-keymap-alist`?

**Comment by minad** [comment]
See this example in the readme: https://github.com/oantolin/embark#telling-embark-about-commands-that-prompt-for-tabs-by-name

~~~ elisp
(defun my-select-tab-by-name (tab)
  (interactive
   (list
    (let ((tab-list (or (mapcar #'(lambda (tab) (cdr (assq 'name tab)))
                                (tab-bar-tabs))
                        (user-error "No tabs found"))))
      (completing-read
       "Tabs: "
       (lambda (string predicate action)
         (if (eq action 'metadata)
             '(metadata (category . tab))
           (complete-with-action action tab-list string predicate)))))))
  (tab-bar-select-tab-by-name tab))
~~~

The category is returned when the lambda is called with the action `'metadata`.

> Do I assume correctly that I should set marginalia-command-categoriesto something like ((password-store-copy . password)) and then use password as a category in embark-keymap-alist?

If you want to add a completion category to an existing command you can either use `marginalia-command-categories` or the prompt classifier in Marginalia, which catches more cases.

**Comment by ecraven** [comment]
Thanks, I just found my error, I bound my testing command to "RET", which is always overwritten with the default action, so I never actually saw it... 
Thank you for helping with this!
