### ISSUE TITLE
dired-jump is not known to be defined

### ISSUE THREAD

**Issue by minad** [oantolin/embark#178]
package-lint shows this warning. Autoload dired-x?

**Comment by oantolin** [comment]
I'm surprised! I actually did make sure to check that `dired-jump` had an autoload cookie on [Emacs 25](https://github.com/emacs-mirror/emacs/blob/c3ff6712ad24fcf45874dc0665a8606e9b2208a4/lisp/dired-x.el#L409), [Emacs 26](https://github.com/emacs-mirror/emacs/blob/7497ee44b471f69ce59d131a6dece261e871534f/lisp/dired-x.el#L473) and [Emacs 27](https://github.com/emacs-mirror/emacs/blob/ed2b23ecc10925b5b29ab13949a5d154c7d0cbe6/lisp/dired-x.el#L456). Are the autoloads for `dired-x` ignored somehow? Is this a bug in the linter?

**Comment by hmelman** [comment]
I'm on Emacs 27 and while it does have an autoload, it's in dired-x.el and I think I have to load dired-x explicitly.  My understanding is that in Emacs 28 it's been moved to dired.el.

**Comment by minad** [comment]
It has an autoloading cookie but it is somehow ignored?! This is indeed the case in my Emacs 27 installation.

**Comment by minad** [comment]
https://www.gnu.org/software/emacs/manual/html_mono/dired-x.html "Optional Installation Dired Jump" :eyes:

**Comment by oantolin** [comment]
Does this placate the linter on Emacs 27?

```elisp
(unless (fboundp 'dired-jump)
  (autoload 'dired-jump "dired-x"))
```

**Comment by minad** [comment]
> Does this placate the linter on Emacs 27?

No. With the `fboundp` it does not work.

**Comment by oantolin** [comment]
> If you use only the `autoload` does it make problems on Emacs 28?

No, it does find it in `dired.el` even if I autoload it from `dired-x`. I guess if an autoload exists a second one is ignored. I'll put in the autoload for now.
