### ISSUE TITLE
embark-exit-and-act UI

### ISSUE THREAD

**Issue by clemera** [oantolin/embark#18]
When executing `embark-exit-and-act` the minibuffer closes immediately and if the action invokes the minibuffer again it reopens. With selectrum the minibuffer bumps down and after you invoke the action bumps up again. Ideally one would keep the minibuffer open to avoid the visual noise and also the target wouldn't vanish in front of your eyes before you press the action key but that doesn't seem to be possible within the constraints of the minibuffer API. 

Emacs wouldn't be Emacs if there wouldn't be a way to get what you want ;) I experimented a bit and found a way to avoid that visual noise:

```elisp
(add-hook 'embark-pre-action-hook
          (lambda () (setq inhibit-redisplay nil)))

(defun embark-exit-and-act ()
  "Exit the minibuffer and embark upon an action."
  (interactive)
  (run-at-time 0 nil (lambda ()
                       (setq inhibit-redisplay t)))
  (embark--setup)                       ; setup now
  (run-at-time 0 nil #'embark--start)   ; start action later
  (top-level))
```

Note that with selectrum the embark act `message` triggered from `embark--start` shows in the echo area and does not flash the prompt. But if a message is shown could be configurable as well. 

The only problem I have with this hack is that I haven't figured out how to still show the `which-key` help with this. Now I'm not sure how you think about including this but maybe this could be an opt-in user option. Or maybe there are better ways to get the desired behaviour?

**Comment by clemera** [comment]
Another possible hack would would be to wait until the transient map exits before going back to top level, that would avoid dealing with display hacks as above and which key help works as usual:

```elisp
(set-transient-map embark--keymap #'embark--prefix-argument-p
                     (lambda ()
                       (setq embark--keymap nil)
                       (run-hooks 'embark-pre-action-hook)
                       (when exit
                         (run-at-time 0 nil
                                      (let ((cmd this-command))
                                        (lambda ()
                                          (let ((this-command cmd))
                                            (command-execute cmd)))))
                         (top-level))))
```

**Comment by oantolin** [comment]
> the target wouldn't vanish in front of your eyes before you press the action key 

Wait, does it vanish? There is supposed to be an "Act on '_target_'" message visible.

Well, even if it is visible, you probably want to avoid the closing and opening of the minibuffer anyway. I'll test your fix and report back.

**Comment by clemera** [comment]
That was poorly phrased, there is a message but the minibuffer closes before you press the action key (the feeling that it "vanishes" is probably stronger with selectrum where the prompt isn't right above the echo area). With the code above the minibuffer stays open until you pressed the action key. If it then reopens immediately it you won't notice that it closed.

**Comment by oantolin** [comment]
Your code worked great. It's an improvement even for non-selectrum users, because now embark-cancel really cancels the whole thing, including the exiting.

I also took the opportunity to bring bask the prefix argument to `embark-act` to mean "exit too", and added a prefix argument to `embark-exit-and-act` to mean "don't actually exit". The idea is that people that use both variants can just bind both to keys, but people who most of the time use only one, can bind just it and the other is but `C-u` away.

**Comment by clemera** [comment]
Very nice, thanks. Now the menu behaviour is mostly like with `ivy-actions`. I had to update something that I also added previously to the wiki:

```elisp
(advice-add #'embark--bind-actions
            :after
            (defun embark-wk-help+ (&rest _)
              (let ((which-key-show-transient-maps t))
                (which-key--update))))
```
Maybe there could be user option `embark-show-wk-immediately` or something like that?
