### ISSUE TITLE
Many embark keymaps are not available

### ISSUE THREAD

**Issue by karthink** [oantolin/embark#181]
My `embark-keymap-alist` is as follows:

```elisp
((project-file . embark-file-map)
 (file . embark-file-map)
 (environment-variables . embark-file-map)
 (url . embark-url-map)
 (buffer . embark-buffer-map)
 (identifier . embark-identifier-map)
 (symbol . embark-symbol-map)
 (command . embark-command-map)
 (variable . embark-variable-map)
 (minor-mode . embark-command-map)
 (unicode-name . embark-unicode-name-map)
 (package . embark-package-map)
 (bookmark . embark-bookmark-map)
 (region . embark-region-map))
```

Out of these, the following are activated when running relevant commands: `find-file`, `consult-buffer`, etc:

`embark-file-map`, `embark-buffer-map`, `embark-unicode-name-map`, `embark-region-map`.

The rest are not available, and which-key shows me only the commands in `embark-general-map`. So Embark shows me nothing beyond these when I run `execute-extended-command`, for instance.

I've verified that they're actually not available and that this isn't a failure of `which-key` to show them. I'm running emacs 27.1, and the vanilla completion system + embark live occur (no icomplete/selectrum etc). I haven't messed with the completion categories system in any way. I'm probably doing something stupid, but can't figure it out!

**Comment by minad** [comment]
Marginalia?

**Comment by oantolin** [comment]
Long ago Embark contained some code to enhance built-in commands to report the appropriate completion category. This code was moved into the Marginalia package. Just install Marginalia and activate `(marginalia-mode)` and Embark will offer you the correct actions, @karthink.

**Comment by karthink** [comment]
Yup, turning on marginalia-mode fixed it! Thanks.

Shouldn't the code that reports the appropriate completion category be upstreamed into Emacs? Right now it appears to be inconsistently applied.

**Comment by karthink** [comment]
> Shouldn't the code that reports the appropriate completion category be upstreamed into Emacs? 

I take this back. I just took a look at how Marginalia finds the completion categories for various commands, and it looks like it's mostly based on regexp matching in `marginalia-prompt-categories`. (`marginalia-command-categories` is almost empty.)

**Comment by minad** [comment]
> Yup, turning on marginalia-mode fixed it! Thanks. I had it turned off since I use the grid arrangement in most kinds of embark live occur buffers.

If you want to turn off annotations, cycle the annotators to the `nil` annotator. But marginalia mode should never be turned off because of Embark.
