### ISSUE TITLE
Inserting the candidate string to the buffer

### ISSUE THREAD

**Issue by linwaytin** [oantolin/embark#184]
First, thanks for this package. 
I'm not sure if this question can be asked here. If it's not appropriate, please let me know.

I'm using `consul` and like its preview functionality.
Sometimes I want to insert the candidate as a string to the buffer, instead of the default action defined by `consult`. 
Is this easy to achieve with this package?
The doc describes how to define my own action but it's not quite clear to me (I'm new to elisp programming, sorry.)

**Comment by oantolin** [comment]
Well, there is the `embark-insert` action which may be what you are looking for. It's bound to `i` in most cases (and to `I` in a few cases like for packages where `i` means install).

**Comment by linwaytin** [comment]
Fantastic! That's almost what I want.
Is it possible to write a function to transform the string?

**Comment by oantolin** [comment]
Yes, of course. Emacs Lisp is a normal programming language. You can write a function to do any sort of transformation you wish.

**Comment by oantolin** [comment]
It seems to me we can probably close this issue now. Let me know if I'm wrong about that.

**Comment by linwaytin** [comment]
Sorry I am busy this week. I will try the user-defined functions and let you know if I have problems. Thank you for answering my questions.
