### ISSUE TITLE
DOC: embark-define-keymap docstring should mention RET handling

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#188]
I think the docstring for `embark-define-keymap` should include a note about the special handling of RET as described in the docstring of `embark-default-action`. As mentioned [in this comment](https://github.com/minad/consult/issues/6#issuecomment-804936478), someone writing a new keymap might not know to look at the `embark-define-keymap` docstring.

**Comment by oantolin** [comment]
Yes, good point. Will do.
