### ISSUE TITLE
question: general.el/which-key menus, doom integration?

### ISSUE THREAD

**Issue by bdarcus** [oantolin/embark#197]
I was just wondering:

Given the work on a selectrum et al module for doom, which includes embark, and that doom uses general.el for kb/map configuration and which-key for menus, I was just wondering if that has an implications for embark integration?

Here's what the kb files for evil and vanilla respectively:

- https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/+evil-bindings.el
- https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/%2Bemacs-bindings.el

If a doom module defines kbs, can and should those be used for the `embark-act`?

Or am I overthinking this?

PS - my understanding is this module is planned for merger in the next release (3.0).

https://github.com/hlissner/doom-emacs/pull/4664

**Comment by minad** [comment]
I assume there are no implications. Embark keymaps are normal keymaps and general is managing normal keymaps. It should be possible to use general to define Embark keymaps.

**Comment by bdarcus** [comment]
So once the selectrum module is merged, if i'm adding my package to their biblio module, I would want to define the doom keybindings, and use _that_ in `embark-keymap-alist`; right?

And that may be the right strategy with other modules, depending on the details of the respective packages and commands?

**Comment by oantolin** [comment]
I guess Embark could support which-key's replacements, I wouldn't oppose such a change. It does already support Emacs' "simple menu items", where instead of binding a key to a command, you bind it to a pair of the form `("Description" . command)`. (I think which-key should drop its replacement mechanism and instead support those; I also think @minad told me it was supposed to gain support for simple menu items --probably not dropping it's own mechanism.)

**Comment by bdarcus** [comment]
> I also think @minad told me it was supposed to gain support for simple menu items

Oh, I didn't know this, but now see this PR:

https://github.com/justbur/emacs-which-key/pull/282

I suppose best all around would be for that PR to be merged, and then the doom `map!` macro to make use of that instead of the which-key specific replacement?

cc @hlissner

**Comment by bdarcus** [comment]
> It does already support Emacs' "simple menu items", where instead of binding a key to a command, you bind it to a pair of the form `("Description" . command)`.

I was mainly wanting to raise the larger doom issue, but this should work?

``` elisp
(defvar bibtex-actions-map
  (let ((map (make-sparse-keymap "BibTex actions")))
    (define-key map "o" '("Open pdf or link" . bibtex-actions-open))
    (define-key map "p" '("Open pdf" . bibtex-actions-open-pdf))
    (define-key map "l" '("Open link" . bibtex-actions-open-link))
    (define-key map "c" '("Insert citation" . bibtex-actions-insert-citation))
    (define-key map "r" '("Insert reference" . bibtex-actions-insert-reference))
    (define-key map "k" '("Insert citekey" . bibtex-actions-insert-key))
    (define-key map "b" '("Insert bibtex" . bibtex-actions-insert-bibtex))
    (define-key map "t" '("Add pdf attachment" . bibtex-actions-add-pdf-attachment))
    (define-key map "n" '("Open notes" . bibtex-actions-open-notes))
    (define-key map "e" '("Open bibtex entry" . bibtex-actions-open-entry))
    (define-key map "a" '("Add pdf to library" . bibtex-actions-add-pdf-to-library))
    map)
  "Keymap for 'bibtex-actions'.")
```

I get this error:

``` elisp
embark-completing-read-prompter: Invalid function: ("Add pdf to library" . bibtex-actions-add-pdf-to-library)
```

**Comment by oantolin** [comment]
Yep, that was supposed to work. I'll look into why it didn't.

**Comment by oantolin** [comment]
I don't know what's happening, that works here. Maybe you have an out of date embark?

**Comment by bdarcus** [comment]
> I don't know what's happening, that works here. Maybe you have an out of date embark?

Yeah, I think that's it.

I test with the test scripts in the selectrum repo. But it seems I have to manually update the packages.

**Comment by bdarcus** [comment]
Another thought (cc @Emiller88):

When using descriptions rather than commands, it's easier to lose the contextual commands amidst the list of more general embark commands.

So by default in the Doom module, the embark map should either hidden, or (better?) placed in a submenu.

Given embark already supports simple menus, perhaps this could be a defcustom here?

**Comment by bdarcus** [comment]
>  it works fine with the default embark menu, but not with which-key ...

Tested with Emacs 27.1 and 28, and same behavior.

**Comment by oantolin** [comment]
Indeed I would not expect that to work with which-key, since as we discussed it does not yet support simple menu items, and I believe that is indeed one of the things that PR you linked is supposed to fix.

But maybe you can combine both approaches for now? Add a `:desc` for which-key and also use simple menu items for embark? I'm not familiar with Doom's `map!` command, so I have no idea if that works. If it doesn't, one can still create the weird which-key pseudo keys manually.

**Comment by bdarcus** [comment]
> maybe you can combine both approaches for now? Add a `:desc` for which-key and also use simple menu items for embark? 

Yeah, that's likely the only way until which-key support simple menus. So I shouldn't add simple menus to my project until that happens.

> I'm not familiar with Doom's `map!` command, so I have no idea if that works. If it doesn't, one can still create the weird which-key pseudo keys manually.

The `map!` macro does indeed create the psuedo keys from the `desc` properties; that what drives doom's menus.

That's what prompted this issue; just wondering how this should ideally work, so that doom menus and embark-act menus are consistent.

**Comment by oantolin** [comment]
I think I wasn't very clear. Concretely, I was wondering if this works in Doom?

```elisp
(map!
 :leader
 :map bibtex-actions-map ; I don't understand what this line does exactly
 :prefix ("B" . "biblio")
 :desc "Insert bibtex"         "b" '("Insert bibtex" . bibtex-actions-insert-bibtex)
 :desc "Insert citation"       "c" '("Insert citation" . bibtex-actions-insert-citation)
 :desc "Insert citekey"        "k" '("Insert citekey" . bibtex-actions-insert-key)
 :desc "Open pdf or link"      "o" '("Open pdf or link" . bibtex-actions-open)
 :desc "Open link"             "l" '("Open link" . bibtex-actions-open-link)
 :desc "Open pdf"              "p" '("Open pdf" . bibtex-actions-open-pdf)
 :desc "Open bibtex entries"   "e" '("Open bibtex entries" . bibtex-actions-open-entry)
 :desc "Open notes"            "n" '("Open notes" . bibtex-actions-open-notes))
```

**Comment by oantolin** [comment]
By the way, the line with the comment just says to store the created keymap in the variable `bibtex-actions-map`. The macro  then binds `B` to that keymap. (As I said, I don't use Doom, but if this guess is wrong, whoever wrote that macro is a little crazy 😛.)

**Comment by bdarcus** [comment]
> I was wondering if this works in Doom?

By works do you mean in the doom menus alone?

Yes.

I tried to change the name of the map, and bind embark-act to that, but got a void symbol error. Were you speculating that might work?

I can experiment a bit more.

**Comment by oantolin** [comment]
No, I was asking if the code in my last comment showed the descriptions in both which-key and the embark-completing-read-prompter.

If you got an error when you changed the name of the map, maybe its because Doom's `map!` macro needs the variable to already exist, in which case you can probably just stick a `(defvar new-map-name (make-sparse-keymap))` above the `(map! ...)` form. (I'm sorry I can't be of more help, but Doom seems pretty alien and a bit of a hassle to install.)

**Comment by bdarcus** [comment]
> I was asking if the code in my last comment showed the descriptions in both which-key and the embark-completing-read-prompter.

I'll double-check when I get a chance, but I'm assuming yes.

WDYT about my thought for a way to customize the menu display of the embark commands?

**Comment by oantolin** [comment]
> WDYT about my thought for a way to customize the menu display of the embark commands?

Do you mean about being able to hide the general actions? I do want to add that option.

**Comment by bdarcus** [comment]
> Do you mean about being able to hide the general actions? I do want to add that option.

Yes.

And maybe also allow them to be placed in a submenu.
