### ISSUE TITLE
embark-target-collect-candidate strips text properties

### ISSUE THREAD

**Issue by jakanakaevangeli** [oantolin/embark#205]
Text properties are needed when operating on targets in collect buffers of type
consult-multi.

Perhaps `(button-label (point))` should be replaced with something like
```elisp
(buffer-substring (button-start (point))
                  (button-end (point)))
```

**Comment by oantolin** [comment]
I had that code before and forgot why!

**Comment by oantolin** [comment]
I should have done this sooner, but I had a busy week.

**Comment by jakanakaevangeli** [comment]
Thanks!
