### ISSUE TITLE
Args out of range error in grep mode buffer

### ISSUE THREAD

**Issue by minad** [oantolin/embark#209]
Exported from `consult-ripgrep`, then after a while I observed this issue repeatedly.

~~~ elisp
Debugger entered--Lisp error: (args-out-of-range 0 0)
  get-text-property(0 compilation-directory)
  compilation-find-file(#<marker at 1 in  *temp*> "lisp/tab-bar.el" nil)
  apply(compilation-find-file #<marker at 1 in  *temp*> "lisp/tab-bar.el" nil nil)
  compilation-next-error-function(0 nil)
  next-error-internal()
  compile-goto-error()
  embark-consult-goto-location("lisp/tab-bar.el:1465:     (list (completing-read")
~~~

Then there is a weird effect where two windows are opened with the same content if pressing RET on the candidates.

**Comment by oantolin** [comment]
So far I've been unable to reproduce with `consult-grep`, maybe this bug somehow only happens with `ripgrep`?

The double window problem sounds like something that happened before and that I believe I fixed. See the comments starting [here](https://github.com/oantolin/embark/pull/158#issuecomment-782466237).

**Comment by minad** [comment]
I think I was wrong and the error was in a snapshot buffer since it uses `embark-consult-goto-location`? But I think we should just replace this function at some point. We had some many issues with this.

**Comment by oantolin** [comment]
> I think I was wrong and the error was in a snapshot buffer

Oh, that's what I testing with, since I remembered the earlier error I linked to. I didn't even notice you said "export"!

**Comment by minad** [comment]
You probably looked at the stack trace and assumed the correct thing.

**Comment by minad** [comment]
Not seeing this issue anymore. I will reopen another more detailed report when I see the issue again. I should have directly investigated this a bit better.

**Comment by oantolin** [comment]
Sure, I tried to reproduce but couldn't, but definitely reopen if you see this again.
