### ISSUE TITLE
Mention vertico in the manual

### ISSUE THREAD

**Issue by DamienCassou** [oantolin/embark#211]
Hi,

I'm reading the embark's manual and am surprised to see no mention of [vertico](https://github.com/minad/vertico). For example, the "Quick start" section mentions the Emacs' default tab completion, icomplete, fido, Selectrum and Ivy but not vertico.

**Comment by oantolin** [comment]
Will do! The only reason it isn't mentioned is that the manual hasn't been updated since before Vertico existed. 😄

**Comment by DamienCassou** [comment]
Thank you!
