### ISSUE TITLE
Add support for project-file type

### ISSUE THREAD

**Issue by DamienCassou** [oantolin/embark#214]
[Marginalia](https://github.com/minad/marginalia) seems to correctly associate the `project-file` type to the `project-find-file` command. Would it be possible to have support for this type in embark as well?

**Comment by minad** [comment]
Sure! Which actions do you want? Shouldn't be a problem to add an embark keymap which derives from the usual file keymap and adds special project file actions.

**Comment by DamienCassou** [comment]
I think the equivalent of `embark-file-map` would be a good start. I tried to use the `embark-file-map` for `project-file` directly, but there is indeed a mismatch as filenames arrive broken:

```js
{project}/{pathWithinProject}{pathWithinProject}{filename}
```

The `{pathWithinProject}` part appears twice in commands.

**Comment by oantolin** [comment]
I added a transformer to get full paths of project files. This allows you to use all file actions, maybe that's already good enough?

Note that this has the same limitation as the partial support in marginalia for project files: you can call `project-find-file` from outside all projects, in which case it prompts you for a project first; in that case there is no current project so neither marginalia nor embark can figure out yet what the correct path is.

**Comment by jakanakaevangeli** [comment]
> I added a transformer to get full paths of project files.

Genius, thanks.

**Comment by oantolin** [comment]
What do you think @DamienCassou, does anything more need to be done here?

**Comment by DamienCassou** [comment]
I think we should close the issue as what you did works perfectly fine for me! Thank you very much.
