### ISSUE TITLE
embark-collect: Add option to remove collected candidates

### ISSUE THREAD

**Issue by mohkale** [oantolin/embark#220]
This might be related to #117.

I often like to run `M-x some-package-prefix` and then `embark-collect-snapshot` to get a list of the interactive functions in a package (or just matching any general search term). Then I like to look through all of them, cross out the ones I've covered or am no longer interested in and then delete the embark-collect buffer.

Is there a command that would let me remove entries from the collected list?

**Comment by oantolin** [comment]
Feel free to use `C-x C-q` to toggle `read-only-mode` and delete any entries you want! If you want to bring the deleted entries back, just press `g` to revert the buffer, or toggle between grid and list view with `M-q`.

You can also install politza's neat tablist package which lets you mark rows and delete them with dired-like keybindings. That package is row-oriented so it's really only appropriate for Embark's list view (I mean, you can use it with grid view, but it would act on an entire row of targets at a time). Using tablist does not require turning off `read-only-mode`.

If you want to narrow focus to a subset of lines based on a search pattern, I recommend Consult's `consult-focus-lines` command, for which you don't need to turn off `read-only-mode` either. The built-in `keep-lines`  and `flush-lines` commands, as well as their more interactive Consult counterpart, `consult-keep-lines`, also work well if you do turn off `read-only-mode`. Note that all of the commands mentioned in this paragraph are line-oriented, so you'd probably want to use them only in Embark collect list view.

**Comment by mohkale** [comment]
@oantolin 

Yep, this works well enough for this use case.
