### ISSUE TITLE
Behavior of 'revert' in snapshots / naming snapshot buffer

### ISSUE THREAD

**Issue by publicimageltd** [oantolin/embark#223]
I like to create snapshots for my Zettelkasten notes with `embark-collect-snapshot`. I think it's a great concept and a great tool! There are some things, however, I do not understand, plus some issues with lacking user feedback. So I hope that issue is the appropriate place to discuss this.

My problem is: If I revert the snapshot buffer, nothing changes, even in cases where the completion query would actually return another result list. My expectation was that together with the snapshot, also the completion input (query) would be stored, so that reverting the buffer actually repeats the query in the background (it's not a live collect buffer) and re-inserts the result. But that does not happen. So am I missing something, or did I misunderstand the functionality?

Another point is that my use case can produce quite a bit of buffers. So I am proposing an option to give them a telling name based on the query, e.g. `*Embark Collect 'this or that !not'*). This way, one could more easily find and identify the snapshot buffer. Additionally the query could be displayed in the header line of the snapshot.

**Comment by oantolin** [comment]
This improved behavior of revert, rerunning the query has already been requested. I agree it is a an excellent idea and I just haven't had time to implement it yet.

Same for more unique names for the buffers: it's been suggested, I agree it is a good idea but I haven't done it yet. I hope to do both things soon.

**Comment by oantolin** [comment]
See #171.

**Comment by publicimageltd** [comment]
Oh great! Thanks for the answer. I'll close this issue, then, since there is one already open. But please do ping me if this feature is installed, or if it can be tested from a separate branch; I'll love to help as much as possible. I think the ability to create collections is a killer feature, seriously.
