### ISSUE TITLE
Add `find-file-as-root` action

### ISSUE THREAD

**Issue by CIAvash** [oantolin/embark#225]
Helm and Counsel have this, and I think it's a useful action to have.

**Comment by oantolin** [comment]
For this I recommend installing [sudo-edit](https://github.com/nflath/sudo-edit) and adding it to the file action map: `(define-key embark-file-map "s" #'sudo-edit)`. (This is an example in the wiki, I believe.)

I'd rather not reimplement something like `sudo-edit` in Embark. If it were just concatenating `/sudo:` in front of the path, maybe, but the syntax is a little more tricky than that and the sudo-edit package already has the details right.

**Comment by kira-bruneau** [comment]
In case anyone else runs into this, I had to bind `sudo-edit-find-file` instead of `sudo-edit` to get this to work:

```elisp
(use-package embark
  :bind*
  (("C-." . embark-act)
   ("C-," . embark-dwim)
   ("C-h B" . embark-bindings)

   :map embark-file-map
   ("s" . sudo-edit-find-file)))
```
