### ISSUE TITLE
Proposal about mini-frame integration

### ISSUE THREAD

**Issue by BooAA** [oantolin/embark#227]
I dig into embark's code and try to find out how to make mini-frame work with embark, here is my attempt:

1. Disable mini-frame when the action is not allowed to edit the input and when the action will quit minibuffer immediately. That is, something like below show be added before embark execute action.
```elisp
(when (and (not allow-edit) quit)
  (mini-frame-mode -1))
...
(command-execute action)
```

2. Re-enable mini-frame after injecting inputs, this is simple, just
```elisp
(add-hook 'embark-setup-hook (lambda () (mini-frame-mode 1))
```
3. Make action in embark collect buffer explicitly quit minibuffer, e.g.
```elisp
;; in embark--action-command
(fset name (lambda ()
                 (interactive)
                 (embark--act action (cadr (embark--target)) t))) ; set quit t here

;; in embark-collect-choose
...
(embark--act (embark--default-action embark--type) text t)` ; set quit t here
...
```

Only (3) is necessary and needs changes in embark's code. (2) is trivial. For (1), we need some ways to dynamically capture those variable (`allow-edit` and `quit`) in order to make decision, my elisp knowledge is limited and don't know any elegant way to do this (elisp doesn't support using macro as hook so macro expansion capturing may not work here), below is what I use in my config now
```elisp
(use-package embark
  :custom (embark-prompter 'embark-completing-read-prompter)
  :bind ("C-;" . embark-act)
  :hook (embark-collect-mode . embark-collect-direct-action-minor-mode)
  :config (require 'embark-consult))

(defun embark-mini-frame-disable ()
  (mini-frame-mode -1))

(defun embark-mini-frame-reset ()
  (remove-hook 'embark-pre-action-hook #'embark-mini-frame-disable)
  (mini-frame-mode 1))

(defun embark-mini-frame-detect (action target &optional quit)
  (unless (memq action '(embark-become
                         embark-collect-live
                         embark-collect-snapshot
                         embark-collect-snapshot
                         embark-export))
    (let ((allow-edit (if embark-allow-edit-default
                        (not (memq action embark-skip-edit-commands))
                        (memq action embark-allow-edit-commands))))
      (when (and (not allow-edit) quit)
        (add-hook 'embark-pre-action-hook #'embark-mini-frame-disable)))))

(advice-add #'embark--act :before #'embark-mini-frame-detect)
(add-hook 'embark-setup-hook #'embark-mini-frame-reset)

```

What do you think?

**Comment by minad** [comment]
This looks interesting. You may want to put it in the wiki? The which-key integration is described there too.

**Comment by BooAA** [comment]
Sure, I will do that if (3) can be added to embark, which is the minimum requirement to make mini-frame work when acting on target in embark collect buffer. I see no harm to do so, but maybe @oantolin will have different opinion.

**Comment by minad** [comment]
> Sure, I will do that if (3) can be added to embark, which is the minimum requirement to make mini-frame work when acting on target in embark collect buffer. I see no harm to do so, but maybe @oantolin will have different opinion.

Oh okay I see. I am not sure what kind of negative side effects this has in other scenarios. Can you tell?

**Comment by BooAA** [comment]
To make mini-frame work with embark seamlessly, there are several situation to consider:

Case 1. When the action allow user to edit the input further, mini-frame should on, (ex, the `delete-file` action)

Case 2. When the action ask user for more than one arguments, then mini-frame should toggle after embark inject the target as first argument. (ex the `copy-file` action).

Case 3. When the user don't want to exit minibuffer after taking action (e.g. when the `quit` argument in `embark--act` is `nil`)

Case 4. For `embark-act` on target in normal buffer, mini-frame should be disable before the action and toggle after, otherwise there will be a flash of child frame when embark injects the content and exits immediately.

We cannot just disable mini-frame before the action and toggle it after, this way case 2 will not work, the prompt for second and the rest argument will stay in normal minibuffer, which I think is not desirable for mini-frame user.

(3) is actually IMO a bug fix for embark, since I see no reason why the `quit` argument is not set when embark is acting on target in normal buffer. (e.g. the result of `embark-snapshot` and `embark-export`). I find this behavior against my intuition when tracing embark's code, but I'm not sure whether this is intended or not.

> it should suffice to set up mini-frame around the embark-completing-read prompter

Never tried this.


BTW, @minad do you have any plan to make another child frame package? :smile:

**Comment by minad** [comment]
> BTW, @minad do you have any plan to make another child frame package?

Actually I have some child frame code lying around which can be used by Vertico and is more robust than mini-frame. However it is Vertico-specific and I am not very interested in using this. I am happy with Vertico in the minibuffer and Corfu for completion popups. So this code may never make it into a proper package, except someone comes along genuinely interested in maintaining such functionality.

**Comment by BooAA** [comment]
>  However it is Vertico-specific and I am not very interested in using this.

Have you consider putting this to vertico's wiki or public somewhere? I'm interested in switching to vertico from selectrum + mini-frame, this may help other child frame users as well.

**Comment by minad** [comment]
No, this code is unpolished. If you are interested you can give it a try: https://gist.github.com/minad/bc68d0b01c8056b45e58da93196ca6bb

See also the Corfu code as reference for child frames: https://github.com/minad/corfu/blob/a56e80e152a555afebe6b8ca1d0963ce4cb93b5f/corfu.el#L202

**Comment by BooAA** [comment]
> https://gist.github.com/minad/bc68d0b01c8056b45e58da93196ca6bb

Try this a bit, all problems mentioned above doesn't exist in vertico-popup, quite amazing. I will play around with it, thanks.

**Comment by oantolin** [comment]
> (3) is actually IMO a bug fix for embark, since I see no reason why the `quit` argument is not set when embark is acting on target in normal buffer.

It's not set because there is no minibuffer to quit in that case. The quit parameter is completely irrelevant for those cases (for non-miniframe users), so I have no problem in setting it if makes your miniframe integration easier. I could also make some dynamic variables to store whether editing is allowed and whether the action should quit. With that pair of changes you should be able to do all the integration with the provided hooks, right?

**Comment by BooAA** [comment]
> With that pair of changes you should be able to do all the integration with the provided hooks, right?

Yes, if so then we can add those detection code in `embark-pre-action-hook` and things become much easier.

**Comment by oantolin** [comment]
> BTW, if action fails or gets canceled somehow, hooks after that will not be executed, right? (like `embark-post-action-hook`). Do you think we need a `embark-cleanup-hook` or `embark-exit-hook` to let user make sure their settings can be recovered?

Oh. That's correct! I could have sworn the post action hook was outside the bodyform of the unwind-protect. I meant for it to be run even if there was a problem with the action, but put a parenthesis in the wrong place. I think I'll just make sure the post action hook always runs, and add a separate cleanup hook only if someone requests it.

**Comment by minad** [comment]
@oantolin It seems to be okay to close this one, since it hasn't been updated for a long time.
