### ISSUE TITLE
consult-multi actions are not provided in the *Completions* buffer

### ISSUE THREAD

**Issue by minad** [oantolin/embark#228]
In the Embark collect buffers it works. I have not yet figured out the reason for this issue. Any good guesses?

**Comment by oantolin** [comment]
Oops, sorry, I was stripping properties from the candidates. The completions buffer target finder was written long ago, back when I frowned on using text properties in all circumstances, before the more nuanced approach we have now where we use text properties freely before injecting targets.

**Comment by oantolin** [comment]
And generally, the code to do with `*Completions*` doesn't really get a lot of testing. 😬

**Comment by minad** [comment]
> Oops, I was stripping properties from the candidates.

The *standard* problem. 

> And generally, the code to do with `*Completions*` doesn't really get a lot of testing.

How can that be given that you are such a big advocator of the `*Completions*` buffer in general ;)

**Comment by oantolin** [comment]
> The _standard_ problem.

Yes, _sigh_. :)

> How can that be given that you are such a big advocator of the `*Completions*` buffer in general ;)

Am I? I don't even use it myself. 😛

**Comment by minad** [comment]
The next time I tell someone to use Embark collect to get a buffer, you are going to chime in and recommend the default completions buffer instead ;)

At least the Completions buffer supports group functions now, in contrast to Embark!
