### ISSUE TITLE
embark-target-finder for current buffer/file?

### ISSUE THREAD

**Issue by karthink** [oantolin/embark#231]
How can I write an `embark-target-this-file` and `embark-target-this-buffer` that act on the current file/buffer? I have a bunch of functions like `load-this-file`, `byte-compile-this-file`, `sudo-this-file` and built-in ones like `diff-buffer-with-file` that I would like to call using embark directly. Right now I do `dired-jump`, then call embark on the current file.

These target finders should, of course, have a lower priority than `embark-target-active-region`, `embark-target-file-at-point` etc, so they're only activated if all the other target finders fail.

**Comment by oantolin** [comment]
If I understand correctly what you want to do you may not even need to define `load-this-file`, and just use the regular `load-file` instead. Something like this?

```elisp
(defun embark-target-this-buffer ()
  (cons 'this-buffer (buffer-name)))

(add-to-list 'embark-target-finders #'embark-target-this-buffer 'append)

(embark-define-keymap this-buffer-map
  "Command to act on current file or buffer."
  ("l" load-file)
  ("b" byte-compile-file)
  ("d" diff-buffer-with-file))

(add-to-list 'embark-keymap-alist '(this-buffer . this-buffer-map))
```

Does that work as you'd like?

**Comment by oantolin** [comment]
I should have said before answering: great idea! I think I want this in my config too!

**Comment by minad** [comment]
What about adding a target finder to Embark by default which returns (major-mode . buffer-name)? It allows you to copy the major mode via a general action 😎 or is there some value in not having an Embark context everywhere?

**Comment by hmelman** [comment]
I don't understand the value of this compared to just binding these commands to a key.  Particularly `load-file` and `byte-compile-file` are only useful in emacs-lisp buffers, why not bind them via the `emacs-lisp-mode-hook` to something like `C-c l` and `C-c b`?  Since a "this buffer" target would be lower priority, I think I would be annoyed when I wanted to use it but point was on a region or symbol (which it should be most of the time).

I totally understand the value of having these bound on the `embark-file-map` as they already are, though perhaps it would be cleaner if there was an elisp-file target and an `embark-elisp-flle-map` whose parent is `embark-file-map`.

FWIW, I have the following bound to `C-c L` in emacs-lisp bufers and use it all the time:

```elisp
(defun hrm-load-current-lisp-file ()
  "Load the byte compiled form of the file if it's there or the .el file."
  (interactive)
  (and (buffer-modified-p)
       (y-or-n-p (format "Save file %s? " (buffer-file-name)))
       (save-buffer))
  (let ((possible-elc-file (concat buffer-file-name "c")))
    (if (and (file-exists-p possible-elc-file)
	     (file-readable-p possible-elc-file))
	(load possible-elc-file)
      (load buffer-file-name))))
```

**Comment by minad** [comment]
@hmelman having such buffer local bindings would let embark act like a context dependent leader key. Of course you could just bind everything under a prefix in the mode map. So I am also not really convinced that this is needed. The context of a buffer or mode somehow feels to big for embark.

**Comment by hmelman** [comment]
IMHO given the shadowing problem, embark feels like the wrong solution for this.

**Comment by oantolin** [comment]
@hmelman 

> I don't understand the value of this compared to just binding these commands to a key.

It's a little silly: it just saves you from choosing the file: `M-x load-file` prompts you for a file, `M-n` will pick the current file from the future history, and then you press `RET` to confirm. This saves the `M-n` and `RET` steps. It is only a minor inconvenience having to do those steps, but Emacs is the one piece of software where you almost never have to put up with minor inconveniences.

But of course I was talking about using `load-file` as an action verus using the same `load-file` as a command. However, @karthink already wrote a `load-this-file` command that does not prompt for a file an just operates on the current one. Binding _that_ command to a prefix key is probably as good as using this target finder.

@minad 

> The context of a buffer or mode somehow feels to big for embark.

Yes, I can understand that feeling. It's fiddly, you have to make sure you're not on a smaller target.

**Comment by karthink** [comment]
> If I understand correctly what you want to do you may not even need to define `load-this-file`, and just use the regular `load-file` instead. Something like this?
>  ...
> Does that work as you'd like?

This is perfect, thank you. I still need to figure out how to combine all the file-based and buffer-based commands I use into a single keymap, or write different triggers and figure out the context to activate them separately, but I'll think about that for a bit.

As @minad points out, this is functionality that usually lives under a leader key, but that would require writing a bunch of functions that act on the current file (like `load-this-file`, `email-attach-this-file` etc), and I don't need that with embark. Even if I decide to use a leader key (or the shadowing annoys me), I can just do something like

```elisp
(defun embark-act-on-buffer-file (&optional arg)
  (interactive "P")
  (let ((embark-target-finders (list embark-target-this-buffer)))
    (embark-act arg)))
```

and bind that to a leader instead. 

Alternatively I can use a major-mode specific hydra for buffer/file actions, but I don't have any of that set up (and I'm not sure how to), and Embark is 90% of the way there already.

**Comment by oantolin** [comment]
I'll close this to indicate nothing in the Embark code base needs to change, but of course the discussion can continue.

**Comment by karthink** [comment]
In case someone wants to use embark as a leader key, here's the full recipe:

```elisp
(defun embark-target-this-buffer-file ()
  (cons 'this-buffer-file (or (buffer-file-name) (buffer-name))))

(add-to-list 'embark-target-finders #'embark-target-this-buffer-file 'append)

(add-to-list 'embark-keymap-alist '(this-buffer-file . this-buffer-file-map))

(embark-define-keymap this-buffer-file-map
      "Commands to act on current file or buffer."
      ("l" load-file)
      ("b" byte-compile-file)
      ("S" sudo-find-file)
      ("U" 0x0-upload)
      ("r" rename-file-and-buffer)
      ("d" diff-buffer-with-file)
      ("=" ediff-buffers)
      ("C-=" ediff-files)
      ("!" shell-command)
      ("&" async-shell-command)
      ("x" consult-file-externally)
      ("C-a" mml-attach-file)
      ("c" copy-file)
      ("k" kill-buffer)
      ("z" bury-buffer)
      ("|" embark-shell-command-on-buffer)
      ("g" revert-buffer))
```

The advantange over just defining a prefix-command in Emacs is that due to the fact that Embark injects the target into the input prompt of these interactive functions, I didn't have to write any wrappers to make them act on the current buffer/file (except for `mml-attach-file` which is broken here for now).

One modification you might consider is to let-bind embark-target-finders so that the above keymap is consistently activated, even if some other Embark target is active (like the region or a symbol). Then this acts like a true leader key, not a fallback behavior of Embark.

```elisp
(defun embark-act-on-buffer-file (&optional arg)
  (interactive "P")
  (let ((embark-target-finders '(embark-target-this-buffer-file)))
    (embark-act arg)))

(global-set-key (kbd "C-c o") 'embark-act-on-buffer-file)
```

**Comment by oantolin** [comment]
Now that we have @minad's fabulous multiple target support, this target finders triggers anywhere within a buffer, but with lowest priority. If you feel you need to cycle too much to reach it, then probably you should change the expression and defun target finders in your personal configuration.

**Comment by karthink** [comment]
A timely comment! I was just trying to figure out how to tweak embark's new behavior so I could get to this-buffer-file-map quickly.

**Comment by minad** [comment]
A cheap addition would be adding a prefix argument to `embark-cycle`.

**Comment by karthink** [comment]
I settled on a really dumb solution for now:

```elisp
(unless (member 'embark-target-this-buffer-file embark-target-finders)
      (setq embark-target-finders
            (append (butlast embark-target-finders 2)
                    '(embark-target-this-buffer-file)
                    (last embark-target-finders 2))))
```

I need embark for buffer/file actions more than expression/defun actions so this works for now.

However based on @minad's suggestion I'm also thinking about replacing `embark-act` with

```elisp
    (defun embark-reverse-act (&optional arg)
      (interactive "p")
      (let* ((order (pcase arg (4 #'reverse) (_ #'identity)))
             (embark-target-finders (funcall order embark-target-finders)))
        (embark-act (when (= arg 16) 4))))
```

Acting without exiting now requires a double `C-u`, but otherwise it gets the job done.

**Comment by karthink** [comment]
Added recipe from this issue to the wiki.

**Comment by oantolin** [comment]
I just wanted to let you know that numeric prefix arguments for embark-act, embark-cycle and embark-dwim have been added, as discussed above. 5811924f0da52d3a0210a66dffbe3fd4d975949b
