### ISSUE TITLE
embark-transformer-alist defcustom should be of :type alist

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#239]
` embark-transformer-alist` is defined as `:type 'hook` and I think it should be `:type 'alist`.

**Comment by oantolin** [comment]
Definitely! I'll fix it when I'm at a computer later today. I think the way it happened was that I was considering both options, went back and forth, and forgot to update the defcustom form with the winner.

**Comment by oantolin** [comment]
Thanks for reporting!
