### ISSUE TITLE
embark-default-action should take prefix argument

### ISSUE THREAD

**Issue by minad** [oantolin/embark#242]
For symmetry with embark-act?

Another alternative is to use the prefix for an alternative command:

~~~ elisp
(defun embark-dwim-xref (&optional arg)
   (interactive "P")
   (if arg
       (xref-find-definitions t)
     (embark-default-action)))
~~~

related #237

**Comment by minad** [comment]
One could write the dwim command such that it is indeed a drop in for xref-find-definitions. If no target is found or a prefix is given, fallback to xref-find-definitions.

**Comment by hmelman** [comment]
I think it's slightly cleaner to pass `arg` instead of `t` to `xref-find-definitions`, in case in the future it starts differentiating different prefix args.

**Comment by oantolin** [comment]
I don't really like this. It gives too much special treatment to `xref-find-definitions` and the only real motivation to do so is that we like its default key binding.

**Comment by minad** [comment]
I am not suggesting this for addition to Embark, this is more a solution for a user-level configuration. I only want to point it out, since it is a possible use of the prefix argument. The issue here is about using the prefix argument to adjust the quitting behavior in alignment with embark-act.

**Comment by minad** [comment]
For reference, this is what I am currently using for M-.

~~~ elisp
;; bound globally
(defun dm-embark-dwim (&optional arg)
  (interactive "P")
  (if arg
      (call-interactively #'xref-find-definitions)
    (embark-default-action)))

;; bound in the minibuffer
(defun dm-embark-preview (&optional arg)
  (interactive "P")
  (when (or arg (not (bound-and-true-p consult--preview-function)))
    (save-selected-window
      (let ((embark-quit-after-action))
        (embark-default-action)))))
~~~

**Comment by oantolin** [comment]
Oh, I was really confused by what you wanted the prefix argument to do. What's in your pull request is much more reasonable. Maybe you meant that all along and I misunderstood. Sorry.

**Comment by minad** [comment]
Yes, I meant that all along. I only added the confusion since I wanted to point out that users may also want to use the prefix argument for other reasonable use cases, as in my case where M-. is bound to embark-dwim.
