### ISSUE TITLE
ffap-file-at-point finds too much

### ISSUE THREAD

**Issue by minad** [oantolin/embark#249]
For my taste the ffap file finder conflicts too often with the symbol target finder. I would prefer the file finder to only match filenames with extensions or slashes. Probably this can be configured by modifying the `ffap-alist`. However I want to keep the more fuzzy ffap functionality enabled globally. Should I use an advice around the file target finder or should we improve this in Embark itself?

**Comment by oantolin** [comment]
I say we improve this in Embark itself. I think that I'd still want `foo` to count as a file, even with no slashes or extensions, in contexts like `(require 'foo)` or `(use-package foo ...)`

**Comment by oantolin** [comment]
I have made a commit addressing this but have no electricity and thus no WiFi at the moment. I'll push it when I can. The rule I went with is this: in Emacs Lisp mode, only match files when point is in a string or comment, or if it is preceded by `require` or `use-package` (this list may need to be extensible because people love writing package managers).

**Comment by hmelman** [comment]
`load` would be another.

**Comment by oantolin** [comment]
(Decided to commit from my phone.)

**Comment by oantolin** [comment]
> `load` would be another.

Don't you have to call `load` with a string?

**Comment by minad** [comment]
> (Decided to commit from my phone.)

This is indeed a pressing issue which required intermediate intervention. What about my PR #248? I recommend to merge it without proper testing or review from the phone. This is what the github webui is for, isn't it?

**Comment by oantolin** [comment]
The one thing I'm not sure about with #248 is using strings for s-expressions. I think using the very numerous commands that act on the sexp before or after point would be better.

**Comment by hmelman** [comment]
> > `load` would be another.
> 
> Don't you have to call `load` with a string?

Ah, yes, you're right.

**Comment by minad** [comment]
@oantolin 

> I think using the very numerous commands that act on the sexp before or after point would be better.

Actually I would like to have both string commands and the at-point commands. If we don't use strings we cannot reuse the embark-general-map. Therefore I think my current approach is justified.

Putting the at-point commands into the embark-expression-keymap is a bit more problematic, since these commands require a specific point location. It seems to me that we cannot reuse any of the existing commands as is. We would have to write wrappers for all of the at-point commands, which adjust the location. This is an open end in my PR #248.

In comparison, the defun commands in the defun map are also at-point commands. The target finder also returns a string target to support the general-map. The difference of the defun commands is that these work everywhere inside the defun, while the sexp commands are more strict regarding the point location.
