### ISSUE TITLE
Is it possible to concat target with variables and strings? (example inside)

### ISSUE THREAD

**Issue by thy6** [oantolin/embark#25]
Here's the thing that is stopping me from switching to embark. How can I accomplish something like the following with it? Thanks!

    (defun reddit-browser ()
      (interactive)
      (ivy-read
       "Reddit: "
       (mapcar 'car subreddit-list)
       :action
       '(1
         ("o" (lambda (x)
                (browse-subreddit x "new"))
          "new")
         ("t" (lambda (x)
                (browse-subreddit x "top"))
          "top")
         ("r" (lambda (x)
                (browse-subreddit x "rising"))
          "rising")
         ("c" (lambda (x)
                (browse-subreddit x "controversial"))
          "controversial"))))

**Comment by oantolin** [comment]
You can certainly program anything you want as an action, so this is definitely possible, but I get the impression in this particular case it may not be necessary.

I'm not familiar with the `browse-subreddit` function but is it a command (that is can you call it interactively)? And if so, does it first prompt you for a subreddit and then prompt you to choose a sort order (one of "new", "top", "rising", "controversial")?

If the answers to both those are yes, then what I would do is simply use `browse-reddit` as an action. What will happen is that embark will inject the target into the first prompt (the one for the subreddit) and then you still get prompted for the sort order.

In fact I think I wouldn't even bother writing this `reddit-browser` function and just use `browse-reddit` directly (assuming again you can use it interactively and it prompts you as I guessed above).

Maybe I'm missing something, what is the workflow you are trying to achieve?

**Comment by thy6** [comment]
Thanks, this function is from a personal package that was posted on reddit. Yes, the `browse-subreddit` function first prompts for subreddit and then to choose a sort order so I think what you are saying is true and reddit browser function can be eliminated. 

I guess if the readme or the wiki for this package had more examples I wouldn't have asked this, but thank you for your detailed response!

**Comment by oantolin** [comment]
> I guess if the readme or the wiki for this package had more examples I wouldn't have asked this, but thank you for your detailed response!

I agree, more documentation is on the todo list.
