### ISSUE TITLE
embark-dwim is broken in terminal emacs

### ISSUE THREAD

**Issue by adbull** [oantolin/embark#257]
Calling `embark-dwim` in terminal emacs fails with the message:

    Symbol’s value as variable is void: mwheel-scroll-up-function

The issue is that `mwheel-scroll-up-function` is defined only for GUI emacs.

**Comment by oantolin** [comment]
That's unfortunate. Embark uses that to detect Ivy and workaround some of its quirks. I'll look into other methods of detecting ivy (but maybe the truly sensible thing is to declare Ivy unsupported).
