### ISSUE TITLE
Add a possibility to specify the parent keymap of an embark-keymap (general/meta)

### ISSUE THREAD

**Issue by minad** [oantolin/embark#258]
The parent keymap is currently hardcoded to either the meta or the general map, depending on if the Embark target is region. Wouldn't it make sense to offer the possibility to specify the parent keymap per Embark keymap or offer some override?

~~~ elisp
(defvar embark-parent-map
   '((region . embark-meta-map)
     (something . nil) ;; disable the parent
     (otherthing . other-map) ;; use another map
     (t . embark-general-map))) ;; the default
~~~

(Why are you not simply using `:parent`? I think you told me before, or I asked this before, but I forgot the reason for the current approach.)

**Comment by bdarcus** [comment]
Since I have a screenshot that suggests the impulse that prompted this.

I am experimenting here with menu descriptions, to bundle contextual actions from two packages together with common menu entries.. 

![Screenshot from 2021-07-12 15-10-12](https://user-images.githubusercontent.com/1134/125342989-8b939e80-e323-11eb-987d-30a374d92aec.png)

I'd actually like to also remove the embark map here (this is for actions at point, so they're not useful here),  and the other menu items, so it's just a very clean menu, focused only on the contextual commands.

**Comment by oantolin** [comment]
I think I'd be happy to go back to the original approach: explicitly setting the parent of the keymap (which now would mean using `:parent`). I think it was @clemera that suggested to always automatically inherit from the general map (or the meta map, as the case may be), as a convenience for users who then wouldn't need to remember to inherit from the general map.

Requiring explicit inheritance feels less magic, I think I'd be happy with that even if it is a slightly breaking change.

**Comment by minad** [comment]
You could still default to general map in the embark-define-keymap macro. This won't be less convenient.

**Comment by oantolin** [comment]
Yes, that would leave the common case the same. Just to be through let me see if I can find where this automatic inheritance was discussed.

**Comment by oantolin** [comment]
Mmh, I couldn't quickly find the discussion but I'm pretty sure it was just meant as a convenience so you don't have to remember to inherit from the general map. The commit message for the change just says:

> Make embark-general-map actions always available
    
> Previously this happened by convention only: the action keymaps that
> come with embark all had embark-general-map as their parent. Now this
> is enforced by embark--setup-action. This also means the key t in
> embark-keymap-alist is no longer necessary.

**Comment by oantolin** [comment]
See also 7d11ba626d5edeb0e3427086f567e6cf18e63508 which fixes an embarrassing bug in the previous commit.

**Comment by bdarcus** [comment]
So how can I use this? This is what I tried:

```elisp
(defvar embark-parent-map
   '((region . embark-meta-map)
     (bibtex-actions-org-cite-map . nil) ;; disable the parent
     (t . embark-general-map))) ;; the default
```

**Comment by oantolin** [comment]
We didn't go with the extra configuration variable, @bdarcus. Instead the change was that embark no longer forces the action keynap to inherit from embark-general-map. So just create a key map without a parent or with any parent you want and use that.

**Comment by bdarcus** [comment]
OK, @oantolin, but how do I do _that_?

This is the map in question:

https://github.com/bdarcus/bibtex-actions/blob/main/bibtex-actions-org-cite.el#L77

**Comment by minad** [comment]
Ah, I guess you don't have to do anything. Embark will just not add parent keymaps anymore. @oantolin Now I also understand why @clemera proposed this change. The problem is that we lose a bit of modularity if we do not automatically derive from general map. If a third party package does not depend explicitly on Embark, it cannot make use of the general map at all. This is quite unfortunate. This means that when the user registers the keymap in the alist, the user must create *another* keymap manually which derives from the third-party keymap and the embark general map. One could offer a helper function.

~~~ elisp
(defun embark-register-keymap (map &optional parent)
   (when (and parent (not (eq parent t)))
      (setq map (make-composed-keymap (list map) parent)))
   ...push-to-alist...)

**Comment by oantolin** [comment]
Oh, that's a pretty compelling argument to go back to automatic inheritance from embark-general-map, @minad!

Maybe let's start over. What's wrong with automatic inheritance again? In which circumstances is it problematic?

**Comment by minad** [comment]
We need an opt-out mechanism. If a keymap specifies an explicit parent or a nil-parent, we don't want automatic inheritance. In the other cases where no explicit parent has been specified we want the general map. How can we achieve this? I don't think the old mechanism was sufficient so we should not go back. We need a better different design which caters for both scenarios, automatic inheritance and explicit parent keymaps without automatic inheritance.

What about opting in to automatic inheritance per keymap? embark-keymap-auto-parent-alist, bit this would still require user configuration, maybe not even easier than creating another composed map.

We should really consider - is automatic generally a good idea for third party keymaps which are embarkified. In the case discussed here @bdarcus wants to *disable* auto inheritance.

**Comment by oantolin** [comment]
Right, but that doesn't really answer my question. Why does one sometimes want to avoid the automatic inheritance? Is it because the general actions are really unapplicable sometimes? Is it just to get a nicer which-key display (which can easily be dealt with by tweaking the indicator)?

I want to understand the root problem first, and I think I only understand in a fuzzy way, not precisely.

**Comment by oantolin** [comment]
> If a keymap specifies an explicit parent

Also, I'm not completely sure about this, since, for example, the variable map inherits from the symbol map, etc.

**Comment by bdarcus** [comment]
> Why does one sometimes want to avoid the automatic inheritance? Is it because the general actions are really unapplicable sometimes? Is it just to get a nicer which-key display (which can easily be dealt with by tweaking the indicator)?

Yeah, both.

So it goes back to earlier discussions of UX design, and a desire for more control here. Plus that this is often the first question I get: "why are those there, and can I get rid of them?"

But in working with the in-buffer details, it just seemed more acute, as I literally didn't know what the Embark commands do there, and why they would be valuable for (this case, there's no reason to do a snapshot, etc.).

Admittedly some of this is related to a which-key bug. and if I can fix the issue with this, that's a reasonable workaround even without that bug-fix.

https://github.com/oantolin/embark/issues/207#issuecomment-881476606

But I don't care about the technical details on this. So if it causes you problems, no objection from me to you changing your mind :-)

**Comment by oantolin** [comment]
OK, I guess we probably do want an opt-out mechanism then. Here's a proposal that uses only built-in features of keymaps: as @minad suggested, we only do automatic inheritance for keymaps for which `keymap-parent` returns nil.

- What about the built-in keymaps in Embark, some of which have a parent but for which we still do want the automatic inheritance from embark-general-map? We modify the `embark-define-keymap` macro so that it applies `keymap-canonicalize`, this "inlines the parent", resulting in an equivalent keymap but with nil parent.
- What about keymaps for which I want to opt-out of automatic inheritance but don't have any sensible parent to inherit from? Just set `'(keymap)` as the parent! It is non-nil but has no bindings.

What do you think? (Particularly @minad who seems more interested in the technical details. :P)

**Comment by oantolin** [comment]
We could even modify the `embark-define-keymap` macro to have both `:include` and `:parent` directives.

**Comment by bdarcus** [comment]
> Particularly @minad who seems more interested in the technical details.

More about competence than interest :-)

**Comment by bdarcus** [comment]
I will add another related thought I had:

My keymap uses menu descriptions, so was wondering, if I did want to include embark commands, about a custom map there that uses menu descriptions also.

**Comment by minad** [comment]
Maybe it is fine to not have automatic inheritance at all. Just because it is so simple and predictable. The variants with canonicalize-keymap etc sound more complicated, of course in different scenarios. But one makes one scenario easy and one scenario complicated.

Given that the status quo is technically simpler, we could also just not provide auto inheritance at all.

**Comment by bdarcus** [comment]
Sorry if this is a dumb question, but is it feasible, and likely not too difficult, to hook up `transient.el` or `hydra` menus to embark?

Or is there something different about which-key that makes that not practical?

I was playing a bit with transient to see if it would work for the org-ref rewrite (which I've been giving feedback on), and I guess this is what I've been looking for; the ability to group commands semantically.

https://gist.github.com/bdarcus/f03a60ec8994f06cbd4b9733b25b7782

![Screenshot from 2021-07-23 04-45-43](https://user-images.githubusercontent.com/1134/126758364-ac2ae83e-aeee-4bd8-a294-5cebe7ba61b6.png)

**Comment by oantolin** [comment]
Well, you'd have to somehow communicate to transient or hydra what the grouping and the group titles should be. That's information typically not contained in an Emacs keymap, which is what Embark uses. And if you do list the groups and the group titles somewhere, you are pretty close to just writing a transient or hydra definition anyway, so I think it's probably simpler to directly define either a transient or hydra.

**Comment by bdarcus** [comment]
Yes.

I think I had an epiphany finally today to ask iyefrat if we can have which-key optional in the doom module, and the completing-read prompter available. That would allow me to avoid all the hassles with which-key.
