### ISSUE TITLE
let*: Wrong type argument: listp, keymap

### ISSUE THREAD

**Issue by liebkne** [oantolin/embark#263]
When evaluating the `embark-consult.el` file, I get this error: `let*: Wrong type argument: listp, keymap`.

Version: `956ee04`

**Comment by oantolin** [comment]
Wow, that commit for 258 was cursed. I don't think I've ever introduced so many bug with a single "fix". New rule for myself: always test in emacs -q before pushing. (This precise problem didn't show up with my configuration, but I could reproduce in emacs -q.)
