### ISSUE TITLE
Recursive action

### ISSUE THREAD

**Issue by 0x462e41** [oantolin/embark#266]
One thing I always forget I cannot do and keep trying to do it anyway is this:

- Call the `find-file` command;
- Enter a few characters to narrow down to a specific file/directory (_FILE_);
- Call the `embark-act` command;
- Select `rename-file`;
- Navigate to a distinct path.

At this point, I realize that I need to put this _FILE_ in a new directory, so I:

- Enter the new directory name;
- Again, I call the `embark-act` command, but this time with the `universal-argument`;
- Select `make-directory`.

When the directory is created, instead of going back to where I was, that is, with the _FILE_ already selected and selecting a new destination and/or a new name (_NEWNAME_), I go back to the first step, being asked to select _FILE_.

I think it would be really useful to be able to add this to my workflow. Is it possible?

Thanks.

**Comment by oantolin** [comment]
Woah, that really doesn't work? I could have sworn I have done this very thing! I'll look into it.

**Comment by oantolin** [comment]
This seems to work fine for me... I can't reproduce the problem you are seeing.

**Comment by 0x462e41** [comment]
Strange... Maybe it's some change I made to the Emacs C source then. I'll check. Sorry for not doing enough testing before opening this issue, but this helped me to narrow down the problem. Thanks, I will close this issue now.

**Comment by oantolin** [comment]
So you have figured the problem? Feel free to reopen if you're still experiencing this (but it will be difficult for me to help if I can't reproduce it).
