### ISSUE TITLE
bookmark suggestion: `bookmark-set`

### ISSUE THREAD

**Issue by jdtsmith** [oantolin/embark#268]
Sometimes you want to "update" an existing bookmark with a new location, which can be done easily with `bookmark-set`, which isn't exposed yet by embark.  Seems to work if I add this as `s` to `embark-bookmark-map`:

```
   :map embark-bookmark-map
   ("s" . bookmark-set))
```

**Comment by oantolin** [comment]
Great idea, thanks!
