### ISSUE TITLE
Reintroduce embark-undefined?

### ISSUE THREAD

**Issue by clemera** [oantolin/embark#27]
Hi there :)

Your recent improvements are great and solve another problem I had: Make it easy to use commands as actions which don't consume the target. I still use `embark-undefined` in my config though because it's kind of annoying to me if self insert commands get accepted:

```elisp
(define-key embark-general-map
  [remap self-insert-command]
  (defun embark-undefined ()
  (interactive)
  (minibuffer-message "Not an action")))

(define-key embark-region-map
  [remap self-insert-command]
  'embark-undefined)
```

This way they are blocked which I prefer, is there something you don't like about blocking them by default? Related to that could the general `Not an action:...` message in `embark-cleanup` be removed? Maybe we could assume that if the user binds a command intentionally in action maps it can be treated as a valid action (even if it doesn't consume the target).

**Comment by oantolin** [comment]
> I still use `embark-undefined` in my config though because it's kind of annoying to me if self insert commands get accepted.

Yes, it is annoying! I think I removed that without sufficient experience using the "improved" code. :)

> Related to that could the general `Not an action:...` message in `embark-cleanup` be removed? Maybe we could assume that if the user binds a command intentionally in action maps it can be treated as a valid action (even if it doesn't consume the target).

Yes, we could do that, but maybe we can take it farther: if that message is annoying, just remove it in all cases! That is, declare that any command, whether or not it is bound in an action map and independently of how it was run --whether through the action map, a global binding or `M-x`--, always counts as an action, and just silently consume the target.

The idea of the message was just to notify the user that they probably didn't do what they intended after `embark-act`, but maybe that's not actually all that helpful. And if you do press some keys by mistake and you really want to know what you ran by accident, you don't need a minibuffer message to tell you: there's always `view-lossage`.

I think I'll bring back undefined for `self-insert-command` which is the most common case of erroneous actions, and silently ignore the other cases. And also remove all the `(ignore (embark-target))` which will become unnecessary.

**Comment by oantolin** [comment]
Done! 4a3ff8b

By the way, there seems to have been a small bug when trying to run `embark-occur` from `embark-act` which I fixed (I remember you saying you wanted all embark stuff under the `embark-act` "prefix").

**Comment by clemera** [comment]
Cool thanks! 

> By the way, there seems to have been a small bug when trying to run embark-occur from embark-act which I fixed (I remember you saying you wanted all embark stuff under the embark-act "prefix").

Thanks I finally decided against it and have now a special purpose occur key in my config, too.
