### ISSUE TITLE
Create an embark-minimal-indicator

### ISSUE THREAD

**Issue by minad** [oantolin/embark#284]
...and remove support for strings in embark-action-indicator. Then we should really consider the snazzy verbose indicator as default ;)

And to not forget, add a few screenshots to the README, featuring the modus themes of course.

**Comment by oantolin** [comment]
I wrote the embark-minimal-indicator, and decided to unify the action and become indicators (which required a small update to the verbose indicator). 2b9053ffe26c4441cc12b28c865e66bf09382a9c

There are still several things to do:

- Rewrite the which-key indicator in the wiki to work for both acting and becoming.
- Add some documentation to the README (but a lot can simply be taken from the docstrings, I think).
- Take some screenshots!

**Comment by oantolin** [comment]
I didn't explicitly mention it in that last comment, but I did remove the string case of the indicator, they need to be functions now.

**Comment by oantolin** [comment]
Oh, and best of all: I made the verbose indicator the default! 🎉

**Comment by minad** [comment]
Great news! Thank you!

This may be controversial: I wonder do we still need embark become? I think I've not used it a single time. Or I've not understood where I would use it.

My main confusion with the command is that it has its own keymaps. Is embark-become not just the same as embark-act such that you always keep the input and such that you don't press RET?
It would seem more embarkier to me if embark-become just offers the same keymap as the actions, meaning "become one of the actions". 

The the verbose action indicator could be more helpful too. Press B x to become x.

**Comment by minad** [comment]
Oh and this issue can be closed! :tada:

**Comment by oantolin** [comment]
One item on the TODO list is done: I've [rewritten the which-key indicator](https://github.com/oantolin/embark/wiki/Additional-Configuration#use-which-key-like-a-key-menu-prompt) to conform to the new indicator protocol and thanks to @minad's tireless efforts it now updates for submenus!
