### ISSUE TITLE
Verbose indicator - add support for submenus

### ISSUE THREAD

**Issue by minad** [oantolin/embark#286]
The verbose indicator needs submenu support - not letting you off the submenu hook here :D 

It would be good to have the ability to update the indicator when a prefix key has been pressed. Given that we changed the configuration of the indicator to `embark-indicator`, now is a good time to also add update support.

This also affects the which-key indicator #139 and the completing-read-prompter #187.

**Comment by minad** [comment]
The Consult submenu is too aggressive, this does not make me comfortable. But I also don't want to add the commands to the exclusion list.

![screen](https://user-images.githubusercontent.com/50754/127158602-9d9e10fd-ce0e-43ce-89ab-1dea4cdfd4c7.png)
![screen2](https://user-images.githubusercontent.com/50754/127158610-0e74d351-6740-4a70-af84-c96830ff54cb.png)

**Comment by bdarcus** [comment]
Quick thoughts ...

I think there are two issues, both of which relate to visual or conceptual grouping or hierarchy.

Submenus allow what I've previously asked for; the ability to place "general" commands a low-level in the hierarchy.

Sorting and grouping allow like commands to be groked more easily; so in my use case, say I have a map with commands from three packages:

1. bibtex-actions (general bib stuff)
2. org-roam-bibtex (notes integration)
3. biblio (look up stuff online)

I think I want to be able to sort and group those, so easier for the users to quickly scan.

I also _think_ this is related to all the indicators, when you consider embark support for key descriptions (where command name and prefix is not available for display).

**Comment by minad** [comment]
> I also think this is related to all the indicators, when you consider embark support for key descriptions (where command name and prefix is not available for display).

To the indicators yes, but *not* to the prompters. The completing-read prompter should show a flat list of bindings to allow searching.

Embark only provides the verbose indicator which should show submenus. Ideally, in the above screenshots there should be a single line "C Consult keymap" and not all the Consult actions. The which key indicator should also get the submenus right then.

> Submenus allow what I've previously asked for; the ability to place "general" commands at a lower-level in the hierarchy

General commands can be placed in a submenu. I don't think it would be a good default for Embark, but users can configure the keymaps as they like.

**Comment by bdarcus** [comment]
> General commands can be placed in a submenu. I don't think it would be a good default for Embark, but users can configure the keymaps as they like.

Yeah, to be clear, I am not proposing any specific solutions; just trying to explain  _why_ I was suggesting that earlier.

**Comment by minad** [comment]
@oantolin Problem here is only that I have no idea how to implement this. Hiding the submap in the indicator is easy of course, but the read-key-sequence does not allow to hook in our update. See also https://github.com/justbur/emacs-which-key/issues/284, which I've opened a while ago.

**Comment by minad** [comment]
Fixed by #287

**Comment by oantolin** [comment]
I'll check it out right away! Thanks so much for doing this, I'm eternally grateful! (It feels a little funny that I care so much about a feature I don't plan to use, but I _do_ care a lot about it because people really want this.)

**Comment by minad** [comment]
Good to hear! It is also not that I am going to use this, but somehow many pieces fall into place now.

**Comment by oantolin** [comment]
I've [rewritten the which-key indicator](https://github.com/oantolin/embark/wiki/Additional-Configuration#use-which-key-like-a-key-menu-prompt) to conform to the new indicator protocol and thanks to @minad's tireless efforts it now updates for submenus!

**Comment by bdarcus** [comment]
Do you two think these recent changes should have an impact on the doom module?

**Comment by oantolin** [comment]
I'm no expert on Doom, @bdarcus, but I think Doom users like which-key always on, right? You should probably update Embark and add the new which-key prompter in that case. You're much better qualified to judge this than I am.

**Comment by minad** [comment]
Yes, the indicator in doom should be updated.

**Comment by bdarcus** [comment]
> I'm no expert on Doom, @bdarcus, but I think Doom users like which-key always on, right? 

It's actually stronger than that; one has to go out of their way to turn it off in Doom. It's kind of a core assumption at this point.

> You should probably update Embark and add the new which-key prompter in that case.

@iyefrat - when you get a chance, maybe take a look at this?

**Comment by minad** [comment]
> It's actually stronger than that; one has to go out of their way to turn it off in Doom. It's kind of a core assumption at this point.

Is it hard to turn off? `(which-key-mode -1)` should do it, or will you see breakage all over the place then?

**Comment by bdarcus** [comment]
Actually I don't know about breakage, but interestingly, if I eval that, the menu turns off generally, but not in `embark-act`!

**Comment by minad** [comment]
Yes, this is expected. The Embark which-key indicator manually summons which-key.

**Comment by minad** [comment]
But you can also turn off the Embark which-key indicator of course, using for example the new shiny verbose indicator.
