### ISSUE TITLE
Melpa recipe

### ISSUE THREAD

**Issue by leungbk** [oantolin/embark#29]
It would be nice if this package were available on Melpa.

**Comment by oantolin** [comment]
That's the plan once things stabilize (and, um, find themselves documented), which should be pretty soon.

**Comment by oantolin** [comment]
Done, it has been submitted as melpa/melpa#7284

**Comment by oantolin** [comment]
I'm closing the issue not because the package is already on MELPA but as a way of crossing off the submission from my todo list.
