### ISSUE TITLE
Add variable for verbose indicator help

### ISSUE THREAD

**Issue by olivertaylor** [oantolin/embark#290]
I suggest adding something like this:

``` lisp
(defvar embark-verbose-indicator-show-help t
  "Non-nil means show help in verbose indicator.")
```

Which would mimic the behavior of `completion-show-help`.

Setting it to `nil` would remove the "Act on..." and "Shadowed targets..." lines at the top of the buffer. Perhaps some of that information could be displayed in the mode-line when `nil`? Similar to how eldoc adds info to the modeline when you're editing the minibuffer.

**Comment by minad** [comment]
Not a good idea. This information is crucial.

**Comment by olivertaylor** [comment]
I agree that it's critical information, but expensive in screen real estate terms (I know, it's a nitpick). I just wonder if there's a more efficient way to display that information for tiny screens (that's why my mind went to eldoc).

**Comment by oantolin** [comment]
Well, the minimal indicator does show it in either the echo area or the minibuffer (depending on whether the minibuffer is open or not, of course). I guess one could crossbreed it with the verbose indicator...

**Comment by minad** [comment]
> I guess one could crossbreed it with the verbose indicator...

To what purpose? The most space is taken by the keybindings here. The small amount of space taken by the headline and the shadowed targets is not that relevant. And in order to save some space you can scale the faces. In my opinion we are sufficiently covered by the minimal and the verbose indicator.

**Comment by minad** [comment]
If one really wants to compress the information we should use a grid view. I would say that's a reasonable addition.

~~~~
Act on function(expression defun) "..."
key command   key command   key command   key command
key command   key command   key command   key command
key command   key command   key command   key command
~~~

**Comment by oantolin** [comment]
> one could use a grid view without documentation

The which-key indicator does that pretty well. As does the completing-read prompter with embark-collections grid view (the latter is what I use when I forget a key binding, if I additionally forget what a command does, I'll switch to list view to see the docstrings).

**Comment by minad** [comment]
Ah right, I forgot the which-key indicator. Maybe that's a good option for @olivertaylor then?

**Comment by olivertaylor** [comment]
On further experimentation I was able to get something more in line with my expectations with:

```lisp
(set-face-attribute 'embark-verbose-indicator-title nil :height 1.0)

(custom-set-variables
 '(embark--verbose-indicator-display-action
   '(display-buffer-below-selected (window-height . fit-window-to-buffer))))
```

Stepping back, I think my problem with the window was that it *looked* like a `*Help*` window but *acted* like a transient or completions window. Which I realize is totally off-topic for this issue.

Personally, I don't like which-key, and as @minad pointed out on Reddit the completing-read prompter is not key-driven, which I prefer - so neither of those are my preference.

I would argue that the minimal indicator is not simply a more compact way of displaying the indicator but a fundamentally different one. I've defined a bunch of nested transients in my init file because prefer interactive menus to simple keymaps (most of the time).

I still think that a more compact presentation of the verbose indicator would be worthwhile (and I like the grid idea, very Emacs-y), but I'll leave that to you.

**Comment by minad** [comment]
> I would argue that the minimal indicator is not simply a more compact way of displaying the indicator but a fundamentally different one.

Yes, minimal and verbose are at the edges of the spectrum. A grid view could be a compromise. It is just the question if Omar wants this. Maybe the grid and verbose view could use the same code and the formatting could be simplified by using a tabular view?

**Comment by minad** [comment]
@olivertaylor The PR #297 by @jaor should resolve this issue in a general way.

**Comment by oantolin** [comment]
Now that #297 is merged, this is issue can be closed.
