### ISSUE TITLE
Why are we killing the window in the verbose indicator?

### ISSUE THREAD

**Issue by minad** [oantolin/embark#293]
If we use `(display-buffer-reuse-window (dedicated . t))` and `(kill-buffer embark--verbose-indicator-buffer)` it seems to work and retain the window configuration. There should be the possibility to reuse a window. You added many configurations here, but none reuses a window https://github.com/oantolin/embark/blob/2c45a3e503ca1ae9b573a56e81fc0ba8381a127b/embark.el#L906-L945.

**Comment by oantolin** [comment]
Mmh. The destroying part needs some rethinking, huh? Ideally we could both use new windows (which should be killed) and reuse windows (which should not be killed). Let me try your suggestion.

**Comment by minad** [comment]
Note that the mode-line-format cannot be overwritten then for reused windows. I am also not sure what the effect of dedicated are. If we have a dedicated window it seems to be killed, e.g., newly created windows. But if a window is taken over, I assume that the dedicated flag is not set despite the dedicated=t in the display action. Then the window stays alive. I am only speculating here. I have no clue about window configurations. I mostly work with very few windows. Probably @karthink can give some input.

**Comment by oantolin** [comment]
I think I figured it out: you are supposed to use the `quit-window` function. It normally only buries the buffer (which actually would be fine for me), but it has a kill parameter you can set to non-nil to have it kill the buffer instead. It only remains to decide exactly what the reuse buffer preset option should be. I currently have a plain `(display-buffer-reuse-window)` with no extra parameters.

**Comment by karthink** [comment]
This is a tricky problem. My solution to this has been something like this:

```elisp
(if-let ((prev (car (window-prev-buffers))))
    (kill-buffer (current-buffer))
  (kill-buffer-and-window))
```

You can place this in `embark-kill-buffer-and-window` and it should now work as follows:

- If the window showing the indicator buffer was showing a buffer before, restore it
- Otherwise kill the buffer and window.

**Comment by oantolin** [comment]
Oh, I found a different solution by reading the entire Windows section of the manual. See what you think, @karthink.

**Comment by oantolin** [comment]
So, does this seem to work? If not, please reopen.

**Comment by karthink** [comment]
Testing, I'll update in a bit. Your current solution should do what my code above does but cleaner.

**Comment by karthink** [comment]
However for the options where the indicator buffer takes over an existing window, the `mode-line-format` of the previous buffer is not restored. I didn't open this issue so I can't reopen it, but this needs to be fixed.

**Comment by oantolin** [comment]
But the preset option don't do that, right? I thought the only one that takes over a new window is this last one I added, "Reuse a window" and for that one I omitted the mode line format precisely to avoid this problem.

So unless I'm mistaken, you aren't worried about the presets but about some display action a user might write?

**Comment by minad** [comment]
Yes, I already pointed this out. Either we get rid of the mode line adjustments or we restore them somehow. But how is this supposed to be done, at the point where we get access to the window it is already modified. So we have to store the mode-line-format of all windows first?!

**Comment by karthink** [comment]
Also, consider changing the default option back to `display-buffer-reuse-window`? The current default (-below-selected) will split the current window, which means it will almost certainly not show all the options and there is no way to scroll the indicator buffer.

Alternatively, we need a way to scroll the indicator buffer.

**Comment by minad** [comment]
@oantolin Right, for the reuse option you didn't add the mode-line-format. But wouldn't it be nice to set this consistently? I am also for changing back the default in order to get some Helm feeling ;)

**Comment by karthink** [comment]
> Yes, I already pointed this out. Either we get rid of the mode line adjustments or we restore them somehow. But how is this supposed to be done, at the point where we get access to the window it is already modified. So we have to store the mode-line-format of all windows first?!

If I'm not mistaken, using `(setq-local mode-line-format ...)` after spawning the indicator-buffer should fix this problem.

**Comment by oantolin** [comment]
We probably do need a way to scroll the indicator buffer too.

**Comment by minad** [comment]
@karthink 

> If I'm not mistaken, using (setq-local mode-line-format ...) after spawning the indicator-buffer instead of setting it through display-buffer should fix this problem.

Yes, of course. Forgot about that. When I initially added the mode-line-format to the display action the idea was to make it configurable, but it seems we need an extra configuration variable then. Or just hard code it.

**Comment by oantolin** [comment]
I'd be happy just removing the mode line format changes. It's only a minor cosmetic tweak that seems to be causing some trouble.

**Comment by karthink** [comment]
> But the preset option don't do that, right? I thought the only one that takes over a new window is this last one I added, "Reuse a window" and for that one I omitted the mode line format precisely to avoid this problem.
> 
> So unless I'm mistaken, you aren't worried about the presets but about some display action a user might write?

My apologies, you are correct. I had various windows with altered mode-line-formats from the previous version of embark, I should have tested with a fresh Emacs.

**Comment by minad** [comment]
@oantolin 

> I'd be happy just removing the mode line format changes. It's only a minor cosmetic tweak that seems to be causing some trouble.

Agree, let's remove it consistently everywhere. Users can add such tweaks via advices or display action adjustments.

**Comment by oantolin** [comment]
> Also, consider changing the default option back to `display-buffer-reuse-window`?

How about at-bottom as the default? I think that's the most predictable.

**Comment by minad** [comment]
> How about at-bottom as the default? I think that's the most predictable.

My problem with this setting is the same as @karthink's. The candidate list is cutoff. Fortunately the problem is not as severe anymore thanks to the subkeymap support.

**Comment by oantolin** [comment]
But reusue window can also have a cut off list of actions, depending on how big the window chosen for reuse is.

**Comment by karthink** [comment]
If reuse-window is good enough for org-mode dispatch buffers, it's good enough for me! Plus that helm-feeling, like @minad brought up :)

at-bottom should be fine with scrolling support.

**Comment by oantolin** [comment]
If you think reuse is more likely to be large enough, we can go with that, at least until we do have scrolling.

**Comment by karthink** [comment]
There is no good solution to this, but reuse works very well (without scrolling) in the extremely common 2 windows with vertical-split use case. When working with a tall (as opposed to wide) frame, reuse will behave near-identically to at-bottom.

Helm's default is to use a new frame, which is a mess on tiling window managers!

**Comment by oantolin** [comment]
> Helm's default is to use a new frame, which is a mess on tiling window managers!

😮 I thought it was something like at-bottom. I haven't use Helm in a long time, though.

**Comment by oantolin** [comment]
I think I'll close this again. Since what's really missing now is the scrolling and we have a separate issue for that.
