### ISSUE TITLE
embark-keymap-prompter: Add scroll-other-window passthrough

### ISSUE THREAD

**Issue by minad** [oantolin/embark#294]
To keep track of this feature as proposed by @karthink in #293. Needed to scroll the verbose indicator window.

It could also be that we need dedicated commands for this if it is supposed to work in the minibuffer.

**Comment by karthink** [comment]
I'm not sure if passing `scroll-other-window` will work, since the indicator buffer may not spawn predictably in the `other-window`.

**Comment by minad** [comment]
Hmm, maybe we shouldn't add scrolling. It is better to toggle to the completing-read prompter in this case.

**Comment by karthink** [comment]
When toggling to the completing read prompter, do you think the indicator (verbose buffer or which-key popup etc) should go away? It seems redundant the way it works now.

**Comment by minad** [comment]
Yes it should go away. I also thought about this. The problem is that there is some overlap between indicator and prompter. Maybe we should use the indicator only for the keymap prompter. The completing read prompter can have its own indicator "Act on ...:" In the prompt.

**Comment by karthink** [comment]
> Maybe we should use the indicator only for the keymap prompter. The completing read prompter can have its own indicator "Act on ...:" In the prompt.

[This](https://github.com/oantolin/embark/wiki/Additional-Configuration#switch-between-candidates-and-actions-like-in-helm) is indeed how I use the completing read prompter.

**Comment by oantolin** [comment]
Forgot to mention that I fixed this in the commit message. b75607fba4e7b00dc1338cc94c2b7019abc410e8

It was easier than I thought, `scroll-other-window` worked fine for out-of-minibuffer actions, and I let-bind `minibuffer-scroll-window` to cover the minibuffer case.
