### ISSUE TITLE
embark-cycle: Add prefix argument for skipping targets

### ISSUE THREAD

**Issue by minad** [oantolin/embark#295]
Also consider using the prefix argument of `embark-act/dwim` for skipping when invoked at point. See https://github.com/oantolin/embark/issues/231#issuecomment-887940726.

**Comment by minad** [comment]
We are quickly back at 40 issues again, now that we closed so many. We should not violate the Embark issue number conservation.

**Comment by minad** [comment]
Oh, great! Using `embark-dwim` with a prefix argument is bold, but could work in combination with `embark-target-mode` (#292).

**Comment by oantolin** [comment]
True!

**Comment by oantolin** [comment]
Actually probably 1 and -1 are fine for embark-dwim. I tend to know what those are.

**Comment by minad** [comment]
But what is the dwim buffer action? bury the buffer?

**Comment by oantolin** [comment]
I have no default action buffer action yet. I can't make up my mind. Maybe eval-buffer?

**Comment by oantolin** [comment]
Oh, just to be clear I wasn't planning on adding the buffer target to embark (yet?). I'm talking about my personal configuration.

**Comment by minad** [comment]
Are you using buffer actions in your config?

My feeling is that we should not add this. Such commands should go into some custom keymap or the mode map.

**Comment by oantolin** [comment]
I'm trying them out, but I think I'm quite likely to switch to a prefix keymap instead. It depends on how many actions actually benefit from the buffer name being injected.

**Comment by oantolin** [comment]
I agree that they probably shouldn't be added to Embark.

**Comment by karthink** [comment]
I agree as well. I overloaded embark with buffer actions because I don't
have (keyboard or cognitive) room for a leader key. These belong to a
separate keymap.
