### ISSUE TITLE
Optional delay for the verbose indicator display?

### ISSUE THREAD

**Issue by protesilaos** [oantolin/embark#296]
As the title suggests, this is about making the verbose indicator more adaptable for those who normally know what action they will take.  An optional delay, which could be set to 0 by default, would help with a workflow where if, say, I wait for 1 second then I must have forgotten what key/action I want, so the detailed buffer comes to offer help.

At any rate, thanks for the new features!

**Comment by oantolin** [comment]
That sounds reasonable, like the register preview delay.

**Comment by minad** [comment]
@protesilaos What do you think about my proposal #298? The idea is to show the minimal indicator immediately and the verbose indicator after a delay. This can be written nicely as a separate mixed indicator which composes the other two indicators.

**Comment by protesilaos** [comment]
> @protesilaos What do you think about my proposal #298? The idea is to
> show the minimal indicator immediately and the verbose indicator after
> a delay. This can be written nicely as a separate mixed indicator
> which composes the other two indicators.

Looks great and has the delay I would have probably used anyway :)

-- 
Protesilaos Stavrou
https://protesilaos.com
