### ISSUE TITLE
What are good default actions to include?

### ISSUE THREAD

**Issue by oantolin** [oantolin/embark#3]
The package currently includes the basic actions off the top of my head. I'd be very interested in suggestions for other common actions. I do want to only include very basic actions most people would find useful: it's easy enough for users to add their own most exotic actions.

(And of course, `embark` doesn't keep you from using any command as an action! So, by "including actions" I really mean assigning them single-letter shortcuts.)

**Comment by a13** [comment]
I'd take a look at counsel ones :)

**Comment by protesilaos** [comment]
## Can be done

For what it's worth, I like to have a direct "insert+exit" without passing an arg.

This exits the given level of recursion in the minibuffers:

```elisp
    (with-minibuffer-selected-window (insert (embark-target)))
    (abort-recursive-edit))
```

And this exits all recursive levels (my preference):

```elisp
    (with-minibuffer-selected-window (insert (embark-target)))
    (top-level))
```

## Unlikely

I also intend to experiment with the possibility of transforming a list of candidates for file paths into a `dired` buffer by means of `(dired (cons BUFFER CANDS))`, which could be useful for some relevant commands I have.  I guess an Ibuffer variant of this goes for buffer actions.  But these are just ideas right now that need to be tested.  Not sure if they make sense for good defaults.  Just noting them in case you need ideas.

**Comment by a13** [comment]
Another source of inspiration
https://github.com/conao3/transient-dwim.el

I already see git branches as a new category

**Comment by oantolin** [comment]
> For what it's worth, I like to have a direct "insert+exit" without passing an arg.

It the completely opposite direction, would it be a good idea to be able to pass an argument to go to top-level? If so, would `C-u C-u` or `C-0` be better?

**Comment by protesilaos** [comment]
>  would C-u C-u or C-0 be better?

In those cases, I feel `C-u C-u` is easier for me to press.  The `C-0` is easier (for me) in read-only buffers, like Dired or Gnus Group, where you can skip the modifier and just press `0`.

**Comment by oantolin** [comment]
I also thought `C-u C-u` might be easier to type, I'm not sure there's actual demand for a prefix arg to go to top-level. :)

Looking at counsel is clearly a good idea. I'll gradually get to doing that. Helm has plenty of sensible actions too.

In other news I ran a quick grep to see what completion categories I could find built-in to Emacs:

   - bookmark
   - dabbrev
   - info-menu
   - environment-variable
   - command
   - email
   - buffer
   - unicode-name
   - project-file
   - bibtex-key
   - bibtex-string
   - ecomplete

**Comment by protesilaos** [comment]
Very well! Looking forward to your findings.

Also, I agree that there is no particular need for going to the top level, especially by means of a double prefix arg.

**Comment by oantolin** [comment]
# Ivy/Counsel actions

I'm not actually going to list all the commands Counsel has actions for, many are definitely specialized. Here are the relatively "basic" or "mainstream" categories.

## General

- insert
- save

## Buffers

- find file (`find-file` from buffer's `default-directory`)
- switch in other window
- kill buffer
- rename buffer

## Symbols, variables and functions

- info manual
- goto definition

## Commands (like from M-x)

- describe function
- goto definition

Weird, no info manual lookup

## Files

- other windows
- other frame
- open externally (uses xdg-open, open or start depending on OS)
- open as root
- open read only
- cd bookmark (prompts for bookmarked directory then runs find-file there)
- copy
- rename
- delete
- mkdir

## Recentf

- open in other window
- open in other frame
- remove from recentf

## Bookmarks

- delete
- edit
- overwrite
- open externally
- open as root

## Packages

- describe package
- open package homepage
- install (handled by syntax, not action)
- delete (handled by syntax, not action)

## Unicode character names

- save the character (not the name) to the kill ring

**Comment by oantolin** [comment]
Wow, Helm has so more many actions that I remembered... Here are the file actions:

- Find File
- Find file in Dired
- View file
- Query replace fnames on marked `M-@`
- Marked files in dired `C-x C-q, C-u wdired`
- Query replace contents on marked `M-%`
- Query replace regexp contents on marked `C-M-%`
- Attach file(s) to mail buffer `C-c C-a`
- Serial rename files
- Serial rename by symlinking files
- Serial rename by copying files
- Open file with default tool
- Find file in hex dump
- Browse project `C-x C-d`
- Complete at point `C-c i`
- Insert as org link `C-c @`
- Find shell command `C-c /`
- Add marked files to file-cache
- Open file externally `C-c C-x, C-u to choose`
- Grep File(s) `C-s, C-u Recurse`
- Grep current directory with AG `M-g a, C-u select type`
- Git grep `M-g g, C-u from root`
- Zgrep File(s) `M-g z, C-u Recurse`
- Pdf Grep File(s)
- Gid `M-g i`
- Switch to Eshell `M-e`
- Etags `M-., C-u reload tag file`
- Eshell command on file(s) `M-!, C-u take all marked as arguments.`
- Find file as root `C-c r`
- Find alternate file `C-x C-v`
- Ediff File `C-c =`
- Ediff Merge File `M-=`
- Delete File(s)%s `M-D` (C-u reverse trash)
- Touch File(s) `M-T`
- Copy file(s) `M-C, C-u to follow`  
- Rsync file(s) `M-V`
- Rename file(s) `M-R, C-u to follow`
- Backup files
- Symlink files(s) `M-S, C-u to follow`
- Relsymlink file(s) `M-Y, C-u to follow`
- Hardlink file(s) `M-H, C-u to follow`
- Find file other window `C-c o`
- Find file other frame `C-c C-o`
- Find file other tab `C-c C-t`
- Print File `C-c p, C-u to refresh`
- Locate `C-x C-f, C-u to specify locate db`

**Comment by oantolin** [comment]
I've added a modest selection of actions to the existing keymaps. (Although I'm calling it modest, people might still disagree with some of the choices, feel free to bring it up in this thread.)

I'm keeping this issue open in case there are more suggestions.

**Comment by protesilaos** [comment]
[These additions](https://github.com/oantolin/embark/commit/264aa726166ade4f050fdde4373716ccaa4e4494) look sensible to me.

Perhaps there is also scope for `bury-buffer` in `embark-buffer-map`?  Maybe also a `e?diff-buffers`?

**Comment by oantolin** [comment]
I like the idea of adding bury-buffer and ediff-buffers. How about q and =, respectively?

**Comment by protesilaos** [comment]
Yes for `=`. 

No particular opinion on `q`, especially since the equivalent in `M-x ibuffer` and `M-x list-buffers` is bound to `b`.

**Comment by oantolin** [comment]
Mmh. I used b for switch-to-buffer thinking of `C-x b`, but maybe we could use s for switching and b for burying.

**Comment by protesilaos** [comment]
Yes, I noticed.

`ibuffer` and `list-buffers` bind `ibuffer-visit-buffer` and `Buffer-menu-this-window` respectively to `RET`, `e`, and `f`.  None of these feels right for your case.

**Comment by oantolin** [comment]
You probably got the reference, but just to be explicit, I used `q` for `bury-buffer` because `q` is often bound to `quit-window` which in my mind is just `bury-buffer` plus `delete-window`.

**Comment by protesilaos** [comment]
Yes, `q` is fine.

By "no particular opinion", I should have written "indifferent".  Besides, if someone has a strong opinion about it, they can always change the keys.

**Comment by oantolin** [comment]
Hi @protesilaos , I've activated the GitHub wiki for the project and added your configuration to the [examples page](https://github.com/oantolin/embark/wiki/Additional-Configuration). I hope that's OK with you. Feel free to edit it however you see fit.

**Comment by a13** [comment]
@oantolin JFYI, defuns in `:config` section of use-package example won't be bound in `:bind`, you have to use `:init`, since `:bind` checks for functions to be defined before with `fboundp`, you can check with macroexpand yourself.

Another thing: while `:load-path` is nice for testing your local dev version, I think end-users would prefer smth like `:quelpa`/`:el-get`/`:straight`. But I think the info on installation should be in README.

**Comment by protesilaos** [comment]
Thanks you @oantolin!  That is fine by me.  If/when I make changes to it, I will make sure to ping you about the wiki.

Thank you @a13: I was not aware about that aspect of `:config`.  I will make sure to use `:init` for those cases.

I agree that `:load-path` is not necessarily the best for other users.  I have it because I also check the source, commit logs, etc.

**Comment by oantolin** [comment]
> JFYI, defuns in `:config` section of use-package example won't be bound in `:bind`, you have to use `:init`, since `:bind` checks for functions to be defined before with `fboundp`, you can check with macroexpand yourself.

I don't think that's true. I just tested it again and it seems to work just fine. I inspected the macroexpansion and it does issue a harmless `autoload` if your function is unbound, *but* it binds it unconditionally. Maybe your using an older version of `use-package`?

**Comment by a13** [comment]
> I inspected the macroexpansion and it does issue a harmless autoload if your function is unbound

yes, but it tries to autoload from the package, but your ones are defined in your config

**Comment by oantolin** [comment]
> yes, but it tries to autoload from the package, though your ones are defined in your config

Yes, it does do that, but that's completely harmless. The autoload never gets used because when you use the binding, it runs the config section defining your function.

Try it. It works fine, the function gets defined in time, you don't get any error messages.

**Comment by oantolin** [comment]
I added a classifier and some actions for packages:

- `h`: `describe-package`
- `i`: `package-install`
- `d`: `package-delete`
- `r`: `package-reinstall`
- `u`: use `browse-url` to open the package homepage

**Comment by protesilaos** [comment]
Which commands benefit from those?

**Comment by oantolin** [comment]
> Which commands benefit from those?

I set them up to be active whenever the minibuffer prompt ends in `package: `. :P

This is mainly just those actions themselves (describe, install, delete, reinstall)! So the idea is that from anyone of those commands you can run any other as an action.

I'd say `describe-package` and `embark-browse-package-url` are useful as actions from any of the package commands. And `delete-package` is useful as an action from `package-reinstall`, and viceversa. They need a little help, though: the completion candidates for `package-delete` are full package names with version numbers included, while the completion candidates reinstall are plain package names. So if you call `package-delete` as an action from `package-reinstall` you get the bare package name and can use completion to add the version number of the exact one you want to delete. But if the other way around, you'd have to delete the version number. *shrug*

Some other combinations make no sense: if you are using `package-install` the completion candidates are only the uninstalled packages, so the `package-delete` and `package-reinstall` actions become useless. :( Similarly, `package-install` can't be used as an action from `package-delete` and `package-reinstall` because the completion candidates in those cases are packages you already have installed.

Finally, it's actually always sensible to use each command as an action from within itself! Say you want to install various, I don't know, company backends. Run `package-install`, type "company", pop up the completions buffer, switch to it and use the `i` action on the packages you want.

**Comment by oantolin** [comment]
`counsel-package` actually handles this in a clever way: it gives you a single list of all packages, both installed and uninstalled, so all of the actions make sense all the time,

**Comment by protesilaos** [comment]
> I set them up to be active whenever the minibuffer prompt ends in package: . :P

For a moment there I thought there already existed some built-in `counsel-package` equivalent :(

What you describe here does make things clear.  Thanks!

> Finally, it's actually always sensible to use each command as an action from within itself! Say you want to install various, I don't know, company backends. Run package-install, type "company", pop up the completions buffer, switch to it and use the i action on the packages you want.

Yes, this is a good technique for this case.

**Comment by karthink** [comment]
> I like the idea of adding bury-buffer and ediff-buffers. How about q and =, respectively?

I suggest 'z'. By default "C-z" will minimize Emacs, which buries it in the OS window list. In the terminal this stops Emacs and brings you back to the shell. I remember using modifier+z for similar functions in other Emacs packages  over the years.

**Comment by oantolin** [comment]
> For a moment there I thought there already existed some built-in `counsel-package` equivalent :(

How about this, @protesilaos ?

```elisp
(defun package-ignore (package)
  "Do nothing to PACKAGE.
Called interactively, prompt for a package, either installed or
uninstalled, with completion.  This command exists solely to apply
embark actions to the packages."
  (interactive
   (progn
     (unless package--initialized
       (package-initialize t))
     (unless package-archive-contents
       (package-refresh-contents))
     (list (completing-read "Ignore package: "
                            package-archive-contents))))
  (ignore package))
```

>  I suggest 'z'. By default "C-z" will minimize Emacs, which buries it in the OS window list.

I like that, @karthink , since burying a buffer means putting it at the end of the list, just like `z` is at the end of the alphabet.

**Comment by oantolin** [comment]
> 'q' can then be bound to quit-window.

For buffers? Do you mean binding `q` to a command that searches for windows displaying the given buffer and quits, I don't know, the first such window, or all such windows?

**Comment by karthink** [comment]
`embark-file-map`:
"~" : `vc-revision-other-window`
"+" : `dired-create-directory`
"I" : insert relative path

`embark-buffer-map`:
"|" : `shell-command-on-buffer`
"z" : bury-buffer
"q" : kill-buffer-and-window

`embark-symbol-map`:
"S" `embark-info-lookup-symbol` (change from "s" for consistency with Emacs' `help-map`)

`shell-command-on-buffer` is basically `shell-command-on-region (buffer-substring-no-properties (point-min) (point-max)`

**Comment by protesilaos** [comment]
> How about this, @protesilaos?

The completion part works, though I feel this has the potential for a more DWIM functionality.  Such as (i) delete if installed, (ii) with prefix key attempt re-install, (iii) install if missing.

Embark then extends the core tool, whereas now it acts in its stead (completion notwithstanding).

> I suggest 'z'. By default "C-z" will minimize Emacs, which buries it in the OS window list. In the terminal this stops Emacs and brings you back to the shell. I remember using modifier+z for similar functions in other Emacs packages over the years.

I also like this.

**Comment by karthink** [comment]
> > 'q' can then be bound to quit-window.
> 
> For buffers? Do you mean binding `q` to a command that searches for windows displaying the given buffer and quits, I don't know, the first such window, or all such windows? @karthink

I was thinking of making the action valid only when the buffer is being shown in a live window. This is not helpful when using `switch-buffer`, but it can be when using `kill-buffer` etc.

Something like
```
(let ((win (get-buffer-window buffer)))
 (save-current-buffer (select-window win) (kill-buffer-and-window)))
```
without accounting for edge cases etc.

**Comment by a13** [comment]
> > I like the idea of adding bury-buffer and ediff-buffers. How about q and =, respectively?
> 
> I suggest 'z'. By default "C-z" will minimize Emacs, which buries it in the OS window list. In the terminal this stops Emacs and brings you back to the shell. I remember using modifier+z for similar functions in other Emacs packages over the years.
> 
> 'q' can then be bound to quit-window.

that's why I use

```el
(use-package frame
  :bind
  ("C-z" . nil))
```

**Comment by oantolin** [comment]
@karthink: good suggestions! I'll add them.

@protesilaos: package-dwim is much better than package-ignore. I'm on it.

**Comment by oantolin** [comment]
@karthink 

Is it really worth it to complicate "s" to "S" just to be consistent with `C-h S` (the current action isn't exaaactly what `C-h S` does anyway :P)? A vim user would say it's silly to use an uppercase letter when the lowercase one is avaiable...

**Comment by karthink** [comment]
@oantolin 
I personally don't use `describe-syntax` (which is bound to "C-h s") and thus don't feel strongly about either "s" or "S". The extent to which you should follow Emacs' default conventions is always a tricky issue, both in personal configs and when writing packages.

Things like having "o" do slightly different things in an xref vs occur  buffer gets infuriating after a while!

**Comment by karthink** [comment]
> that's why I use
> 
> ```emacs-lisp
> (use-package frame
>   :bind
>   ("C-z" . nil))
> ```

Yeah this behavior seems like a holdover from the time before terminal multiplexing, terminal emulators or graphical environments were a thing. I'm not sure if the use of "C-z" to stop jobs was pioneered by Emacs (stop and return to shell) or early shells, but it works in Vim too.

**Comment by oantolin** [comment]
@karthink I think it might be more useful for the "shell command on buffer action" to replace the buffer contents with the output (i.e. call `shell-command-on-region` with fourth parameter `replace` set to `t`). Do you think your non-replacing version is better?

**Comment by karthink** [comment]
@oantolin I think it's least confusing to follow the default here, which is to pop up the result in an output buffer. And yeah, the prefix argument takes care of the evaluate-and-replace requirement.

I say this as someone who almost always wants to evaluate and replace!

**Comment by oantolin** [comment]
OK, the lastest commit add all of @karthink's suggestion except that (1) I kept "s" for the symbol lookup, and (2) I didn't add vc-revision-other-window because I couldn't understand it's docstring (what does it do?).

The bury buffer always buries the target buffer and, additionally, if it is currently displayed in a window removes it from the window (but leaving the window to display some other buffer).

Implementing the shell command on buffer action I noticed I actually needed to do something special to allow `C-u`! That should work now.

Please, please test. :)

**Comment by karthink** [comment]
Testing them now. `embark-shell-command-on-buffer` asks to confirm the buffer after calling. Since it was called on a specific candidate buffer this shouldn't happen.

![embark-shell-command-on-buffer](https://user-images.githubusercontent.com/8607532/82280116-00975e00-9943-11ea-870b-ef342ea0fd8e.gif)

Also, this is just a thought: `embark-file-map` can actually handle all the dired operations (change mode/owner/group, load/byte-compile, compress etc). This would effectively make the completions buffer a dired listing. I'm not sure it's wise to add them right away though. I already snuck in one common dired command (`dired-make-directory`). Maybe it would be better to let the userbase grow, see what kinds of actions folks use and use those as a guide?

**Comment by oantolin** [comment]
> (EDIT: Just realized this is the default behavior of `embark-act` with most commands)

Yeah, you are supposed to explicitly use `(put 'embark-shell-command-on-buffer 'emark-ratify t)` if you are sure you want the buffer auto-confirmed for you. Maybe for this one we can just set that property in the embark package, because since there is a further prompt (for the command), there's ample time to cancel.

>  I already snuck in one common dired command (dired-make-directory).

I switched it out on you: I used `make-directory` instead (to avoid loading dired, I think `make-directory` is always loaded). :)

>  Maybe it would be better to let the userbase grow, see what kinds of actions folks use and use those as a guide?

This sound like a good idea, of course an `embark-add-many-dired-file-keybindings` function might be a good idea too. People who want them can call the function.

**Comment by oantolin** [comment]
Hey, @karthink, I just noticed in your animated gif above that the digits take up a lot of valuable `which-key` real estate, you may want to hide them. I've added to the README how to configure `which-key` in order to do so.

**Comment by karthink** [comment]
> Hey, @karthink, I just noticed in your animated gif above that the digits take up a lot of valuable `which-key` real estate, you may want to hide them. I've added to the README how to configure `which-key` in order to do so.

Thanks, that's a useful tip. I looked for a function like `which-key-show-major-mode` but for transient maps (since keys in `embark--keymap` are the only ones I need to see). It doesn't look like such a function exists.

BTW, the embark actions `rename-file` and `rename-buffer` have different behaviors. The former asks to confirm the name of the file being renamed, the latter "ratifies" the buffer name, _i.e._ assumes the buffer in the minibuffer input is the one being renamed. You might want to make them match for consistency.

**Comment by oantolin** [comment]
> BTW, the embark actions `rename-file` and `rename-buffer` have different behaviors. The former asks to confirm the name of the file being renamed, the latter "ratifies" the buffer name, _i.e._ assumes the buffer in the minibuffer input is the one being renamed. You might want to make them match for consistency.

Now that the default is to auto-confirm everything, they do match. Now both behave like the rename-buffer used to.

**Comment by karthink** [comment]
`embark-act` on files from the completion buffer:

1. `rename-file` in the completions buffer selects the file (with full path) correctly. However the prompt for the new name is always "~/", not the value of `default-directory` in the completions buffer.

2. `embark-insert` on a file inserts only the base name of the file. It should be appended with the `default-directory` in the completions buffer before insertion.

3. `embark-save` on a file name has the same behavior as `embark-insert`.

**Comment by oantolin** [comment]
I'm starting to have trouble finding things among the issues, since the issue titles don't have much relation to part of the contents. So I moved your last comment to a new issue. Hope that's OK.

**Comment by oantolin** [comment]
In fact, I think I'll close this one. People wanting more default keybindings can ask for them in new issues.
