### ISSUE TITLE
Shrink verbose indicator

### ISSUE THREAD

**Issue by xendk** [oantolin/embark#300]
I love the new verbose indicator, but could it shrink down so the window is just big enough for the contents?

**Comment by minad** [comment]
This is of course fully configurable using the usual display action mechanism: https://github.com/oantolin/embark/blob/52bd3fd9153790f58e530547ff54b8232fda9715/embark.el#L906-L926

**Comment by xendk** [comment]
Doh, but of course. Thanks!!

**Comment by minad** [comment]
You may also want to watch out for https://github.com/oantolin/embark/pull/297, which will make the vindicator fully customizable.
