### ISSUE TITLE
Use an empty embark-verbose-indicator-exclude list

### ISSUE THREAD

**Issue by minad** [oantolin/embark#302]
~~~ elisp
(defcustom embark-verbose-indicator-excluded-commands nil
  "Commands not displayed by `embark-verbose-indicator'."
  :type '(repeat (choice regexp symbol)))
~~~

We added the bindings to the maps to make them accessible, now we hide them again. We should not do this by default. The exclusion list can be configured on the level of the user configuration. This already led to confusion due to the discrepancy with the which-key indicator.

**Comment by oantolin** [comment]
Again, I'll add some presets. The current one, plus another that includes the Consult search commands too.

**Comment by oantolin** [comment]
Hey, why is `nil` in the list?

**Comment by oantolin** [comment]
What's less confusing in the custom buffer, "Exclude nothing" or "Include everything"? I don't like the "double negative" of "Exclude nothing", but the variable _is_ an exclusion list after all.

**Comment by minad** [comment]
> Hey, why is nil in the list?

I was wondering about that too. Should not be there in my opinion. Maybe this is some remnant since @jaor's keymap iterator didn't filter this out?

**Comment by oantolin** [comment]
> The current one, plus another that includes the Consult search commands too.

Just the current one, I forgot the Consult search commands are under a prefix so it makes no sense to exclude them! 😆

**Comment by oantolin** [comment]
I'm growing more and more fond of customize for temporarily changing settings, which I think is why I've been putting more effort into the presets. I like using `customize-set-variable` (usually as the `c` embark action from `C-h v`), and @minad's neat custom variable exporter.

**Comment by oantolin** [comment]
Oops, typed the wrong issue number in that commit. 😆
