### ISSUE TITLE
Quoted symbols are incorrectly identified in Org source blocks 

### ISSUE THREAD

**Issue by localauthor** [oantolin/embark#303]
The following occurs in org mode source blocks, but not in elisp files.

When invoking `embark-act` on a symbol that is quoted (preceded by an apostrophe), such as `'next-buffer`, Embark includes the apostrophe as a part of the target. This results in the failure of many available Embark actions.

Invoking the default action `xref-find-definitions` produces a message is in this form:
```
Act on identifier(expression defun) ''next-buffer'
visit-tags-table-buffer: File /Users/username/directory/path/'next-buffer does not exist
```

**Comment by oantolin** [comment]
Oh, Org source blocks! I think that makes sense. Let me poke around a bit.

**Comment by oantolin** [comment]
I already had a special check for org mode markup of the form `=symbol=` or `~symbol~`, I just added another special case for `'symbol`. Thanks for reporting!

**Comment by localauthor** [comment]
Thanks for handling it so quickly! Working as expected now. 👍
