### ISSUE TITLE
Support mwheel in the verbose indicator

### ISSUE THREAD

**Issue by minad** [oantolin/embark#307]
Related to #294. Embark will get proper mouse support soon :D

**Comment by minad** [comment]
How hard would it be to make an actual Embark mouse interface, which opens a context menu? Probably this will lead to a new `embark-menu-prompter`.

~~~ elisp
(x-popup-menu (list '(0 0) (selected-window))
              '("Embark" ("Actions" ("Action1" . act1) ("Action2" . act2))))
~~~

**Comment by oantolin** [comment]
A popup menu prompter would be pretty cool (well, I would _never_ use it, but why not have it?). It should be used automatically if `embark-act` is bound to a mouse button. I think @rswgnu suggested this.
