### ISSUE TITLE
Clear echo-area after mixed indicator shows verbose actions' buffer

### ISSUE THREAD

**Issue by protesilaos** [oantolin/embark#310]
The `(setq embark-indicator #'embark-mixed-indicator)` first shows the minimal indicator in the echo area and then pops up the verbose buffer.  When the latter is visible, the echo area retains the information it provided, thus creating a duplication between it and the verbose buffer's header.  What do you think about clearing the echo area after the verbose buffer pops up?

![Screenshot from 2021-07-30 09-33-46](https://user-images.githubusercontent.com/12828033/127610958-e1fc6afa-c4a2-4a7d-9a68-244f02daec30.png)

**Comment by minad** [comment]
Yes, this ist true. My personal preference would be to not clear the echo area in order to reduce the amount of jumping elements. Furthermore I am using the reuse window configuration where the verbose indicator does not open directly above the window. In this configuration the result looks less odd than in your case where you have the act message above and below the bindings.

We could add an option `embark-mixed-indicator-move/clear/close` (any name suggestions?) which allows to configure to destroy the mindicator early.

**Comment by protesilaos** [comment]
> Yes, this ist true. My personal preference would be to not clear the
> echo area in order to reduce the amount of jumping
> elements. Furthermore I am using the reuse window configuration where
> the verbose indicator does not open directly above the window. In this
> configuration the result looks less odd than in your case where you
> have the act message above and below the bindings.

Ah yes, in that case it doesn't look odd.

> We could add an option `embark-mixed-indicator-move/clear/close` (any
> name suggestions?) which allows to configure to destroy the mindicator
> early.

Options are nice, though I guess it may be too specific and thus kind of
unnecessary or confusing?

Thinking about it, perhaps it is best we leave this for user
configurations.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by oantolin** [comment]
I tried this change @protesilaos but didn't keep it because I too thought it looked "jumpy" when cycling. Try it for yourself with this patch:

```
index c1670d2..0045fe1 100644
--- a/embark.el
+++ b/embark.el
@@ -1102,6 +1102,7 @@ further user intervention."
               (run-at-time
                embark-mixed-indicator-delay nil
                (lambda ()
+                 (message nil)
                  (setq vindicator (embark-verbose-indicator keymap targets)))))
       (setq vindicator (embark-verbose-indicator keymap targets)))
     (setq mindicator (embark-minimal-indicator keymap targets))
```

**Comment by protesilaos** [comment]
On 2021-07-30, 09:14 -0700, Omar Antolín Camarena ***@***.***> wrote:

> I tried this change @protesilaos but didn't keep it because I too
> thought it looked "jumpy" when cycling. Try it for yourself with this
> patch:

Oh, I see what you mean by that.  It would definitely not be good to
have it that way.

No worries: this will be done on my end.  Thanks for your time!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by oantolin** [comment]
But maybe the mixed indicator could stop using the minimal indicator all together once the verbose indicator pops up? That is, maybe after it switches to the verbose one it just uses the verbose one when cycling, with no timer anymore and no minimal indicator anymore. This requires keeping a little more state than we do now but it would probably look nicer.

What do you think @protesilaos  and @minad?

**Comment by minad** [comment]
> But maybe the mixed indicator could stop using the minimal indicator all together once the verbose indicator pops up? That is, maybe after it switches to the verbose one it just uses the verbose one when cycling, with no timer anymore and no minimal indicator anymore. This requires keeping a little more state than we do now but it would probably look nicer.

Oh yes, I wanted to have this! Also thought about it before, but so far didn't implement it since it will make things more complex. It requires some restructuring, since some indicator state must be preserved when cycling.

**Comment by minad** [comment]
My idea was to start the indicator right away before the embark--cycle catch block and then provide a more sophisticated update function which can update the full indicator state (changed keymap, changed target, etc). It will require changing the protocol again, but this is not too bad since we are currently restructuring that part of the package.

**Comment by protesilaos** [comment]
Well, I am happy to help test things whatever direction you choose to go to.

**Comment by oantolin** [comment]
I've modified the mixed indicator along the lines of my earlier comment: now, once the verbose indicator is shown, the minimal indicator is no longer displayed, and any further cycling uses the verbose indicator without a delay.

**Comment by oantolin** [comment]
Please test!

**Comment by protesilaos** [comment]
It does not work here on commit `1a7e6b5`.

In `emacs -Q`:

```elisp
(require 'embark "/home/prot/Git/emacs-packages/embark/embark.el")
```

Then `M-x embark-act`:

```
progn: Wrong type argument: arrayp, nil
```

**Comment by oantolin** [comment]
Ha! That bug is because `embark-act` is not bound to a key! Fixed it: 76fb4fac1e4a74325d070455e1c19147dd833eae

**Comment by protesilaos** [comment]
Okay!  Looks good here.

**Comment by oantolin** [comment]
@protesilaos So @minad just added a custom variable controlling whether the minimal indicator stops being shown when the verbose indicator kicks in, called `embark-mixed-indicator-both`.

**Comment by protesilaos** [comment]
Yes, I noticed.  Thanks!  Now I need to check what the repeatable actions entail :)
