### ISSUE TITLE
Create snapshot out of embark-prefix-help-command?

### ISSUE THREAD

**Issue by protesilaos** [oantolin/embark#313]
I have been using `(setq prefix-help-command #'embark-prefix-help-command)`, which generally feels better than the default method.  Though I noticed that when I try to do `embark-collect-snapshot` at its prompt, it tells me "Only a single target".

Do you think it is possible to put those candidates in a buffer?

[ my second issue today --- sorry for pestering you! ]

**Comment by minad** [comment]
Yes :D 

There we have it @oantolin, acting on the actions ;)

**Comment by oantolin** [comment]
It sounds like you are running `embark-collect-snapshot` through `embark-act`. And you probably get the message right after `embark-act` before even pressing `S`, right? This is an unfortunate side effect of the fabulous new cycling machinery.

Running `embark-collect-snapshot` directly does work. You can bind it to a key or, if you have recursive minibuffers, good old `M-x` works too.

You can avoid the problem with `embark-act` if you use a different key for `embark-cycle`.

**Comment by minad** [comment]
Or we don't rebind the cycle key to the error message?

**Comment by oantolin** [comment]
> Or we don't rebind the cycle key to the error message?

That's certainly an option. Maybe it would be better.

**Comment by minad** [comment]
More consistent at least, but it will be confusing for many users. I guess one needs an expert option.

**Comment by oantolin** [comment]
The fundamental issue is that it is great to reuse the embark-act binding for cycling, but it is also great to have embark-act _everywhere_. 😭

**Comment by minad** [comment]
But then, we already can use M-x or use another key for cycling as you wrote. I would say we keep things as is and improve the error message to be more instructive and doesn't only say "Only a single target".

**Comment by oantolin** [comment]
Maybe we could bind cycling to `>` and `<` by default instead? In both the keymap prompter and the completing-read prompter.

**Comment by minad** [comment]
Oh I wouldn't like this. The cycling is so much better on embark-act. The edge case is acting on the actions.

**Comment by oantolin** [comment]
> Maybe we could bind cycling to `>` and `<` by default instead? In both the keymap prompter and the completing-read prompter.

Mmh, no. I love reusing the embark-act key binding in the keymap prompter.

**Comment by oantolin** [comment]
> Oh I wouldn't like this. The cycling is so much better on embark-act. The edge case is acting on the actions, the common case is cycling.

You beat me to saying this.

**Comment by protesilaos** [comment]
Just making the error message more informative would be an easy way to fix this.

**Comment by minad** [comment]
Yes, I think that's the way to go. embark-act could be bound to a second key or you could invoke the export via M-x.

**Comment by oantolin** [comment]
Long ago I bound export to a key, because I was very dogmatic: "exporting and collecting are not _actions_, they do not act on the current target!" But now I'm grateful to not need an extra key... 😆

**Comment by protesilaos** [comment]
I think I also had separate keys for those.  No problem with doing it again.

**Comment by oantolin** [comment]
So, would "Cannot cycle: no other targets" be a good error message?

**Comment by protesilaos** [comment]
Maybe be more specific?  Like "cannot act on actions; call the command directly or with M-x".

**Comment by protesilaos** [comment]
Or there may be more cases... Hard to tell.

**Comment by minad** [comment]
"Single target, not cycling. Act with M-x embark-act."

**Comment by minad** [comment]
Can we find a good message which is not too long such that it fits well into the minibuffer?

"Cannot cycle: No other targets. Press M-x embark-act to act on actions."

**Comment by protesilaos** [comment]
Maybe?

```
"Cannot cycle: No other targets. Press M-x embark-act to act on actions."
"Single target; can't cycle. `M-x embark-act' to act on actions."
"Can't cycle. `M-x embark-act' to act on single targets."
```

**Comment by oantolin** [comment]
That M-x business only works for the recursive minibuffer crowd.

**Comment by protesilaos** [comment]
Ah, too bad.

```
"Single target; can't cycle. Call `embark-act' to act on actions."
"Can't cycle. Call `embark-act' to act on single targets."
```

**Comment by oantolin** [comment]
We could print an error message *and* rebind the key to embark-act.

**Comment by minad** [comment]
@oantolin Ah okay, that's a good idea. Press again to act!

"Single target; can't cycle. Press \[embark-cycle] again to act."

**Comment by protesilaos** [comment]
Sounds good!
