### ISSUE TITLE
Add a changelog/release notes for the next release

### ISSUE THREAD

**Issue by minad** [oantolin/embark#317]
We added a lot of features, maybe a changelog is a good idea?

**Comment by oantolin** [comment]
Probably. 😛

**Comment by minad** [comment]
On the other hand I would argue that Embark is quite accessible now, it is basically self documenting. Just press embark-act at point and see what you've got. So maybe there is no point in all this documentation :grimacing:

**Comment by iyefrat** [comment]
This feels like a good a place as any to say, all the recent embark changes are really exciting! I'm having a hard time keeping up with every thing on the Doom side of things :upside_down_face:

**Comment by oantolin** [comment]
That reminds me, @iyefrat, the which-key indicator in the wiki changed again.

**Comment by iyefrat** [comment]
Oh yeah I saw, that's in Doom already, some Vertico module improvements got merged a few hours ago (hlissner/doom-emacs#5299). The Vertico module also dethroned Ivy as the default completion module way faster than expected :D
