### ISSUE TITLE
Readme: Document more callconvs

### ISSUE THREAD

**Issue by minad** [oantolin/embark#320]
1. Action command taking a prefix argument.
2. Action command which does not take any arguments and ignores the target. We use this convention for some at point commands.

Maybe it is obvious that such commands work, but it is probably better to explicitly give these examples.

**Comment by oantolin** [comment]
By the way, this reminds me that it has always bothered me that there is no way to pass a prefix argument to an action with the completing-read prompter.

**Comment by oantolin** [comment]
> Maybe it is obvious that such commands work, but it is probably better to explicitly give these examples.

I think it's obvious that 2 works, but not that 1 does. But even if 2 is obvious, you are right that it is better to give an example.

**Comment by oantolin** [comment]
Also we could warn people that `y-or-n-p` and `read-char-choice` also open a minibuffer and you are unlikely to want the resulting candidate injection!

**Comment by minad** [comment]
Yes, indeed. It is a good idea that the action commands should not read (at point commands) or read exactly once from the mb, and they should read the target.

But did you consider to advise/temporarily replace these known bad read functions, such that they are not injected in embark--act?

**Comment by oantolin** [comment]
> read exactly once from the mb

No! Any number of times is fine, 0 or more! I use lots of actions that read twice, the target gets injected at the first prompt and I type at the second.

**Comment by minad** [comment]
Right, rename actions etc. There is still the point that no multi target injection is supported or that the target must be read first. I think we talked about this a while ago in some other discussion. It makes sense to describe all these things, since there are so many different scenarios. Of course they can all be explained by the basic concept, but this will still be helpful.

**Comment by oantolin** [comment]
The injection mechanism for interactive actions was already fully explained in the readme before this new section, but I agree it somehow wasn't enough and you are right that I should add some more examples of various cases...

**Comment by minad** [comment]
I agree. But somehow I missed this myself, some kind of cheatsheet like listing or brief section with examples of how Embark works internally.

**Comment by oantolin** [comment]
Wow, Emacs 28 has a variable called `y-or-n-p-use-read-key`. If you set it to `t`, then `y-or-n-p` uses `read-key` instead of `read-from-minibuffer`, and thus doesn't get the target injected!

**Comment by minad** [comment]
What a mess ;) cc @salutis

**Comment by minad** [comment]
Thanks!
