### ISSUE TITLE
Can I include a command in a keymap, that does not pass an argument?

### ISSUE THREAD

**Issue by bdarcus** [oantolin/embark#324]
I would like an at-point embark menu, where one of the commands is listed, but when chosen runs without argument.

Specifically, I need this:

```elisp
(org-cite-insert)
```

... and not this:

```elisp
(org-cite-insert '("one" "two"))
```

Is that possible?

**Comment by minad** [comment]
We are currently adding support for this. See `embark--ignore-target` in #323.

**Comment by minad** [comment]
Note that you can always write a function which takes an argument and just ignores it. Or alternatively write a command which does not read from the minibuffer or reads from the minibuffer and ignores what it got.

The special mechanism we are adding in #323 is probably not a good fit for your use case.

**Comment by bdarcus** [comment]
> Note that you can always write a function which takes an argument and just ignores it.

OK, I'll just do this; it's simple enough.

Thanks!

**Comment by bdarcus** [comment]
Although, it does seem a little awkward to add a command, that's exposed, just to do this?

**Comment by minad** [comment]
If you don't want an extra command you can use the #323 mechanism.

**Comment by bdarcus** [comment]
Perfect then.

**Comment by minad** [comment]
But note that the #323 mechanism (`embark-pre-action-hooks`) is Embark specific. I don't recommend to use it if it can be avoided. If you can make a command which can just be used in Embark as is, it is better, in particular in a third-party package. However in Embark itself we want to support many existing commands out of the box and then it is beneficial to avoid the boilerplate of these wrappers.

**Comment by oantolin** [comment]
if you want to use a command both normally and ignoring the target you can define an alias:

```elisp
(defalias 'org-cite-insert-ignoring-embark-target 'org-cite-insert)
(add-to-list 'embark-pre-action-hooks '(org-cite-insert-ignoring-embark-target embark--ignore-target))
```

**Comment by bdarcus** [comment]
> But note that the #323 mechanism (embark-pre-action-hooks) is Embark specific.

There's no use for the wrapper command here outside Embark; I only want to have it in the Embark menu.

This is the description of the function in question:

```
org-cite-insert is an interactive compiled Lisp function in ‘oc.el’.

It is bound to C-c C-x @.

(org-cite-insert ARG)

Insert a citation at point.
Insertion is done according to the processor set in ‘org-cite-insert-processor’.
ARG is the prefix argument received when calling interactively the function.
```

**Comment by oantolin** [comment]
Does the function prompt you for anything at the minibuffer? If so, when used as an action, Embark inserts the target at the first minibuffer prompt and simulates pressing RET afterwards. It doesn't matter if the thing prompted for is not an argument to the function: if the command opens a minibuffer at least once, the first time it does so, the target gets injected. If you want to avoid this injection you need to ignore the target somehow: either with a wrapper or with a pre-action hook (which already existed before this change @minad mentioned, but got easier to use now).

**Comment by oantolin** [comment]
> We are currently adding support for this. See `embark--ignore-target` in #323.

@minad, the support was already there, you mean you changed the interface. 😛

**Comment by bdarcus** [comment]
> Does the function prompt you for anything at the minibuffer? 

Yes; different things depending on where point is. 

If a citation is `[cite/style:@key]`; if before the colon, will prompt to change the style; elsewhere, it will prompt to add or change the citation key.

> If you want to avoid this injection you need to ignore the target somehow: either with a wrapper or with a pre-action hook (which already existed before this change @minad mentioned, but got easier to use now).

OK, so I do want to use this then.

**Comment by bdarcus** [comment]
Wait, now that's merged, how do I add `org-cite-insert` to that list?

**Comment by oantolin** [comment]
You can do something like:

```elisp
(with-eval-after-load 'embark
  (add-to-list 'embark-pre-action-hooks '(org-cite-insert embark--ignore-target)))
```

**Comment by minad** [comment]
@oantolin 

> the support was already there, you mean you changed the interface

No, actually we added support to ignore targets. Before #323 there was no way @bdarcus could register a command with Embark without having to write (1) a separate wrapper command or (2) a special ignore target function. But this is exactly what he wants to avoid, otherwise he could go with https://github.com/oantolin/embark/issues/324#issuecomment-891074245 :stuck_out_tongue:

**Comment by oantolin** [comment]
OK, fair enough. I just meant you could always have written a pre-action hook to ignore a target, but I agree there is a qualitative difference having to write a hook yourself and just setting up an existing function to be used as a hook.

**Comment by minad** [comment]
Of course, I agree. But I am glad we somehow distilled a good pattern now with `embark--ignore-target` and `embark--beginning-of-target`. Much embarkier! ;)

**Comment by bdarcus** [comment]
> You can do something like:
> 
> ```emacs-lisp
> (with-eval-after-load 'embark
>   (add-to-list 'embark-pre-action-hooks '(org-cite-insert embark--ignore-target)))
> ```

Thanks; will get this added ASAP.

On versions before this commit, this will just effectively be ignored?

BTW, what's your strategy on versioning?

**Comment by oantolin** [comment]
> On versions before this commit, this will just effectively be ignored?

Ah, no. You'll get an error message that says:

```
Symbol’s value as variable is void: embark-pre-action-hooks
```

Because the variable used to not have an `s` at the end. You can wrap the `add-to-list` in `(when (boundp 'embark-pre-action-hooks) ...)` if you want it to be ignore when the variable does not exist.

> BTW, what's your strategy on versioning?

I don't really have one.
