### ISSUE TITLE
README: Document that embark-consult is necessary for Occur/Grep

### ISSUE THREAD

**Issue by minad** [oantolin/embark#328]
Related #106. See https://www.reddit.com/r/emacs/comments/oyd33n/question_about_editing_consultembark_ripgrep/.

I don't think we have to document much more than that. The exporters are the relevant feature here. This issue has come up a few times if I recall correctly.

**Comment by oantolin** [comment]
The README currently says:

>   There is also support for exporting a list of grep results to an honest grep-mode buffer, on which you can even use wgrep if you wish. In order to make use of this exporter you will need a command that prompts you in the minibuffer for a grep result line. In the near future you will be able to configure Emacs 28 to use `xref-show-definitions-completing-read` as the value of `xref-show-xrefs-function` and `xref-show-definitions-function`. With that configuration, `project-find-regexp`, for example, with use the minibuffer to offers search results. Additionally, today, you can use the grepping commands from the Consult package, `consult-grep`, `consult-git-grep` or `consult-ripgrep`.

All the stuff about `xref` is outdated, right? I think we removed support for that. (And the stuff about Consult should mention mention you need embark-consult, per this issue).

**Comment by minad** [comment]
Yes, xref stuff is outdated. But you could add an xref-show-definitions-completing-read/consult-xref to xref-mode exporter?

**Comment by oantolin** [comment]
Doesn't xref-mode at least let you press RET to go to the correct location? I don't think I can easily add an exporter for xref-show-definitions-completing-read though, since I don't think the candidates have necessary data attached.

**Comment by minad** [comment]
> Doesn't xref-mode at least let you press RET to go to the correct location?

Indeed embark-collect-snapshot does not work. We could fix this issue though by overwriting the default action.

>  I don't think I can easily add an exporter for xref-show-definitions-completing-read though, since I don't think the candidates have necessary data attached.

Ah right, I forgot about this. We already discussed this back then. So we should not do anything about this.

**Comment by oantolin** [comment]
If I recall correctly we asked the maintainer to add the xref objects as text properties to the candidate but were refused.

**Comment by oantolin** [comment]
Oh, but `consult-xref` does add the necessary data. Maybe `consult-xref` could change the category to `consult-xref-location` and we could an exporter for it.

**Comment by minad** [comment]
More or less. But if you send Embark to ELPA we may have another chance ;)
