### ISSUE TITLE
embark-act on alist's associated value

### ISSUE THREAD

**Issue by thy6** [oantolin/embark#33]
There are times when I want to display keys of an alist for the completions in the minibuffer but act upon the associated value after selecting. For example, displaying a list of filenames, and then acting on the filepath.

How can I achieve that with embark in a custom function like this:

     (completing-read "prompt: " '(("red" . "first")("green" . "second")("blue" . "third")))

I would like to be able to to it with a let binding which can read from `(cdr (assoc KEY ALIST))`

Sorry if the question is not clear, but for example I can do this in ivy like this:

    (ivy-read
     "prompt: " '(("red" . "first")("green" . "second")("blue" . "third"))
     :action '(1
               ("o" (lambda (x)
                      (mpv-enqueue-play
                       (cdr x) t))
                "play")
               ("x" (lambda (x)
                      (mpv-music-player
                       (cdr x) nil nil t))
                "music")
               ("b" (lambda (x)
                      (qutebrowser
                       (cdr x)))
                "browse")
               ("w" (lambda (x)
                      (kill-new
                       (cdr x)))
                "copy url")
               ("d" (lambda (x)
                      (youtube-dl
                       (cdr x)))
                "download")))

**Comment by thy6** [comment]
I guess a solution would be to call the calling function again with the selected key to lookup the value, like this:

    (defun foo (&optional key)
      (interactive)
      (let ((list '(("red" . "first")("green" . "second")("blue" . "third"))))
        (if key
            (let ((value (cdr (assoc key list))))
              (message "associated value is %s" value))
          (let ((key (embark-with-actions (("RET" . embark-alist))
                       (completing-read "prompt: " list))))
            (message "selected key is %s" key)))))
    
    
    (defun embark-alist ()
      (interactive)
      (foo (substring-no-properties (embark-target))))

Where `embark-with-actions` is the macro that was defined in #26  

    (defmacro embark-with-actions (actions &rest body)
      (declare (indent 1))
      (let ((type (make-symbol "type"))
            (keymap (make-symbol "keymap")))
        `(let ((embark--type ',type)
               (,keymap (embark-keymap '(,@actions) embark-general-map))
               (embark-keymap-alist
                (cons '(,type . ,keymap) embark-keymap-alist)))
           ,@body)))

Using this with selectrum, kind of in a non-intuitive way `embark-target` is the topmost candidate instead of the currently selected candidate (unless you tab select it to fill the prompt), I wonder if this behavior can be changed.

It would also be great if the `embark-alist` function could tell which function called it so that it could be generic and automatically return the key to whichever function called it.

**Comment by oantolin** [comment]
I think this is best handled by looking up the key in the alist. I believe that is the `completing-read` way, since when you call `completing-read` with an alist it offers the keys as completions and leaves looking them up to you.

By the way, that old `embark-with-actions` has been superseded by the variable `embark-overriding-keymap`.
