### ISSUE TITLE
Generalize embark-indicator to a list of indicators

### ISSUE THREAD

**Issue by minad** [oantolin/embark#330]
* Support multiple indicator hooks.
* Use an alist with target type as key? But it would probably be easier to make it a plain list. The indicator gets passed the target as argument so it can simply bail out on unsupported target types.
* Make target highlighting an `:always` indicator instead of the ad-hoc `embark--highlight-target` function we have right now
* As proposed by @jdtsmith in https://github.com/oantolin/embark/issues/291#issuecomment-894588296. Add a special symbol indicator which highlights all symbols after a delay. We could either reuse hi-lock or maybe the Isearch lazy highlighting mechanism?
* More fancy features become possible, e.g., highlighting the current target in completion UIs like Vertico with the "Act" highlight face.

I am glad we added this comment to the source:

https://github.com/oantolin/embark/blob/e4bdbd55af2e948d0bceb5d08b9d9518d91fc563/embark.el#L287-L292

**Comment by oantolin** [comment]
Oops, I mentioned this issue by accident in commit 4f8b5a6, I meant #320.

**Comment by minad** [comment]
Well, the issue has been resolved now. I opened #336 as a follow-up to keep the symbol highlighting idea in mind :)

**Comment by minad** [comment]
See also https://github.com/oantolin/embark/wiki/Additional-Configuration#colorize-the-current-vertico-candidate-differently-when-acting

**Comment by oantolin** [comment]
Nice!

**Comment by oantolin** [comment]
Generalizing embark-indicator to a list of indicators was a great idea, @minad, thanks again!

**Comment by minad** [comment]
Thanks! Also thanks to @jdtsmith to get the ball rolling on this :)

I guess one could even find more specialized indicators which only activate for certain target types or in certain contexts.

**Comment by oantolin** [comment]
Probably time will reveal more of those. But for example, one can imagine a marginalia indicator for at-point targets that displays the marginalia annotation somewhere, the echo area, an overlay or one of those mouse hover popups.
