### ISSUE TITLE
M-x default action in the minibuffer is broken

### ISSUE THREAD

**Issue by minad** [oantolin/embark#335]
@oantolin Do you observe this too?

**Comment by oantolin** [comment]
No, they seem to work here. I tried `find-file` and `describe-{function,variable}`. Which command do you see problems with?

**Comment by jdtsmith** [comment]
These are working for me as well on 0806.1318.

**Comment by minad** [comment]
It is broken for me with every command and with every completion UI. I tried it with emacs -Q.

**Comment by oantolin** [comment]
That is weird! Let me try from `emacs -Q`.

**Comment by minad** [comment]
It works with the completing-read-prompter, but not with the keymap prompter.

**Comment by oantolin** [comment]
Weird, `RET` works just fine from `emacs -Q` here.

**Comment by minad** [comment]
Weird, it is broken on Emacs 27 and Emacs 28 for me.

**Comment by oantolin** [comment]
What happens exactly?

**Comment by minad** [comment]
Okay, I have to correct what I wrote above: It seems only M-x is broken. The rest works.

**Comment by oantolin** [comment]
Oh, that makes perfect sense!

**Comment by oantolin** [comment]
After thinking about several possible fixes, I think that one is the most principled. I also got to remove an old wart: the `embark-execute-command` alias to `execute-extended-command`!

**Comment by oantolin** [comment]
You know, I think the reason I hadn't noticed this is that `embark-dwim` did work, and I don't think I've used `RET` as an action since I finally decided to add a key binding for `embark-dwim` to my config.

**Comment by minad** [comment]
I don't know why I just observed this, probably because of the testing of my PRs. Otherwise one doesn't use this particular default action very often. I only use default actions often from the snapshot, but not for M-x of course.
