### ISSUE TITLE
Add special indicator which highlights all symbols

### ISSUE THREAD

**Issue by minad** [oantolin/embark#336]
Follow up to #330. Proposed by @jdtsmith in https://github.com/oantolin/embark/issues/291#issuecomment-894588296.

Ideally the indicator should highlight the symbols after a delay and lazily to avoid performance problems.

**Comment by minad** [comment]
Prototype:

~~~ elisp
(defun embark-hi-lock-symbol-indicator ()
  (let ((highlighted))
    (lambda (&optional _keymap targets _prefix)
      (when (and highlighted (not (eq (plist-get (car targets) :orig-type) 'symbol)))
        (hi-lock-unface-buffer (concat "\\_<" (regexp-quote highlighted) "\\_>"))
        (setq highlighted nil))
      (when (and (not (minibufferp)) (eq (plist-get (car targets) :orig-type) 'symbol))
        (setq highlighted (plist-get (car targets) :target))
        (hi-lock-face-buffer (concat "\\_<" (regexp-quote highlighted) "\\_>")
                             'region)))))
~~~

Doesn't work well since it interferes with the target at point highlighting.

**Comment by oantolin** [comment]
I'm testing this one that reuses the isearch machinery:

```elisp
(defun embark-highlight-all-occurrences-indicator ()
  (lambda (&optional keymap targets _prefix)
    (let ((target (car targets)))
      (if (memq (plist-get target :orig-type) '(symbol identifier))
          (let ((isearch-string (plist-get target :target))
                (isearch-regexp-function #'isearch-symbol-regexp))
            (isearch-lazy-highlight-new-loop))
        (lazy-highlight-cleanup t)))))
```

(To test, also increase the priority of the other highlight indicator overlay to 1001.)

**Comment by oantolin** [comment]
> Doesn't work well since it interferes with the target at point highlighting.

This is probably also fixed by increasing the priority of the overlay in `embark-highlight-indicator`.

**Comment by minad** [comment]
I tested your `embark-highlight-all-occurrences-indicator`. It looks like the better approach in general, but I was worried that it would be a bit brittle (I also looked into isearch before). For me it does not work reliably, sometimes I see the isearch highlights, sometimes not. Probably some other setting is needed to make this robust?

**Comment by oantolin** [comment]
Oh, that's a shame. Have you indentified any situation where the iseach highlights don't appear? It seems to work here, but I probably haven't hit some edge case you hit.

**Comment by minad** [comment]
> Oh, that's a shame. Have you indentified any situation where the iseach highlights don't appear? It seems to work here, but I probably haven't hit some edge case you hit.

It is not clear to me. Half of the time it appears, half not. Then it doesn't work for a while, then works again. I have to look a bit more systematically at it.

**Comment by minad** [comment]
Okay, it seems when I act on symbol-a and then on symbol-b it works reliably, but acting on symbol-a and again on symbol-a does not work. Probably the cleanup/reset is insufficient.

**Comment by minad** [comment]
Resetting `isearch-lazy-highlight-last-string` seems to do it.

~~~ elisp
(defun embark-highlight-all-occurrences-indicator ()
  (lambda (&optional keymap targets _prefix)
    (let ((target (car targets)))
      (if (memq (plist-get target :orig-type) '(symbol identifier))
          (let ((isearch-string (plist-get target :target))
                (isearch-regexp-function #'isearch-symbol-regexp))
            (isearch-lazy-highlight-new-loop))
        (setq isearch-lazy-highlight-last-string nil) ;; ADDED
        (lazy-highlight-cleanup t)))))
~~~

**Comment by oantolin** [comment]
Cool!

**Comment by minad** [comment]
This is a great solution! I like it!

**Comment by oantolin** [comment]
I think it's probably worth adding to embark, right? Maybe even on by default?

**Comment by minad** [comment]
Yes! Very embarky, integrating isearch in 9 lines of code. Embark will be much embarkier if this is enabled by default!

**Comment by oantolin** [comment]
I also modified the next/previous symbol actions so they skip the current match. Currently if point is at the start of the match, the next symbol action just takes you to the end of the same match.

**Comment by oantolin** [comment]
Can you think of a better name? `embark-highlight-all-occurrences-indicator` is descriptive but long.

**Comment by minad** [comment]
* embark-lazy-isearch-indicator
* embark-isearch-highlight-indicator

**Comment by jdtsmith** [comment]
You guys are too good.  Really awesome, thanks.  BTW, the word "indicator" seems to get thrown around a lot and I'm not clear what it means exactly.  I thought it was the "which-key" "you can do this" analog, but perhaps not given this function name.

**Comment by oantolin** [comment]
That which-key analog is an indicator too, namely it's `embark-verbose-indicator`.

An indicator is a function that helps convey context for actions using any Emacs UI elements: it can inform the user of things like what the target is, the type of the target, where the target is located in the buffer, whether there are other targets to cycle to, what those other targets are, what actions are bound in the action keymap, etc.

@minad had the brilliant idea of letting you have as many indicators running at once as you like. So now the previous highlighting of the target is reimplemented as an indicator too.

**Comment by jdtsmith** [comment]
Just tried out the new lazy highlighter for symbols: really great, thanks!  I actually prefer isearch's current target highlight face to embark's.  But perhaps it is trying to achieve consistency with the in-minibuffer faces?

**Comment by minad** [comment]
@jdtsmith This is a theme issue. Maybe we should refine/split a few faces to give more freedom to the themes. We could even go as far as remapping the isearch lazy highlighting face temporarily or use a different face directly, while the isearch indicator is active. See for example https://github.com/oantolin/embark/wiki/Additional-Configuration#colorize-the-current-vertico-candidate-differently-when-acting. Maybe @protesilaos has some thoughts about the target highlighting and the lazy highlighting.

We use these faces as of now:

* `highlight` is used for the "Act/Become" label, maybe introduce face `embark-label`
* `shadow` is used for shadowed targets in the indicator, maybe introduce face `embark-shadow`
* `embark-target` for the target highlighting
* `lazy-highlight` for the additional highlighting

**Comment by jdtsmith** [comment]
Thanks.  So for me it's just:

```lisp
  (set-face-attribute 'embark-target nil :inherit 'isearch)
```

I'm happy recycling isearch current/other target highlighting, since the buffer/modeline indicator(s) tell me I'm embarking and not isearching.

**Comment by protesilaos** [comment]
On 2021-08-08, 06:36 -0700, Daniel Mendler ***@***.***> wrote:

> Maybe we should refine/split a few faces to give more freedom to the
> themes. We could even go as far as remapping the isearch lazy
> highlighting face temporarily or use a different face directly, while
> the isearch indicator is active. See for example
> https://github.com/oantolin/embark/wiki/Additional-Configuration#colorize-the-current-vertico-candidate-differently-when-acting. Maybe
> @protesilaos has some thoughts about the target highlighting and the
> lazy highlighting.

Hello Daniel!

[ I could not reply sooner as I did not have access to a personal
  computer.  All should be good now.  Still working through my
  backlog... ]

More faces are fine.  The main area where I would like more granilarity
is in the cycling feedback.  When you target a smaller item such as a
symbol, it is desirable to apply a more intense background.  But as the
scope expands, you want to make that a bit more subtle.  Basically
because it is easier to discern finer colour variations over larger
surfaces.

It probably is tricky to implement and likely to lead to problems with
estimating when a target is "small" or "large".  Plus there is the issue
with finding suitable default faces.  I can't think of any: `highlight`
is already covered, the isearch faces are fairly intense, the `region`
may not be suitable in context, `secondary-selection` is intense too by
default...  Only `match` may pass the test, though it is defined in the
`replace.el` library (should be available in most scenaria, but not
always).

Anyway, just an idea.

> We use these faces as of now:
>
> * `highlight` is used for the "Act/Become" label, maybe introduce face `embark-label`
> * `shadow` is used for shadowed targets in the indicator, maybe introduce face `embark-shadow`
> * `embark-target` for the target highlighting
> * `lazy-highlight` for the additional highlighting

I think the state of affairs is okay, even if the above is not done.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by minad** [comment]
@protesilaos Good to see you back!

> It probably is tricky to implement and likely to lead to problems with
estimating when a target is "small" or "large".

I am not sure if distinguishing small or large targets is desirable. The size of the target does not seem meaningful - using a different face would only be a visual effect. The region highlight also does not vary depending on the size of the region. One could use different highlight faces for different target types, but maybe this would be more confusing than helpful.

**Comment by protesilaos** [comment]
On 2021-08-28, 16:57 -0700, Daniel Mendler ***@***.***> wrote:

> @protesilaos Good to see you back!

Thank you!

>> It probably is tricky to implement and likely to lead to problems
>> with estimating when a target is "small" or "large".
>
> I am not sure if distinguishing small or large targets is
> desirable. The size of the target does not seem meaningful - using a
> different face would only be a visual effect. The region highlight
> also does not vary depending on the size of the region. One could use
> different highlight faces for different target types, but maybe this
> would be more confusing than helpful.

You are right: it would cause too much trouble.  Not worth the added
complexity.

-- 
Protesilaos Stavrou
https://protesilaos.com
