### ISSUE TITLE
Pulse when jumping

### ISSUE THREAD

**Issue by minad** [oantolin/embark#338]
The compile goto function pulsed by default. Shall we add this by default to the embark-consult-goto actions? I'd imagine most users would want this. See https://github.com/oantolin/embark/wiki/Additional-Configuration#pulse-after-jump-from-consult-linegrep-collect-snapshot.

**Comment by minad** [comment]
@oantolin Your opinion about this? I think it makes sense to add this for a better ootb experience, given that compile.el pulses too by default.

**Comment by oantolin** [comment]
Any reason `consult--jump` doesn't pulse itself?

**Comment by minad** [comment]
> Any reason consult--jump doesn't pulse itself?

Yes, it doesn't make sense to do this given preview. However in case no preview has happened or is disabled, pulsing automatically may actually make sense. I will look into it, maybe you are right and the issue should be solved in Consult and not in Embark.

**Comment by minad** [comment]
Ah there is one more reason - if you have hl-line-mode, then after jumping for example from consult-line, the active line will be highlighted. This is not the case if you jump from the Embark buffer, since there the focus will stay within the Embark buffer. Then you don't get the highlighting and you will feel a bit lost.

**Comment by oantolin** [comment]
OK, cool, I'll do it in embark-consult then.
