### ISSUE TITLE
embark export and wgrep cannot edit CRLF file

### ISSUE THREAD

**Issue by vohv** [oantolin/embark#339]
It seems there are some problems when use embark export and wgrep to edit CRLF file.

I can edit in `*Embark Export Grep*` buffer. But when I execute `wgrep-finish-edit`，nothing happens.

**Comment by oantolin** [comment]
Does this work without using consult and embark? That is, if you use `M-x grep` and then wgrep, do you run into the same problem? If so, then it's really an issue with wgrep.

**Comment by minad** [comment]
Probably this is a bug in Consult, which should also strip the `^M`?

* https://github.com/minad/consult/blob/7b0137b6d8c16c4b5be194a8ad0b7aa33255c88f/consult.el#L1600
* Also in affe: https://github.com/minad/affe/blob/be08c4ec49681474cbebaf0957568f27e42c4b3c/affe-backend.el#L54

**Comment by vohv** [comment]
Yes, I see the `^M` in `consult-grep`

**Comment by minad** [comment]
@vohv Can you try the newest consult version, which includes https://github.com/minad/consult/commit/271b89af7f59acaa54123d36abb9efdcea0ddc38 if this fixes the problem?

**Comment by vohv** [comment]
Thanks. It's fixed
