### ISSUE TITLE
Straight.el package support

### ISSUE THREAD

**Issue by tpeacock19** [oantolin/embark#34]
Hi, I've spent the past few days looking through this package on a transition from Ivy to Selectrum, its been very useful and informative! I put together a keymap and classifier for Straight.el and figured it may be useful for others.

``` emacs-lisp
(defvar embark-straight-map
  (embark-keymap
   '(("u" . straight-visit-package-website)
     ("r" . straight-get-recipe)
     ("i" . straight-use-package)
     ("c" . straight-check-package)
     ("F" . straight-pull-package)
     ("f" . straight-fetch-package)
     ("p" . straight-push-package)
     ("n" . straight-normalize-package)
     ("m" . straight-merge-package))
   embark-general-map))

(cl-pushnew '(straight . embark-straight-map) embark-keymap-alist)

(defun embark-straight-type ()
  "Determine if currently completing package names."
  (when (or  (string-suffix-p "recipe? " (or (minibuffer-prompt) ""))
             (string-suffix-p "package: " (or (minibuffer-prompt) "")))
    'straight))

(cl-pushnew 'embark-straight-type embark-classifiers)
```

I'd love to help contribute where I can. But I'm still pretty green with elisp. If there's anything simple you all need help with let me know!

**Comment by oantolin** [comment]
Sorry for leaving this here unanswered for such a long time. I think the proper place to put this is in the wiki. It also needs to be rewritten for the current version of embark. The change is trivial: using the new embark-define-keymap` macro. The classifier still works, but nowadays I'd recommend using Marginalia, and configuring it instead.

**Comment by oantolin** [comment]
I've updated these for current Embark, and put them [on the wiki](https://github.com/oantolin/embark/wiki/Additional-Actions#package-actions-using-straightel).
