### ISSUE TITLE
make-directory and target candidates in mini-buffer

### ISSUE THREAD

**Issue by jdtsmith** [oantolin/embark#340]
When completing a find-file, for example, a very convenient ido feature I miss is `M-m`, which prompts for and "makes" a new directory beneath the current, and descends into it immediately.  I see the embark `+` command can make a directory, but by default it picks up on the first matching candidate if there are any matches, and quits the command.  

For example, if I'm under `~/` and want to make the directory `~/tmp`, but there is already a `~/tmp2` directory, I enter `tmp`, then invoke embark-act `+`.  This will not make a `tmp` directory, but silently re-makes the subdirectory `tmp2`.  Obviously not what you want.  

I tried adding `make-directory` to `embark-allow-edit-commands`.  It prompts you first with any matched target which you then have to delete.  But I also note that allow-edit doesn't really freely allow edits.  It has the same behavior as text entered before `embark-act`: if anything you enter matches a completion candidate (subdirectories or files in this example) that will be used in preference to what you entered.  

**Concrete example: attempt to make the new directories `~/tmp2` followed by `~/tmp` (in that order) using just embark `+` from `find-file`.** 

Since it will be incredibly rare to want to make a directory identical to an existing directory (or file) name, perhaps we need an `embark-ignore-candidates-commands` to configure things like `make-directory` to operate preferentially on just the entered text itself.  And/or embark-edit should just be a "free edit" without any completion happening. 

A smaller related issue is that adding `make-directory` to `'embark-repeat-commands` doesn't work; would be nice to have that on by default.  And one final thing: it would be nice if embark's make-directory, when "repeating", would also insert the trailing slash, saving you the Tab (as ido does). 

Thanks for embark, which I use all the time.

**Comment by oantolin** [comment]
First of all, what completion UI are you using?

**Comment by oantolin** [comment]
Second, the quitting or non-quitting nature of actions is controlled by two mechanisms:

- the variable `embark-quit-after-action` sets the default,
- calling `embark-act` with a prefix argument does the opposite of the default set by `embark-quit-after-action`.

**Comment by oantolin** [comment]
I asked about the completion UI because what are asking is basically the same as "how do I select the input as typed instead of the top matching candidate?" and this varies by completion UI. For example, in Vertico or Selectrum what you do press `<up>` to navigate to the minibuffer, which can be highlighted and selected just like the candidates can.

**Comment by oantolin** [comment]
In my setup using default completion, I don't actually have a way to tell `embark-act` that I want it to act on the exact text in the minibuffer. I just realized that now! But somehow it has never been a problem for me, I guess I hardly ever want to create a file or directory whose name matches a pre-existing one. (I tend to pick names so that I can easily get to them with completion by using just a few letters.)

The trick of adding `make-directory` to `embark-allow-edit-commands` should work, though. You said:

> But I also note that allow-edit doesn't really freely allow edits. It has the same behavior as text entered before embark-act: if anything you enter matches a completion candidate (subdirectories or files in this example) that will be used in preference to what you entered.

But their you want to _submit_ the text you typed even if it matches a completion candidate. That's a slightly different problem than the issue of _selecting_ the text you typed. Again how to do this depends on the completion UI. In my setup, for example, I bind `RET` to "submit the top matching candidate" and bind "M-RET" to submit the text in the minibuffer as-is. As I said before in Vertico and Selectrum you can select the text you typed in the minibuffer by moving up to it and then pressing `RET`. In Vertico, additionally, you can press `C-RET` to submit the minibuffer input.

**Comment by oantolin** [comment]
So, in summary, first tell me what completion UI you use and maybe any unusual minibuffer key bindings you might have for `RET`, etc., and then we can try to figure out how to do what you want with your setup.

**Comment by oantolin** [comment]
> A smaller related issue is that adding `make-directory` to `'embark-repeat-commands` doesn't work

Indeed! I think I had only tested the repeatable action stuff outside the minibuffer, so I didn't notice it didn't work for actions in the minibuffer. I have a sort of fix for this, in the sense that I know how to keep the minibuffer alive, but I want to also keep the inidicator alive and that fix doesn't. I'll think a bit more about it. In the meantime remember that you can use `C-u <embark-act>` to have the action not quit (if you have it set to quit by default).

**Comment by jdtsmith** [comment]
> First of all, what completion UI are you using?

Vertico

**Comment by oantolin** [comment]
So does Vertico's way of selecting the prompt work for you here, or do you still think something more is needed for this?

> I admit I didn't quite understand your point about the purpose of edit

Oh, I think there was some miscomunication then, I didn't make any point about the purpose of allowing editing!

> Any thoughts on whether/if the final `/` can be inserted along with sub-directory candidates in a UI/style agnostic manner?

Ah, sorry, I forgot you asked about that. It's easy enough:

```elisp
(defun trailing-slash (&rest _)
  (when (and (minibufferp) (not (looking-back "/" 1)))
    (insert "/")))

(push 'trailing-slash (alist-get 'make-directory embark-post-action-hooks))
```

(The `minibufferp` is in case you call `make-directory` as an action outside the minibuffer, you probably don't want a slash inserted into your buffer in that case.)

**Comment by oantolin** [comment]
> I can navigate "up to the" prompt to enter text as-is (if I remember to)

If you are worried you might forget to select the prompt, you could also allow editing for `make-directory`, but auto-accept when the directory name chosen does not exist. That way if you accidentally forget to select what you meant and instead choose an existing file or directory, you'll be given a chance to rectify (and then you'll need to remember to select the prompt, but at least you're getting a second chance to do so).

```elisp

(defun accept-if-non-existing (_action target _bounds)
  (if (file-exists-p "baaz")
      (message "%s exists, please edit"
               (if (file-directory-p target) "Directory" "File"))
    (add-hook 'post-command-hook #'exit-minibuffer nil t)))

(add-to-list 'embark-allow-edit-commands 'make-directory)

(push 'accept-if-non-existing (alist-get 'make-directory embark-setup-action-hooks))
```

**Comment by oantolin** [comment]
I think with the hooks we have now it's superconvenient to tweak how actions are carried out. It's always just a few lines of code.

**Comment by jdtsmith** [comment]
> > But I also note that allow-edit doesn't really freely allow edits. It has the same behavior as text entered before embark-act: if anything you enter matches a completion candidate (subdirectories or files in this example) that will be used in preference to what you entered.
> 
> But there you want to _submit_ the text you typed even if it matches a completion candidate. That's a slightly different problem than the issue of _selecting_ the text you typed.

I meant this RE the purpose of editing, but possibly you were referring to something else.  I can certainly see why you'd want to be able to correct a choice by hand after accepting a target, but why should that process _also_ be performing completion on candidates?  

The hooks do look quite useful, thanks for the example!

**Comment by oantolin** [comment]
> I can certainly see why you'd want to be able to correct a choice by hand after accepting a target, but why should that process also be performing completion on candidates?

Oh, I see what you mean! The reason you have completion while editing a candidate, is that you're not doing this editing at some made-up Embark-only prompt: you are editing at the actual prompt for whatever command you chose as an action. So in this case, you have file completions while editing the target for `make-directory`, because _that_ is how `make-directory` always works, it prompts for a directory name _with_ file completion. You get file completion because `make-directory` reads its input using `read-file-name`.

(So in fact it's not accurate to say you have completion while editing the target: you do or don't depending on how the action command is defined, it just happens that most Emacs commands tend to have completion of some relevant type at most prompts.)

**Comment by oantolin** [comment]
Also, generally speaking having completion while adjusting the target is super useful. For example, here with directory names, I like having the completion candidates let me confirm visually that I'm in the write directory, and if not, completion helps me navigate to the right one much, _much_ faster than without completion; completion also shows me the names of the other subdirectories, so I can confirm I am conforming to my own naming scheme, etc. It's just reassuring when you are typing a file or directory name to be able to see your file system. Same for buffer completion when you are entering a buffer name, etc.

In fact I think the only downside of having completion is the one you discovered: that completion UIs can make it a little tricky to submit input that is not a candidate but does match one. But this trips people up about completion frameworks all the time, with or without Embark. There are always lots of questions about how you do this!

**Comment by jdtsmith** [comment]
Is it possible that your completion setup does not show _all completions_ right away?  Since mine does, I get all that discoverability up front I think.  So maybe this additional "edit" step is not as useful for those cases.  BTW, Ido's make directory does in fact seem to invoke a recursive non-completing mini-buffer to let you spell out the directory to make, so that's probably what I had in my head when I saw "edit".

**Comment by jdtsmith** [comment]
One other only somewhat related question: for in-buffer completion with e.g. corfu, I was hoping that embark would find the "current candidate target" while completing, just as it does for mini-buffer completion.  Instead it just finds what's in the buffer, like normal.  That would be fantastic to look up help on a function name in realtime, create a directory, etc.  Does this sounds possible to do without much surgery?

**Comment by oantolin** [comment]
> Is it possible that your completion setup does not show _all completions_ right away?

True, my setup does not show them right away. But my point is independent of whether completions are eagerly shown or not. I find the completions useful both at the initial prompt _and_ when editing the target. Say you realize at the editing stage you are in the wrong directory and you actually meant to create a subdirectory of some _other_ directory. Wouldn't you want completion available to navigate to the right place?

**Comment by oantolin** [comment]
Yes, it would be easy to get embark to work with corfu. It is just a matter of adding an appropriate target finder. I'll do that soon.

**Comment by oantolin** [comment]
Since corfu already supports getting documentation on a completion, which is the main reason I'd want embark to work with corfu, it didn't feel urgent.

**Comment by oantolin** [comment]
> Ido's make directory does in fact seem to invoke a recursive non-completing mini-buffer to let you spell out the directory to make

To me this sounds like a minor deficiency in ido. 😛

**Comment by jdtsmith** [comment]
> Since corfu already supports getting documentation on a completion, which is the main reason I'd want embark to work with corfu, it didn't feel urgent.

Oh but embark does so much more! :). Seriously thanks for this great tool. 

Here's an example superpower the _vecom_ universe (**v**ertico-**e**mbark-**c**onsult-**o**rderless-**m**arginalia) brings:

1. `s-L` my binding for `consult-line-multi` with a `(:mode ,major-mode)` flavor.
2. `^(defun !--` all the non internal api defuns in all my files.
3. `C-, E` now I have a multi-occur buffer.
4. `C-c C-f` navigate through the occur however you like and functions pop into view.

**Comment by oantolin** [comment]
Getting Embark to work with Corfu is a little more complicated than I realized, because you have to convince Corfu to stay alive while you are acting (or to startup afterwards and pick up where it left off as if nothing happened, which is maybe easier). In the meantime, if you want to be able to act on completion-in-region candidates you can use `(setq completion-in-region-function #'consult-completion-in-region)`. This uses minibuffer completion for completion in region, so in your setup, you'd get Vertico.

**Comment by minad** [comment]
I didn't see if it was mentioned but you can of course write your own make-directory command which only prompts for a name and takes as a first argument the current target. The current target is the parent directory then.

**Comment by minad** [comment]
Regarding Vertico prompt selection - you can also submit the exact input with C-RET which triggers vertico-exit-input.

**Comment by oantolin** [comment]
@minad 

> Staying alive in Corfu is probably not easy.

Yeah, it seemed tricky when I tried yesterday. What do you think about restarting Corfu instead, like you did to update candidate lists after deleting or renaming things? Is restarting Corfu easier? I thought it might be. 

> you can of course write your own make-directory command which only prompts for a name

We didn't mention that. It is an option.



> Regarding Vertico prompt selection - you can also submit the exact input with C-RET which triggers vertico-exit-input.

That one I did mention. :)

**Comment by minad** [comment]
> Yeah, it seemed tricky when I tried yesterday. What do you think about restarting Corfu instead, like you did to update candidate lists after deleting or renaming things? Is restarting Corfu easier? I thought it might be.

Yes, I think it would be much easier to just restart Corfu. We should get this feature without large Embark changes by writing an `:always` post-action-hook for Corfu, similar to `embark--restart`. The Embark `post-action-hook` and other hooks should probably also get a plist as arguments. Then `embark--act` can add pass `:quit` argument to the hooks.

**Comment by jdtsmith** [comment]
> > Yeah, it seemed tricky when I tried yesterday. What do you think about restarting Corfu instead, like you did to update candidate lists after deleting or renaming things? Is restarting Corfu easier? I thought it might be.
> 
> Yes, I think it would be much easier to just restart Corfu. We should get this feature without large Embark changes by writing an `:always` post-action-hook for Corfu `embark--corfu-restart`, similar to `embark--restart`. The Embark `post-action-hook` and other hooks should probably also get a plist as arguments. Then `embark--act` can add pass `:quit` argument to the hooks, which would be checked by `embark--corfu-restart`.

Analogy: Right-clicking on a popup menu :). But this could be seriously useful.  

RE `consult-completion-in-region`, I separate completion (of function and variable names, file-path strings, dabbrev, etc.) from selection (of files, commands, buffers, etc.) and prefer to keep them distinct, with auto-popup for the former.  

Corfu is perfect for that.  The fact that orderless can be used for both is really very powerful (with only some care needed because "typing new text in the buffer" sometimes collides with "refining my completion search").  Add embark to the mix and the differences between in-buffer and in-minibuffer get reduced yet more.

**Comment by minad** [comment]
> So currently embark-repeat-commands is only used for actions run outside the minibuffer. How about we make it so in the minibuffer, being on the embark-repeat-commands means "do not quit the minibuffer unless requested by prefix argument"?

I actually considered this when proposing the repeat PR. Repeating and not-quitting are not the same thing. Not quitting means to keep the minibuffer alive, repeating means to stay within the embark-act context. We should not do this.

**Comment by jdtsmith** [comment]
That sounds pretty good.  It could also be a specific _opt out_ of the default quit behavior, no matter the setting of `embark-quit-after-action`.  And `C-u` could just toggle or invert the behavior.  

An advantage of this approach is you could still "invert" things which are marked to continue/repeat by calling `embark-act` with a prefix.  Even `n` and `p` in buffer, if you wanted.  

Perhaps `embark-continue-commands` is a better name though?  I'll rarely want to "keep on making directories" for example (as opposed to `n` and `p` which I would do many times in buffer).  

@minad has a good point about the distinction between repeating and not-quitting.  I think for make-directory and others like it, "not-quitting" is what we'd be after.

**Comment by oantolin** [comment]
Sure, non-quitting and repeating are slightly different. Since repeating is not supported in the minibuffer I thought it would be convenient to overload `embark-repeat-commands` for both purposes, but we can add a separate variable for non-quitting. Maybe `embark-quit-after-action-overrides` or something like that.

I also agree that `embark-repeat-commands` is not the best name. It sort of sounds like once you use one of those actions, all you can do is repeat it, but you can of course run any other action.

And this is a little off-topice here, but @minad, would you mind if I removed the `embark-done` stuff bound to `RET`? I miss `RET` being the default action and people can `C-g` when they're done. In fact `C-g` when you're done feels much more natural to me than `RET`.

**Comment by minad** [comment]
> And this is a little off-topice here, but @minad, would you mind if I removed the embark-done stuff bound to RET? I miss RET being the default action and people can C-g when they're done. In fact C-g when you're done feels much more natural to me than RET.

Hmm, I guess I would mind this. I don't see the point in the default action after repeating. For example if you are on a symbol and press next, why would you want the default action on the next symbol? Then you could have as well press RET right away. Pressing C-g is of course also reasonable, but will feel much less familiar overall given Isearch. On the other hand I see your point about Embark consistency. If you don't mind we can introduce a configuration variable `embark-default-repeat-action` which I can set to non-nil. But generally I am hesitant to propose the addition of more configuration variables, see what I wrote before in my other comment.

**Comment by oantolin** [comment]
> I don't see the point in the default action after repeating. For example if you are on a symbol and press next, why would you want the default action on the next symbol?

For symbols there is no point, of course! But consider marking an s-expression and then pressing `u` several times to pass to larger containing s-expressions and then pressing `RET` to evaluate.

But it was just an idea, if people don't think cancelling embark-act with `RET` is wierd, I don't mind keeping this behavior. The default action by convention is always available under some other key.

**Comment by oantolin** [comment]
> But generally I am hesitant to propose the addition of more configuration variables, see what I wrote before in my other comment.

Me too, which is why I wasn't proposing to make this configurable! 🤣 If we do make it configurable, I'd make the variable boolean and call it `embark-RET-cancels-embark-act-but-only-if-you-run-a-repeating-action-first`. 😉

**Comment by oantolin** [comment]
As for the non-quitting actions, how about instead of overloading `embark-repeat-actions`, we change `embark-quit-after-action`. We can make it a plist with keys `:quit`, `:continue` and `:default` or `t` (whose value would have the meaning of the current `embark-quit-after-action`). And then prefix argument can always mean "do the opposite of what the configuration says".

**Comment by minad** [comment]
> For symbols there is no point, of course! But consider marking an s-expression and then pressing u several times to pass to larger containing s-expressions and then pressing RET to evaluate.

Yes, you have a good point here. Therefore I proposed one should make it fully customizable as a list ;)

> As for the non-quitting actions, how about instead of overloading embark-repeat-actions, we change embark-quit-after-action. We can make it a plist with keys :quit, :continue and :default or t (whose value would have the meaning of the current embark-quit-after-action). And then prefix argument can always mean "do the opposite of what the configuration says".

This is a good idea. I agree with that.

**Comment by minad** [comment]
I took the liberty to pull these ideas to the toplevel, such that these ideas don't get lost :)

**Comment by jdtsmith** [comment]
> But consider marking an s-expression and then pressing `u` several times to pass to larger containing s-expressions and then pressing `RET` to evaluate.

This is a strong argument for `RET` consistency!

**Comment by minad** [comment]
> This is a strong argument for RET consistency!

It is a strong argument, but I would say it is as strong as my argument against consistency for symbols. Therefore we should probably make this customizable, even if we all dislike adding more and more customization options. As long as the newly added customization options are in a very general form at least something is won. I am most opposed to configuration options which don't generalize and only tweak a very small detail.

Btw, this u expression action is really good. This feature goes in the direction expand-region if we introduce more target finders, like the comment target finder proposed in #232. I should try if expand-region can somehow integrate with Embark, but I am currently not using this package.
