### ISSUE TITLE
How to export subset of `consult-buffer`candidates?

### ISSUE THREAD

**Issue by okamsn** [oantolin/embark#346]
Hello.

I like to have the recently used files as candidates in `consult-buffer`, since I occasionally try to switch to a file that I mistakenly think is open. However, when I use `embark-export` from `consult-buffer`, I'd prefer to just export the buffer candidates to Ibuffer instead of exporting all of the candidates to an `*Embark Collect*` buffer.

What is the best way to export only the buffer candidates from `consult-buffer`?

Thank you.

**Comment by oantolin** [comment]
Export always takes the current completion candidates, so if you want only buffers, narrow to buffers before exporting. In case you haven't used it before, narrowing is a really neat feature of various consult commands, including `consult-buffer`. If starting from an empty minibuffer at the `consult-buffer` prompt you press `b SPC`, then you will only get buffer matches. See the consult readme for more information on [narrowing in general](https://github.com/minad/consult#narrowing-and-grouping) and specifically [narroing in consult-buffer](https://github.com/minad/consult#virtual-buffers).

>

**Comment by oantolin** [comment]
I also should have pointed out that if `embark-export` notices that all the currently matching `consult-buffer` candidates are in fact buffers, it will use `ibuffer` rather than a generic embark collect buffer. Similarly if all matches were files, you'd get dired; if all matches are bookmark, you get a bookmark list. The generic embark collect buffer is only used if the matching candidates are a mix of types.

**Comment by okamsn** [comment]
> I also should have pointed out that if `embark-export` notices that all the currently matching `consult-buffer` candidates are in fact buffers, it will use `ibuffer` rather than a generic embark collect buffer. 

I'm not seeing that behavior with the most recent versions of Consult, Embark, and Consult-Embark. If I narrow to buffers with `b SPC` and then call `embark-export`, I still get the `*Embark Collect*` buffer, just of only buffer candidates.

Does that make this an issue of Consult?

**Comment by oantolin** [comment]
That sounds like you might not actually be loading `embark-consult`. Do you see that behavior after an explicit `(require 'embark-consult)`?

This stuff works in my configuration, I'll test from `emacs -Q` and report back.

**Comment by oantolin** [comment]
This worked:

1. `emacs -Q`
2. `M-x package-initialize`
3. `M-x load-library RET embark-consult`
4. `M-x global-set-key C-; embark-act`
5. `M-x consult-buffer b SPC C-; E`.

I did get an ibuffer buffer doing that.

**Comment by oantolin** [comment]
Do you see the problem loading `embark-consult` from `emacs -Q`?

**Comment by okamsn** [comment]
> That sounds like you might not actually be loading `embark-consult`. Do you see that behavior after an explicit `(require 'embark-consult)`?

This was the issue.  The README says to do

``` elisp
;; Consult users will also want the embark-consult package.
(use-package embark-consult
  :ensure t
  :after (embark consult)
  :demand t ; only necessary if you have the hook below
  ;; if you want to have consult previews as you move around an
  ;; auto-updating embark collect buffer
  :hook
  (embark-collect-mode . consult-preview-at-point-mode))
```

but for my case, the `:demand t` is needed to load the package. This is because I use `use-package` with `straight.el`.  Without the `:demand`, it expands to 

``` elisp
(progn
  (straight-use-package 'embark-consult)
  (defvar use-package--warning227
    #'(lambda
        (keyword err)
        (let
            ((msg
              (format "%s/%s: %s" 'embark-consult keyword
                      (error-message-string err))))
          (display-warning 'use-package msg :error))))
  (condition-case-unless-debug err nil
    (error
     (funcall use-package--warning227 :catch err))))
```

in which `straight-use-package` makes available, but does not load, `consult-embark`.  Adding the `:demand t` adds the needed `require` to the expansion:

```elisp
(progn
  (straight-use-package 'embark-consult)
  (defvar use-package--warning230
    #'(lambda (keyword err)
        (let ((msg (format "%s/%s: %s" 'embark-consult keyword
                           (error-message-string err))))
          (display-warning 'use-package msg :error))))
  (condition-case-unless-debug err
      (eval-after-load 'consult
        '(eval-after-load 'embark
           '(if (not (require 'embark-consult nil t))
                (display-warning 'use-package
                                 (format "Cannot load %s" 'embark-consult)
                                 :error))))
    (error (funcall use-package--warning230 :catch err))))
```

I apologize for missing that. Thank you for you help.

**Comment by oantolin** [comment]
> I apologize for missing that. Thank you for you help.

No apology is necessary! And you're welcome.
