### ISSUE TITLE
Keymap prompter also shown during M-x despite 'embark-completing-read-prompter'

### ISSUE THREAD

**Issue by woolsweater** [oantolin/embark#354]
With `embark-prompter` set to `embark-completing-read-prompter`, I am seeing the keymap prompter displayed at the same time as the completing prompter when I invoke `embark-act` from the minibuffer. This seems to make sense if one is not using a vertical completion feature (I use selectrum), but it's redundant if one does. I can't make out whether this is intentional, though, or even why it's happening.

My install of Embark is at https://github.com/oantolin/embark/commit/1f8cf373ee5e308ec953315a5803c4e939b40556, from yesterday. With `emacs -Q`, I run just this as setup:

```elisp
(add-to-list 'load-path "~/.emacs.d/straight/repos/embark/")
(require 'embark)
(global-set-key (kbd "C-.") #'embark-act)
(setq embark-prompter #'embark-completing-read-prompter)
````

and then see:

<img width="584" alt="Screen Shot 2021-09-05 at 2 42 49 PM" src="https://user-images.githubusercontent.com/761245/132142177-71844a06-1b11-44f9-b5e0-eedf5ad1164c.png">

**Comment by oantolin** [comment]
The thing you are seeing, that pops up the `*Embark Actions*` buffer, is not the keymap prompter but either the mixed or verbose indicator.  Try customizing `embark-indicators` to replace the mixed or verbose indicator with the minimal indicator.

**Comment by woolsweater** [comment]
I see! I was confused because that indicator appears when the prompter is the keymap prompter as well. This makes sense. Thanks, and thanks for all your work on Embark!

**Comment by oantolin** [comment]
This is confusing! It's the last thing I intend to add to the manual before tagging a release.
