### ISSUE TITLE
embark-act - not show list  of commands

### ISSUE THREAD

**Issue by alexei-28** [oantolin/embark#356]
Linux Mint 20.2.
Emacs 27.1
Embark ver. 0.10

I select some region and `M-x embark-act` but in minibuffer not show list of commands.

![first](https://user-images.githubusercontent.com/303539/132960468-4e7ca5c9-e806-47af-89e1-667ccec2d1ba.png)

Here result. 
Show in minibuffer text: 
**Act on region**
![second](https://user-images.githubusercontent.com/303539/132960473-db011bd3-b360-4fbe-ad22-91ea3f576d2b.png)

**Comment by oantolin** [comment]
You could use the embark-completing-read-prompter instead. You have two options for doing that:

- After calling `embark-act` press `C-h`.
- `(setq embark-prompter #'embark-completing-read-prompter)`.

If you really want to use the new embark indicator that pops up a list of action you'll have to upgrade, it didn't exist in 0.10.

**Comment by alexei-28** [comment]
> You could use the embark-completing-read-prompter instead. You have two options for doing that:
> 
> * After calling `embark-act` press `C-h`.
> * `(setq embark-prompter #'embark-completing-read-prompter)`.
> 
> If you really want to use the new embark indicator that pops up a list of action you'll have to upgrade, it didn't exist in 0.10.

A unisntall Embark ver 0.10. And install **Embark ver. 20210911.37**.
And as result the  problem is gone

![ok](https://user-images.githubusercontent.com/303539/132995613-51250f12-3a09-4d2e-875d-b060bbd40132.png)

**Comment by oantolin** [comment]
Glad to hear it!
