### ISSUE TITLE
embark-find-definitions failing due to symbol argument

### ISSUE THREAD

**Issue by mohkale** [oantolin/embark#357]
## The Problem

After a recent emacs upgrade I'm finding embark-find-definitions is failing.

```lisp
Debugger entered--Lisp error: (wrong-type-argument buffer-or-string-p embark-find-definition)
  get-text-property(0 pos embark-find-definition)
  #f(compiled-function (backend identifier) #<bytecode 0xf438bbcc2b6baa1>)(elisp embark-find-definition)
  apply(#f(compiled-function (backend identifier) #<bytecode 0xf438bbcc2b6baa1>) elisp embark-find-definition)
  xref-backend-definitions(elisp embark-find-definition)
  #f(compiled-function () #<bytecode -0x14921df9f8ff9ee6>)()
  consult-xref(#f(compiled-function () #<bytecode -0x14921df9f8ff9ee6>) ((window . #<window 10 on *scratch*>) (display-action)))
  xref--show-defs(#f(compiled-function () #<bytecode -0x14921df9f8ff9ee6>) nil)
  xref--find-definitions(embark-find-definition nil)
  xref-find-definitions(embark-find-definition)
  (let ((xref-backend-functions #'(lambda nil 'elisp))) (xref-find-definitions symbol))
  embark-find-definition(embark-find-definition)
  funcall-interactively(embark-find-definition embark-find-definition)
  call-interactively(embark-find-definition nil nil)
  command-execute(embark-find-definition)
  #f(compiled-function () #<bytecode 0x208cb6d60e8a4a4>)()
  apply(#f(compiled-function () #<bytecode 0x208cb6d60e8a4a4>) nil)
  #f(compiled-function () #<bytecode -0x1a4d1e07f38d59a4>)()
  #f(compiled-function () #<bytecode -0x15820bb4ad722b9a>)()
```

My best guess is something upstream in xrefs elisp backend used to accept symbols but now only accepts strings, or something to that affect. However strangely I can still use `xref-find-references` (bound to "r") from embark with no issue.

### Minimal Reproduction
I can reproduce the error by evaluating the following lisp form:

```lisp
(let ((xref-backend-functions (lambda () 'elisp)))
  (xref-find-definitions 'embark-find-definition))
```

I'm running on emacs: `GNU Emacs 28.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2021-09-15`

#### With Embark

1. Start emacs
2. Run `M-x describe-variable`
3. Run `M-x embark-act`
4. Hit `Enter`

## A Quick Fix
The following advice seems to fix the issue:

```lisp
(advice-add 'embark-find-definition :filter-args
            (defun embark-stringify-symbol+ (args)
              `(,(symbol-name (car args)) ,@(cdr args))))
```

**Comment by oantolin** [comment]
I think older Emacsen accept both symbols and strings, so I'll just change the interactive spec to "s" for string. I thought using the "S" interactive spec for symbols offered completion from the obarray, but no, so there's 0 advantage to making the argument a symbol.
