### ISSUE TITLE
consult-line: no live preview

### ISSUE THREAD

**Issue by alexei-28** [oantolin/embark#358]
Linux Mint 20,
Emacs 27.1

Consult, Vertico, Embark 

Suppose I want to find text **defun** in file.

Steps:

`M-x consult-line`  and input `defun`

![1](https://user-images.githubusercontent.com/303539/133802449-05bf61da-c574-4039-ac4e-bcc1275b1acf.png)
It's success find all lines with text **defun**. Nice ... but when I move down (on minibuffer) by arrow down (not press RET) the top buffer is not automove to selected line.

![2](https://user-images.githubusercontent.com/303539/133802664-3a5ef784-2940-499f-8b86-cc69c5c8c013.png)

Is it possible to automove line on top buffer (live preview) when moving on minibuffer (and not press RET)?

**Comment by oantolin** [comment]
I think consult has live previews by default, I'm not sure why it's not working for you. Also, I have no idea why you opened this issue here on the Embark repo.
