### ISSUE TITLE
Add a customize variable to help user add actions can run directly?

### ISSUE THREAD

**Issue by TxGVNN** [oantolin/embark#364]
Hi @oantolin,

Thank you for great package. I would like to ask if we can add this feature because I want to add a function in embark-act run as embark-become.

I did not create PR because I want to ask you about the idea first.
Thanks

```diff
 
+(defcustom embark--action-directly '(embark-become        ; these actions should not
+                                     embark-collect-live  ; run in the target window
+                                     embark-collect-snapshot
+                                     embark-export)
+  "List action can run directly."
+  :type 'list)
+
 (defun embark--act (action target &optional quit)
   "Perform ACTION injecting the TARGET.
 If called from a minibuffer with non-nil QUIT, quit the
 minibuffer before executing the action."
-  (if (memq action '(embark-become        ; these actions should not
-                     embark-collect-live  ; run in the target window
-                     embark-collect-snapshot
-                     embark-export))
+  (if (memq action embark--action-directly)
       (command-execute action)
```

**Comment by minad** [comment]
Seems better to not hard code this.

**Comment by oantolin** [comment]
I only hard coded it because I couldn't think of any other commands people would want to run directly (and for many, many months no one requested this so I'm not that crazy 😉). But I'd be happy to make this configurable.

Out of curiosity: what do you want to run directly? I mean, basically the only reason is that you want your action to run in the current buffer rather than in Embark's notion of target buffer. These only differ when you are in the minibuffer, so you'd need this confguration only for actions you want to run _from_ the minibuffer _in_ the minibuffer.

**Comment by oantolin** [comment]
The hard-coded list contains all commands I'm aware of that would give the wrong answer when run from Embark's target buffer.

**Comment by TxGVNN** [comment]
Maybe I have a crazy emacs workflow. Not wanna lie, I have a function as below:

```emacs-lisp
(defun embark-become-project(&optional full)
  (interactive "P")
  (embark--quit-and-run
   (lambda ()
     (let ((use-dialog-box nil)
           (this-command 'project-switch-project))
       (command-execute this-command)))))

(define-key embark-general-map (kbd "p") #'embark-become-project)
```

So I can switch project anywhere with embark-act (almost I'm in `minibuffer` as `find-file`, `project-find-file`). It prompts candidates to switch to other project. But after the commit https://github.com/oantolin/embark/commit/d1b46dafdad8e1ed21075401c0022814e3d08fcd. It doesn't work anymore, it doesn't prompt candidates. I don't know why :(

That why I create this issue, after that I can add my `embark-become-project` to list.

**Comment by oantolin** [comment]
Let me see if I understand correctly: the effect you want when you press `p` is that (1) the current minibuffer quits, (2) `project-switch-project` runs and prompts you for a project?

If so, the only thing you are doing wrong is that you aren't consuming the Embark target, so what happens is that it gets injected at the `project-switch-project` prompt. Also, I have no idea why you have the `full` argument. Try this variation on your function and let me know if it does what you want:

```elisp
(defun embark-become-project(&optional _target)
  (interactive "s") ; prompt for _target and ignore it
  (embark--quit-and-run
   (lambda ()
     (let ((use-dialog-box nil)
           (this-command 'project-switch-project))
       (command-execute this-command)))))
```

**Comment by TxGVNN** [comment]
> Let me see if I understand correctly: the effect you want when you press p is that (1) the current minibuffer quits, (2) project-switch-project runs and prompts you for a project?

Yes, exactly

> Also, I have no idea why you have the full argument. 

I copy-paste follow `embark-become` function without modify, and it did work in the past :D. I don't understand deep about it :(

>(defun embark-become-project (&optional _target)
>  (interactive "s") ; prompt for _target and ignore it
>  (embark--quit-and-run
>   (lambda ()
>     (let ((use-dialog-box nil)
>           (this-command 'project-switch-project))
>       (command-execute this-command)))))

Perfect. It works as my expected. Each time I create an issue, I learned so much. LOL. Thank you very much
