### ISSUE TITLE
completing-read-prompter does not support menu-items

### ISSUE THREAD

**Issue by minad** [oantolin/embark#383]
Complex menu-items are not supported:

~~~ elisp
(embark-completing-read-prompter isearch-menu-bar-map nil 'no-default)
(embark-completing-read-prompter tool-bar-map nil 'no-default)
~~~

Simple menu-items (description/command pairs) are supported:

~~~ elisp
(let ((map (make-sparse-keymap)))
  (define-key map "y" (cons "description" #'command))
  (define-key map "x" #'command)
  (embark-completing-read-prompter map nil 'no-default))
~~~

**Comment by oantolin** [comment]
I'm not sure I made the best choice for what to show as the key binding, I choose the string "menu-item".

**Comment by oantolin** [comment]
I thought the simplest way to support these is to ignore all dynamism and just always show them, but maybe I should respect `:visible` and `:filter`.

**Comment by oantolin** [comment]
I should also make more of an effort to show an actual key bindings. I'm reopening until I add support for those things.

**Comment by oantolin** [comment]
I've added support for `:filter` and simplified the implementation a bit by relying on `keymap--menu-item-binding`. da144277663d761a22e0425117528b19b4fd43ba

I looked up what which-key does, and they also only support `:filter`, not stuff like `:visible` or `:enable`. Maybe we're OK ignoring those latter ones.

**Comment by oantolin** [comment]
I'm leaning towards keeping just the current level of support: `:filter` is supported, but I ignore `:visible`, `:enable`, `:keys` and `:key-sequence`.

**Comment by oantolin** [comment]
I think this is good enough for "naturally occurring" menu items, if anyone wants support for other menu-item properties just let me know. I suspect it's not something people actually need from embark beyond `:filter`
