### ISSUE TITLE
Group headers in embark-collect buffers

### ISSUE THREAD

**Issue by karthink** [oantolin/embark#389]
Apologies if this has already been asked, I couldn't find anything relevant in a search.

Is there a way to see group headers in embark-collect buffers for multiple group lists (like consult-buffer)? I mean these things:

![2021-10-24-094031_982x156_scrot](https://user-images.githubusercontent.com/8607532/138603906-c345db42-c98a-4a58-be94-7f2821f904af.png)

Also it would be useful to jump to the next/previous group in the embark-collect buffer with a keybinding, like when using `vertico-next-group`.

**Comment by minad** [comment]
The group headers would be useful for `consult-imenu` and the live updating TOC.

**Comment by oantolin** [comment]
> I think this issue would also get easier if we remove grid view (#479).

Yes. :)

**Comment by oantolin** [comment]
I implemented group-function support. Pressing RET on a group header hides or shows its members. I'm very much open to suggestions on improving the appearance. I followed @hmelman and @karthink's suggestion to use outline-minor-mode for the hide/show functionality, but kept the outline character visible. I bound `M-n` and `M-p` to `outline-next-heading` and `outline-previous-heading`.

**Comment by oantolin** [comment]
Mmh. I might start using collect rather than export for `consult-grep`! It's significantly cleaner looking!

**Comment by oantolin** [comment]
I also changed the default "table of contents" you get by running `embark-live` in regular buffers to be imenu items if you are in a prog mode buffer and outline headings otherwise. The imenu TOC uses the nice group-function that consult-imenu uses if you have an entry in `consult-imenu-config` for your major mode.
