### ISSUE TITLE
Release list doesn't mention removed features

### ISSUE THREAD

**Issue by unhammer** [oantolin/embark#393]
I was depending on embark-overriding-keymap, then it disappeared without any mention in https://github.com/oantolin/embark/releases and there's nothing about removed features in the main readme either; it would be nice with an UPGRADING section  somewhere of deprecated/removed features.

**Comment by oantolin** [comment]
I'm sorry about this! Does the [recipe in the wiki] (https://github.com/oantolin/embark/wiki/Additional-Configuration#associate-commands-with-actions) serve as an adequate replacement for your usage of `embark-overriding-keymap`?

**Comment by unhammer** [comment]
Thanks, that page helped :) 

(To be clear, I'm not saying I need the old feature, just saying it'd be nice to have a fairly accessible way of finding a list about how to upgrade / what is deprecated. But I understand it's a bit early in the progress – perhaps this issue should be saved for when embark is closer to 1.0, feel free to close and ignore ;))

**Comment by oantolin** [comment]
There is a News section I sometimes but at the beginning of the README, but a more formal and append-only changelog would be better.

**Comment by alphapapa** [comment]
I agree that the readme should contain a changelog for the updates in each released version.  As a user, I'm excited about the new paradigm this package provides, and the development in each version may bring new features and power, but it's not practical for a user to review the git log for each release to find out, e.g. what new commands or options are available.

**Comment by oantolin** [comment]
I finally started a changelog.
