### ISSUE TITLE
Issue with embark-hide-which-key-indicator in Wiki

### ISSUE THREAD

**Issue by ryankask** [oantolin/embark#398]
The `embark-hide-which-key-indicator` and the related advice call in the Wiki don't play well with `(setq prefix-help-command #'embark-prefix-help-command)`.

`embark-hide-which-key-indicator` doesn't call the wrapped function when the `when-let` condition evaluates to `nil`.

I changed it to the following but I'm not sure if there's a cleaner way:

```
(defun embark-hide-which-key-indicator (fn &rest args)
  "Hide the which-key indicator immediately when using the completing-read prompter."
  (if-let ((win (get-buffer-window which-key--buffer 'visible)))
      (progn
        (quit-window 'kill-buffer win)
        (let ((embark-indicators (delq #'embark-which-key-indicator embark-indicators)))
          (apply fn args)))
    (apply fn args)))
```

**Comment by oantolin** [comment]
Can you be a little more precise than "don't play well"? I've been playing around with the configuration from the wiki and it seems to be behaving correctly. I agree with this:

> embark-hide-which-key-indicator doesn't call the wrapped function when the when-let condition evaluates to nil.

But I can't get the when-let condition to evaluate to nil, for it to evaluate to nil I guess the which-key buffer should not be visible, but I can't seem to get that to happen.

So, can you explain in more detail what the problem you observed is?

**Comment by oantolin** [comment]
Oh, I see what you mean! You're solution is fine. We could also do this:

```elisp
(defun embark-hide-which-key-indicator (fn &rest args)
  "Hide the which-key indicator immediately when using the completing-read prompter."
  (when-let ((win (get-buffer-window which-key--buffer 'visible)))
    (quit-window 'kill-buffer win))
  (let ((embark-indicators
         (delq #'embark-which-key-indicator embark-indicators)))
      (apply fn args)))
```

**Comment by oantolin** [comment]
I think I slightly prefer the version with `when-let`, because it avoids repeating `(apply fn args)`. I'll update the wiki. (Also I'm pretty sure `delq` works here, but just to make it super clear `embark-indicators` is only temporarily changed, I'll use `remq` instead.)

**Comment by oantolin** [comment]
Thanks for reporting this!

**Comment by roshanshariff** [comment]
Which-key has a function that does the same thing as that when-let form (and in fact also works for other kinds of which-key displays)::
```emacs-lisp
(define-advice embark-completing-read-prompter (:around (fn &rest args) +hide-which-key)
  (which-key--hide-popup-ignore-command)
  (let ((embark-indicators (delq #'embark-which-key-indicator embark-indicators)))
    (apply fn args)))
```

**Comment by oantolin** [comment]
Thanks @roshanshariff! I've made the change on the wiki.
