### ISSUE TITLE
Dispatch menu displaying keys

### ISSUE THREAD

**Issue by leungbk** [oantolin/embark#40]
In newer Emacsen, `project-switch-project` will, after selecting the project, show a dispatch menu with possible options. It would be nice if Embark did this after using `embark-act`.

**Comment by oantolin** [comment]
There is something like this already in embark. If you type `C-h` at the action prompt (or the become prompt), you get prompted for an action with completion. If you use any completion framework such as the built-in icomplete or fido-mode, or an external framework such as ivy, helm or selectrum, or even embark's `embark-completing-read` function, this displays all the actions and lets you choose one via completion.

If you like choosing actions via completion and don't want to press `C-h` each time, thanks to @clemera, you can simply customize the `embark-prompt-style` to the value `'completion`, and then you will automatically get the completion interface.

**Comment by clemera** [comment]
See also the which-key integration described in the [wiki](https://github.com/oantolin/embark/wiki/Additional-Configuration#use-which-key-like-a-key-menu-prompt).

**Comment by oantolin** [comment]
There is a bunch of formatting logic that would need to be implemented, which would amount to reimplementing a chunk of which-key, so I'm deciding that the official recommendation for this is to install which-key and use the configuration that @clemera mentioned.
