### ISSUE TITLE
embark-collect-live: Separate minibuffer/buffer live delay

### ISSUE THREAD

**Issue by minad** [oantolin/embark#405]
When using live collect for real buffers it may make sense to use a larger delay for the more expensive buffer collectors to reduce cpu and gc load? For minibuffer/completion you may prefer something fast, but there the candidate generation is also very fast.

**Comment by oantolin** [comment]
Good point, I agree.

**Comment by oantolin** [comment]
That reminds me: maybe the delay in `embark-live` needs to be configurable.
