### ISSUE TITLE
Manual: Mention embark-export/collect usage in normal buffers

### ISSUE THREAD

**Issue by minad** [oantolin/embark#407]
The live updating TOC is quite a killer feature :)

**Comment by oantolin** [comment]
I mention it briefly now, when discussing `embark-collect-live`:

> This command can also be used outside the minibuffer if you have a relevant candidate collector registered in `embark-candidate-collectors`. Users of the `embark-consult` package, for example, get such a candidate collector registered for them, and can produce a live-updating table of contents for any buffer, whose items are the lines matching `outline-regexp`.

I just realized that, technically, I only mention `embark-collect-live` can be used in regular buffers, and don't mention that also `embark-export` and `embark-collect-snapshot` can be used.
