### ISSUE TITLE
smerge integration

### ISSUE THREAD

**Issue by fbergroth** [oantolin/embark#412]
How about making smerge diffs be an embark target?

The keymap could perhaps be:
```
(embark-define-keymap embark-smerge-map
  "Keymap for Embark smerge actions."
  ("RET" smerge-keep-current)
  ("u" smerge-keep-upper)
  ("l" smerge-keep-lower)
  ("n" smerge-next)
  ("p" smerge-prev))
```

**Comment by oantolin** [comment]
I'm a little confused about the benefits of doing this. Maybe you can help me understand your motivation.

First, there is a more comprehensive keymap already available in `smerge-basic-map`.

But more importantly, I'm not sure what the benefit of integrating smerge with Embark is. Is it shorter keybindings? If that's the case you can configure `smerge-command-prefix`, you can even set it to the empty string and have the keybinding accessible directly when you are in `smerge-mode`. 

Or is the advantage that the Embark Actions buffer would remind of what the actions are?

Also, when would you want Embark to offer you these actions? When you are in `smerge-mode`? Turning on `smerge-mode` already makes those key bindings accessible, so I'm not sure what you'd gain.

**Comment by fbergroth** [comment]
You are right, I didn't really think this through.

I was thinking it would be nice to have `smerge-keep-current` bound to `embark-dwim` (which I bind to `M-.`), and having the rest of the commands a bit more accessible via embark rather than via their default keybindings.

It would be a bit more ergonomic for me, but probably it doesn't make much sense adding it to embark, so I'll close this.

**Comment by oantolin** [comment]
Oh, I see, yes, having `smerge-keep-current` on `embark-dwim` makes sense. And probably your key binding for Embark is shorter than the default smerge prefix of `C-c ^`. 😄

But I don't think Embark integration would provide enough convenience to really make the addition worth it. It still might be a good example for the wiki. Maybe the target finder could trigger only in smerge mode and only on a `>>>>>>`, `======` or `<<<<<<` line. It could report the bounds of the entire diff hunk to highlight it. The next and prev actions could be repeatable.

If you do add this to your configuration and like the results, please consider adding it to the wiki.

**Comment by fbergroth** [comment]
> Maybe the target finder could trigger only in smerge mode and only on a `>>>>>>`, `======` or `<<<<<<` line. It could report the bounds of the entire diff hunk to highlight it. The next and prev actions could be repeatable.

Right, that was what I had in mind. I hacked something together in case anyone wants to try it.
```
(defun embark-target-smerge-at-point ()
  (when (bound-and-true-p smerge-mode)
    (when-let (ov (cl-find-if (lambda (ov) (eq (overlay-get ov 'smerge) 'conflict))
                              (overlays-at (point))))
      `(smerge-diff "conflict" ,(overlay-start ov) . ,(overlay-end ov)))))

(embark-define-keymap embark-smerge-map
  "Keymap for Embark smerge actions."
  ("RET" smerge-keep-current)
  ("u" smerge-keep-upper)
  ("l" smerge-keep-lower)
  ("n" smerge-next)
  ("p" smerge-prev))

(add-to-list 'embark-keymap-alist '(smerge-diff . embark-smerge-map))
(add-to-list 'embark-target-finders 'embark-target-smerge-at-point)
(add-to-list 'embark-repeat-actions 'smerge-next)
(add-to-list 'embark-repeat-actions 'smerge-prev)
```

**Comment by oantolin** [comment]
I'd suggest not defining `embark-smerge-map`, and simply reusing `smerge-basic-map` (it already contains exactly the key bindings you chose, plus a few other that might be useful). So I'd remove the `(embark-define-keymap ...)` and then use `(add-to-list 'embark-keymap-alist '(smerge-diff . smerge-basic-map))`

**Comment by fbergroth** [comment]
Ah, right, I updated the previous comment.

**Comment by oantolin** [comment]
I didn't know you could omit the variable in `when-let` if you don't care about the value! That's handy,

**Comment by hmelman** [comment]
I'm not an smerge user, but I wonder if it's worth suggesting to them to add an overlay keymap the way `symbol-overlay` does.

**Comment by oantolin** [comment]
> I'm not an smerge user, but I wonder if it's worth suggesting to them to add an overlay keymap the way `symbol-overlay` does.

I missed this remark 24 days ago, @hmelman. I think that's a good idea. And that in general the idea of context-specific keymaps is underused. Another neat package like `symbol-overlay` is `selected` which gives you a keymap for the active region.

**Comment by hmelman** [comment]
> Another neat package like `symbol-overlay` is `selected` which gives you a keymap for the active region.

I don't think I was aware of `selected`.  Do you use this with `embark-region-map`?  I don't use embark on regions much, but I love it for discovery.  TIL about the interactive use of `transpose-regions` from it.  I also love it for easy access to infrequently used commands with complex bindings like `calc-grab-sum-down`. So embark's region utility has been great for me, does `selected` add much on that or just let you skip `embark-act`?

**Comment by oantolin** [comment]
You are right: compared to `embark-region-map` all `selected` does is let you skip `embark-act`. That's actually why I stopped using it: it didn't really seem worth it, but I still think it's a neat package with a great idea and highly recommend it to non-embark users. It should probably be built-in: it seems a little unfair that rectangular selections have their own keymap, namely `rectangle-mode-map`, but regular selections don't.

A few other packages which I think are very good and tightly focused have been subsumed for me by consult and embark: one is `flimenu` which flattens the `imenu` hierarchy, which I replaced with `consult-imenu`; another is `imenu-list`, which is I replaced with `consult-imenu` + `embark-collect-snapshot`, or more recently with just `embark-collect-live` now that we have the `embark-consult-outline-candidates` candidate collector for regular buffer.

**Comment by minad** [comment]
> It should probably be built-in: it seems a little unfair that rectangular selections have their own keymap, namely rectangle-mode-map, but regular selections don't.

Isn't seleted like a transient-mark-mode-map (which does not seem to exist)?

> A few other packages which I think are very good and tightly focused have been subsumed for me by consult and embark

Additionally to selected and flimenu there are more packages which have an equivalent in Embark/Consult and related packages:

* imenu-anywhere: consult-imenu-multi
* amx/smex: Marginalia annotations, vertico/selectrum sorting by history position
* browse-kill-ring: consult-yank+embark-collect

**Comment by hmelman** [comment]
Yeah imenu is best from the keyboard.  Before consult I used the counsel imenu command and before that I had written my own.

**Comment by oantolin** [comment]
> Isn't selected like a transient-mark-mode-map (which does not seem to exist)?

Not quite, the thing is that `rectangle-mode` is only on when there is an active rectangular region; while `transient-mark-mode` is on whether or not you currently do have an active region, so it's keymap would be on all the time!

> amx/smex: Marginalia annotations, vertico/selectrum sorting by history position

Don't forget the OG: icomplete-mode has sorted by history position since before either Vertico or Selectrum existed!

**Comment by minad** [comment]
See also the bug report `https://debbugs.gnu.org/cgi/bugreport.cgi?bug=52457`.

Yes, default completion and Icomplete both sort by history. However the sorting thre is slow and it has even been broken before Emacs 28 for files. I submitted the patch to fix this (but it is still slow). If I recall correctly the only completion system which implements good sorting is currently Vertico and maybe Helm. :-P

**Comment by oantolin** [comment]
I decided in the end to add this to Embark's cofniguration, but I made many more actions repeatable, since I find that whenever I keep a version I always want to go to the next conflict anyway.

**Comment by minad** [comment]
What about inheriting from the embark-general-map. Or do we allow multiple keymaps in the keymap alist?

**Comment by oantolin** [comment]
Oh, darn, I forgot about embark-general-map. We _do_ allow multiple keymaps, I'll put it in.

**Comment by oantolin** [comment]
Thanks for reminding me, @minad. e40f9740310dfe7119491572d7e5aaf8341ef182
