### ISSUE TITLE
embark-bindings-at-point

### ISSUE THREAD

**Issue by minad** [oantolin/embark#414]
Idea by @astoff in https://github.com/minad/consult/issues/6#issuecomment-973983332. See also https://github.com/minad/consult/issues/6#issuecomment-973997603. Added here as an issue such that it does not get lost in the endless Consult wishlist.

**Comment by oantolin** [comment]
So, there are several sources of keybindings you might want to show:

- all of them, the current `embark-bindings`
- the ones at point, this proposed `embark-bindings-at-point`
- the ones in a given keymap: you are prompted for a variable ending in `-map` and then see the key bindings in it ([like this](https://github.com/oantolin/emacs-config/blob/0ec52542f46d6634e400ad9b07c8f3f81d0e6f62/my-lisp/help-extras.el#L3)).

I'd rather not have three different commands for these! Any suggestions? We could have a single command that distinguishes the 3 cases with `C-u` and `C-u C-u`. Or maybe we display the ones at point if there are any, otherwise a single `C-u` picks between the other two functions...

**Comment by minad** [comment]
Hmm I think I prefer separate commands for each of those. I bind them then to `C-h b .`, `C-h b m` and so on. Having separate commands increases visibility.

**Comment by minad** [comment]
On the other hand if there are only few alternatives of a single command C-u is indeed not a bad idea. Or rather if a command is modified in it's behavior. For example in Consult I use C-u to toggle the consult-line start point. But I have a separate consult-line-multi. Same with embark-act where the quitting behavior is modified. One could argue that displaying different keymaps falls into the class of modified behavior. Hmm.

**Comment by oantolin** [comment]
A concrete proposal (that I'm not too fond of) is:

- Without `C-u` either show the keybindings at point if such a map is found or prompt for a keymap variable.
- With `C-u` show all bindings (it's the universal prefix, so it shows you the universe).

Maybe it's annoying that if there are bindings at point you have to move if you wanted to be prompted for a keymap variable but (1) I don't think keymaps at point are very common, so this is unlikely to be a big problem, and (2) those few existing keymaps could use some more discoverability!

Also, this would change the current behavior hiding it behind a `C-u`. Personally  I don't mind, I think pulling up a list of all visible key bindings is a little crazy and I don't ever use `embark-bindings` in its current form. But it was a popular request on the consult wishlist (though I think I already expressed there I didn't much see the point), so maybe it's rude to put it behing a prefix.

**Comment by oantolin** [comment]
But separate commands under a common prefix is probably better. I just mention that proposal, because (1) it only uses one `C-u`, not two, and (2) I think I would probably find it useable.

**Comment by minad** [comment]
I don't understand your proposal. Do you mean introducing a separate command which is then modified further with C-u or baking everything into `embark-bindings`?

**Comment by minad** [comment]
Anyways I don't feel strongly about this - I am happy with either `C-u C-u C-u embark-bindings` or `embark-bindings+embark-bindings-at-point` but maybe I'd use the latter more often ;)

**Comment by oantolin** [comment]
I meant change `embark-bindings` so it does what I described: show all bindings with a single `C-u`; and called normally, without `C-u`, show bindings at point if there are any, otherwise prompt for a keymap variable.

**Comment by minad** [comment]
I am not sure. What if I want to show all bindings but unfortunately I am at a point which is polluted by a keymap? I think many Emacs command are kept separate for such cases, where both `command` and `command-at-point` are offered. However the dwim behavior at point would fit the Embark design, but Embark also allows me to cycle :shrug:

**Comment by hmelman** [comment]
How about have the command show the bindings at point (those from a property map) first and then all bindings appended; or with C-u prompt for a keymap variable?

**Comment by oantolin** [comment]
I think maybe the least controversial way to proceed is to just make three separate commands.
