### ISSUE TITLE
Better handling for target type changing repeatable commands

### ISSUE THREAD

**Issue by minad** [oantolin/embark#418]
See the TODO: 

https://github.com/oantolin/embark/blob/7c502b00a505905f8d08140f55ac789c031e23a8/embark.el#L1917-L1921

See https://github.com/oantolin/embark/pull/416#issuecomment-990342380 for the discussion.

**Comment by oantolin** [comment]
I took care of this in f741dab05b09beb18e0a7e87f5b80ea462ca44a2.
