### ISSUE TITLE
Paths like "~/test1/~/test2/" aren't always handled correctly.

### ISSUE THREAD

**Issue by jakanakaevangeli** [oantolin/embark#42]
To reproduce with `emacs -q`, execute:
```
(load "~/src/pomembno/emacs/embark/embark.el")
(define-key minibuffer-local-map (kbd "M-o") 'embark-act)
```
And then type `C-x C-f ~/test1/~/test2 M-o e`.
Eshell is started in `"~/test1/~/test2"` instead of `"~/test2"`.

**Comment by oantolin** [comment]
I think the problem was specifically in the file actions I wrote. Other file actions that use built-in commands handle this just fine. I fixed embark-eshell-in-directory and will quickly fix the other file actions know that I know the problem.

**Comment by oantolin** [comment]
Exercise for the reader: why doesn't `embark-open-file-externally` need a call to `substitute-in-file-name`?

**Comment by minad** [comment]
> Exercise for the reader: why doesn't embark-open-file-externally need a call to substitute-in-file-name?

No real idea, maybe because of how the interactive arguments of embark-open-file-externally are interpreted?

**Comment by oantolin** [comment]
You got it! The `f` in `(interactive "fOpen: ")` takes care of it.

**Comment by minad** [comment]
I should have just written: f

Damn ;)
