### ISSUE TITLE
Prioritize headings in markdown-mode

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#421]
I think I'll like the new header target and keymap.  I tried it in `markdown-mode` in Emacs 27.2 with `outline-minor-mode` enabled.  With point at the beginning of a heading line I first see the defun map and then the heading map.  Note that `markdown-mode`, like other modes, defines defuns as something useful to the mode (in this case headings with their body). With point at the start of a word in the middle of the heading I first see the Identifier map, then defun, then heading.  I'd like an easy way to have the heading map appear first in modes derived from `markdown-mode` and perhaps all text-modes when `embark-act` is invoked with point in a heading.  I'm not sure what I'd like in prog-modes where I do use `outline-minor-mode` for code folding.

**Comment by minad** [comment]
I would also like to see the headings to be prioritized higher in text modes. In progmodes I prefer if defun is prioritized higher. We could at least prioritize it when the point is at the beginning of the line. In my initial PR I put the heading target in the very end such that it does not interfere with the existing finders. After using it for a while we gain more experience and we can refine the priorities to match the usage patterns better. Omar has applied such refinements a few times.

**Comment by hmelman** [comment]
I'm not sure what it would look like, but assuming people will have different preferences, I'd like a more robust way to prioritize these rather than ordering a single list variable.  The problem is, if I change it, then I don't see new targets that you add in  updates.  And if I start tweaking them in different modes I fear it will be more messy.

**Comment by minad** [comment]
Hmm, I am not sure I would like a different way to specify the priorities. A list is the simplest data structure we can use here. However I see your point. Elisp seems to lack good utility functions to manipulate such lists. Are there functions like insert-after or insert-before? But this is probably just my lack of knowledge and the cl-lib may have appropriate tools. In a mode buffer you could do:

~~~ elisp
(setq-local embark-target-finders
   (remove 'foo
     (insert-after 'bar 'baz
       (insert-before ...
          embark-target-finders))))
~~~

Another idea would be to make the target finders an alist with integer priorities. But plain lists with relevant order are very common in Emacs: hooks, completion-at-point-functions and so on. So I don't think we should move to a different datastructure.

**Comment by hmelman** [comment]
I thought about integer priorities and some things in emacs use them (like property priorities) though they're not the easiest things to use since the values have no recommendations.  I agree that the simplicity of a simple list is desirable.  

While list manipulation is basic, any insert-before/after functions I think are relatively recent in emacs (in the seq libraries).  It would be nice if the embark docs had a recommended example of moving say headers before defuns.

Maybe use simple list as there is but also have a list of all target finders and embark-act combines them.  That way, if customized, new finders are added at the end.  Or maybe ask about unused finders and (have the user) keep a list of those deliberately unused so that a warning can be generated to mention new ones?

**Comment by minad** [comment]
> I thought about integer priorities and some things in emacs use them (like property priorities) though they're not the easiest things to use since the values have no recommendations. I agree that the simplicity of a simple list is desirable.

You are right, hooks have additional priorities which determine the insertion position in `add-hook`. If you use `add-hook` on `embark-target-finders` it should be possible to make use of priorities, but it will only affect new finders and their ordering since the default hooks all have no priority specified.

> Maybe use simple list as there is but also have a list of all target finders and embark-act combines them. That way, if customized, new finders are added at the end. 

I think you are manipulating the target finder list in the wrong way. You should never overwrite the target finder list with a constant, except if you really want to restrict the list of finders to only this list. Instead one should manipulate the list by prepending, appending and inserting.

**Comment by hmelman** [comment]
> I think you are manipulating the target finder list in the wrong way. 

I'm not now, but I have thought about it.

> You should never overwrite the target finder list with a constant, except if you really want to restrict the list of finders to only this list. Instead one should manipulate the list by prepending, appending and inserting.

I think that's right.  If there are now going to be finders like header and defun that people are more likely to want to customize their order, it's probably worth saying this explicitly in the doc.

**Comment by minad** [comment]
I agree, there is a need to document a good pattern on how the list should be manipulated. For example Doom Emacs is doing this, which does not look good :-P

https://github.com/hlissner/doom-emacs/blob/f458f9776049fd7e9523318582feed682e7d575c/modules/completion/vertico/config.el#L189-L198

**Comment by oantolin** [comment]
Oh, I just noticed something weird: the outline hide/show actions work fine before ever activating `outline-minor-mode` except they don't show ellipsis; then, with `outline-minor-mode` on they work exactly as expected, but if you deactivate `outline-minor-mode` they stop working!

**Comment by minad** [comment]
Hmm, maybe the indicator should check if the outline-minor-mode is enabled? I have it enabled always in prog and text buffers. We could also rename the `heading` target to `outline` if it is that specific, but then we lose the ability to have other headline commands.

**Comment by oantolin** [comment]
Now that I've played around with this, I fully agree with you @hmelman that in Markdown and Org buffers the heading target should be much higher, probably before identifier, sentence and paragraph! But in prog modes I think I'd want indentifiers and defuns to have higher priority that.

We do need a good way to manipulate the priorities, but like @minad said I think the best way to go about it is to have convenient list manipulation functions, not to abandon simple lists, which Emacs uses all over the place. Tweaking `embark-target-finders` in a major mode's hook seems the way to go to me. It is a shame there don't seem to be any built-in `insert-before` and `insert-after` functions, but I'd be happy to add some to Embark (lots of packages are forced to have some general utilities in them that would be more at home in `seq` or some library like that).

For the specific case of headings, I think maybe making them the highest priority in text modes is good enough, what do you think?

**Comment by minad** [comment]
> It is a shame there don't seem to be any built-in insert-before and insert-after functions, but I'd be happy to add some to Embark (lots of packages are forced to have some general utilities in them that would be more at home in seq or some library like that).

When we add these functions can we at the same time report a bug for the seq or cl-lib? This is my current approach when I discover such omissions. If sent via report-emacs-bug the bug report may be read by Lars who did a lot of standard library overhauling recently, so it might have a chance to get in.

> For the specific case of headings, I think maybe making them the highest priority in text modes is good enough, what do you think?

Okay. How are you going to do this? Create two target finders, one for text and one for prog modes?

**Comment by oantolin** [comment]
> When we add these functions can we at the same time report a bug for the seq or cl-lib?

Sure, good idea.

> Okay. How are you going to do this? Create two target finders, one for text and one for prog modes?

I think that's a reasonable approach. Another option is to and something to people's `text-mode-hook`, but that's probably frowned upon, right?

**Comment by hmelman** [comment]
Maybe continuing to have an `embark-target-finders` would be good (say for special modes) and then do:

``` emacs-lisp
(setq embark-target-prog-finders embark-target-finders) 
(setq embark-target-text-finders (some-tweaking-function embark-target-finders))
```

**Comment by minad** [comment]
@oantolin 

> I think that's a reasonable approach. Another option is to and something to people's text-mode-hook, but that's probably frowned upon, right?

Yes, we should just add two finders and not complicate the target finder story.

@hmelman 

> Maybe continuing to have an embark-target-finders would be good (say for special modes) and then do:

I am not a fan of complicating the target finder story. Instead of adding such variables use the approriate mode hooks and setq-local the target finders. This is much easier instead of duplicating these variables and it also feels like the more canonical approach.

**Comment by oantolin** [comment]
Let me know if the new priorities feel comfortable.

**Comment by minad** [comment]
Looks good!

**Comment by hmelman** [comment]
I think I like this approach. 👍
