### ISSUE TITLE
file finder matches on keywords

### ISSUE THREAD

**Issue by minad** [oantolin/embark#423]
1. Go to scratch buffer
2. Enter `:foo` or any other `:weird` keyword
3. Move point to beginning of `:foo`
4. Symbol is recognized as file (?!), symbol (okay), defun (?)

The underlying problem of these issues is the thingatpt library which often yields false positives. Related #422, #421

**Comment by oantolin** [comment]
For files I'm using ffap, not thingatpt. What file is it recognized as? (I'm AFE: away from Emacs.)

**Comment by minad** [comment]
Yes, ffap. Right. It is recognized as the current directory, probably because colon is a file name symbol or a protocol separator.

**Comment by oantolin** [comment]
I think probably adding this as a guard in the file target finder fixes things:

```elisp
(string-match-p (regexp-quote (thing-at-point 'filename)) (ffap-file-at-point))
```

I'll do some more testing.

**Comment by minad** [comment]
Okay, but we should report the issue upstream and add a comment referencing the bug. Ideally one can remove this code in a a few years :-P

**Comment by oantolin** [comment]
> defun (?)

This is technically correct if not very useful: remember defun means "toplevel expression". 🤷

**Comment by minad** [comment]
> This is technically correct if not very useful: remember defun means "toplevel expression". 

Yes, maybe we should distinguish defuns from toplevels in non-prog modes, see #422?
