### ISSUE TITLE
Vertico/Selectrum etc indicators

### ISSUE THREAD

**Issue by minad** [oantolin/embark#427]
Do you mind if we add the UI indicators to Embark for a better ootb experience?

~~~ elisp
(defun +embark-vertico-indicator ()
  "Embark indicator which highlights the current Vertico candidate."
  (let ((fr face-remapping-alist))
    (lambda (&optional keymap _targets _prefix)
      (when (bound-and-true-p vertico--input)
        (setq-local face-remapping-alist
                    (if keymap
                        (cons '(vertico-current . embark-target) fr)
                      fr))))))
~~~

There are at least two configs which have it, Doom and my config ;) But it is only a gimmick and not strictly needed for the integration so it would be understandable if you say no the addition here. I think we discussed about this before, but back then I considered this highlighting experimental. Now I think I would miss it.

**Comment by oantolin** [comment]
I don't mind at all. But I was thinking of adding [this indicator](https://github.com/oantolin/emacs-config/blob/9de81bce876a47b3317aa18558a29265564d9bdd/my-lisp/embark-extra-indicators.el#L29--42), which works pretty well with Vertico or Selectrum. I consider it a sort of completion UI agnostic minibuffer candidate indicator.

**Comment by minad** [comment]
> I don't mind at all. But I was thinking of adding this indicator, which works pretty well with Vertico or Selectrum. I consider it a sort of completion UI agnostic minibuffer candidate indicator.

Yes, it is not bad but I like the Vertico-specific indicator a bit better, since it highlights the candidate directly at the place you are looking at. This feels more in line with the other at-point indicators. So I would probably not add the `embark-minibuffer-indicator` to Embark, for buffer-based UIs like Mct and Embark one does not need it since you act directly in the buffer and for Vertico and other UIs the UI-specific solution is better. Of course everyone can configure this in their own configure and I am also super hesitant to add UI-specific code to Consult. So probably we should just leave everything as is.

**Comment by oantolin** [comment]
I think of `embark-minibuffer-indicator` as being aimed primarily at default completion users: it's particularly helpful when completions are not being displayed. But I agree that's a niche audience, so I won't add it. On the other hand maybe we should  add the Vertico and Selectrum indicators: they are small and there is already some Vertico and Selectrum specific code in Embark.

**Comment by minad** [comment]
Okay, I prepared a PR.

**Comment by minad** [comment]
cc @iyefrat if this is merged you can remove the indicator from the doom config :)

**Comment by iyefrat** [comment]
Thanks for the heads up! I'll add this in the next bump.
