### ISSUE TITLE
Reacronymization :)

### ISSUE THREAD

**Issue by minad** [oantolin/embark#435]
Embark should be reacronymized since it has larger scope than MB. I don't have a good idea yet unfortunately.

**Comment by oantolin** [comment]
The same thing happened to @protesilaos's MCT and he came up with _minibuffer confines transcended_.

**Comment by minad** [comment]
Yes, I know. Embark also transcended the confines of the minibuffer. :smile:

**Comment by protesilaos** [comment]
> The same thing happened to @protesilaos's MCT and he came up with minibuffer confines transcended.

That was mostly a joke, though it works!

> Yes, I know. Embark also transcended the confines of the minibuffer. smile

Maybe:

```
Emacs Milieu-Bound Actions Rooted in Keymaps

Or recursive:

EMBARK Milieu-Bound Actions Rooted in Keymaps
```

**Comment by oantolin** [comment]
I like `Milieu-Bound`! I wanted to say something like "context sensitive" but hadn't figured out how to say it with initials MB.

**Comment by protesilaos** [comment]
It could be "Milieu-Based" if you don't want to sound too professorial.

**Comment by iyefrat** [comment]
Environmentally Malleable and Beneficial Actions Rooted in Keymaps

**Comment by minad** [comment]
Malleable is really good. But beneficial seems too generic.

**Comment by iyefrat** [comment]
Well, you could use buffer, but you'd be hard pressed to find things happening in Emacs and not in a buffer :stuck_out_tongue:
