### ISSUE TITLE
(How can I/we) add an action to narrow to subtree to consult-outline (but not other commands of the same category)?

### ISSUE THREAD

**Issue by Hugo-Heagren** [oantolin/embark#436]
I wanted to add an action to `consult-outline` to narrow to the selected heading, like what `outshine-narrow-to-subtree` does. The implementation  doesn't look terribly difficult, and would probably be very similar to `outshine-narrow-to-subtree`'s. The problem is that this action isn't relevant to any of the other consult commands which have category `consult-location` (e.g. `consult-line`, and everything I can find attaches embark keymaps to *categories*, not *commands*. So, having implemented it, is there a way to add it to just `consult-outline`?

**Comment by oantolin** [comment]
You can dynamically bind `embark-keymap-alist` whenever you run `consult-outline`:

```elisp
(defun only-for-consult-outline (string)
  (message "Acted on %s" string))

(embark-define-keymap special-consult-outline-map
  "An action map only for consult-outline"
  ("X" only-for-consult-outline))

(defun with-special-consult-outline-map (fn &rest args)
  (let ((embark-keymap-alist
         '((consult-location . special-consult-outline-map))))
    (apply fn args)))

(advice-add 'consult-outline :around #'with-special-consult-outline-map)
```

**Comment by oantolin** [comment]
If you're a maverick that uses recursive minibuffers or that leaves the minibuffer open while you go edit a buffer, you'll probably want to set `embark-keymap-alist` to `(cons '(consult-location . special-consult-outline-map) embark-keymap-alist)` instead, so that you still have the usual keymaps available while `consult-outline` is running,

**Comment by Hugo-Heagren** [comment]
This was really helpful, thank you!

I think I'm probably not the only person who will find this useful. Would you like me to post my final solution on the wiki, or make a PR to embark-consult?

**Comment by minad** [comment]
This should be added to the wiki, not to embark-consult.

**Comment by oantolin** [comment]
I agree with @minad, it's a good fit for the wiki. Please add it there when you're done!

**Comment by Hugo-Heagren** [comment]
> I agree with @minad, it's a good fit for the wiki. Please add it there when you're done!

Done!

**Comment by oantolin** [comment]
Great, thanks!
