### ISSUE TITLE
embark-bindings-at-point does not respect overlays

### ISSUE THREAD

**Issue by minad** [oantolin/embark#438]
For example the `symbol-overlay` keymap is not recognized. Isn't there a generic function to query all properties at point, including overlays instead of `get-text-property`?

**Comment by oantolin** [comment]
If I recall correctly there are two sets of functions, one takes overlays into account and one doesn't.

**Comment by oantolin** [comment]
Yep, `get-text-property` ignores overlays, `get-char-property` includes overlays. How's that for a naming convention?

**Comment by minad** [comment]
Thanks!
