### ISSUE TITLE
embark--confirm always n but giving a y-or-n-p prompt

### ISSUE THREAD

**Issue by nasyxx** [oantolin/embark#439]
When I run `embark-act` `delete-file`, it always cancelled, raising

```
Run delete-file on ~/.emacs.d/pure.el? (y or n) n
embark PCH: (user-error "Cancelled")
```

instead of giving me a `y-or-n-p` prompt.

But, when I set `y-or-n-p-use-read-key` to t, it gives me the prompt.

------

Not sure if it is a macOS-specific bug.

I use emacs 29 on macOS with this commit "4fedbfbfca87849db343c09c4006b52c845f95d2".  And embark is the master version.

I have tried a very small config.

```emacs-LISP
(defvar bootstrap-version)

(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'embark)
(straight-use-package 'consult)

(require 'consult)
(require 'embark)

(define-key (current-global-map) (kbd "M-o") #'embark-act)
```

**Comment by oantolin** [comment]
Oops, I only tested with `(setq y-or-n-p-use-read-key t)`. I'll look into it.

**Comment by oantolin** [comment]
Wow, that lead to discovering a longstanding bug! Thanks for the report.

**Comment by nasyxx** [comment]
Great!
