### ISSUE TITLE
embark-act-exit/embark-act-noexit distinction per command

### ISSUE THREAD

**Issue by minad** [oantolin/embark#44]
I wrote in https://github.com/minad/marginalia/issues/10:

> This embark-act/embark-act-noexit distinction is something which I wondered about the first time, when I looked into embark. It looks to me as if I have to chose too early what it will do after the action. At the point where I enter the action menu, I might not even know yet which action to execute. Wouldn't it make sense to associate the exit/no-exit behavior with the executed action in order to get some kind of hydra-style interface? Alternatively one could use a toggle/prefix-like command which toggles the behavior for the next command being executed. Default is exit, but you could press some key, then next command will be no-exit. I think I would prefer a hydra style menu though.

**Comment by minad** [comment]
@oantolin Answering here:

>  What does that mean? That some actions are marked as always exiting, and some actions are marked as never exiting? This is how it works in hyda: you need to decide at the moment you write the hydra, long before you use it, which actions exit and which don't. I like the "late-binding" of Embark, where you decide at the moment you are about to execute an action whether it will exit or not. I wouldn't like to loose that flexibility, since I use it all the time. I often noticed I want to move or rename some files whiile I'm on my way to open a file, so I use embark-act and then continue looking for the file I ant to open. Other times, I'm editing in a buffer and need a file action, so then I use embark-act-noexit. Maybe some actions I tend to use in exiting fashion more than others (for example, I very often exit after byte-recompiling a directory), but many actions I use both ways.
> I use both embark-act and embark-act-noexit quite a bit.

Maybe I misunderstood some things here. You bind embark-act to some binding and embark-act-noexit to another binding? Then if you want to rename for example you press the binding for `embark-act-noexit` since you want to do more modifications afterwards. I am looking at from a slightly different point - I press the embark key to get the context menu and then I see what I can do. And then I want to decide if I want to exit or not. Or the author of the menu already made that decision for me - this is the hydra behavior. But you are right, with the hydra behavior everything is already hard coded.

I am not saying what you do is wrong. It is just an alternative way of doing things. I wondered if you considered the alternative. Personally, I am somehow accustomed to hydras.

**Comment by oantolin** [comment]
Yes, I bind both `embark-act` (to `C-:`) and `embark-act-noexit` (to `C-;`). I don't like hardcoding the decision of whether to exit or not, hydra style, and I do in fact sometimes exit and sometimes not for the same.

**Comment by oantolin** [comment]
So I wouldn't want to be forced to choose whether to exit or not at configuration time. (I'd choose defaults that @clemera would hate, basically almost nothing would exit :P). But the idea of being able to see the list of actions first and then decide whether to exit or not is great, that would be slightly better than what we have now.

**Comment by minad** [comment]
Now that we are talking about this - maybe I add a modifier key to [my small hydra implementation](https://github.com/minad/polyp) which allows to invert the default behavior (exiting or not). But it would probably require some heavy code changes ;)

**Comment by minad** [comment]
> But the idea of being able to see the list of actions first and then decide whether to exit or not is great, that would be slightly better than what we have now.

Cool. I would like to see something like this. My preference would be to have some hard coded defaults and then a toggler. But this obviously works only if you have a hydra-like menu where you can see what will happen.

Maybe this is something I would hope for - that I could somehow bind hydras to the embark actions such that the menu is presented by some customizable function. But I am not sure if anything like this is possible to reconcile with the Embark design, since you already use your own transient keymaps etc. Showing a menu should be already possible by hooking into Embark I guess, since you can also add the hooks enabling which-key for transient maps, as @clemera did in the selectrum wiki.

**Comment by oantolin** [comment]
There is currently some support in embark for "prompt styles", and that's a first step towards letting people conveniently choose the UI they want to select actions. It would be great to separate concerns here and make it easy to implement the hydra-like UI with exit/noexit toggles or anything else.

**Comment by minad** [comment]
I am looking forward to this. I can also help out with that and see if I can integrate it in an agnostic way with my stuff/hydras or whatever. I would very much like to have that. But for now I don't want to start to many things and I thought I wait until this marginalia-embark integration has been worked out! It is just that I remembered this idea when we discussed the refreshing/exit/noexit behavior in https://github.com/minad/marginalia/issues/10.

**Comment by oantolin** [comment]
Sure, I don't really have that much time to do this now anyway.

In general, I was happy with the embark code until you came along, but I now realize that was just because I didn't look at it for many months. I was happy with it because it worked and I didn't need to change it, but now  that I've made a few small changes I realize it's pretty intricate, more than in it needs to be and I'd like to gradually disentangle things.

**Comment by minad** [comment]
Cool, when I looked at it, I found it pretty entangled too. It is great to hear that you are improving things with regards to that. I think moving out functionality somewhere else helps too! I hope the marginalia integration turns out well and maybe similar things can be done regarding to how the "menus" are presented (which-key hydra etc). I am not sure yet, maybe it is complicated, not possible or not worth it. But it is nice to try out things :)

**Comment by oantolin** [comment]
You know, after the action refactoring, this is easy to implement! It's a matter of deciding how things should work.

Here's one possible design:

- There will be only one command `embark-act`.
- There is a global default, `embark-actions-exit-minibuffer` you can set to `t` or `nil`.
- There are exception lists, `embark-exiting-actions` and `embark-non-exiting-actions`, where you can put some commands to override your choice in `embark-actions-exit-minibuffer`.
- There is a command `embark-toggle-exit` bound to, say, `C-e` in `embark-general-map` that you can use to override your choice right before running the action.

I think that's a reasonable proposal, but remind me again why we even want to be able to exit after an action? Why not just never exit and let people `C-g` after the action if they want to exit the minibuffer?

**Comment by minad** [comment]
> Here's one possible design: ...

Sounds like a good proposal, which covers everything I would need. Maybe toggle-exit is not even needed, since you can always exit afterwards using C-g. (Except turning an exiting operation into an non-exiting one wouldn't be possible then.)

> I think that's a reasonable proposal, but remind me again why we even want to be able to exit after an action? Why not just never exit and let people C-g after the action if they want to exit the minibuffer?

Well, this is what I am doing. But you are offering embark-act and embark-act-noexit right now, so there is probably a reason to offer both variants. Furthermore there is also the reason that you have exceptional commands which always force an exit like occur. So you automatically have exiting/non-exiting commands...

If you provide this embark-exiting-actions list I would probably make use of it and set it to a few commands where I always want to exit. I cannot tell right now, have to gather more experience. But in hydra this is not a bad idea.

**Comment by minad** [comment]
@oantolin Would it be possible to expose some of the command lists which exit:

https://github.com/oantolin/embark/blob/82a678c5a7b8c215d099b9b896fd5b34e5211f6a/embark.el#L528-L532

This would then allow to add custom commands which should also exit the minibuffer. But it would probably require a bit of a different logic since embark-occur etc seem to perform the exit themselves?

But I am not sure if it is necessary to implement anything like this - I am pretty happy with the status quo now. Embark-act-noexit is good enough for me.

**Comment by oantolin** [comment]
Those commands are pretty special: not only do they make their own choice about whether to exit or not, but they also do not use the target, but require information from the current buffer to work: become need the literal minibuffer input (rather than the top completion), export needs to collect all completions (or targets, more generally), and the occur commands need even more information about the current buffer because they try to not only collect the current candidates but setup so that revert works in the occur buffer.

That's why it easier for them to just take over completely and not go through the usual action preparation.

But I can add some variables to control which commands exit. I [sketched a design earlier](https://github.com/oantolin/embark/issues/44#issuecomment-751288422) but I'm thinking now it's too complicated. I think I have two designs I'm considering now:

1. Do nothing, keep the status quo!
2. Keep both `embark-act` and `embark-act-noexit`, add custom lists `embark-exiting-actions` (used by `embark-act-noexit`) and `embark-non-exiting-actions` (used by `embark-act`).

**Comment by oantolin** [comment]
I I haven't added the list of exiting and non-exiting variables because I'm not really sure they'd get much use.

**Comment by minad** [comment]
I agree that the commands that you currently have listed are special. But if you generalize the mechanism it could make sense to add such a configurable list, basically option 2. But I think this should only be done if it wouldn't lead to significant additional complexity. I am not sure if they would get much use, so keeping the status quo is also perfectly fine with me. I just thought I mention this again.

**Comment by oantolin** [comment]
The lists I mentioned, `embark-exiting-actions` and `embark-non-exiting-actions` are for "true actions", i.e., commands that want the target inserted at the first minibuffer prompt and are OK with running in the target buffer (or more accurately, with some window selected that displays the target buffer).

I could put the special commands, the ones that want the current buffer in a third list `embark-special-actions` or maybe `embark-no-target-buffer-actions`. That list would be a good place to put `marginalia-cycle`, and then it wouldn't need the special minibuffer handling.

You know, while the actions in that special list don't *need* the minibuffer-setup-hook to inject the target, having the injection hook doesn't bother them (they used to have it, in fact). So maybe I could have them go through the normal action preparation and then this list can include things like `embark-save` or `describe-symbol` that only need the candidate and don't need to run in any particular window.

**Comment by minad** [comment]
Makes sense! But if it doesn't hurt to do the setup for some commands there is also no need to put them in the special list. I would only put the ones there which wouldn't work otherwise.

**Comment by oantolin** [comment]
I've been so indecisive about this and I think that's because I don't really believe in it. You said you weren't convinced you needed this anymore, right @minad? If that's the case I'll close for now. I'm always willing to reopen the issue in the future.

**Comment by minad** [comment]
Yes, I am good without this! If some new idea comes up I can always create a new issue.
