### ISSUE TITLE
Problem with embark-consult installing

### ISSUE THREAD

**Issue by wullic** [oantolin/embark#443]
Because I could't find the embark-consult GitHub page and I report the problem here.

Env:
`emacs-version: 29.0.50`
`embark:  embark-20220104.755`
`consult：consult-20220101.2318`
`embark-consult：embark-consult-20211231.1502`
My emacs config is based on prelude's.

LOG:
`Error (use-package): embark-consult/:catch: Symbol’s value as variable is void: embark-target-injection-hooks `

**Comment by oantolin** [comment]
> Because I could't find the embark-consult GitHub page and I report the problem here.

This is the right place, `embark-consult` lives in this repo too.

I'm a little confused by the title: you say you have trouble installing `embark-consult`, but you also make it seem like you already have version `embark-consult-20211231.1502` installed?

Does the problem occur when installing `embark-consult` or when loading it? If it's at load time, could you show how you are loading it?

**Comment by wullic** [comment]
Oh, sorry, it occur at load time.  I should change my title.

I delete all my consult, embark package and reinstall , and it works! Actually I have deleted and reinstalled packages several times before, but this time it load successfully and works. I totally don't know why.

I could used it and so amazing!

**Comment by oantolin** [comment]
I'm glad it worked out!

**Comment by astoff** [comment]
I'm also seeing this error, not at load time but whenever I call `embark-act`. It can solved by adding `(defvar embark-target-injection-hooks nil)` to my init file. I'm using the current GNU ELPA versions of the `embark` and `embark-consult` packages.

**Comment by oantolin** [comment]
Oh, I have no idea what versions are on GNU ELPA, possibly the versions of the two packages are out of sync from each other. I'll look into it.

**Comment by astoff** [comment]
I think the problem is that you created the missing hook variable and bumped Embark's version on the same day (29 Dec 2021) but on different commits, and the commit changing the package version number came first.

**Comment by oantolin** [comment]
Ah, so I need to bump the version on embark (but not embark-consult) again to fix the problem, @astoff?

**Comment by minad** [comment]
Or bump the versions of both to keep them in sync?

**Comment by oantolin** [comment]
I bumped both versions, and think I'll probably pin the packages to GNU ELPA in my personal configuration, so I catch problems like this sooner.

**Comment by minad** [comment]
I would rather use the unpinned versions to catch all other kinds of development issues earlier!

**Comment by oantolin** [comment]
Well, I didn't tell the full story. I often switch to my locally copy of embark until MELPA catches up, then switch to MELPA. I planned on doing the same thing but now with GNU ELPA instead.

**Comment by minad** [comment]
> Well, I didn't tell the full story. I often switch to my locally copy of embark until MELPA catches up, then switch to MELPA. I planned on doing the same thing but now with GNU ELPA instead.

I do the same with MELPA unstable. But with ELPA, catching up will take much longer assuming that you use ELPA stable and not ELPA-devel.

**Comment by oantolin** [comment]
Right. I guess it boils down to this: this is the first time I ever tested the GNU ELPA stable versions of embark and embark-consult. In the future I will test them whenever I bump the versions.

**Comment by minad** [comment]
This makes sense. In my case with Vertico and Corfu, which are only on ELPA, I usually use my local development version. As soon as I bump the version, ELPA updates and package.el pulls the newest release.
