### ISSUE TITLE
`xref--push-markers` missing in Emacs 26.3 for `find-library`

### ISSUE THREAD

**Issue by okamsn** [oantolin/embark#444]
The current version of Embark requires Emacs 26.1. While testing some things in Emacs 26.3 on Ubuntu 20.04, I noticed that this function is missing. It was added on 2019-05-23, after Emacs 26 was released.

This is small and not a problem for me, but I though it worth reporting.

**Comment by oantolin** [comment]
Thanks for reporting this! I guess we could just use `xref-push-marker-stack`. The `xref--push-markers` command just calls both `push-mark` and `xref-push-marker-stack`.
