### ISSUE TITLE
embark-insert unexpectedly deletes blank lines below

### ISSUE THREAD

**Issue by daanturo** [oantolin/embark#451]
```lisp
(form0 |)

(form1)
```
After `embark-insert` at the point:

```lisp
(form0 <inserted>|)
(form1)
```
The above behavior is caused by `delete-blank-lines` in [`embark-insert`](https://github.com/oantolin/embark/blob/c794ca3fc630eee6401121f89fc53bb794c7aab3/embark.el#L3355)

**Comment by oantolin** [comment]
Oh, that's definitely unintended. I'll tweak the behavior.

**Comment by oantolin** [comment]
That should fix it, please test.

**Comment by daanturo** [comment]
It's now fine when we're not at the end of line, but otherwise:
```
a|


b
---
a<inserted>|

b
```
`(looking-at "\n\n")` is true in this case.

**Comment by daanturo** [comment]
Can we check if the buffer has been modified after inserting, then proceed to delete in that case?
```diff
                (ins-string ()
                  (save-excursion
                    (insert string)
-                   (maybe-whitespace)
-                   (when (looking-at "\n\n")
-                     (delete-char 1)))
+                   (let ((tick (buffer-modified-tick)))
+                     (maybe-whitespace)
+                     (when (and (looking-at "\n\n")
+                                (/= tick (buffer-modified-tick)))
+                       (delete-char 1))))
                  (maybe-whitespace)))
       (if buffer-read-only
           (with-selected-window (other-window-for-scrolling)
```

**Comment by oantolin** [comment]
I think the right answer is to trim one trailing newline. The issue is that n consecutive newlines means n-1 blank lines, so when you combine m consecutive newlines with another n consecutive newlines you get m+n-1 blank lines which is one more than the (m-1) + (n-1) = m+n-2 blank lines you expected.

**Comment by oantolin** [comment]
I hope that version is correct: I decided to trim one trailing newline if there are any. Thanks for finding the error in the first attempted fix!

**Comment by daanturo** [comment]
Thank you!
