### ISSUE TITLE
Specify commands that will not exit the minibuffer by default 

### ISSUE THREAD

**Issue by suconakh** [oantolin/embark#453]
Right now my configuration has `embark-quit-after-action` set to `t` and i have two keybindings - one for `embark-act` and the other one configured as follows:
```emacs-lisp
(defun +embark-act-noquit ()
  "Run action but don't quit the minibuffer afterwards."
  (interactive)
  (let ((embark-quit-after-action nil))
    (embark-act)))
```
It's very inconvenient for me to think what to press when i want to execute some commands and not exit the minibuffer after that. For example, if i am at the `swith-buffer` completion and want to do `kill-buffer` on a candidate, i never want to exit the minibuffer after that. I tried to change `kill-buffer` a bit:
```emacs-lisp
(defun +embark-kill-buffer-no-quit ()
  (interactive)
  (let ((embark-quit-after-action nil))
    (kill-buffer)))
```
But it didn't work. It would just delete the buffer i'm in right now. 
I also tried to add switching of the `embark-quit-after-action` to `embark-(pre|post)-action-hooks` but that didn't work either:
```emacs-lisp
(defun +embark-no-quit-pre (&rest args)
  (setq embark-quit-after-action nil))

(defun +embark-no-quit-post (&rest args)
  (setq embark-quit-after-action t))

(add-to-list 'embark-pre-action-hooks '(kill-buffer +embark-no-quit-pre))
(add-to-list 'embark-post-action-hooks '(kill-buffer +embark-no-quit-post))
```
Maybe i am missing something? What i want to implement in my config is that i specify some commands or keybindings in embark maps that will change `embark-quit-after-action` on their own so that i don't have to press other keybinding to run `+embark-act-noquit`. How can i do that?

**Comment by oantolin** [comment]
I think this was been discussed before, and it would be good to link to the past discussion here. I'll see if I can find it.

**Comment by minad** [comment]
Maybe #343? Or was there a more recent discussion?

**Comment by oantolin** [comment]
It might be worth pointing out that the reverse is easy to obtain: if you set `embark-quit-after-action = nil` but want some actions to quit the minibuffer, you can put quitting in a post-action hook or include it in the definition of the action.

**Comment by oantolin** [comment]
Thanks @minad! I suspect there might also be a more recent one.

**Comment by minad** [comment]
As proposed in #343 we could still generalize embark-quit-after-action to a list with the key t as default value.

**Comment by minad** [comment]
Btw why not change everything to non-quitting and implement quitting always as post action? What was again the reason to keep these two different code paths for quitting and non quitting? Mainly the window configuration restoration issue?

**Comment by oantolin** [comment]
Yes, the window restoration issue. Actions like `find-file-other-window` are useless if you do them _before_ quitting because the window configuration gets restored, so quitting actions actually quit first and then carry out the action.

**Comment by suconakh** [comment]
I think for now i'll set `embark-quit-after-action` to `nil` and gradually gradually add quitting actions. The `embark-quit-action-alist` proposed by Daniel in #343 is great and would make so much sense in my opinion. And i think it's much cleaner to change variable than creating a separate function to customize your quitting actions.

**Comment by oantolin** [comment]
It seems very few people want this configurable, but it kind of annoys me that the configuration is hard to achieve. So here's the plan (which is exactly what @minad suggested, I'm just repeating it here for convenience):

- Deprecate `embark-quit-after-action`.
- Introduce `embark-quit-after-action-alist`. You can associate commands to `t` for quitting and to `nil` for not quitting. In addition to commands, you can associate the key `t` to a default value, i.e., the value associated to `t` acts as the current `embark-quit-after-action` variable.
- The prefix argument to `embark-act` means "do the opposite of what `embark-quit-after-action-alist` would tell you".

How does that sound?

**Comment by minad** [comment]
I would just generalize embark-quit-after-action to also support an alist in addition to t and nil. But if you prefer having an alist only, that seems okay too.

**Comment by minad** [comment]
I should add - I also don't consider this a particularly important addition, but we usually allow fine grained per-action configuration. Furthermore since there are actions which basically require quitting like the find-file-in-other-window, I think it is justified to add this.

If we go the route via deprecation as you proposed we could also change the default and preconfigure a few common commands like find-file-other-window. So this is probably a good reason to go with your proposed approach in contrast to the generalisation of embark-quit-after-action.

**Comment by oantolin** [comment]
Now that I think about it a bit more, I think generalizing `embark-quit-after-action` to also allow the alist use is fine, and probably friendlier: people happy with the status quo don't need to change anything in their configuration! And the advantage you mentioned for the deprecation (changing the default) is not really that big of an advantage.

**Comment by oantolin** [comment]
OK, done! I went with generalizing to allow an alist (I really don't like deprecation if it can be avoided). Please test. Also, @jdtsmith is probably interested in using this.

**Comment by jdtsmith** [comment]
Looks like a good and simple generalization; I'll give a try. I presume there is still not any refreshing of content on non-quitting, i.e. I still need:

```elisp
(push 'embark--restart (alist-get 'set-variable embark-post-action-hooks))
```

**Comment by minad** [comment]
Yes, restarting must be specified on a per-action basis. Since you said "still", this is a feature not a bug.
