### ISSUE TITLE
Always confirm for act on multi

### ISSUE THREAD

**Issue by minad** [oantolin/embark#457]
Hey Omar,

I remember there was some discussion about the confirmation behavior of `embark-act-all`. I would like to have an option to always confirm multi actions, since I find these operations generally dangerous and intrusive. I am worried about this, since it feels like `rm -rf`. Is there an easy way to add this back and would you accept a patch? I know we are both not eager to add superfluous configuration options. We could either add a variable `embark-act-multi-paranoid` or extract the following code block to its own function:

~~~ elisp
(or (not (memq 'embark--confirm
               (alist-get action embark-pre-action-hooks)))
    (y-or-n-p (format "Run %s on %d %ss? "
                      action (length candidates) type)))
~~~

Then I could advise it with an override in my config.

**Comment by oantolin** [comment]
I think it would be a good idea to have the ability to confirm all multi-actions. If I recall correctly, my first instinct was to always have confirmation for them. Now I kind of like that it confirms or not as the non-multi action would, but I certainly understand the impulse to confirm all multi actions.

Maybe instead of adding a new variable or using advice, we can add a `:multi` parameter when we can the action hooks. That way confirmation could be implemented by putting a hook on the `:always` key that checks for multi-ness.

**Comment by oantolin** [comment]
Or alternatively add a new `:multi` key to the pre/post action hooks that is only called for multi-actions.

**Comment by oantolin** [comment]
Either way, I'd prefer to do this via the pre-action hook for consistency with confirming non-multi actions.

**Comment by minad** [comment]
So you want to add special keys to the `embark-*-hooks`? I like the idea to add an `:always` key, but a `:multi` key feels a bit odd, since it does not match depending on which action is called, but it matches on the method which calls the action (multi or single). Furthermore using pre-action hooks already doesn't work well for `embark-act-all`, since you explicitly check for `embark--confirm` in the hook list. So this feature lies already beyond the capabilities of the basic hook mechanism. Therefore I think an extra variable would also be fine. However I don't feel strongly about this. I am happy with any solution which allows me to put `embark-act-multi` in paranoid mode.

**Comment by oantolin** [comment]
> Furthermore using pre-action hooks already doesn't work well for `embark-act-all`, since you explicitly check for `embark--confirm` in the hook list.

True. 😢

**Comment by minad** [comment]
There is also the discoverability argument, so a separate variable may be justified. And I would also enable it by default just to be on the safe side.

**Comment by oantolin** [comment]
Upon further reflection, I agree with you. My idea of using hooks for this isn't very good because those run per candidate in the act-all case (except for `embark--confirm` and `embark-restart` which would be annoying if they ran once per candidate). Probably adding a separate user option is best.

**Comment by minad** [comment]
Thanks! Yes, it would make more sense to add `embark-pre-act-multi-hooks` and `embark-post-act-multi-hooks`. Then the confirmation could go there. However there is probably no other use case for such hooks.
