### ISSUE TITLE
[feature request] Supporting hide matched/unmatched item  in "*Embark Occur*" buffer

### ISSUE THREAD

**Issue by jixiuf** [oantolin/embark#46]
> What do you mean? I'm afraid I don't understand.

What I want is add two binding for ` embark-occur-mode-map`
```
(define-key embark-occur-mode-map (kbd "/") 'hide-item-not-matching)
(define-key embark-occur-mode-map (kbd "z") 'hide-item-matching)
```

something like `dired-narrow`

http://pragmaticemacs.com/emacs/dynamically-filter-directory-listing-with-dired-narrow/

**Comment by oantolin** [comment]
What do you mean? I'm afraid I don't understand.

**Comment by oantolin** [comment]
Ah, understood! Good idea.

**Comment by oantolin** [comment]
I like solutions where I don't write any code, so how about this?

Install politza's excellent [tablist](https://github.com/politza/tablist) package. In an Embark Occur buffer, run `tablist-minor-mode`. If you want it available in all Embark Occur buffers, you can use:

```elisp
(add-hook 'embark-occur-mode-hook #'tablist-minor-mode)
```

Now if you are in an Embark Occur list view buffer you can:

- filter to items matching a regexp with `/ r`
- negate the last filter with `/ !`
- remove the last filter with `/ c`
- remove all filters with `/ C`
- display the active filters with `/ /`

These operations can be done either in the candidate column or the annotation column.

You can also do ad hoc, dired-style removing of some items:

- mark individual items with `m` or unmark with `u`
- mark items matching a regexp with `% m`
- toggle all marks with `t`
- unmark all items with `U`
- kill the marked items with `k`
- revert all killed items with `G`

I think this is much more comprehensive than I would implement. And I like that it is a separate general package that can be used with any tabulated-list buffer.

Does this solution work for you?
