### ISSUE TITLE
Can we take advantage of `read-minibuffer-restore-windows`?

### ISSUE THREAD

**Issue by minad** [oantolin/embark#461]
I finally made the switch to Emacs 28, dropping the support for 27 from my init.el to force me to stick with it. :) Therefore I looked at a few of the new additions. I wonder if we could take advantage of `read-minibuffer-restore-windows` for some Embark actions, for example when invoking actions in a non-quitting fashion, which change the window configuration.

**Comment by oantolin** [comment]
It does sound like it will be useful in a few years. I don't have that variable yet, and am on some kind of Emacs 28, so it's probably very new. Probably in a couple of years we'll be able to use it.

**Comment by minad** [comment]
One could gradually add features which are only supported by newer releases. For example a variable `embark-preserve-window-actions` could be added. Actions listed in this variable will set `read-minibuffer-restore-windows` temporarily to nil. Of course this would only have an effect on Emacs 28 and newer. But there is no hurry or clear plan. I only created the issue to keep this in mind for the future.

**Comment by minad** [comment]
In the long term it may be better to just recommend `read-minibuffer-restore-windows=nil` as default and make our packages work well with that setting. I don't plan to work on this soon, but we should keep it in mind. I think it needs a lot of testing across various packages to ensure that everything works, since currently packages are written under the assumption of window restoration. See also https://github.com/minad/vertico/issues/222.

**Comment by oantolin** [comment]
I'm not even sure about recommending it as the default. I kind of like that the window configuration gets restored, so I can lookup as many files or docstrings as I want and trust that at the end my window configuration will be restored. Otherwise, I'd probably often have to save window configuration or open new tabs or something like that. And running actions as quitting just got more convenient to do with `q`.

**Comment by minad** [comment]
True, one can abuse the minibuffer and recursive editing as a means of window restoration. I also do that. Otoh one argue that it is better to use an orthogonal feature for window configuration and prefer a minibuffer which stays out of the way. Technically there is no fundamental reason why the minibuffer requires window restoration (maybe there was?). Anyway I assume that now that Emacs 28 has been released, more people may start to experiment with this.
