### ISSUE TITLE
embark-dwim fails to prompt xref candidates

### ISSUE THREAD

**Issue by dalgong** [oantolin/embark#464]
Hi,

(sorry for missing a clear reproduction scenario)
I'm binding `M-.` to `embark-dwim` which seems breaking candidate selection when an xref backend has multiple candidates. I don't know if this break always but at least with `consult-xref`, it seems broken. My guess is the following code fragment in `embark--act` is problematic:

```
(minibuffer-with-setup-hook ... (command-execute action))
```

Inside this block, it ultimately calls `consult--read` which does not prompt and simply returns nil.

**Comment by oantolin** [comment]
Oh, I see. Let me try to reproduce the issue.

**Comment by oantolin** [comment]
Oh, I think this is a simple oversight. Could you please evaluate this and try again?

```elisp
(push 'embark--ignore-target
      (alist-get 'xref-find-definitions embark-target-injection-hooks))
```

**Comment by dalgong** [comment]
It works great! Thanks for the quick fix!

**Comment by oantolin** [comment]
Glad to hear it worked correctly!
