### ISSUE TITLE
Calling `sort-regexp-fields` from `embark-act` does not work

### ISSUE THREAD

**Issue by usaoc** [oantolin/embark#465]
Normally, `sort-regexp-fields` prompts for `RECORD-REGEXP` and `KEY-REGEXP` when interactively called.  However, calling `sort-regexp-fields` from `embark-act` causes it to prompt for `KEY-REGEXP` only, and `RECORD-REGEXP` appears to be the selected text in such case.

**Comment by oantolin** [comment]
Whoops, sorry about that and thanks for reporting it.

**Comment by oantolin** [comment]
I should have said: if you want to test that fix before updating Embark, just evaluate this:

```elisp
(push 'embark--ignore-target
      (alist-get 'sort-regexp-fields embark-target-injection-hooks))
```
