### ISSUE TITLE
`embark-export` doesn't work on `consult-line` candidates with `embark-consult`

### ISSUE THREAD

**Issue by josephmturner** [oantolin/embark#469]
Thank you for this versatile package - it's a lot of fun to use :)

With `emacs -Q` and the following config:
```
(require 'embark)
(global-set-key (kbd "C-.") 'embark-act)
(require 'consult)
(require 'embark-consult)
```
In a buffer (I tested in a file buffer and also `*scratch*` buffer FWIW), run `M-x consult-line` followed by `C-. E` (to export the `consult-line` candidates). 
Instead of the expected `*Embark Collect*` buffer, I get `embark PCH: (wrong-type-argument markerp (#<buffer *scratch*> . 72))`.

If you comment out the last line of the config, it works fine.

Have a good day!

**Comment by minad** [comment]
Your Embark version is outdated. I made a mistake with the release of Consult yesterday since stable Consult doesn't work with stable Embark anymore due to the addition of cheap location markers. Embark should have been released first. @oantolin can you please tag a new Embark version?

**Comment by oantolin** [comment]
Oh, darn. Will do.

**Comment by oantolin** [comment]
Done. I'm also closing this issue since it is not present with the latest version, nor should it be present once this release hits the package repos.

**Comment by minad** [comment]
Omar, thanks and sorry for not coordinating with you first!

**Comment by oantolin** [comment]
No problem, @minad!

**Comment by josephmturner** [comment]
Thank you @oantolin @minad! It's working now.
