### ISSUE TITLE
How to add indicator for `ido-find-file`?

### ISSUE THREAD

**Issue by nurdann** [oantolin/embark#471]
Currently, I am able to add command to `embark-file-map` and it shows up as `Act on file` when I run `C-x C-f` (`find-file`) then press command to trigger `embark-act`.

How can I replicate behaviour for `ido-find-file` mini-buffer? 

I am a slowly digesting documentation but this package looks amazing!

**Comment by oantolin** [comment]
I've never tried making Embark recognize `ido-find-file`, I'll look into it, but it may be difficult because `ido-mode` is pretty idiosyncratic. Embark does work with `fido-mode` (also built-in) which is a pretty close replacement for `ido-mode`.

**Comment by nurdann** [comment]
I have just tried `fido-mode` minor mode and it looks good. I am giving try to using `fido-mode` for `find-file` but for switching buffers I'll keep using `ido-switch-buffer` because of `ido-use-virtual-buffers`, not sure if `fido-mode` has similar feature where it shows recently closed file buffers as well.

**Comment by minad** [comment]
> I am giving try to using fido-mode for find-file but for switching buffers I'll keep using ido-switch-buffer because of ido-use-virtual-buffers, not sure if fido-mode has similar feature where it shows recently closed file buffers as well.

You can use the `consult-buffer` command from my [Consult](https://github.com/minad/consult) package, which displays both buffers and files. You can even add your own virtual buffer sources.

**Comment by oantolin** [comment]
If you like fido-mode and @minad's consult-buffer command, I suggest switching away from ido: the ido package is pretty idiosyncratic and fido-mode fits in better with Emacs's completion system. Having said that, Embark is very flexible and it can be taught to work with ido. Please test this integration code:

```elisp
(defun embark--ido-type ()
  (cond
   ((string-match-p "File" (minibuffer-prompt)) 'file)
   ((string-match-p "Buffer" (minibuffer-prompt)) 'buffer)
   (t (user-error "Unknown ido command"))))

(defun embark--ido-selected ()
  (when ido-matches
    (cons (embark--ido-type) (ido-name (car ido-matches)))))

(defun embark--ido-candidates ()
  (when ido-matches
    (cons (embark--ido-type) (mapcar #'ido-name ido-matches))))

(add-to-list 'embark-target-finders #'embark--ido-selected)
(add-to-list 'embark-candidate-collectors #'embark--ido-selected)
```

**Comment by minad** [comment]
@oantolin I hope we don't add Ido support to Embark. Ido is obsolete, idiosyncratic and very complex for what it achieves. There exist many better alternatives now. Most importantly, Ido doesn't work in most completion scenarios. To make it work in a wider context one needs ido-completing-read-plus and other hacks, which overall lead to a brittle, half broken and very complex system if compared with minimal completion systems like Vertico, Mct or Icomplete. I would vote to not try to make Marginalia, Embark, Consult work with Ido-related packages. From my perspective, the right place for this integration code is the wiki. On the other hand the integration code you just presented is minimal, so it wouldn't hurt Embark too much. I just don't see any reason to keep Ido on live support. See also https://github.com/minad/vertico/issues/177, where a migration from Ido to Vertico etc was discussed.

**Comment by oantolin** [comment]
I'm not keen to have ido support in Embark either, I was just thinking of putting that code on the wiki.

**Comment by oantolin** [comment]
Also note that the code above only supports ido, I haven't attempted to make things work with ido-completing-read-plus.

**Comment by minad** [comment]
Okay, to be clear - the main small risk I see here is that we lose the editorialization aspect and give a false impression about the status of Ido and the landscape of completion alternatives. Ido is obsolete and should not be used anymore if you want a full-featured completion experience. Ido simply cannot be considered to be on the same level as the other systems. It is still mentioned quite often in discussions, which adds to the false impression. Therefore I think it would be better to not officially support it.

**Comment by nurdann** [comment]
I tested @oantolin code snippet and it worked. But as suggested by @minad, I am switching to `fido-mode` as it seems to have better support. As for the virtual buffers, I'll give try to `recentf` and Consult. Thanks!

**Comment by oantolin** [comment]
It looks like we can close this issue, then. Feel free to continue the discussion though!
