### ISSUE TITLE
Toggling between list and grid view in an embark collect buffer unmarks all candidates

### ISSUE THREAD

**Issue by oantolin** [oantolin/embark#473]

**Comment by minad** [comment]
@oantolin What about simply removing the grid view?

- It seems we don't really need this, given that embark-collect-completions was removed. Do you still use it or is it there only for historical reasons? 
- The grid view does not really fit to the use of the tabulated *list* mode
- We have this overlay issue
- We don't have the ability to highlight candidates, see #161. For lists hl-line-mode just works.

**Comment by oantolin** [comment]
I do like the idea of removing the grid view. It does seem pretty unnecessary if we aren't thinking of Embark as a completion framework. I don't personally use grid view anymore, not since I switched to Vertico. 

I agree with all your arguments but want to point out some minor caveats: `hl-line-mode`, `consult-focus-lines` and `consult-keep-lines` are all line-based so they don't work that well will multiline candidates, such as those from `consult-yank-pop`. But that's not really a big deal: (1) multiline candidates seem to be pretty rare, (2) those commands all have line in the name so it's pretty clear what they do and what you should expect from them.
