### ISSUE TITLE
Why is embark-occur not in the embark-general-map?

### ISSUE THREAD

**Issue by minad** [oantolin/embark#48]
Is there a reason why you don't put all the possible embark operations into the actions keymap directly? I am experimenting with the new embark version now - everything seems to work great so far, but it could be that I have more beginner questions, since I am not accustomed to actions.

**EDIT**: Is the reason that embark-occur is an action which acts on all candidates at once in contrast to acting on a single candidate?

**Comment by oantolin** [comment]
Yes, that's right: `embark-occur` is not an action, that is, it is not a function you want to apply to the current target.

If you want to bind functions like `embark-occur` as actions, beware that you must consume the target! So don't put `embark-occur` in an action map, but, if you wish, you can put this function in an action map:

```elisp
(defun embark-ignore-target-and-occur ()
  "`embark-occur' repackaged as an action."
  (ignore (embark-target))
  (embark-occur))
```

**Comment by minad** [comment]
Ok, thank you! Makes sense, the action function must consume the candidate. But I still think it makes sense to have this when one sees the embark menu as a context menu. The same applies to embark-export!

**Comment by minad** [comment]
Maybe it also makes sense to have it on an extra keybinding, but then I wonder how often it is used. I wished a few times now for an embark-occur buffer before, but it was still rare. Probably if you get accustomed to it, you use it more. Checking out your config now https://github.com/oantolin/emacs-config/blob/2e5135a83eb20668d67b0adebf7efd54fea2db11/init.el#L390 :)

**Comment by oantolin** [comment]
I think @clemera said the same thing a while ago about binding `embark-occur` and `embark-export` in `embark-general-map`.

That never felt right to me, maybe because even though I mostly program in Emacs Lisp, I really think in a strongly typed way. You're a Haskeller, right? In Haskell terms I think of actions as having type `Candidate -> IO ()` and I think of `embark-occur` and `embark-export` as having type `[Candidate] -> Buffer`. So for me, putting `embark-occur` or `embark-export` in an action keymap feels like a type error.

**Comment by oantolin** [comment]
I do however have `(defun embark-ignore-target (&rest _) (ignore (embark-target)))` in my personal and use it as `:before` advice on non-actions I want to call from `embark-act`, so maybe I'm a hypocrite.

**Comment by minad** [comment]
Since the actions are `Candidate -> IO ()`, you can also implement occur with it - simply access the candidate list via IO and show the buffer ;) But I agree it is not very clean. Ideally the actions should not access to the candidate list. 

However given the context menu perspective, I think one could also justify it. `Context -> IO ()` and `Context` is the selected candidate and the candidate list if you are in the minibuffer.

My point here is mostly that it would be nice to have all the embark related functionality directly available - but I am an action noob. For someone experienced it might make more sense to have the different operations bound to different keys.

**Comment by oantolin** [comment]
No, you're probably right that it is not worth "wasting" a key binding on `embark-occur` or `embark-export`. What would you bind them to in `embark-general-map`? Maybe `C-o` and `C-e`? Using the `C-` modifier to set them apart from "real" actions?

**Comment by oantolin** [comment]
I could also throw in `embark-ignore-target` and document its use as `:before` advice to be able to bind non-actions in action maps.

One thing I like about doing that via advice is that then `C-h f` will tell you the function is safe to use as an action.

**Comment by oantolin** [comment]
Ah, I just remembered: you can run `embark-occur` and `embark-export` from `embark-act-noexit`, but they don't work from `embark-act` (I only squirrel away the current candidate, not the full candidate list).

**Comment by minad** [comment]
> Maybe C-o and C-e? Using the C- modifier to set them apart from "real" actions that are bound to key without modifers?

For example, or use uppercase letters? But you also use uppercase for other stuff.

> I could also throw in embark-ignore-target and document its use as :before advice to be able to bind non-actions in action maps.

Would it be possible to somehow auto-detect this? I mean after the action the target must be gone always - I am not into the code, maybe this does not make sense. Such that a command is always safe as action.

> Ah, I just remembered: you can run embark-occur and embark-export from embark-act-noexit (and they do exit!), but they don't work from embark-act (I only squirrel away the current candidate, not the full candidate list). This is the actual reason.

Right now I am only using nonexit and exit manually. I find that cleaner with respect to what I wrote in #44 regarding not deciding too early if I want to exit or not. (Revisiting #44, I would like to have a possibility to mark actions as exiting, embark-occur would then be of the exiting kind)

**Comment by hmelman** [comment]
I'll say, coming from `ivy`, I'd like a way to get a buffer of completions from the minibuffer (like `ivy-occur`) which I think is `embark-occur` (or maybe it's `embark-export`?) and I'm completely stumped at how to do that now.   Something out of the box or described in the README would be much appreciated.

**Comment by minad** [comment]
I am doing recursive M-x embark-occur. I really hope embark-occur/export get added to the embark keymap such that they become directly accessible from the embark menu :)

**Comment by oantolin** [comment]
> I'll say, coming from `ivy`, I'd like a way to get a buffer of completions from the minibuffer (like `ivy-occur`) which I think is `embark-occur` (or maybe it's `embark-export`?) and I'm completely stumped at how to do that now. Something out of the box or described in the README would be much appreciated.

You are correct, @hmelman, the correct command is `embark-occur`. Run it the way any Emacs command is run. For example `M-x embark-occur` works if you use recursive minibuffers. Or, if you prefer, bind it to a key. A global binding works, of course, but if you think you will only ever use it from the minibuffer, I suggest binding it in `minibuffer-local-completion-map` (or in `selectrum-mode-map` if you use selectrum).

**Comment by oantolin** [comment]
@hmelman The difference between between `embark-occur` and `embark-export` is that `embark-export` tries to give you a more appropriate buffer type, falling back on the generic Embark Occur buffer if it doesn't know a good class of buffer to use. For now, it only knows 3 types: for files it uses dired; for buffers, ibuffer; and for packages, package-menu-mode.

**Comment by oantolin** [comment]
But it is probably a good idea to add an example key binding in the README. I think I'll do that.

**Comment by hmelman** [comment]
Thanks.  I'm using selectrum and the proper map is `selectrum-minibuffer-map`.  It seems to give an error when I use it on `consult-line`  (no candidates for occur).  On find-file it seems to work though the buffer has several candidates on a line and I'd very much want one per line so I can easily use `flush-lines` or `keep-lines` on it or run a macro on each one, etc.  I do really like that `embark-export` on files creates a dired buffer.

**Comment by oantolin** [comment]
Thanks for pointing out what the correct keymap is for selectrum, as you can probably tell I'm not a selectrum user myself (yet?). The Embark Occcur buffer has two ways to list candidates: grid view and list view. The grid view is what you are seeing. The list view has one per line and include annotations (I know you use marginalia too, @hmelman, so you'll get those). To toggle between the two views use `M-q` which is bound to `embark-occur-toggle-view`.

**Comment by oantolin** [comment]
You can configure for each category whether the Embark Occur buffer starts in grid or list view, by customizing the variable `embark-occur-initial-view-alist`.

**Comment by oantolin** [comment]
> It seems to give an error when I use it on `consult-line` (no candidates for occur).

Oh, that's weird. It should work. I may have to install Selectrum if only to debug Embark problems... 🙄

**Comment by hmelman** [comment]
Gotcha and yes I found `embark-occur-initial-view-alist`.  I appreciate the annotations that marginalia adds to an `embark-occur` buffer of files (in list mode).  I think I'd also like a way to get a list (one line per item) without any annotations (even if annotations are usually enabled).  Maybe `embark-occur-toggle-view` becomes `embark-occur-cycle`?  I'm not sure if this should be a marginalia or an embark feature?

**Comment by joostkremers** [comment]
> It seems to give an error when I use it on `consult-line` (no candidates for occur). 

I just ran into the same problem. Came here to open an issue, but since it's mentioned here, I thought I'd just give it a "me too".

I'm a recent convert, having switched just two days ago from ivy/swiper to selectrum/consult/embark, and so far, `ivy-occur` is the one thing I really miss. Though I must admit it was only useful because the `ivy-occur` buffer integrates with `wgep`. Don't know if that's the case for `embark-occur`.

**Comment by clemera** [comment]
If the `consult-line` issue is selectrum related (does not happen with icomplete) please open an issue there. I just tested it and it seems to work fine for me so please provide a recipe when you do that.

**Comment by hmelman** [comment]
I'm trying to debug this (and it's a good excuse to finally edebug).  I see that `(run-hook-with-args-until-success 'embark-candidate-collectors)` is returning nil.  It returns something in my working `find-file` case.  The only config I'm doing for embark is `(define-key selectrum-minibuffer-map (kbd "C-o") 'embark-occur)`.  Is more needed?  I'm in the embark.el buffer and run `consult-line` and use the string "create" to generate 9 matches.  Is it `embark-minibuffer-candidates` that should return something?

**Comment by clemera** [comment]
Yes, with selectrum there is some more setup required, see our [wiki](https://github.com/raxod502/selectrum/wiki/Additional-Configuration#minibuffer-actions-with-embark), with that things should work for you.

**Comment by hmelman** [comment]
Yes, that solved it for me, thanks.  

I'll try to think through this more, but I think ideally this would be self-configuring.  Or at least the embark README or wiki should point to this info.  My path was trying selectrum first then adding marginalia and consult and then embark (though part of that was because embark wasn't yet on melpa, I know soon).  So at the point I added embark, I didn't think to go back to the selectrum docs to see what to configure with embark.

**Comment by clemera** [comment]
As the special setup is require for Selectrum I think it's better to keep it on the Selectrum wiki. But we are planning to add and auto setup option for various packages to Selectrum eventually, see [here](https://github.com/raxod502/selectrum/pull/174).

**Comment by oantolin** [comment]
OK, I bit the bullet and committed the type error of adding occur and export to the general map, they are `O` and `E`. 😛 The principles we compromise for the sake of better key bindings...

**Comment by minad** [comment]
Works great! Thank you :)

**Comment by oantolin** [comment]
I should have done it a while ago. I think I didn't realize it took so little code to make `embark-occur/export` work with `embark-act`.
