### ISSUE TITLE
embark-collect: Add column in front for marker character

### ISSUE THREAD

**Issue by minad** [oantolin/embark#482]
Dired puts a `dired-marker-char` in front of marked files. Ibuffer does the same. Maybe we should also add such an indicator to Embark Collect?

**Comment by oantolin** [comment]
Oh, yes, I meant to keep the special face as well, just like dired and ibuffer, which use both a character and a face.

**Comment by oantolin** [comment]
There is a `tabulated-list-put-tag` function that one can use for this purpose.

**Comment by oantolin** [comment]
Now that we use the new selection functionality instead, I think I don't want a marker character, for uniformity with regular buffers where I certainly don't want such a character.
