### ISSUE TITLE
Binding RET in embark keymap

### ISSUE THREAD

**Issue by orki** [oantolin/embark#483]
`RET` on an embark keymap seems to be ignored and redirects to the command that initiated the completing read. Here's my definition of an embark keymap:
```
(with-eval-after-load "embark"
  (embark-define-keymap consult-dash-embark-keymap
    "Actions for consult dash results"
    ("RET" consult-dash--open-url)
    ("y" consult-dash-yank-candidate-url))
  (add-to-list 'embark-keymap-alist
               '(consult-dash-result . consult-dash-embark-keymap)))
```
In the embark buffer, `y` does call the right function, but `RET` does not. `RET` points to the command the top-level interactive function (`consult-dash-at-point`, in this case) that eventually led to the call to `consult--read`. How can it be overridden?

**Comment by oantolin** [comment]
Yes, RET runs the default action, which is chosen according to the rules in the docstring for `embark-dwim`, or, with fewer details [in this section of the README](https://github.com/oantolin/embark#the-default-action-on-a-target). If you want to override this behavior so that Embark ignores the command that opened the minibuffer, add an entry to `embark-default-action-overrides` for your completion category.

**Comment by oantolin** [comment]
I think it's pretty unusual to not want RET to run the command that initiated the completing read. Out of curiosity why don't you want RET to run that command?

**Comment by orki** [comment]
The flow is as follows:
  - `consult-dash-at-point` calls `consult--read`
  - `consult--read` returns a result, which is a list with multiple elements
  - the result is passed into `dash-docs-browse-url`
  -  the candidate that `embark` provides is just the string shown in the minibuffer, and hence is passed through `consult-dash--open-url` which extracts the corresponding list from its string properties to send to `dash-docs-browse-url`

Is the flow above unusual?

```
  (when-let* ((builder (consult-dash--with-buffer-context #'consult-dash--builder))
              (search-result (consult--read
                              (consult--async-command builder
                                (consult--async-transform consult-dash--format)
                                (consult--async-highlight builder))
                              :prompt "Dash: "
                              :require-match t
                              :group #'consult-dash--group
                              :lookup #'consult--lookup-cdr
                              :category 'consult-dash-result
                              :annotate #'consult-dash--annotate
                              :initial (consult--async-split-initial initial)
                              :add-history (consult--async-split-thingatpt 'symbol)
                              :history '(:input consult-dash--history))))
    (dash-docs-browse-url search-result))
```

**Comment by minad** [comment]
@orki      

> Is the flow above unusual?

I cannot tell. However it is a general Embark rule that "RET" is the default action, so it is unlikely that your dash command should be an exception. If you run `embark-act` on a minibuffer candidate of an arbitrary command, then "RET" will run that command as default action. This makes sense. For example when you use the command `find-file` and set `embark-quit-after-action=nil`, then you can use `C-. RET` on multiple files to open each of the files separately without leaving the minibuffer. (If you use `embark-quit-after-action=t` you can still do that but you need a prefix argument `C-u C-. RET`.)

**Comment by oantolin** [comment]
Usually what you want to do to a completion candidate for the default action is exactly what the command already does to the result of the completing-read call. By having the default action be the same as the command that opens the minibuffer, Embark let's you do that without any code at all. I can't quite tell if in this case the binding you want for RET does something different than just pressing RET to submit the candidate would do.

**Comment by orki** [comment]
The model does not always make sense to me. Consider the case of `consult-locate`. Suppose you enter some string which matches 4 filenames on the system. Now call `embark-act`, and then press `RET`. As a user of `consult-locate`, my mental model is that `RET` should have called `find-file`, but it goes back into `consult-locate`, which rarely (if ever) does anything more useful.

In the case of `consult-dash`, the candidates are strings with a whole bunch of associated metadata. Sticking this string back into the minibuffer prompt, which cannot provide any further refinement, makes no sense. It should simply call some sort of action on the candidate, the default one being browsing a URL computed from the metadata.

**Comment by minad** [comment]
Oh, I should have known. You are right. The model does not make sense for asynchronous consult commands. For such commands embark-default-action-overrides should be used to define the default action.

See https://github.com/oantolin/embark/blob/7e6db952d01a7908eaa3c3550fd5d4b27cb1f923/embark-consult.el#L175 or https://github.com/oantolin/embark/blob/7e6db952d01a7908eaa3c3550fd5d4b27cb1f923/embark-consult.el#L218.
