### ISSUE TITLE
Consult async commands: Override default actions

### ISSUE THREAD

**Issue by minad** [oantolin/embark#484]
We override the default action for `consult-grep`, but we don't do that for `consult-find` and `consult-locate` as @orki pointed out in https://github.com/oantolin/embark/issues/483#issuecomment-1089734571. The problem is that `consult-find` and `consult-locate` use the `file` category (which is reasonable). Unfortunately using the category doesn't allow us to overwrite the default action in this case. I vaguely remember that we discussed this issue before, but I am not entirely sure. I will search the issue tracker.

**Comment by minad** [comment]
We discussed async commands in https://github.com/oantolin/embark/issues/145, but the discussion was more about the insertion of the async split character which is done by a function registered in `embark-target-injection-hooks`.

**Comment by minad** [comment]
To resolve this issue, my proposal would be to use the command instead of the category as key in `embark-default-action-overrides` or add additional support to specify commands.

**Comment by oantolin** [comment]
Ha, I hadn't noticed! I think because I don't use `consult-find` that often and when I do, since it produces files, I almost always export rather than collect.

**Comment by oantolin** [comment]
> To resolve this issue, my proposal would be to use the command instead of the category as key in `embark-default-action-overrides` or add additional support to specify commands.

I think having both ways to override is probably better. For example, it's very nice that the `consult-location` override automatically works for, say, any user defined command that relies on `consult-line`, like a variant that uses the symbol at point as the initial input.

We should just add a way to also override by command name.

**Comment by oantolin** [comment]
I guess we could also just install a category override for `file` buffer-locally in the collect buffer.

**Comment by minad** [comment]
> I guess we could also just install a category override for file buffer-locally in the collect buffer.

No, it is not about the collect buffer only but also about minibuffer commands. I think we should allow command keys in `consult-default-action-overrides`.

~~~ elisp
(setq embark-default-action-overrides
   '(((:command . consult-find) . find-file)
     ...))
~~~

Unfortunately this is quite ugly. Do you have a better idea? One could also use strings as keys (interpret them as command name regexps) or introduce special symbols which are then looked up via `intern-soft`. Are there other places where we may want to specify both types and commands? It would be nice to have a uniform solution.

~~~ elisp
(setq embark-default-action-overrides
   '((command:consult-find . find-file)
     ...))
~~~

**Comment by oantolin** [comment]
I think the best option is to allow to override the default action based on either category or command. Now, there are several ways to allow that:

1. The marginalia way: we rename the current `embark-default-action-overrides` to `embark-default-action-category-overrides` and add a separate `embark-default-action-command-overrides`.

2. The "hope there aren't many collisions" strategy: simply allow the keys in `embark-default-action-overrides`to be either categories or commands, checking, say, category first.

3. The "add the command as a predicate" strategy: allow as keys either a category (as now) but also a `(category . command)` pair; the idea here is that we think of the command as a predicate that restricts matches of the category.

I'm voting for 3.

**Comment by oantolin** [comment]
I think that category-command pair option is pretty nice: `((file . consult-find) . find-file)` reads nicely as "use `find-file` for `file`s but only if you got them from `consult-find`".

**Comment by minad** [comment]
Okay, option 3 sounds reasonable. Unfortunately Embark is a bit inconsistent in using either categories or commands for configuration variables. But it seems that most of the hooks use commands instead of categories. Keymaps (and default action overrides) use categories.

**Comment by minad** [comment]
We could at least (if needed) generalize all the category-keyed customization variables to these pairs `(file . consult-find)`.

**Comment by oantolin** [comment]
I wouldn't say it's inconsistent, it consistently uses commands for things that really are specific to the command and that you don't want for the whole category, like the hooks. And it consistently uses categories for basically everything else. Here it makes sense to have both.

**Comment by oantolin** [comment]
> We could at least (if needed) generalize all the category-keyed customization variables to these pairs `(file . consult-find)`.

Sure, I guess. It would allow to have special keymaps just for certain commands. Which is a little wrong-headed, but someone will find a sensible use for it.

**Comment by minad** [comment]
> I wouldn't say it's inconsistent, it consistently uses commands for things that really are specific to the command and that you don't want for the whole category, like the hooks. And it consistently uses categories for basically everything else. Here it makes sense to have both.

Agree. I just would like to avoid the situation where we can specify `type` and `(type . command)` for some variables as keys and `command`  and `(type . command)` for some other variables. If we allow the wrong-headed keymap configurations we end up with exactly such a situation.

**Comment by oantolin** [comment]
I like this `(category . command)` idea, it reminds me of the recent generalization of `embark-repeat-actions`: now, in addition to commands, elements can be `(command . category)` pairs which means "if `command` is used as an action, then keep embark-act alive and cycle to the `category` target next, if there is one". A typical example is `(some-command-that-marks . region)`.

**Comment by minad** [comment]
> I like this (category . command) idea

Yes, I like it too. It is a good idea.

**Comment by oantolin** [comment]
> (EDIT: But maybe this is just what we will end up with since for some variables types make more sense and for some commands make more sense as normal key type...)

I think that might happen, and that's fine, as long as the types are useful in each case. For now, I think I'd only generalize the default action overrides leaving all other variables as they are. We can discuss changing that later.

**Comment by minad** [comment]
Great, thanks!

**Comment by orki** [comment]
> I think having both ways to override is probably better. For example, it's very nice that the `consult-location` override automatically works for, say, any user defined command that relies on `consult-line`, like a variant that uses the symbol at point as the initial input.

What is the canonical way of wrapping a consult command with thing-at-point? I keep thinking that there should be a higher order function (or worse, a macro) that produces it automatically:
```
(defmacro consult-thing-at-point-command (command &rest thing-types) ...)
(consult-thing-at-point-command consult-line 'symbol)
```

**Comment by minad** [comment]
You can use this:

~~~ elisp
(defalias 'consult-line-thing-at-point 'consult-line)

(consult-customize
 consult-line-thing-at-point
 :initial (thing-at-point 'symbol))
~~~

It is documented in the Consult readme, see https://github.com/minad/consult#fine-tuning-of-individual-commands.
