### ISSUE TITLE
How to make `embark-act` act on information that is not visible in the completion list?

### ISSUE THREAD

**Issue by rdrg109** [oantolin/embark#486]
# The context

Let's suppose I want to manage my bookmarks within Emacs and for each bookmark I expect to add a title that helps me find that bookmark, so when I'm prompted for a bookmark, I get a completion list similar to the following one.

```elisp
(consult--read
 '(("GNU" . "https://www.gnu.org")
   ("Gentoo Linux" . "https://www.gentoo.org")
   ("Python" . "https://www.python.org"))
 :lookup 'consult--lookup-cdr)
```

When I select an option, I would expect the URL to be selected (that's the reason why `consult--lokup-cdr` is used) instead of the title because the URL is the concept of the bookmark and the title is just a name that I've assigned to it. The sexp shown above is able to retrieve the URL instead of the `car` thanks to `consult--lokup-cdr`.

# The problem

When I use `embark-act` on a candidate that is shown in the completion list created by the sexp shown above, `embark-act` considers the `car` (i.e. the title of the bookmark) instead of the `cdr` (i.e. the URL of the bookmark).

I want Embark to act on the URL instead of the title, so I'm looking for a way to make Embark (through `embark-act` or some other function) consider other information of the candidates that is not necessarily visible in the completion list.

# The question

How to make Embark act on a candidate but consider other information that is not necessarily visible in the completion list (e.g. the data is on the `cdr`)?

**Comment by minad** [comment]
You can attach text properties and then access those. But this works only for non-interactive actions. I recommend to approach the problem differently, in a way which is more canonical regarding to how Embark works usually:

~~~ elisp
(defun my-compute-candidates ()
  '(("GNU" . "https://www.gnu.org")
    ("Gentoo Linux" . "https://www.gentoo.org")
    ("Python" . "https://www.python.org")))

(defun my-action (cand)
  (interactive "s")
  (message "url=%S" (cdr (assoc cand (my-compute-candidates)))))

(let ((cands (my-compute-candidates)))
  (cdr (assoc (completing-read "Select: " cands) cands)))
~~~

**Comment by rdrg109** [comment]
@minad Thanks for the answer! I think the approach you mentioned would imply creating a function whenever I want to add a new action.

I'm mostly interested in using `embark-act` and define all actions in `embark-define-keymap` because I don't need to define a new function whenever I want to add a new action and because I would be able to call any action by using the same completion list, so there's no need for me to start a new completion list if I change my mind on the action I want to execute.

**Comment by oantolin** [comment]
@minad's advice is great for the case when the actions you want are not already functions that you have, so you have to write them anyway. I'd add that in that case you should put the `completing-read` (or `consult–read`) call in a helper function, say, `my-read-a-thing`, so that you can reuse it in the `interactive` spec of your action commands:

```elisp
(defun my-action (thing)
   (interactive (list (my-read-a-thing)))
   ...)
```
But, as you pointed out, in this URL case you'd like to resuse the existing URL actions and keymap. For that I recommend using an Embark transformer that does the lookup for you:

```elisp
(defvar my-bookmarks
        '(("GNU" . "https://www.gnu.org")
          ("Gentoo Linux" . "https://www.gentoo.org")
          ("Python" . "https://www.python.org")))

(defun lookup-url (_type target)
  (when-let ((url (cdr (assoc target my-bookmarks))))
    (cons 'url url)))

(add-to-list 'embark-transformer-alist '(my-bookmark . lookup-url))

(consult--read
 my-bookmarks
 :category 'my-bookmark
 :lookup 'consult--lookup-cdr)
 ```

**Comment by oantolin** [comment]
I'm going to close because I don't think anything needs to change in Embark to accommodate this use case, but the conversation can of course continue, specially if none of these suggestion work for you, @rdrg109 (in which case let me know and we'll figure it out).

**Comment by rdrg109** [comment]
@oantolin Thanks for the info! :+1: 

I like your approach but I'm afraid it wouldn't work when there are two bookmarks with the same title. In that scenario, because `assoc` is being used, the first bookmark with that title would be selected, but this isn't always the expected behavior.

I think that problem would be solved if all the information of the candidate is sent to `embark-transformer-alist` so that then I can get the `cdr` of the bookmark.

With the following experiment, I found out that `embark-transformer-alist` just receives the content that is shown in the completion list, but not the entire information (i.e. the `cdr` is not a provided argument)

```elisp
(defun my/function (&rest args)
  (message (format "args: %s" args))
  (cons "foo" "bar"))

(add-to-list 'embark-transformer-alist '(my/type . my/function))

(consult--read
 '(("GNU" . "https://www.gnu.org")
   ("Gentoo Linux" . "https://www.gentoo.org")
   ("Python" . "https://www.python.org"))
 :category 'my/type)
```

Executing `embark-act` on each candidate in the completion list shows the following messages

```text
args: (my/type GNU)
args: (my/type Gentoo Linux)
args: (my/type Python)
```

**Comment by minad** [comment]
@rdrg109

1. No, this is not possible.
2. Candidate strings must be unique. See https://github.com/minad/consult/issues/549.

**Comment by oantolin** [comment]
> I like your approach but I'm afraid it wouldn't work when there are two bookmarks with the same title.

You shouldn't allow two bookmarks with the same title because when they are shown to you it's very confusing!
