### ISSUE TITLE
the function cl-constantly is not known to be defined

### ISSUE THREAD

**Issue by minad** [oantolin/embark#487]

**Comment by oantolin** [comment]
I wonder why that one is problematic but the other cl-lib functions seem to be OK. Maybe it's new? I'll just replace it with its definition.

**Comment by minad** [comment]
Hmm I don't see cl-constantly in cl-lib? Does it exist only on your Omarcs?

**Comment by oantolin** [comment]
I did check the help and didn't see a "added in Emacs 29" message so I thought it was OK to use. But the name is longer than the definition, there's really no point in using it.

**Comment by minad** [comment]
Very useful addition for people who like verbose names!

**Comment by minad** [comment]
You should probably also replace all uses of lambda with cl-anonymous-function to improve readability.
