### ISSUE TITLE
Embark occur list view without annotations

### ISSUE THREAD

**Issue by oantolin** [oantolin/embark#49]
Gotcha and yes I found `embark-occur-initial-view-alist`.  I appreciate the annotations that marginalia adds to an `embark-occur` buffer of files (in list mode).  I think I'd also like a way to get a list (one line per item) without any annotations (even if annotations are usually enabled).  Maybe `embark-occur-toggle-view` becomes `embark-occur-cycle`?  I'm not sure if this should be a marginalia or an embark feature?

_Originally posted by @hmelman in https://github.com/oantolin/embark/issues/48#issuecomment-744082694_

**Comment by hmelman** [comment]
I now think the ideal thing would be to be able to use `marginalia-cycle` in an embark-occur buffer.  That doesn't work now and I'm not sure if that's a sensible suggestion.

**Comment by oantolin** [comment]
I'm not at my computer to test now, but I believe marginalia- cycle does work, except that you need to revert the Embark occur buffer afterwards (this is bound to `g` in the Embark occur buffer).

**Comment by hmelman** [comment]
I did try that and it did not work for me.

**Comment by oantolin** [comment]
Ah, OK. I'll fix it later when I'm at the computer and get back to you.

**Comment by oantolin** [comment]
OK, I think it's working now (it still requires reverting). Please test and reopen if it doesn't work for you.

Are you sure this enough for you? Even with marginalia-cycle there's no convenient way to disable all annotations. The entry `nil` in `marginalia-annotators` does not mean "no annotators", but rather "no Marginalia annotators, just built-in ones".

**Comment by hmelman** [comment]
I'll try it (have to wait for it to make it to melpa).  It might not be perfect but it might be "enough".  I'm using marginalia and not am not too aware of seeing builtin annotations (other than insert-char?).  I'm not sure about non-marginalia users.  I do think it's useful to get an occur buffer with no annotations (but including nil in marginalia-annotators mostly does that for me).

**Comment by oantolin** [comment]
I guess the other prominent example of built-in annotations is that commands in `M-x` are annotated with their key bindings.

**Comment by oantolin** [comment]
The fix is on Melpa now.

**Comment by hmelman** [comment]
Seems to work :)
