### ISSUE TITLE
Tofu problem with consult-buffer

### ISSUE THREAD

**Issue by minad** [oantolin/embark#490]
The discussion in #437 led me to do some tests again. There is a case where we can still get tofus for some reason. I had observed this problem before but had forgotten about it.

emacs -Q, Emacs 28:

~~~ elisp
(package-initialize)
(vertico-mode)
(require 'embark)
(require 'embark-consult)
(setq recentf-list '("/etc/hosts")
      recentf-mode t
      embark-quit-after-action nil)
(global-set-key [remap switch-to-buffer] #'consult-buffer)
(global-set-key [remap switch-to-buffer-other-window] #'consult-buffer-other-window)
(global-set-key (kbd "C-.") #'embark-act)
~~~

1. C-x b
2. select /etc/hosts
3. C-. RET -> we get a tofu. The problem does not occur for C-u C-. RET

**Comment by oantolin** [comment]
This is weird! Was there maybe some changes in Consult? Is the tofu a pure function of the name and type of the thing? I ask because it's inserted into a new call of consult-buffer, so if the tofu for the same file in the new instance of consult-buffer is different, then the "no match ⇒ new buffer" would kick in. 

Although that can't be the problem or it would most likely happen for C-u C- RET too...

**Comment by oantolin** [comment]
I forgot to say: I can easily reproduce this. I'm baffled as to why it happens.

**Comment by minad** [comment]
I think I understood the problem now a bit better. It is an unfortunate interaction of preview and embark. If a recent file is previewed and then acted upon with `consult-buffer` (`C-. RET`), then the file does not appear anymore in the list of files for the action invocation of `consult-buffer`. Therefore the `consult-buffer` action treats the injected input as buffer name. Just recently I switched to automatic preview for files, after I made preview more robust and faster (see https://github.com/minad/consult/issues/538). This explains why I haven't observed the problem before.

**Comment by oantolin** [comment]
Ah! That makes perfect sense.

**Comment by minad** [comment]
Any ideas on how we could circumvent this problem? This is a really bad one, the completion table changes behind our back and this messes up the Embark injection. We could reconsider pausing preview as we discussed before. But pausing preview means more than what we discussed before. It means that all preview effects must be undone completely during the action execution. For example `consult--file-preview` and `consult--temporary-files` keeps a list of buffers open instead of closing them immediately. When pausing the preview, all temporary buffers must be closed. It is not sufficient to only undo the change to the window configuration.

**Comment by oantolin** [comment]
You won't love this solution, but Consult could make a best effort to use the source encoded in the tofu even if the candidate is not found:

```elisp
(defun consult--multi-lookup (sources _ candidates cand)
  "Lookup CAND in CANDIDATES given SOURCES."
  (if-let (found (member cand candidates))
      (cons (cdr (get-text-property 0 'multi-category (car found)))
            (consult--multi-source sources cand))
    (if-let (source (consult--multi-source sources cand))
        (let ((w/o-tofu (substring cand 0 -1)))
          (cons w/o-tofu source))
      (unless (string-blank-p cand)
        (list cand)))))
```

**Comment by oantolin** [comment]
Consult would be following this reasoning: "Someone handed me a non-existing candidate but with tofu that does correspond a source I know about, let's give it the benefit of the doubt and assume it works with that source ---even though that so-called candidate is not on my list!"

**Comment by minad** [comment]
Yes. I also thought about this. Or it could just ignore unknown candidates with tofu. These solutions are probably better than introducing a pause/resume protocol.

**Comment by oantolin** [comment]
Between the "trust the tofu" approach and Ignoring unknown candidates with tofu, I prefer trusting the tofu. Realistically, if there is tofu present it is probably correct about the type of candidate. Ignoring unknown candidates with tofu would not give us the behavior we want for this C-. RET case.

**Comment by oantolin** [comment]
It is a kludge, but seems like a very innocent one.

**Comment by oantolin** [comment]
You know, you could even decide to not lookup the candidates at all and simply trust the tofu. That opens up the possiblity of having a command that inserts the appropriate tofu for you, so when the user types a non-existing candidate the user could even say what source to interpret it as coming from. A user can currently say, "make me a new buffer", but with this change they could also say, make me a new terminal buffer with this name", or "open this file" (for an existing file that is not on the recentf list), etc.

**Comment by minad** [comment]
> Ignoring unknown candidates with tofu would not give us the behavior we want for this C-. RET case.

It would almost, since the candidate is previewed. ;)

The problem with trusting the tofu is that I have to extract the multi-category property to retrieve the actual candidate. Taking the substring is not sufficient, see for example the project file source. I think the solution is one of those:

1. We have to make sure somehow that the text properties are retained in this case. Then consult--multi doesn't have a problem to dispatch to the correct source.
2. Use a default action override and dispatch to the default action of the actual candidate type. However then it is not guaranteed that we are performing the correct action.

**Comment by minad** [comment]
> You know, you could even decide to not lookup the candidates at all and simply trust the tofu. That opens up the possiblity of having a command that inserts the appropriate tofu for you, so when the user types a non-existing candidate the user could even say what source to interpret it as coming from.

Not a bad idea. Unfortunately it won't work because of the issue I mentioned before, that the actual candidate must be retrieved from the multi-category.

**Comment by minad** [comment]
What about this?

1. Embark injects not the original candidate but the string "actual-candidateTOFU".
2. Consult looks up the original candidate and looks up the actual string via the multi-category
3. If this fails but there is a tofu, Consult interprets the string without the tofu as the actual candidate

**Comment by minad** [comment]
See also https://github.com/minad/consult/issues/539, where the creation of new candidates has been requested. I think I will also integrate this then into the modified lookup function.

**Comment by oantolin** [comment]
Sure, that sounds like a good plan to me. All I would have to do is add this to `embark-consult`:

```elisp
(cl-defun embark-consult--real-candidate
    (&key type target &allow-other-keys)
  "Replace the inserted TARGET with Consult's \"real\" candidate, keeping tofu."
   (when (eq type 'multi-category) ; unrefined, it must be from default action
    (delete-minibuffer-contents)
    (insert (cdr (get-text-property 0 'multi-category target)))
    (insert (consult--tofu-get target))))

(push 'embark-consult--real-candidat
      (alist-get 'consult-buffer embark-target-injection-hooks))
```

**Comment by oantolin** [comment]
I guess technically this could happen for other `consult--multi` commands too, does consult ship with others?

**Comment by minad** [comment]
This should happen for all multi-category commands I would say.

**Comment by oantolin** [comment]
Oh, I see. Like this:

```elisp
(cl-defun embark--multi-category-real-candidate
    (&key type target &allow-other-keys)
  "Replace the inserted TARGET with the \"real\" candidate, keeping tofu.
This function only does the replacement for the multi-category TYPE."
   (when (eq type 'multi-category) ; unrefined, it must be from default action
    (delete-minibuffer-contents)
    (insert (cdr (get-text-property 0 'multi-category target)))
    (insert (aref target (1- (length target))))))

(push 'embark--multi-category-real-candidate
      (alist-get :always embark-target-injection-hooks))
```

**Comment by minad** [comment]
Sounds good. But I somehow dislike that we have both a multi category transformer and this target injection hook. Is there a better way? Maybe really transforming the original candidate?

**Comment by oantolin** [comment]
I think that's the best solution without modifying `embark--act`. The issue is that here the default action wants one transformation and all other actions want a different transformation. Transformers don't know what action is going to use their result or what the desired transformed type is, so they can only do one of those two transformations. The current strategy is that the transformer for `multi-category` does the non-default-action transformation. Embark keeps the orginal untransformed candidate around in case the user picks the default action, and in that case uses the original candidate. 

This of course implements only the identity transformation for the default action, and now we want a different one. We could, for example, add a second variable of transformers used exclusively for default actions and put the above function there. But I feel that transformations just for default actions have only come up in this example for the first time, so the ad hoc injection hook seems like a better solution for now. If we have more examples later we can always add an `embark-default-action-transformers-alist` variable.

**Comment by minad** [comment]
Why not change how the transformer operates? Just give the transformer more responsibility. It should return both a transformed and the (transformed) original candidate.

**Comment by oantolin** [comment]
That's definitely possible. I guess it could be done in a backwards compatible way. If it returns a `(type . target)` cons, you keep the original untransformed; but it can also return a `(type target new-original)` list. That way people don't need to update their transformers.

**Comment by minad** [comment]
Yes. Maybe that would be better.

**Comment by minad** [comment]
Okay, @oantolin I added support for non-existing tofued candidates. See https://github.com/minad/consult/commit/f628806a7fe6fe509b1c4b808aa740d01dd6a895.

**Comment by oantolin** [comment]
Good, I'll expand the meaning of transformers.

**Comment by minad** [comment]
Maybe we should take a different approach. The problem I am seeing is that these non-existing tofu'ed candidates somehow violate the assumptions of the sources which don't expect that their action is called with a non-existing candidate. Maybe I should solve the issue on a different level. I could simply modify the previewed buffers such that they are not associated with the files anymore. Then the problem should go away. Also we don't require the weird additional treatment of the tofus then.

**Comment by oantolin** [comment]
Oh, OK. I'm done making the change in embark (untested so far), but I can put that in a branch somewhere, in case we do go with this approach after all. Your idea about not associating previewed buffers with the files sounds good. The file is reopened anyway if you switch to it in the end, right? It doesn't somehow reuse the preview buffer?

**Comment by minad** [comment]
> Oh, OK. I'm done making the change in embark (untested so far), but I can put that in a branch somewhere, in case we do go with this approach after all. 

Okay, I will try the approach where I disassociate the preview buffer from the file. If this works I would go with that since it is a more localized fix.

> The file is reopened anyway if you switch to it in the end, right? It doesn't somehow reuse the preview buffer?

Yes, the buffer is killed and recreated entirely to ensure proper initialization. See 

https://github.com/minad/consult/blob/8dbf6b3e0ccab93107cef320bca732ba858e81c1/consult.el#L1173-L1191

**Comment by minad** [comment]
Hmm, but the recursive editing and embarking afterwards on the same file candidate will trigger the bug.

**Comment by minad** [comment]
I am afraid we have to go with the ugly fix. At least it is already finished... :sweat_smile:

**Comment by oantolin** [comment]
> The problem I am seeing is that these non-existing tofu'ed candidates somehow violate the assumptions of the sources which don't expect that their action is called with a non-existing candidate.

I thought that's what the `:new` key you proposed is for. In the case of a file, that should just be `find-file` and that should also solve this C-. RET issue, no?

**Comment by oantolin** [comment]
Or maybe I misunderstood the problem.

**Comment by minad** [comment]
The problem is actually this: the way we call consult-buffer via embark with the "actual-candidateTOFU" can cause that consult--multi-lookup doesn't find the candidate in the candidates list. Then it will just use "actual-candidate" as candidate string and derive the source from TOFU. Unfortunately actual-candidate does not have text properties, but the consult--multi API guarantees the preservation of text properties. We have to think of a better approach. 😢

**Comment by minad** [comment]
I will revert the commit in consult and think of a better fix.

**Comment by minad** [comment]
I fixed this in https://github.com/minad/consult/commit/e5f4f5cde390d7f5aaa6e4558d7cf7755aec0e54. The fix is quite complicated but hopefully the right approach. No changes in Embark are needed.
