### ISSUE TITLE
embark.texi should use @dircategory Emacs misc features

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#491]
embark.texi should use:

    @dircategory Emacs misc features

instead of:

    @dircategory Emacs

to put its manual below Emacs and Elisp in the Info directory listing.

See [this message in emacs bug 54961](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=54961#26)

**Comment by hmelman** [comment]
Thanks.  It's the same for Orderless, Vertico, and Corfu.  Should I open separate bugs?

**Comment by oantolin** [comment]
I'll take care of Orderless, of course. @minad, would you mind changing this in Vertico and Corfu?

**Comment by minad** [comment]
Sure. This affects a few of my packages I guess?

**Comment by oantolin** [comment]
Probably all the ones that do have info manuals, @minad! 😛

**Comment by oantolin** [comment]
Wow, I have all of these manuals above Emacs: AUCTeX, preview-latex, Corfu, Elpher, Embark, Ghub, Icomplete-vertical, Ivy, Magit, Magit-Section, MCT, Modus Themes, Orderless, Dash, SLY, Transient, use-package, Vertico, With-Editor

**Comment by oantolin** [comment]
I never noticed because I don't read the main info directory, I just press `m` and use completion.

**Comment by oantolin** [comment]
Why on Earth do I have Dash installed? People like that package too much.

**Comment by oantolin** [comment]
I knew there was no consult info manual, but there's no osm manual either, @minad?

**Comment by hmelman** [comment]
> Why on Earth do I have Dash installed? People like that package too much.

I agree, I don't get it.

**Comment by minad** [comment]
> I knew there was no consult info manual, but there's no osm manual either, @minad?

I don't know why. It is either (M)ELPA's responsibility to generate an info manual out of the org file.

**Comment by minad** [comment]
I updated all my packages.
