### ISSUE TITLE
the buffer name after embark-export is too long ,it is not friendly for tab-line-mode user 

### ISSUE THREAD

**Issue by jixiuf** [oantolin/embark#492]
https://github.com/oantolin/embark/blob/master/embark.el#L2995
Can you add an option to replace  `embark--descriptive-buffer-name` 

too many buffer  like  
![image](https://user-images.githubusercontent.com/461743/163944698-a05b66ee-e5db-4cd4-bd22-89e969348b11.png)

![image](https://user-images.githubusercontent.com/461743/163944158-4224f8c9-724e-4fed-a6aa-7ee3d91cfe7f.png)

**Comment by jixiuf** [comment]
never mind ,I just figure out 
`  (add-hook 'embark-after-export-hook #'(lambda()(rename-buffer "*grep*" t)))
`

**Comment by minad** [comment]
FWIW I agree with the criticism stated here. Using a slightly shorter buffer name would be nice, see https://github.com/oantolin/embark/issues/494#issuecomment-1107475766.

**Comment by oantolin** [comment]
I'm very much open to suggestions! I do want to include the originating command and input, but everything else seems unnecessary. Maybe we can also keep the word `collect` or export`, but maybe even that is not needed. How about changing `*Embark Export: M-x consult-line RET what I searched for*` to just `*consult-line: what I searched for*`?

**Comment by minad** [comment]
I would like `*Embark Export: consult-line - what I searched for*`. It will still be long but all the information should be there. I only argue against the `M-x` and `RET` :)

If a user wants an agressively shortened name like only `*grep*` it can be easily done using a hook as in https://github.com/oantolin/embark/issues/492#issuecomment-1102173099. On the other hand we could also consider adding an `embark-export-buffer-format` variable which will be used via `format-spec`.

**Comment by oantolin** [comment]
Sure, that shortening is completely uncontroversial. I'll do it right away and we can keep discussing shortening further or making this configurable.

**Comment by oantolin** [comment]
How about `*mode: command input*` where mode is the major mode (without `-mode`)? So you'd get stuff like `*occur: consult-line search terms*`. Using the mode is more informative than saying "collect" or "export". And the hyphen between the command and the input can be just a space.

**Comment by minad** [comment]
I would prefer if both "Embark" and "Export" or "Collect" are in the name. But well, if it is an export buffer it would also work to hav "Embark Dired", "Embark Occur" etc. But I definitely like to have "Embark" in the name since this helps with filtering.

**Comment by oantolin** [comment]
Haha. I see how I what I wrote could be misunderstood! I did not mean just the input I meant first the command name, then a space, then the command input. Compared to your proposal I was just eliminating the hyphen.

If having "Embark" in the name helps with filtering we can keep it. I like your suggestion of replacing the word "Export" with the major mode. I think that might also be something one wants to filter on.

**Comment by hmelman** [comment]
I don't think I care about the result but I have two comments.  
1. If a user has more than one export, maybe two greps, they may want the unique part first so that if it's truncated the can tell the difference between the buffers.
2. The general solution is of course to create a format string function that can let the user customize it easily.  Gnus has a lot of these, probably too many, but they come in handy at times. :)  Maybe `%c` for command and `%i` for input?
