### ISSUE TITLE
C-.

### ISSUE THREAD

**Issue by astoff** [oantolin/embark#493]
In Gnome (at least as shipped by Fedora, which should be very standard), the key `C-.` is taken by Ibus for Emoji entry. Unfortunately, it's not obvious how to change or disable this. The keyboard shortcuts section of the settings app doesn't provide this possibility.

Perhaps it should be mentioned in the readme that one can free up `C-.` by running `ibus-setup`, as suggested [here](https://www.reddit.com/r/gnome/comments/tqx0lx/how_to_disable_or_reassign_ctrl_shortcut/)?

(Apropos of mnemonics, I use `M-c` for `embark-act` since it's a weird version of `C-c`.)

**Comment by minad** [comment]
Yay, emojis!

**Comment by oantolin** [comment]
> Perhaps it should be mentioned in the readme that one can free up C-. by running ibus-setup, as suggested here?

Sure, we can mention that.

> Apropos of mnemonics, I use M-c for embark-act since it's a weird version of C-c.

I use `M-c` for `capitalize-dwim`, and I actually use it very often (probably my most common type of typo is DOuble CApitalization). Do you not use `capitalize-word` or `capitalize-dwim`? If you do, what do you bind it to?

**Comment by astoff** [comment]
> Do you not use capitalize-word or capitalize-dwim? If you do, what do you bind it to?

Eh, not really. But I don't just lose it.

I bind `M-u` to `transient-caps-lock-mode`, which is like `caps-lock-mode` but it goes away after you type something that's not a word/symbol constituent. But it also doubles as a transient keymap, so `M-u M-u ...` (n times) is upcase (n - 1 times), `M-u M-c` is capitalize, and `M-u M-l` is downcase. I use `M-l` for avy.

This transient caps mode is not in the caps-lock package. I actually never got it assimilated into muscle memory, so I'm not so convinced it's useful and therefore I never pitched the idea. But from your discussions I feel like you guys have a much fancier workflow than mine :-P.

To fix your double capitalization typo you need to press `M-- M-u`, right? At that point, I just hit `M-DEL` and start over. After 2 to 5 attempts, I usually am able to fix the typo.

**Comment by oantolin** [comment]
I find `M-b M-c` easier to type than `M-- M-c`, so I often use that to fix a DOuble capital. (You said `M-u` but that uppercases every letter, not just the first ---in the default key bindings.) But I just realized I should make a single `M-c` capitalize the previous word if I am at a word ending. I already do the same for marking words, it's silly I don't do it for case change...

**Comment by minad** [comment]
I must say that I really dislike the default emoji key binding. I think `C-x 8-)` makes a lot more sense. Maybe you want to recommend that too? 8-)
