### ISSUE TITLE
Configurable outline titles?

### ISSUE THREAD

**Issue by minad** [oantolin/embark#497]
See `completions-group-format` (Emacs 28) and `vertico-group-format`. Do we also want to make this configurable or do we want a style which is consistent with Vertico and default completion? I also like the bullet headlines you have now, but overall I prefer a consistent style.

**Comment by oantolin** [comment]
I'm not against making it configurable. Embark has so many user options that I always start with non-configurability first to see if an option is really necessary.

**Comment by minad** [comment]
Of course, then we could maybe use the same style as I did in Vertico? Or do you dislike that?

**Comment by oantolin** [comment]
No, that style would be fine too, I didn't go with it for two reasons:

- The line would only extend through the candidate column not the annotation, but that's fine, since I think we only use group-function for candidates that happen to be very long anyway.
- I wanted to be honest about using outline-minor-mode so I wanted the outline character to be visible.

If we did use Vertico's style, would you suggest using a number of spaces as `outline-regexp` or adding an invisible character to use for the outline?

**Comment by minad** [comment]
> If we did use Vertico's style, would you suggest using a number of spaces as outline-regexp or adding an invisible character to use for the outline?

I would probably add an invisible character. A tofu, yey! In case you make this configurable I would introduce a pair format and regexp or alternatively only use a format string always prefix it behind the scene with a tofu.

**Comment by oantolin** [comment]
I think I'd go with always prefixing with tofu rather than making the regexp configurable.

Do you think the title format it should be configurable? I blindly copied the configurability in icomplete-vertical, but do you think people ever change the default in Vertico?

**Comment by oantolin** [comment]
Oh, I had somehow missed that Emacs 28 has it configurable too. I guess that makes configurability standard for this.

**Comment by minad** [comment]
Configurable all the thing! :tada:

**Comment by oantolin** [comment]
> Configurable all the things! 🎉

 I agree in principle but it seems like overkill in this particular case. Maybe Vertico, Emacs and Icomplete-vertical should get ri of this option instead.

**Comment by minad** [comment]
Yes, but Vertico got it before default completion. It is hard to tell which configuration options of the default completion UI belong to the actual UI and which belong more to the backend functionality. For example completion-ignore-case or completion-ignored-extensions belongs imo more to the backend but some others belong purely to the UI, e.g., completion-show-help.

**Comment by oantolin** [comment]
> Yes, but Vertico got it before default completion.

I know, that's why I listed Vertico first in the above comment.

**Comment by oantolin** [comment]
Mmh. With the lines (which do extend all the way to the right, by the way, I was wrong about that above) I don't think I need the `:height 1.1` anymore.
