### ISSUE TITLE
Maybe a customize group for embark help

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#505]
I was curious about an indicator setting and did `customize-group` for embark and find there are a lot of indicator settings interspersed with other settings. I think they should be in their own defgroup.  Maybe it should be called embark-help and could include embark-help-key or maybe it's just embark-indicators.

**Comment by oantolin** [comment]
I think I'd prefer the help key option to stay in the group of the prompter and keymap prompter key options. But definitely a group for the indicators makes sense.

**Comment by oantolin** [comment]
OK, done.
