### ISSUE TITLE
blacklist/whitelist to replace embark-confirm-act-all 

### ISSUE THREAD

**Issue by theottm** [oantolin/embark#508]
Hi,

Among the actions I use on multiple candidates some are safe (like killing buffers), some are dangerous (like deleting files). For the first kind I like it when `embark-confirm-act-all ` is set to nil so I can be quick, for the other kind I don't trust myself, so I end up keeping `embark-confirm-act-all ` to t to protect myself from my silliness.
So I was thinking it would be nice to be able to use a blacklist or whitelist of commands for which we ask the user or not. Not sure how difficult this could take to implement. You sure can estimate this better than me. If it's not too involved I could come up with a MR. 

Anyway thanks for the package, it rocks!

**Comment by oantolin** [comment]
You can get the behavior you want by setting `embark-confirm-act-all` to nil, and putting `embark--confirm` on the pre-action hook for the individual commands you want confirmed. (By default you do get asked to confirm both buffer killing and file deletion.) See the docstring for `embark-confirm-act-all` and checkout the variable `embark-pre-action-hooks`.

**Comment by theottm** [comment]
Great this is exactly what I was looking for! Thanks
