### ISSUE TITLE
Can we have a version bump for ELPA and MELPA Stable?

### ISSUE THREAD

**Issue by sthesing** [oantolin/embark#510]
It would be very helpful to users and downstream projects that prefer to depend on versioned releases.

**Comment by oantolin** [comment]
Sure, Embark seems pretty stable at the moment. We're actually gearing up to tag 1.0 releases for a bunch of packages: Vertico, Corfu, Consult, Cape, Embark, Orderless and possibly other like Affe and Tempel. But bumping now seems warranted to have this be sort of the 1.0 pre-release.

**Comment by oantolin** [comment]
Done.

**Comment by minad** [comment]
Shall we also publish the versions 1.0 of the packages Marginalia and Orderless from the oantoliverse in the next days?

(I will wait a bit longer with Vertico, Corfu and Consult. The minadverse rolls a bit slower, with some hiccups here and there...)

**Comment by minad** [comment]
Your Embark 0.17 changelog reminds me - we should probably drop the obsolete variables and functions before tagging 1.0. So it is good to have this or more prereleases.

**Comment by oantolin** [comment]
The way I was using the term "minadverse" it comprises both your packages and mine, @minad: it's your 'verse, I'm just helping out. 😛

I forgot about Marginalia in the above list. That one is ready for 1.0, I'd say. Orderless is definitely ready: it has felt complete for a while now.

One thing I'm not sure about for embark is what to do about embark-org. It's not finished, but it's already useful. Should embark's 1.0 include it or not? (Also, related to embark-org: I need to figure out how to include it in the MELPA and GNU ELPA embark packages ---I think for MELPA I just need to submit a PR to the recipe, for GNU ELPA I know step 1 is to remove the `.elpaignore` file, but I have no idea what step 2 is.)

**Comment by oantolin** [comment]
> we should probably drop the obsolete variables and functions before tagging 1.0.

Yes.

**Comment by minad** [comment]
Not sure if 1.0 should include embark-org. But to include it you don't have to do much. Remove the elpaignore and adjust the MELPA embark recipe. I think updating the MELPA recipe should come first such that people get convenient access to embark-org.

**Comment by oantolin** [comment]
I'm confused about GNU ELPA: how does it know that embark.el and embark-consult.el each become their own package? If remove the `.elpaignore`, would `embark-org.el` become its own package? Is there some manual step of writing a recipe that Stefan did for me that I am unaware of?

**Comment by minad** [comment]
Why do you want to make this a separate package? I would just distribute it as part of embark as I do with consult, consult-org, consult-flymake and so on.

**Comment by oantolin** [comment]
I do want to distribute it with embark! But somehow GNU ELPA is distributing embark.el and embark-consult.el separately (even thought they live in the same repo) and I am worried that once I remove the `.elpaignore` file, GNu ELPA might start distributing `embark.org.el` separately too!

**Comment by minad** [comment]
See my comment here: https://github.com/oantolin/embark/issues/502#issuecomment-1120249350

**Comment by oantolin** [comment]
Thanks!

**Comment by sthesing** [comment]
Thank you!

**Comment by tmtvl** [comment]
@oantolin would it be possible to give embark-consult.el a version bump as well? Without it I'm getting an error:

> Symbol’s value as variable is void: embark-collect-initial-view-alist

That has been fixed already, but the version header wasn't updated.

**Comment by oantolin** [comment]
Oh, sorry! Will do.
