### ISSUE TITLE
embark-act: When excute function org-set-tags-command not as expected.

### ISSUE THREAD

**Issue by kevinfis** [oantolin/embark#514]
Hi,
Suppose i have a org file:
 #+FILETAGS: tag1 tag2 tag3
 * Test

after added a key "t" and eval done:
(embark-define-keymap embark-heading-map
  "Keymap for Embark heading actions."
  ("t" 'org-set-tags-command)  ;; add this function for  C-c C-q  in org mode
  )

then i execute embark-act in headline the Test,
i expected if i enter key "t" would like as i enter C-c C-q,
it will show a Mini-buffer, let me choose tags such as tag2,
after done it becomes :
 * Test  :tag2:

but 'embark-act' make it become:
 * Test  :Test:
_the headline name become tag to set to headline._

because other function ( such as : ">"  'outline-demote) can handle headline well,
so, is it possible made 'org-set-tags-command also well as C-c C-q do?

**Comment by oantolin** [comment]
All you need to do is to tell Embark that when using `org-set-tags-command` you do not want Embark to type the target (the heading text) at the minibuffer prompt for you. This is called ignoring the target and you configure it as follows:

```elisp
(push (alist-get 'org-set-tags-command embark-target-injection-hooks)
      'embark--ignore-target)
```

**Comment by kevinfis** [comment]
Thanks for your reply.
your hint made me more convenient to reduce memorizing keybinding in Emacs.
  (push 'embark--ignore-target (alist-get 'org-set-tags-command embark-target-injection-hooks))

**Comment by oantolin** [comment]
Oops, sorry for flipping the arguments to `push`! I'm glad you figured out the right way to do it.

**Comment by kevinfis** [comment]
It’s ok.
i found README.org has explained lot of feature,
but i can't understand all and related operation of list and push,
your advice helped me got the section that i do not understand before.
