### ISSUE TITLE
Can't scroll the actions indicator window in terminal

### ISSUE THREAD

**Issue by twlz0ne** [oantolin/embark#515]
# Environment

- macOS 10.13
- iTem2.app / Terminal.app
- Emacs 29.0 / 28.1 / 27.2
- embark 20220527.2228

# Steps to reproduce

1. Start Emacs

```sh
$ emacs -Q --eval "(progn
           (require 'seq)
           (setq user-emacs-directory
                 (car (seq-filter
                       #'file-exists-p
                       (list (format \"~/.emacs.d/%s/\" emacs-version)
                             (format \"~/.emacs.d/%s/\" emacs-major-version)
                             \"~/.emacs.d/\"))))
           (setq package-user-dir (concat user-emacs-directory \"elpa/\"))
           (package-initialize)
           (require 'embark)
           (global-set-key (kbd \"C-c .\") #'embark-act))
         " -nw
```

2. Press `C-x 2` to split window
3. Press `C-x C-f` to find file
4. Press `C-c .` to active embark
5. Press `C-M-v` to scroll actions indicator window

# Actual behavior

1. The actions indicator window had been killed
2. Error message: `embark PCH: (end-of-buffer)`

    If skip the step 2, the error message becomes `embark PCH: (error "There is no other window")`.

# Expected behavior

Scroll the actions indicator window.

**Comment by oantolin** [comment]
Weird! I can't imagine what about this behavior is GUI-specific, but I can reproduce the issue and will look into it.

**Comment by oantolin** [comment]
That was interesting! I won't spoil the answer, it is in the commit message if you're curious.

**Comment by twlz0ne** [comment]
It works. Thanks for the fix and commit message.
