### ISSUE TITLE
Manual: "C-x 8 e e" is unbound

### ISSUE THREAD

**Issue by DamienCassou** [oantolin/embark#516]
The manual says:

> You can select a different key binding for `embark-act` or use `ibus-setup` to change the shortcut for emoji insertion (Emacs uses <kbd>C-x 8 e e</kbd>, in case you want to set the same one system-wide).

Running `emacs -Q` with Emacs 28 doesn't seem to bind anything to <kbd>C-x 8 e</kbd>.

**Comment by minad** [comment]
I think it is Emacs 29.

**Comment by oantolin** [comment]
What is a better fix: removing that parenthetical remark or changing it to say "the current preview of Emacs 29 uses ..."?

**Comment by DamienCassou** [comment]
I think it is better to say that it is in Emacs 29.

**Comment by oantolin** [comment]
Well, that would be a prediction. How about "likely to be in Emacs 29"?

**Comment by DamienCassou** [comment]
Very good!
