### ISSUE TITLE
Working around the absence of embark-around-action-hooks

### ISSUE THREAD

**Issue by DamienCassou** [oantolin/embark#518]
`embark--cd` and `embark--narrow-to-target` have a very similar and, in my opinion, complex implementations. I think these implementations are complex because the code is trying to implement the concept of "around" in a code that is only executed before the command.

I suggest introducing an `embark-around-action-hooks` variable instead. This will not only simplify the implementation of the 2 functions but will also make it simpler for others to have around hooks.

I volunteer for implementing that if you want to.

**Comment by DamienCassou** [comment]
Maybe `embark--confirm` could be moved to the new hooks variable. This would avoid using an exception for what is normal behavior.

**Comment by DamienCassou** [comment]
Would you like a PR?

**Comment by oantolin** [comment]
Hi @DamienCassou! I wrote an around hook implementation in a separate branch called around-hooks. I'd greatly appreciate it if you could test it.

**Comment by DamienCassou** [comment]
I've switched to the new branch and will report any issue.
