### ISSUE TITLE
recentf-list uses abbreviated names now

### ISSUE THREAD

**Issue by minad** [oantolin/embark#519]
See https://github.com/emacs-mirror/emacs/commit/c753e4cb2a2a5998626d48d85071c047cbab6c54

To be safe, we should probably delete both the expanded and the abbreviated filename in `embark-recentf-remove` from both the minibuffer history and the recentf list.

**Comment by oantolin** [comment]
Oh, OK. Removing both versions of the file name seems like the right fix. I'll merge.
