### ISSUE TITLE
ido-find-file by default?

### ISSUE THREAD

**Issue by agenbite** [oantolin/embark#523]
Hi! For some reason, when I call embark on a filename, the default action is "find-file", which in turn calls `ido-find-file`. I really want my selectrum file selection here, and I don't know where to start looking for the culprit. I'm on spacemacs, but the package is configured in a default manner (see [here](https://github.com/syl20bnr/spacemacs/blob/42b6ff3f09021ab4b59dc1a75c1ff75301d90d7e/layers/%2Bcompletion/compleseus/packages.el#L252)). Any help would be appreciated! :)

EDIT: Of course, a solution is to add 
```
  (define-key embark-file-map     (kbd "RET") 'spacemacs/compleseus-find-file)
```
but I wonder why that's not the default behaviour.

**Comment by agenbite** [comment]
I guess this is indeed a spacemacs issue, not embark's. Closing it thus.

**Comment by oantolin** [comment]
It sounds like you had `find-file` remapped to `ido-find-file` without actually wanting to use `ido-find-file`! That's definitely something you should fix in your configuration. The solution you gave of rebinding `RET` in `embark-file-map` seems fine to me. It would also work to remap `find-file` to `spacemacs/compleseus-find-file`, if that's a function you'd prefer using.
