### ISSUE TITLE
embark-collect on consult-ripgrep: cannot visit results

### ISSUE THREAD

**Issue by actondev** [oantolin/embark#524]
Hi!
Not sure if I should post this to consult or here, so.. here I am!

When running `embark-collect` on `consult-ripgrep`, I get the following message
`Error running timer ‘consult--async-after-change’: (buffer-read-only #<buffer *Embark Collect: consult-ripgrep - #defun*<4>`
when trying to visit any result (either by `RET` or mouse click)

- emacs 27.1
- consult 20220712.1046
- embark 0.17

**Comment by oantolin** [comment]
You need the embark-consult package to be able to use embark-collect with consult-ripgrep. Are you also loading that package?

**Comment by actondev** [comment]
Yikes, apologies! Apparently not!
I had
``` emacs-lisp
(use-package embark-consult
  :after (embark consult)
  )
```
as suggested in the readme, but apparently this won't load it, since I'm always deferring

adding `(require 'embark-consult)` to the embark use-package `:config` section did the trick.

Thanks!
