### ISSUE TITLE
embark-export in a vertico find-file (or project-find-file) only works once

### ISSUE THREAD

**Issue by aaronjensen** [oantolin/embark#526]
There are several oddities when using vertico with embark-export for dired. I don't know if these are embark, vertico, or emacs issues /cc @minad 

1. If you quit an export, you can no longer export as usual without vertico reappearing and forcing you to select an entry.
2. If you use wdired in an export and save changes with C-c C-c, vertico opens again, and you must select an entry

## First Repro

```el
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(package-install 'vertico)
(package-install 'embark)
(global-set-key (kbd "C-c C-o") #'embark-export)
(vertico-mode)
```

```
M-x find-file
C-c C-o
q
M-x find-file
C-c C-o
```

What I see when I do that is an error about not being able to open a recursive minibuffer. If I enable those, a recursive vertico opens, and when I quit it, I return to the original. If I select something, it does open the dired buffer.

I'm on Emacs 29, build a few week ago, if that matters.

**Comment by aaronjensen** [comment]
From my limited debugging, it looks like it may be a problem with the way that `dired-noselect` works. It appear to trigger vertico to reopen.

**Comment by minad** [comment]
>  1. If you quit an export, you can no longer export as usual without
>     vertico reappearing and forcing you to select an entry.

I don't see this in my Emacs 28 setup, but maybe I didn't follow your
repro precisely enough. However I observe another problem when pressing
q. See 3. below.

>  2. If you use wdired in an export and save changes with C-c C-c,
>     vertico opens again, and you must select an entry

I observe this too.

3. I observe an additional issue when pressing q in the exported Dired
buffer. q is bound to quit-window. When exporting again from the same
completion session, the old buffer is not displayed again. Furthermore
when I try to open the same buffer as the exported buffer again via
find-file by pressing M-RET it also doesn't open. It seems that the
Embark export somehow interferes with the ability of dired of opening
the same directory again?

**Comment by oantolin** [comment]
Oh, this is weird! I can reproduce it, thanks for the recipe. I'll look into it.

I think the reason I never noticed this is that I usually kill dired buffers when I'm done with them.

**Comment by oantolin** [comment]
I bet I know what it is: the dired buffer is probably reverting itself, and Embark abuses the revert-buffer-function for its "revert-as-rerun" functionality.

**Comment by minad** [comment]
> I bet I know what it is: the dired buffer is probably reverting itself, and Embark abuses the revert-buffer-function for its "revert-as-rerun" functionality.

Makes sense. Maybe Embark should set the revert-function to ignore in all exported buffers and instead remap revert-buffer to its own revert command such that no possible interference can happen (auto reverting etc)?

**Comment by aaronjensen** [comment]
Thank you @oantolin, much appreciated.

**Comment by oantolin** [comment]
I followed @minad's suggestion to leave `revert-buffer-function` alone and added a new `embark--rerun-function` instead. I remapped `revert-buffer` to run `embark-rerun-collect-or-export` so `g` still works as before.

**Comment by oantolin** [comment]
Whoops, forgot to update some docstrings. 😬

**Comment by oantolin** [comment]
Done.

**Comment by aaronjensen** [comment]
I did not know about the `revert-buffer` functionality. I always wondered how to rerun the thing that was embarked, that's great.
