### ISSUE TITLE
Jump to result without closing minibuffer

### ISSUE THREAD

**Issue by mattiasdrp** [oantolin/embark#532]
So, I wanted to have a keybinding that would execute the default action without prompting for the embark possibilities and jump to the result. So far I've managed to have the following working code

```elisp
    (defun embark-default-act-noquit ()
      "Run action but don't quit the minibuffer afterwards."
      (interactive)
      (let* ((embark-quit-after-action nil)
             (target (car (embark--targets)))
             (orig-target (embark--orig-target target))
             (action (embark--default-action
                      (plist-get target :type))))
        (embark--act
         action
         (if (and (eq action embark--command)
                  (not (memq action embark-multitarget-actions)))
             (embark--orig-target target)
           target))))
```

But my issue is that it won't jump to the other window (I tried using better-jumper but couldn't manage to have something working) and if I replace `action` with `'consult--jump` I have an error message:

```
Wrong type argument: number-or-marker-p, #("init.el:7:;; Maintainer: mattiasdrp <https://github.com/mattiasdrp>" 0 7 (consult--grep-file "init.el" face (consult-file)) 8 9 (face (consult-line-number)) 30 33 (face (consult-preview-match)))
```

I know this isn't really an issue with embark but I wondered if I missed something in it that would allow to do it without using a custom function or if you had a better idea for my function.

**Comment by oantolin** [comment]
Please let me know if this does what you want:

```elisp
(defun embark-default-act-noquit ()
  (interactive)
  (let ((embark-quit-after-action nil))
    (embark-dwim)
    (when-let ((win (minibuffer-selected-window)))
      (select-window win))))
```

I'm going to close the issue, because I don't think this requires any changes to Embark, but we can always continue the conversation here.

**Comment by mattiasdrp** [comment]
This works perfectly, thanks!
