### ISSUE TITLE
Put cursor behind `embark-insert`ed item

### ISSUE THREAD

**Issue by Atemu** [oantolin/embark#533]
When I insert an item, I usually want to continue writing after it. `embark-insert` leaves the cursor behind the inserted item however.

Would it be possible to make that behaviour configurable?

**Comment by oantolin** [comment]
Mmh. Maybe it doesn't need to be configurable, maybe point should always be left after the inserted item.

**Comment by oantolin** [comment]
I changed embark-insert to put point after the insertion. Let's leave this unconfigurable for now and see if anyone complains.

**Comment by oantolin** [comment]
I'm liking this so far, leaving point after insertion definitely feels more natural. I should have noticed this a long time ago since I am a heavy user of embark-insert and probably used to almost always move point after the insertion manually!
