### ISSUE TITLE
next-error doesn't use most recently started grep buffer created by embark-export

### ISSUE THREAD

**Issue by cmann** [oantolin/embark#537]
I've run into an unexpected interaction between `next-error` and grep buffers created by using `embark-export` on `consult-grep` minibuffers. I'm not sure if it's a bug in embark, a bug in `next-error` or expected behaviour and I'm just missing something.

Anyways, here's a basic reproduction:

1. Start a grep with `M-x consult-grep`
2. Use `embark-export` to export the results to a grep buffer
3. Using `next-error` in that buffer will jump to the first result as expected
4. Start another grep with `M-x consult-grep`
5. Use `embark-export` again to export the results to another grep buffer
6. Using `next-error` in the new buffer will jump to the second result of the first grep rather than the first result of the second grep

Basically as far as I can tell, `next-error` will only ever use a grep buffer created by `embark-export` if no previous grep/compilation buffer exists. If such a buffer does exist, the only way to get `next-error` to use the new one is via `next-error-select-buffer`. On the other hand, if I create another grep buffer via plain old `M-x grep` then `next-error` starts using that one no problem.

The relevant documentation for `next-error`:

```
C-x ` normally uses the most recently started
compilation, grep, or occur buffer.  It can also operate on any
buffer with output from the M-x compile, M-x grep commands, or,
more generally, on any buffer in Compilation mode or with
Compilation Minor mode enabled, or any buffer in which
‘next-error-function’ is bound to an appropriate function.
To specify use of a particular buffer for error messages, type
C-x ` in that buffer.  You can also use the command
‘next-error-select-buffer’ to select the buffer to use for the subsequent
invocation of ‘next-error’.

Once C-x ` has chosen the buffer for error messages, it
runs ‘next-error-hook’ with ‘run-hooks’, and stays with that buffer
until you use it in some other buffer that uses Compilation mode
or Compilation Minor mode.
```

My `init.el` for reproduction:

```
(use-package general)

(use-package consult)

(use-package embark
  :general
  (minibuffer-local-map
   "C-." 'embark-act
   "M-." 'embark-dwim))

(use-package embark-consult
  :after (embark consult))
```

**Comment by cmann** [comment]
Alrighty, I've tracked down the issue. So `next-error` uses `next-error-find-buffer` to choose the buffer it's going to use. Roughly speaking, that function prioritizes `next-error-last-buffer` (the most recent compilation mode buffer), then the current buffer, then any valid buffer it can find. Now that does seem to conflict with the `next-error` documentation which, at least to me, strongly implies using it in any compilation mode buffer should cause it to switch to that buffer if it's not already using it. But on its own that still doesn't explain why using `next-error` in step 6 didn't use the new buffer because shouldn't it have become `next-error-last-buffer`? The answer to that is the new buffer does not become `next-error-last-buffer` because that only gets updated in `start-compilation` which is invoked by the various grep commands, but is not invoked by `grep-mode` which is what `embark-consult-export-grep` does.

Based on all of that, I think it would make sense for `embark-consult-export-grep` to set `next-error-last-buffer` to the newly created buffer. Would a PR for that be accepted?

**Comment by oantolin** [comment]
Thanks for figuring this out, @cmann. I went ahead and set `next-error-last-buffer` as you suggested.
