### ISSUE TITLE
Can't get the Wikipedia Example to work

### ISSUE THREAD

**Issue by 7uXi** [oantolin/embark#545]
Hi,

I tried the Wikipedia example from the README, but can't get it to run.
Copied the function "my-short-wikipedia-link" to the scratch buffer and evaled it, copied "add-to-list ..." and evaled it. Run embark on "wikipedia:Garry_Kasparov"

Error: "Wrong type argument: stringp, (format "https://en.wikipedia.org/wiki/%s" (match-string 1 str))" after Return (browse-url).

I am not an expert or programmer, so it can be me or my setup and the debugging is over my skill level. Can someone confirm this?

Thank youl and best regards,

Frank

**Comment by oantolin** [comment]
Oh, my god, that's a nasty typo: the code is missing a comma in front of `(format "https://en.wikipedia.org/wiki/%s" ...`. I've now added the comma (see 2422d4e86f24b2b4204f2441f953e8407d011a2e). Thanks for catching this.
