### ISSUE TITLE
wgrep-mode doesn't  work with consult-line export

### ISSUE THREAD

**Issue by agzam** [oantolin/embark#554]
It seems that wgrep-mode is no longer works with buffers exported from `consult-line`. Embark export of `consult--grep` (multiple files) works fine. But `consult-line` (single file) doesn't.

## Repro steps

- Run consult-line with multiple occurrences in any normal, writable file
- Export the results with `embark-export`
- Run `wgrep-change-to-wgrep-mode` 

### Observed

```
Debugger entered--Lisp error: (wrong-type-argument markerp nil)
  occur-after-change-function(1 285 284)
  put-text-property(1 285 read-only t)
  wgrep-prepare-header/footer()
  wgrep-prepare-to-edit()
  wgrep-change-to-wgrep-mode()
  funcall-interactively(wgrep-change-to-wgrep-mode)
  command-execute(wgrep-change-to-wgrep-mode record)
  execute-extended-command(nil "wgrep-change-to-wgrep-mode" nil)
  funcall-interactively(execute-extended-command nil "wgrep-change-to-wgrep-mode" nil)
  command-execute(execute-extended-command)
```

If you run `wgrep-change-to-wgrep-mode` again, it appears to be changing to wgrep-mode, but the export buffer remains read-only.

### Versions

Emacs: 
GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6 (Build 21G115)) of 2022-10-21

Consult: 3226c1a01e0a2a4352b2c885b8f4eb22610d99af
Embark: 3a86e4ba70e2e35c2d833016cd1e5b1fd8d8416d
Emacs-wgrep: f9687c28bbc2e84f87a479b6ce04407bb97cfb23

**Comment by oantolin** [comment]
Export from consult-line does not produce a grep-mode buffer but rather an occur-mode buffer. To edit those use the built-in occur-edit-mode not wgrep. It is bound to `e` in any occur-mode buffer.

**Comment by artemkovalyov** [comment]
You can benefit from this alternative exporter if you still want to use wgrep with consult-line

https://github.com/oantolin/embark/pull/560/files#diff-f584aec8c356d120612b2236de2a31a953f48f69b5ddbfc28d89ab0e4857c615
