### ISSUE TITLE
How to do a project-wide find-and-replace with embark/consult?

### ISSUE THREAD

**Issue by WorldsEndless** [oantolin/embark#555]
Note: this seems to have been discussed in <https://github.com/oantolin/embark/issues/47> , so I must be doing something wrong.

I have successfully run a project-wide search via `consult-git-grep`, and then used embark to `collect` the results into a stable buffer (called **Embark Collect: consult-git-grep - #buffername**). With other tools this is where I would slip into wdiff mode and make changes that go to every changed file, but in my collect buffer I get an error that the file results are read-only. Knowing this is probably a mainstream functionality, what is the correct way to do a project-wide find-and-replace with Embark/Consult? Once I have this figured out, I would be happy to make a PR with some documentation on how to do project-wide find-replace.

**Comment by oantolin** [comment]
You need to have the following packages loaded for this: consult, embark, embark-consult (very recent versions of embark load this for you and complain if you have both consult and embark loaded but don't have embark-consult installed; older version require you to load it yourself) and wgrep. With those, you should be able to use wgrep on the exported buffer. (I'm not familiar  with the wdiff mode you mentioned.)

**Comment by oantolin** [comment]
Please try using wgrep instead of wdiff and let me know how it goes.

**Comment by WorldsEndless** [comment]
Just had this issue again. The "gotcha" was that I was "Collecting" my results instead of "Exporting" them. Only by exporting do they make it to a wgrep-compatible buffer

**Comment by oantolin** [comment]
I'm glad you figured out the issue. As the documentation says:

> When in doubt choosing between exporting and collecting, a good rule of thumb is to always prefer `embark-export` since when an exporter to a special major mode is available for a given type of target, it will be more featureful than an Embark collect buffer, and if no such exporter is configured the `embark-export` command falls back to the generic `embark-collect.`

**Comment by WorldsEndless** [comment]
ah! So it does! In multiple re-reads and searches on the repo, I missed that section. Thanks for putting it out there!
