### ISSUE TITLE
embark-download-url is broken in Emacs 27.1

### ISSUE THREAD

**Issue by astynax** [oantolin/embark#557]
Hi!
I just started to grocking the embark and it feels great! But now I have a problem with my Emacs 27.1 when I'm trying to do `embark-download-url`. Here is a part of the backtrace:
```
Debugger entered--Lisp error: (wrong-number-of-arguments (2 . 2) 3)
  eww-download-callback((:peer...) "https://www.emacswiki.org/images/logo218x38.png" "~/Downloads/"))
  url-http-activate-callback()
  url-http-content-length-after-change-function(742 3886 3144)
  url-http-wait-for-headers-change-function(1 3903 3902)
```
I think that I see a problem. [This call](https://github.com/oantolin/embark/blob/9796324be854889d32b6c7e301c9274e9dd50146/embark.el#L3748) applies `#'eww-download-callback` to the pair of arguments but this callback in my Emacs 27.1 has just one.

When I change this line this way the problem disappears.
```elisp
(url-retrieve url #'eww-download-callback (list url))))
```
Maybe the `dir` isn't necessary at all here? Looks like that `eww-download-callback` already knows how to use `eww-download-dir`.

**Comment by oantolin** [comment]
>  Looks like that `eww-download-callback` already knows how to use `eww-download-dir`.

It doesn't know in more recent versions of Emacs! Here's the version in Emacs 28.2:

```elisp
(defun eww-download-callback (status url dir)
  (unless (plist-get status :error)
    (let* ((obj (url-generic-parse-url url))
           (path (directory-file-name (car (url-path-and-query obj))))
           (file (eww-make-unique-file-name
                  (eww-decode-url-file-name (file-name-nondirectory path))
                  dir)))
      (goto-char (point-min))
      (re-search-forward "\r?\n\r?\n")
      (let ((coding-system-for-write 'no-conversion))
        (write-region (point) (point-max) file))
      (message "Saved %s" file))))
```

Let me look at the source for Emacs 27.1 and figure out to do something that works in both versions.

**Comment by oantolin** [comment]
OK, I just use `func-arity` to figure out how many arguments I'm supposed to give `eww-download-callback`. (I seemed to recall wanting to use `func-arity` before and deciding not to since it was too new, but I just looked it up and it was added in Emacs 26, so that must have happened back when Embark targeted Emacs 25.3!)
