### ISSUE TITLE
General "perform action in other window" action

### ISSUE THREAD

**Issue by dschrempf** [oantolin/embark#559]
Hi!

I am trying to write a general embark action that runs the action usually bound to `RET` but in another window (usually those functions would be called `function-other-window`). For example, in the `embark-file-map`, `o` is bound to `find-file-other-window`.

Instead of calling specific functions such as `find-file-other-window`, I am planning to do this using a simple wrapper that first splits the window, changes cursor position to the new window and then runs the action usually run by `RET` on that window. However, I can not find out how `RET` is bound, and how I can access this action. Do you have any ideas?

Thank you!

**Comment by dschrempf** [comment]
Hi @oantolin ! I appreciate your help, but let me know if you do not have the capacity. In this case I try to seek help elsewhere!

**Comment by oantolin** [comment]
Hi, I'm sorry! I have been very occupied with personal issues and have neglected embark a bit the last couple of months. Fortunately your question is easy to answer. The function `embark--default-action` computes what RET should be bound to; basically the rules are: if you are in the minibuffer the default action is the command that opened the minibuffer; if you are in a regular buffer, the default action is whatever RET is bound to in the action keymap for the type of target. You do need to know the type of target for that, which isn't normally available to actions, but you can fake it by making the action not do anything and have all the work happen in an action hook (which do have access to the type).

```elisp
(defun embark-default-action-in-other-window ()
  "Run the default embark action in another window."
  (interactive))

(cl-defun run-default-action-in-other-window
    (&rest rest &key run type &allow-other-keys)
  (let ((default-action (embark--default-action type)))
    (split-window-below)
    (funcall run :action default-action :type type rest)))

(setf (alist-get 'embark-default-action-in-other-window
                 embark-around-action-hooks)
      '(run-default-action-in-other-window))

(define-key embark-general-map "O" #'embark-default-action-in-other-window) ; or whatever key you prefer
```

**Comment by oantolin** [comment]
Please let me know if that works. (I closed the issue because it doesn't require any changes to embark, but we can certainly keep discussing it.)

**Comment by dschrempf** [comment]
Thanks a lot. The solution works perfectly! I only changed the `(split-window-below)` function to a function that splits side by side, and doesn't use more than 2 columns. I actually think this general way could replace the current "per mode" functionality. For example,

- `embark-file-map` has `find-file-other-window` bound to `o`. 
-  `embark-buffer-map` has `switch-to-buffer-other-window` bound to `o`.

These, and possibly others, could be replaced (but they do a bit more than just splitting windows).

**Comment by oantolin** [comment]
I think this action is probably wiki-worthy.

**Comment by oantolin** [comment]
[Wikified for posterity](https://github.com/oantolin/embark/wiki/Additional-Actions#run-the-default-action-in-another-window).
