### ISSUE TITLE
Always execute actions in embark--target-buffer

### ISSUE THREAD

**Issue by minad** [oantolin/embark#56]
As discussed in #52. From what I see now it is not totally trivial and needs some changes to the logic around the transient keymap. But I still would some like to have this since it makes actions standard commands, for example embark-insert-unicode-character would just go away and be replaced by insert-char. I am sure there are more examples.

**Comment by oantolin** [comment]
This change was small but fairly tricky, please, please, test. Fingers crossed.

**Comment by minad** [comment]
Cool, I will try it out soon! 👍

**Comment by minad** [comment]
@oantolin It works well! Thank you!
