### ISSUE TITLE
Additional Org targets and actions

### ISSUE THREAD

**Issue by minad** [oantolin/embark#562]
Hello @oantolin,

in my personal config I have a wrapper command around `embark-dwim` which looks like this:

~~~ elisp
(defun +embark-dwim ()
  "Act at point with Embark or Org."
  (interactive)
  (or
   (if (derived-mode-p 'org-mode)
       (or (ignore-errors (or (org-open-at-point) t))
           (ignore-errors (or (org-ctrl-c-ctrl-c) t)))
     (ignore-errors (or (org-open-at-point-global) t)))
   (when-let (button (get-char-property (point) 'button))
     (if (widgetp button)
         (call-interactively 'widget-button-press)
       (push-button))
     t)
   (when-let* ((cmd (lookup-key
                     (make-composed-keymap
                      (list (get-char-property (point) 'keymap)
                            (get-char-property (point) 'local-map)))
                     "\r"))
               ((functionp cmd)))
     (funcall cmd)
     t)
   (embark-dwim)))
~~~

Now it would be great if I could get rid of the `org-mode` part there. This means we should support all targets which can be opened or acted upon with C-c C-c. I think that would be natural, since C-c C-c and RET usually behave like dwim at point commands. One example are items/checkboxes, which can be toggled. What do you think?

**Comment by oantolin** [comment]
I think it would be great to cover all uses of `C-c C-c` in `embark-dwim`! Let's aim for that.

**Comment by oantolin** [comment]
Hi @minad! I added actions for list items (with default to toggle the checkbox), and for plain lists (with default to repair indentation). Any suggestions about those or suggestions for other targets?

Also, target finders can now return lists of targets, and embark-org uses this to target the entire org lineage at point. I could remove the separate whole-table target finder thanks to this.

**Comment by minad** [comment]
Thanks, for adding these! So far I don't have other suggestions, but I would have to check the source of C-c C-c.

Regarding the multiple targets per finder, I would like to ask you to reconsider or to reevaluate. Personally I don't have a fixed opinion, except that I would be careful. 

The two commits where you made this change don't seem to remove significant amounts of code. So objectively Embark doesn't seem to get simpler thanks to that. However there are at least two downsides: The user loses control over the target ordering. I know that we usually go from small to large, but users may want to change this in some special cases. The second downside is worse imho, since we lose a bit of conceptual clarity. 

The question is also if there are other places where one would want to use this. Org is kind of a natural candidate since it gives you access to the lineage of the ast. Maybe the same can be said about the upcoming treesitter. In all scenarios where we query an ast locally we get this scenario. So it could be worth it to make this generalization. But so far I don't see it yet. Probably I wouldn't have made the change for Org only.

Anyway these are just some thoughts in the hope of avoiding overeager generalization. But maybe it is the totally right thing to do. Do you have some more thoughts?

**Comment by oantolin** [comment]
Looking at the source code of `org-ctrl-c-ctrl-c` is a good idea, I'll do that.

I look at the multi-valued target finder extension from the opposite point of view: it hardly added any complexity but let me implement the org target finders cleanly. The alternative would have been, as [@jakanakaevangeli suggested here](https://github.com/oantolin/embark/issues/502#issuecomment-1134920591), to have a fixed number of target finders for the element, its parent, its grandparent, etc. I think 3 would have been enough for me, but fixing the limit at 3 would have felt hackier. By the way, you seemed to [like the suggestion back then](https://github.com/oantolin/embark/issues/502#issuecomment-1134928903), and I still agree with everything you said there.

Also, I haven't done it yet, but I plan to make it so Emacs Lisp symbols which are both functions and symbols get reported as both.

**Comment by oantolin** [comment]
I've changed the identifier target finder so that it reports all applicable types. I also fixed it so `pp-eval-expression` only allows editing and wraps the target in parenthesis when the symbol was targeted as a function (it used to do this whenever the symbol was bound as a function, even if you got it from, say, `describe-variable`.)

I think between Org and Emacs Lisp symbols the multi-valued target finder extension pulls its own (small) weight.

**Comment by oantolin** [comment]
I added an action keymap for org headings to embark-org. I decided that the default action would be to toggle todo status. In Org what C-c C-c does on a heading is let you add or remove tags, which I don't think is as commonly needed as changing the todo status, is it? 28e1be702dd9ad96bff8d4fa580816f412d8212b

**Comment by oantolin** [comment]
What additional Org actions might we want here? If the goal is to have embark-dwim subsume org-ctrl-c-ctrl-c, there are a bunch of other targets we need, such as statistics cookies (the default action being to update them). Some of its functions don't seem easy to include in embark-dwim to me, like "if there are highlights, remove them", unless I guess, we only trigger that when on top of a highlight.

I don't really like adding a target if there is only one sensible action. I think for statistics cookies the only org built-in is `org-update-statistics-cookies`; but I could write a function to toggle the cookie between a fraction and a percentage, maybe.

**Comment by alphapapa** [comment]
This idea has a lot of potential.  One action I don't see that would be useful is to store a link to the heading at point with `org-store-link`.

**Comment by oantolin** [comment]
Great idea, @alphapapa! I'll definitely add that. Any suggestion for a key binding for org-store-link? `l` is currently bound to `org-metaleft` and `s`  shows the entire subtree; `l` comes from org speed keys, `s` comes from outline mode, but I am open to changing them.

**Comment by oantolin** [comment]
I bound `org-store-link` to `L`, which I think is probably reasonable (it shadows `embark-live`, but that's OK). I am open to a major restructuring of the bindings in `embark-heading-map` and `embark-org-heading-map` if anyone has a better scheme.

**Comment by minad** [comment]
I think this rather generic issue can be closed. If more scenarios come up, we can open new issues.

**Comment by oantolin** [comment]
Sure. With the recent addition of bindings for `org-{set,delete}-property` to `embark-org-heading-map`, I don't think I've needed any action that isn't already bound.

**Comment by oantolin** [comment]
And I just added a bunch more actions to table cells... 🙄
