### ISSUE TITLE
action for symlinking multiple files 

### ISSUE THREAD

**Issue by dinojr** [oantolin/embark#569]
I often need to symlink several files from one directory to another. So far I drop from vertico to a dired buffer, mark them and use dired-do-symlink. It would be very convenient to be able to do the same from an embark collect buffer.

**Comment by oantolin** [comment]
You can easily add an action like that to your own configuration:

```elisp

(defun symlink-multiple (files)
  "Prompt for a directory and symlink FILES into it.
Asks for confirmation before overwriting existing files in the
directory."
  (let ((directory (read-directory-name "Make links in directory: ")))
    (dolist (file files)
      (make-symbolic-link file directory 1))))

(add-to-list 'embark-multitarget-actions #'symlink-multiple)

(define-key embark-file-map "L" #'symlink-multiple)
```
The key point for embark's perspective is that you register the action as being multitarget. (If you don't then you'd get prompted for a directory separately for each file!)

**Comment by dinojr** [comment]
Omar Antolín Camarena ***@***.***> writes:

> You can easily add an action like that to your own configuration:
>
> ```elisp
>
> (defun symlink-multiple (files)
>   "Prompt for a directory and symlink FILES into it.
> Asks for confirmation before overwriting existing files in the
> directory."
>   (let ((directory (read-directory-name "Make links in directory: ")))
>     (dolist (file files)
>       (make-symbolic-link file directory 1))))
>
> (add-to-list 'embark-multitarget-actions #'symlink-multiple)
>
> (define-key embark-file-map "L" #'symlink-multiple)
> ```
>
> The key point for embark's perspective is that you register the action
> as being multitarget. (If you don't then you'd get prompted for a
> directory separately for each file!)

Thanks, I'd missed the multitarget system.

-- 
Julien Cubizolles
