### ISSUE TITLE
undefined function vertico--update perhaps renamed to vertico--update-candidates?

### ISSUE THREAD

**Issue by Inc0n** [oantolin/embark#570]
It seems `vertico--update` has been renamed to `vertico--update-candidates`? 
This issue is somewhat confusing to me because I could not pin down the commit in which vertico made this change, my search went to as far as https://github.com/minad/vertico/commit/1bd5438da9c661e2df5e9516f36d9cbc6d100a34.

My setup
---------

vertico version: `0.27`
embark version: `20221208.1524` or commit: `f12955c7ac8bebe762cee30f89c64be20b672ce2`
Emacs version: 
`GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin21.4.0, NS appkit-2113.40 Version 12.3 (Build 21E230)) of 2022-12-01`

**Comment by minad** [comment]
You should update vertico.

**Comment by Inc0n** [comment]
Right, I see, I did not consider that...
