### ISSUE TITLE
Move embark-file-externally back

### ISSUE THREAD

**Issue by minad** [oantolin/embark#572]
Hello @oantolin,

I recently thought about the scope of Consult and the defining aspects, see https://github.com/minad/consult/issues/6#issuecomment-1358112519. It turns out that there are a few commands in Consult which don't fit there very well and your `consult-file-externally` is among them. ;) Given that the completion aspect of this command is only `(interactive "fOpen externally: ")` I'd like to move this command back to Embark, essentially reverting https://github.com/oantolin/embark/commit/470f64c864bf7437ffd610607d8fdc05ec4c1257. 

I consider this command a classical action, the bulk of the code is not the completion but the action on the candidate. We've added more and more commands to Embark which work great as actions, but which you wouldn't usually bind to a key at the toplevel. It seems to me that `embark-open-externally` belongs to the same class of commands. Also this would be useful for the decoupling of the libraries and simplification of the documentation.

Then there is a small issue I'd like to point out regarding `xdg-open`. The process will be killed when Emacs is killed or restarted. It seems better if we detach the process from Emacs via disown.

~~~ elisp
(call-process-shell-command "(xdg-open ...) & disown" nil 0)
~~~

What do you think?

**Comment by minad** [comment]
My naive first reaction two years ago to `consult-file-externally`: https://github.com/minad/consult/issues/6#issuecomment-739551587 ;)

**Comment by oantolin** [comment]
Sure, the consult command doesn't do anything really consulty like previews or define narrowing categories. We can keep it here instead.

**Comment by oantolin** [comment]
About disowning the process I don't really have an opinion either way: I'm quite used to the processes launched from Emacs being child processes, so I don't mind them dying when Emacs does, but I also wouldn't mind disowning them. I will point out that to my knowledge no-one ever requested that behavior over on the consult repo.

**Comment by minad** [comment]
🖐️ I would like disowning!

**Comment by minad** [comment]
Actually I have my own small library in my config which I use to launch external stuff. It is not sophisticated at all (nothing like detached.el) but at least it does disown.

**Comment by oantolin** [comment]
I'm on Windows right now, but will tweak the command to disown on Linux when I'm on my other computer. I just tested here and on Windows the behavior is as if the child process were disowned: when you close Emacs the external process stays alive. So I guess it'll be good to make the behavior more uniform across OSes. (I have no idea what happens on macos, and trust that this command works there.)

**Comment by hmelman** [comment]
> (I have no idea what happens on macos, and trust that this command works there.)

I used it to open a .png in Preview.app and quit emacs and Preview was still running (as I would expect).

**Comment by oantolin** [comment]
Thanks, @hmelman! That means Linux is the odd man out, let's disown our children to increase harmony.
