### ISSUE TITLE
I cannot push to the embark.wiki via git

### ISSUE THREAD

**Issue by minad** [oantolin/embark#576]
Is there some permission problem? I can edit via the web interface though, which is not convenient.

**Comment by oantolin** [comment]
I think I've only ever edited the wiki via the web interface. I'll poke around the setting to see if I disabled git somehow but it's certainly not something I did on purpose.

**Comment by oantolin** [comment]
I don't see anything in the settings that sounds like it would keep from pushing to the wiki. I'll try to edit the wiki that way myself in a little while. I also found this [question on StackExchange](https://stackoverflow.com/questions/47861701/how-to-push-wiki-to-github) that says using Large File Storage doesn't work with GitHub wikis.

**Comment by minad** [comment]
Hmm, maybe only the owner of the wiki can push via git. I don't know.

**Comment by oantolin** [comment]
Oh, what did you want to update about the generator?

**Comment by minad** [comment]
It was broken, you can inspect the diff.

**Comment by oantolin** [comment]
Oh, right! Thanks for fixing that! I obviously keep forgetting to keep the default actions wiki page up to date. That must have been broken for quite a while.

Funnily, the diff was pretty useless: the whitespace differs on every line so the diff is a huge deletion followed by a huge insertion.

**Comment by oantolin** [comment]
Thanks for updating the wiki! I still haven't tested updating through git but if it does work for me, as owner of the wiki, I'll defintiely run the generator more often.

**Comment by minad** [comment]
On 1/2/23 16:53, Omar Antolín Camarena wrote:
> Oh, right! Thanks for fixing that! I obviously keep forgetting to keep
> the default actions wiki page up to date. That must have been broken for
> quite a while.
> 
> Funnily, the diff was pretty useless: the whitespace differs on every
> line so the diff is a huge deletion followed by a huge insertion.

Oh yes, but you can use git-diff --word-diff. I think the github web UI
also allows you to ignore whitespace changes.
