### ISSUE TITLE
Request: allow keymap values in embark-keymap-alist in addition to symbols

### ISSUE THREAD

**Issue by jinnovation** [oantolin/embark#578]
Currently `embark-keymap-alist` requires that values be symbols for which the values are keymaps.

For my use case, I'd like to have arbitrarily many keymaps stored in an alist that I register in one fell swoop, like so:
```emacs-lisp
(defvar my-keymaps '((foo . (make-sparse-keymap))
                     (bar . (make-sparse-keymap)))

(dolist (entry my-keymaps)
  (add-to-list 'embark-keymap-alist `(,(car entry) . ,(make-composed-keymap (cadr entry) embark-general-map))))
```

I admit that it technically would be possible for me to define symbols `foo-keymap`, `bar-keymap`, and so on and pass those into `embark-keymap-alist`. However, this would be cumbersome and result in a lot of boilerplate for what otherwise are not meaningful values to keep in my package's namespace. It would also require some fairly awkward workarounds, as I don't want to reference `embark-general-map` when defining the `my-keymaps` variable -- only when actually adding to `embark-keymap-alist`.

From a cursory glimpse at the references to `embark-keymap-alist`, this doesn't feel like an unreasonable feature request, but let me know if I missed something!

**Comment by oantolin** [comment]
The name of the symbol *is* currently used, at least in the nested mode of the verbose indicator, but we can make up some name like "<Unnamed prefix keymap>", like we already do for anonymous commands.

I'm a little reluctant to add this since customizing the `embark-keymap-alist` variable with actual keymaps rather than symbols is such a poor experience. On the other hand, it would be self-inflicted and who am I to keep people from annoying themselves? 😛

Have you considered just making up a variable name on the spot like this?

```elisp
(defvar my-keymaps '((foo . (make-sparse-keymap))
                     (bar . (make-sparse-keymap))))

(dolist (entry my-keymaps)
  (let ((var (intern (format "my-embark-%s-map") (car entry))))
    (set var (make-composed-keymap (cadr entry) embark-general-map))
    (add-to-list 'embark-keymap-alist `(,(car entry) . ,var))))
```

**Comment by oantolin** [comment]
Well, I already caved on naming once, when someone (maybe @astoff?) wanted anonymous commands as actions. 🤷🏽

**Comment by minad** [comment]
Maybe revert that ;)

**Comment by oantolin** [comment]
> I think you can even generate unique symbols with `make-symbol`

That's right.

**Comment by oantolin** [comment]
> Maybe revert that ;)

That's a slightly different situation in that keymaps are already allowed to contain anonymous commands, and the request was just for Embark to support them. Here the request is about the format of an Embark variable, which Embark can of course control.

**Comment by jinnovation** [comment]
> Have you considered just making up a variable name on the spot like this?

I could certainly do that. 

All good points raised in this thread. Appreciate the discussion.

Feel free to close this as a "will not implement" if you deem appropriate. 👍

**Comment by oantolin** [comment]
OK, then I'll close this as WONTFIX. I also think users of kele.el might appreciate having named keymaps where they can define new actions or change key bindings. Modifying the anonymous keymaps would be a little tricky for users.
