### ISSUE TITLE
Default action key variable

### ISSUE THREAD

**Issue by Cletip** [oantolin/embark#580]
Hey!
I'm having trouble with the "RET" key as a default action. I think you should maybe let the user choose where to place the key. This could be done by : 
- creating a variable to change the key
```
(defvar embark-default-action-key &optional "RET" "default action key")
;; (setq embark-default-action-key "SPC")
```
- change the line 2012 ? (not sure if it works)
`(lookup-key (embark--raw-action-keymap type) (kbd embark-default-action-key))`

**Comment by minad** [comment]
RET was chosen since RET also usually submits the minibuffer input. Therefore it doesn't make much sense to change this except if you also submit the minibuffer input with a different key than RET. This seems related to your issue #579? Maybe such a remapping feature could also be part of a separate package.

**Comment by Cletip** [comment]
I understand. But for me, I don't use the enter key much, and I might prefer to have the "j" key on the home row (in azerty) to keep it ergonomic. 

Yes it can be related to this issue, because the default key would be dependent on the keyboard obviously.

Moreover, we should also define the default key like this in the definitions: 
```
(embark-define-keymap embark-url-map
  "Keymap for Embark url actions."
  (embark-default-action-key browse-url) ;; here
  ("b" browse-url)
  ("d" embark-download-url)
  ("e" eww)
  ("a" eww))
```

Is there a package with remapping feature already?

**Comment by Cletip** [comment]
This issue is I think over. I will create a package gathering this functionality and this one : #579.
