### ISSUE TITLE
Unable to map keys to SPC

### ISSUE THREAD

**Issue by Cletip** [oantolin/embark#582]
Hello. 
I'm just trying to do the following thing: replace the "RET" with "SPC" in the keymap.
So I do the following test: 
modify embark.el with
```
(embark-define-keymap embark-buffer-map
  "Keymap for Embark buffer actions".
  ("SPC" switch-to-buffer) ;; here is the modification
  ("k" kill-buffer)
  ("b" switch-to-buffer)
  ("o" switch-to-buffer-other-window)
  ("z" embark-bury-buffer)
  ("K" embark-kill-buffer-and-window)
  ("r" embark-rename-buffer)
  ("=" ediff-buffers)
  ("|" embark-shell-command-on-buffer)
  ("<" insert-buffer)
  ("$" eshell))

```
Do the "eval-buffer" command.

And nothing changes in the shortcuts. Why ? (RET is always for the "switch-to-buffer" command)

**Comment by oantolin** [comment]
I can't reproduce the problem here, that does bind SPC. In addition RET always gets bound to the default action, which if you are in the minibuffer is the command that you ran to open the minibuffer. Are you sure SPC is not also bound?

**Comment by oantolin** [comment]
Oh, I just noticed you said you used `eval-buffer`! That is not actually supposed to update variables when their declaration changes. Put point in the keymap definition and use `eval-defun` instead.

**Comment by oantolin** [comment]
I'm blanking on a reference that explains that `eval-buffer` behavior, but it must be somewhere in `(info "(elisp)")`.

**Comment by Cletip** [comment]
Sorry, late reply.
If what you say is true, then I have learned something about eval-buffer.

It works perfectly with "eval-defun", I'm sorry I could have sworn I did. Thank you very much.

**Comment by Cletip** [comment]
Strange, because even with "load-file path-to-file.el", that don't work too. Maybe I didn't understand how emacs loads things
