### ISSUE TITLE
Embark-become does not offer any keys

### ISSUE THREAD

**Issue by Cletip** [oantolin/embark#583]
My problem is strange: I use embark-become "correctly". But, no key is available. I can do "C-x C-f", and it works fine. But, when helping with "C-h" after embark-become, no key is available. By the way, this is the only key displayed: "C-h" to call "embark-keymap-help". 
I don't understand why, I tried with a blank configuration. I have the latest version of embark and version 28.1 of emacs. 
Thanks in advance ^^

**Comment by oantolin** [comment]
From within what command were you running `embark-become` when it offered no keys? `embark-become` looks at the `embark-become-keymaps` variable, and searches for the current command in those keymaps, and offers the keybindings in any keymap in which it finds the current command. Maybe you were running a command that you have not added to the relevant keymaps? (The default configuration has a bunch of built-in commands but if you were using some 3rd-party command it won't be listed.)

**Comment by Cletip** [comment]
Sorry for the delay :(
Okay, I understand the problem. I had named a function (A) which called another function (B). And the B function was added in embark-become-keymaps, but not the A. So, embark didn't detect anything, because A wasn't added. 
This is a behaviour I didn't expect, but your message helped me to clarify this problem. Thank you! (maybe make a precision in the documentation ?)

**Comment by oantolin** [comment]
Oh, I see, the user command that you ran directly is the one that needs to be added to the embark keymaps. Any functions that that command calls are just an implementation detail of how that command is defined, those are not searched for (and Embark actually doesn't have any way to know what other functions your command may have called).

**Comment by Cletip** [comment]
Yes, that's exactly what it was ! Thanks you very much ^^
