### ISSUE TITLE
consult-man and consult-info default action overrides

### ISSUE THREAD

**Issue by minad** [oantolin/embark#584]
The asynchronous commands have the usual problem that the default action does not work. The commands consult-man and consult-info miss an override (for the general category). Is there a possibility to solve the problem in a more general way?

**Comment by minad** [comment]
For `consult-man`:

~~~ elisp
(setf (alist-get 'consult-man embark-default-action-overrides)
      #'embark-consult-man)

(defun embark-consult-man (cand)
  (man (get-text-property 0 'consult-man cand)))
~~~

**Comment by oantolin** [comment]
Mmh. Maybe that's a remnant of an earlier system? We certainly want to strip tofus and the like for most actions that deal with the text of the target, like saving on the kill-ring. For the default action what we really need are the text properties with extra location information. As long as those are not removed the default action could use the stripped candidate.

**Comment by oantolin** [comment]
Oh, right in some cases there is no default action override, we just use the existing command as is in which case we might need an exact match to a candidate, so we use the original target verbatim for the default action.

**Comment by oantolin** [comment]
I think. 😃 I'm not completely sure.

**Comment by minad** [comment]
The newest version of the default actions. Just tested it again:

~~~ elisp
(setf (alist-get 'consult-man embark-default-action-overrides)
      #'embark-consult-man)

(defun embark-consult-man (cand)
  (man (get-text-property 0 'consult-man cand)))

(setf (alist-get 'consult-info embark-default-action-overrides)
      #'embark-consult-info)

(defun embark-consult-info (cand)
  (consult-info--action cand)
  (pulse-momentary-highlight-one-line (point)))

(setf (alist-get 'consult-info embark-transformer-alist)
      #'embark-consult--target-strip)
~~~

**Comment by oantolin** [comment]
> Okay, makes sense! I think the only downside of this system is that there could be additional non-default actions which need the tofu. I don't think there are any but in principle this could happen.

Yes, that is a possible downside, but I think a "we'll deal with it when the need arises" approach is indicated.

**Comment by oantolin** [comment]
Those look good to me, I'll just add them to embark-consult right now.

I haven't tried the new `consult-info` command yet, but it sounds pretty cool. I also have never used `consult-man` because I didn't really see a need over plain `man`.

**Comment by oantolin** [comment]
Done. ba30b46502a90baec42e51f0e8017e7a4997c4f4

**Comment by minad** [comment]
> I also have never used consult-man because I didn't really see a need over plain man.

I also don't use it. But I think there are advanced man implementations which allow full text search (mandoc?).

**Comment by minad** [comment]
Thanks for adding the integration. 

> I haven't tried the new consult-info command yet, but it sounds pretty cool. I also have never used consult-man because I didn't really see a need over plain man.

Yes, I find it pretty good. I finally made my peace with the info format thanks to ELPA/ELPA-devel which automatically build the info files, such that all the info pages are automatically around. Furthermore I have to maintain the info manual from Compat. It is written in the ugly texinfo format (which I have not yet made my peace with).

But then, the `Info-*` api is not great. There is an `Info-search` function which could in principle be used to implement `consult-info`, but it seemed too slow. Now I just use the basic regexp search functions with some additional filtering. So overall, Info feels like a dumpster fire. Maybe the peace I've made won't last for long... :laughing:

**Comment by oantolin** [comment]
The new `consult-info` command is great, @minad! And using `embark-collect` on it is pretty useful (now that we have these default action overrides). I had even forgotten that the heading in the collect buffer were collapsible, that's a nice touch.

**Comment by minad** [comment]
> The new consult-info command is great, @minad! 

Thanks. Unfortunately there is a small flaw regarding interrupting the search, which doesn't always work. I know the cause but I still have to figure out how to fix this. I hope I don't have to refactor too much of the consult async infrastructure.

> I had even forgotten that the headings in the collect buffer were collapsible, that's a nice touch.

I also wondered who made this and since when we've got it. I like it!

**Comment by oantolin** [comment]
Apparently the history is that @karthink requested group headers in collect buffers and I said I had been thinking about doing that and making the sections collapsible. Then @hmelman suggested using the outline commands to implement it and I followed his suggestion. I did not remember any of that, but it does sound familiar now. See #389.

**Comment by oantolin** [comment]
Ooh, `M-n` and `M-p` navigate among sections. It's so nice when things are better than you remember them. 🤣

**Comment by oantolin** [comment]
> I finally made my peace with the info format thanks to ELPA/ELPA-devel which automatically build the info files, such that all the info pages are automatically around.

I should install Consult from there instead: it's one of only two manuals I wish had but don't. The other one is the compact org mode guide which for some reason never gets installed (I do have the full org mode manual, but the compact guide is very nice and often enough for me).
