### ISSUE TITLE
embark-become indicator for non-nil embark-become-keymaps lookup and undo

### ISSUE THREAD

**Issue by slayer152** [oantolin/embark#585]
Omar,

Clubbing two requests here as they are related to `embark-become`

1) Is it possible to add a visual indicator in the `*Embark Actions*` buffer to indicate that the current command is listed in one of the keymaps in the `embark-become-keymaps` variable? 

2) Once I've invoked `embark-become`, can I get back to the original actions without using any of the commands offered by `embark-become`? 

Context: `embark-become` is super helpful and helps recover from my mistakes. E.g. smash a keybinding for `consult-line` -> type something -> oops -> `embark-act` -> `embark-become` -> `consult-imenu` or `info-display-manual` -> type -> oops -> `embark-act` -> `embark-become` -> `devdocs-lookup` or `woman` or `man`. 

But for some less frequently used commands, I invoke `embark-act` and can't recollect upfront whether `embark-become` will yield different commands. A visual indication that the current command is in one of the keymaps of `embark-become-keymaps` will be helpful. Also, if i've erroneously invoked `embark-become` or invoked `embark-become` but don't want to choose a different command and want to return to the original actions, is it possible without aborting the full sequence?

Thanks for your consideration.

**Comment by oantolin** [comment]
You can use `C-g` to cancel `embark-become` without losing your minibuffer session (the same goes for `embark-act`). Also, remember that you don't need the current command to be in any of the `embark-become-keymaps` to use `embark-become`: you can always have the current command become any command you want using your global key binding for the command or even `M-x`. The keymaps in `embark-become-keymaps` are solely a convenience, providing even shorter keybindings for common commands.

For the indicator you could do something like this in your configuration:

```elisp
(defun relevant-become-maps (&rest _)
  (when-let
      ((miniwin (active-minibuffer-window))
       (command (with-current-buffer (window-buffer miniwin) embark--command))
       (keymaps
        (cl-loop
         for keymap-name in embark-become-keymaps
         for keymap = (symbol-value keymap-name)
         when (where-is-internal command (list keymap))
         collect
         (let ((name (symbol-name keymap-name)))
           (if (string-match "^embark\\(?:-become\\)?-\\(.*\\)-map$" name)
               (match-string 1 name)
             name)))))
    (format "\nBecome maps: %s\n" (string-join keymaps " "))))

(setq embark-verbose-indicator-buffer-sections
      '(target "\n" shadowed-targets " " cycle
               relevant-become-maps "\n" bindings))
```

You might want a more subtle indicator that doesn't take up a whole line and doesn't list the names of the become keymaps. You can easily adapt the above code to whatever you want.

**Comment by slayer152** [comment]
Thanks for the indicator snippet - TIL about `where-is-internal`.

> You can use C-g to cancel embark-become without losing your minibuffer session (the same goes for embark-act). 

sorry, I wasn't talking about losing the minibuffer session. 
E.g. `find-file` -> `embark-act` -> `*Embark Actions*` pops up with `Act on file ..` -> `embark-become` -> oops (and I just want to  re-view the actions under `Act on file...`).

Currently, after I realize the oops, I do `C-g` -> back to minibuffer session -> `embark-act` (Wanted to check if there's a easier way to avoid the `C-g` -> back to minibuffer session -> `embark-act`)

> Also, remember that you don't need the current command to be in any of the embark-become-keymaps to use embark-become: you can always have the current command become any command you want using your global key binding for the command or even M-x

I'm aware of this but adding to/creating keymaps  in `embark-become-keymaps` is a such a nice convenience by allowing a smaller curated list of actions and simpler keybindings.

**Comment by oantolin** [comment]
> Currently, after I realize the oops, I do `C-g` -> back to minibuffer session -> `embark-act` (Wanted to check if there's a easier way to avoid the `C-g` -> back to minibuffer session -> `embark-act`)

Oh, I see. Sorry, I have no solutions for that. The `C-g` cancels the action and then you have to restart `embark-act`.
