### ISSUE TITLE
load-with-code-conversion: Symbol’s function definition is void: defvar-keymap

### ISSUE THREAD

**Issue by abtxu** [oantolin/embark#597]
I am using embark 0.21 with windows 10, and found the following error message:
load-with-code-conversion: Symbol’s function definition is void: defvar-keymap

Is there any way to define defvar-keymap?

**Comment by oantolin** [comment]
That macro is defined in the compat library, which  is a dependency of embark. If you installed embark through package.el you should have gotten compat automatically. So this sounds like either you used a non-standard installation method or something went wrong. Try installing or reinstalling compat and/or embark.

**Comment by oantolin** [comment]
I'm closing this issue because I feel almost certain it is just an installation problem, requiring no changes to embark, but please reopen if I'm wrong, and in any case let me know if reinstalling embark or compat fixed it.
