### ISSUE TITLE
Embark Eldoc?

### ISSUE THREAD

**Issue by minad** [oantolin/embark#599]
https://www.masteringemacs.org/article/seamlessly-merge-multiple-documentation-sources-eldoc

We could show the first target at point.

**Comment by oantolin** [comment]
Oh, interesting idea! Although I think the target at point is the identifier at point the vast majority of the time, so maybe that's not so useful. Maybe more useful would be the full list of target types?

**Comment by minad** [comment]
The full list will add too much noise. It will be useful if you see "Press M-. Or C-. to embark url: ..." or "embark symbol: ...". This is like in a web browser. I had tried different variations before. Showing all target types in the modeline or even auto highlighting. These alternatives were not satisfactorily. Maybe it would be with Eldoc. It is worth a try.

**Comment by minad** [comment]
If this turns out useful, one could of course offer multiple variants. The simple one should probably be the default.

**Comment by minad** [comment]
See https://github.com/oantolin/embark/wiki/Additional-Configuration#show-the-current-embark-target-types-in-the-modeline for the older attempt.

**Comment by minad** [comment]
Fixed by #600
