### ISSUE TITLE
ivy/helm integration

### ISSUE THREAD

**Issue by a13** [oantolin/embark#6]
Is it possible at all?

**Comment by oantolin** [comment]
I'm not sure, I think it is possible and not _too_ difficult.

Is it necessary though? Both Ivy and Helm have robust (and more featureful) action mechanisms. In fact this package started because I was jealous of them, and nostalgic for my action-filled days as an Ivy user. :P

I was thinking the target audience for this mode where users of default completion, Icomplete, Ido, maybe Icicles, etc., certainly not Ivy and Helm users.

**Comment by a13** [comment]
> Is it necessary though?

maybe it's not necessary, but I like general solutions 

> I was thinking the target audience for this mode where users of default completion, Icomplete, Ido, maybe Icicles, etc., certainly not Ivy and Helm users.

To be fair, I'm still an Ivy user (and I can't see I can leave it soon as my everyday driver, though I can't see why I can't use embark-based actions there.

**Comment by oantolin** [comment]
I see. But... you can't possibly like embark better than Ivy actions?

With counsel you have a nicely curated set of actions already set up for you. And actions in ivy can be used in more ways: you can, for example, set a default action and then hammer `ivy-next-line-and-call` (or something like that, I forget) to run it on a bunch of candidates. And you can use `ivy-occur` to get a nice buffer for prosperity and run actions there (embark now works from the completions buffer, but only if the minibuffer from whence it came is still live). It's a featureful and well-thought system from what I recall.

**Comment by a13** [comment]
Another thing is I don't like ivy-actions are implemented not using keymaps

**Comment by rswgnu** [comment]
Good point about the keymaps and nice job on the documentation with the code.

If you want a truly generalized solution and an application, you could donate the code to the FSF and integrate it with the Hyperbole package which already has selection of completions but no associated completion-action framework nor keymaps for such (though it does have a key-driven minibuffer menu system already built in).  We'd be happy to help you with this.

**Comment by oantolin** [comment]
I seriously doubt many Ivy or Helm users would be interested in Embark. I've decided I'm not going to work on this myself, but I'd be happy to consider a pull request if you or someone else cares to make one.

**Comment by minad** [comment]
I thought about trying ivy with consult just to see what works :)

**Comment by minad** [comment]
There has been some recent discussion on reddit initiated by @clemera, see https://www.reddit.com/r/emacs/comments/kqutap/selectrum_prescient_consult_embark_getting_started/gi7gtyq/

Maybe we should try to get it working with Ivy after all.

**Comment by oantolin** [comment]
Here's a preliminary version of the Ivy integration:

```elisp
(add-hook 'embark-target-finders
	  (defun ivy-current-candidate+category ()
	    (when ivy-mode
              (cons (completion-metadata-get (embark--metadata) 'category)
		    (ivy-state-current ivy-last)))))

(add-hook 'embark-candidate-collectors
          (defun ivy-current-candidates+category ()
            (when ivy-mode
	      (cons (completion-metadata-get (embark--metadata) 'category) 
		    ivy--old-cands))))
```

It may have a bug with filenames, since I haven't checked whether those functions produce full paths and whether they are supposed to. :)

**Comment by clemera** [comment]
As ivy is a global minor mode it would probably better to check somehow if actually inside an ivy minibuffer session but I don't know the best way to do that.

**Comment by oantolin** [comment]
How about just `(and ivy-mode (minibufferp))`, @clemera?

**Comment by clemera** [comment]
This still wouldn't cover the case when you rebind completing-read-function? I have some macros `with-ivy`, `with-helm` and so on, though I don't use them so often anymore.

**Comment by clemera** [comment]
One could also use ivy-read without having set completing-read-function. The session setup for ivy is done in `ivy--minibuffer-setup` probably best to check some local var or check post-command-hook for ivy--queue-exhibit

**Comment by oantolin** [comment]
How about `(bound-and-true-p ivy--all-candidates)`, @clemera?

**Comment by clemera** [comment]
It depends how accurate you want to be ;) I guess this is good enough, but it seems the variable is not local bound so it would also be set for recursive non ivy sessions.

**Comment by clemera** [comment]
I just discovered it is also bound after exiting the session

**Comment by oantolin** [comment]
So is `(memq 'ivy--queue-exhibit 'post-command-hook)` better?

**Comment by oantolin** [comment]
No, I think I like the randomness of `(eq mwheel-scroll-up-function 'ivy-next-line)`. 😆

**Comment by clemera** [comment]
How do you feel adding ivy/selectrum target finders/collectors to the defaults of embark? So embark would "just work" with these out of the box

**Comment by oantolin** [comment]
I don't mind, but my spiritual guide in these matters of how much soft-dependency should be allowed is @minad, I'll let him chime in.

**Comment by oantolin** [comment]
> No, I think I like the randomness of `(eq mwheel-scroll-up-function 'ivy-next-line)`. 😆

This of course doesn't work either because the minibuffer gets reused, so even after you turn off ivy that binding stays visible.

**Comment by minad** [comment]
I think those should go to an embark-selectrum package in the end, this seems to be the MELPA guideline and it is probably not a bad idea since dependencies can be specified etc.

**Comment by oantolin** [comment]
I'm very tempted to violate it in this case. Or at least violate it for selectrum. For ivy, only if we can figure out a good way to check if its on. 😆

**Comment by oantolin** [comment]
Oh, my god, Ivy leaves `ivy--queue-exhibit` in the minibuffer's post command hook *forever*. 😱

**Comment by clemera** [comment]
Really?  But it does it it locally, also the mwheel-scroll-up-function is also set locally

**Comment by oantolin** [comment]
Yes, but the top level minibuffer gets recycled! Every time you use a non-recursive minibuffer it's the *same* minibuffer.

**Comment by oantolin** [comment]
Or rather there's one per frame, I think.

**Comment by oantolin** [comment]
> Oh, my god, Ivy leaves `ivy--queue-exhibit` in the minibuffer's post command hook _forever_. 😱

I the pot calling the kettle back, I leave some hooks there forever in Embark too. 😛

**Comment by clemera** [comment]
I think the local bindings are killed the next time you start a session no?

**Comment by oantolin** [comment]
I don't think so. I turned off Ivy mode, turned on Selectrum and those ivy variables are still bound in the minibuffer.

**Comment by oantolin** [comment]
I'm very confused: running `M-: mwheel-scroll-up-function` while I'm in the minibuffer with selectrum on (so, in a recursive minibuffer), says `ivy-next-line`. But I can actually use the mouse to scroll the selectrum candidates.

**Comment by clemera** [comment]
For me they are gone, did they change something upstream? What Emacs version are you using?

**Comment by clemera** [comment]
Maybe you are still in ivy-mode?

**Comment by oantolin** [comment]
Oh, I was. That's embarrasing. I turned on Selectrum without turning off Ivy.

**Comment by clemera** [comment]
Thank god, you made me panic ;)

**Comment by oantolin** [comment]
Sorry. :(

So the mwheel test it is, then. I think I really do want to add the Ivy and Selectrum integration. It's kind of silly not to have it when it doesn't affect anything else and it doesn't make Embark depend on either Ivy of Selectrum.

**Comment by oantolin** [comment]
Plus, I've gotten two or three questions about weird behavior in Embark, where I replied by asking "Are you by any chance using Selectrum, but forgot to use the integration code from the Selectrum wiki?". I was right every time. :)

**Comment by clemera** [comment]
@minad 
> I think those should go to an embark-selectrum package in the end, this seems to be the MELPA guideline and it is probably not a bad idea since dependencies can be specified etc. But I know that this guideline has been violated often.

What are the downsides? Users would benefit :)

**Comment by minad** [comment]
> Plus, I've gotten two or three questions about weird behavior in Embark, where I replied by asking "Are you by any chance using Selectrum, but forgot to use the integration code from the Selectrum wiki?". I was right every time. :)

Yes this is not good. I added two big fat notes to the Consult readme now.

>> I think those should go to an embark-selectrum package in the end, this seems to be the MELPA guideline and it is probably not a bad idea since dependencies can be specified etc. But I know that this guideline has been violated often.
> What are the downsides? Users would benefit :)

I think it is only some kind of more idiomatic style since you can specify dependencies and you don't have to clutter your code with declare-function or autoload declarations. In particular you can just require things statically which helps a lot for elisp analysis and will ensure that things will not miraculously break.

Originally I also used that declare-function style too and then @purcell intervened. See the discussion here https://github.com/minad/consult/pull/53. I disagreed in the beginning but after I refactored things a little bit it turned out to be good since there is a real incentive to keep things well separated. It really improved the code. (@oantolin as you know, I argued before to split up things). However now that I have done this nice refactoring, I could as well just move back the Selectrum specific code from consult-selectrum.el to consult.el with only very few declare-function declarations or eval-after-load blocks. Note that consult-selectrum.el is only like 40 loc (without whitespace and comments). The same applies to consult-flycheck.el and consult-flymake.el. So during the splitting process, the code got better. In the short term it might be worse for the users with multiple packages and for the maintainer. Maybe the benefits in the long term are worth it, if packages are refactored etc, then you benefit from the dependency declarations and the static requires.

**Comment by oantolin** [comment]
I think the situation is a little different for Embark and Consult. You started out with code that had some Selectrum specifics in various places. And separating consult-selectrum as you say gave you incentive to keep that file small. On the other hand in Embark these target finder and target collectors will be the only place I ever mention Selectum or Ivy.

I think I'm going to do it.

**Comment by minad** [comment]
> I think the situation is a little different for Embark and Consult. You started out with code that had some Selectrum specifics in various places. And separating consult-selectrum as you say gave you incentive to keep that file small. On the other hand in Embark these target finder and target collectors will be the only place I ever mention Selectum or Ivy.

Well, maybe that's true. In particular there was this consult-buffer offender which had selectrum specifics for a while. You already have the good separation. But now Consult is in the exactly same situation as Embark, with only three hooks to be set by the integration.

**Comment by oantolin** [comment]
> But now Consult is in the exactly same situation as Embark, with only three hooks to be set by the integration.

I'd actually suggest to get rid of the `consult-selectrum` package by incluing that in consult now.

**Comment by minad** [comment]
> I'd actually suggest to get rid of the consult-selectrum package by incluing that in consult now.

I will try that and see how it looks.

**Comment by minad** [comment]
It only requires this block to make the elisp checker happy.

~~~ elisp
(defvar selectrum-active-p)
(defvar selectrum--move-default-candidate-p)
(defvar selectrum-fix-minibuffer-height)
(defvar selectrum-refine-candidates-function)
(defvar selectrum-highlight-candidates-function)
(declare-function selectrum-exhibit "selectrum")
(declare-function selectrum-get-current-candidate "selectrum")
~~~

I am not sure. Maybe I should do this. It would certainly avoid some setup issues people had with selectrum+consult before.

**Comment by clemera** [comment]
@minad I would definitely like that :)

**Comment by oantolin** [comment]
Me too.

**Comment by oantolin** [comment]
Embark actually seems to work fine with Ivy. I know I shouldn't be surprised, but I am.

**Comment by oantolin** [comment]
Ah, maybe Counsel breaks the metadata! I should test with Counsel... some day.

**Comment by minad** [comment]
@clemera Why is there a prescient-ivy and selectrum-prescient package then btw? I am really not sure about this. I know it is not convenient but there are examples of both approaches. On the other hand users have problems because of this split.

**Comment by clemera** [comment]
I don't know, personally I prefer when packages include setup code for the popular packages they typically interact with. As you said there are also arguments to be more strictly, as we discussed earlier an alternative could also be to put all the integration code in some meta package but someone has to maintain that meta package but for each package you integrate with the best person to talk with is usually the maintainer of that package. We could also have a meta package where each maintainer would get commit rights but it would require more organizational effort.

**Comment by minad** [comment]
@clemera I think about it. I agree that it is not very convenient to have all these integration packages. But I think consult unfortunately has more the tendency to grow without limits than embark since its scope is so fuzzy. Therefore having things split at some reasonable points is not such a bad idea. The scope thing is something I really like about Marginalia for example. This is just done :)

**Comment by purcell** [comment]
> I agree that it is not very convenient to have all these integration packages.

I actually think it can be _more_ convenient in some cases to have integration packages, because if a user uses packages `foo` and `bar` and installs a `foo-bar` integration package, then that package can contain code which does setup for the specific `foo` + `bar` case with almost no configuration. Otherwise, either `foo` or `bar` gets cluttered with code that tries to detect the other package, or users have to set additional config vars for those packages. So, my 2c is that keeping things granular is still preferable overall.

**Comment by minad** [comment]
@purcell In this case embark-selectrum would be tiny. And the same applies to consult-selectrum.el, see https://github.com/minad/consult/blob/main/consult-selectrum.el. Except for the declaration faking the arguments do not apply. And regarding convenience, I got at least five bug reports where people just didn't have consult-selectrum installed. I added bold notes to the readme after that, so we will see how things develop.

**Comment by purcell** [comment]
Yeah, it's also reasonable to expect confusion for a short while after splitting the packages. Doesn't mean anything's wrong: I expect the bold will help and things will settle down. (And fwiw, I don't have strong feelings about the specific case of `embark-selectrum`, I'm just generally speaking up in support of clean packaging as a default.)

**Comment by clemera** [comment]
>  Otherwise, either foo or bar gets cluttered with code that tries to detect the other package (risky/error-prone) and work around compilation issues by faking declarations, or users have to set additional config vars for those packages.

@purcell
The approach embark takes is to run hooks which should return non-nil when they apply. This way the user does not have to set any configuration, the hooks automatically detect when inside a selectrum session. But I think you make a good point, it is not always possible to have such a clean auto detection.

**Comment by minad** [comment]
@clemera @purcell The same applies to consult-selectrum. I checked how a patch would look like. It is not super nice since you need some declare-functions and either bound-and-true-p or eval-after-load. But the trade-off is that installation becomes slightly simpler. So from the development perspective I think it is only marginally better (at least as soon as you have the packages set up) but from the user perspective it is clearly worse. I consider to move this back into consult.el such that completion system integration will just work out if the box in any case. But packages like consult-flycheck.el will stay external since they are supplements. I think this is a pragmatic compromise. What do you think?

**Comment by clemera** [comment]
I think for consult it is similar as for embark, as the consult hooks can also check which frameworks session is active. The advices you currently use could also take care of only running relevant code when the framework is active.

**Comment by oantolin** [comment]
Can you poke arbitrary github users here? I think @astoff might want to try the Ivy integration.

**Comment by astoff** [comment]
@oantolin Apparently yes, you can poke arbitrary users. The code snippet for Ivy integration you sent me, which checks the value of `mwheel-scroll-up-function`, works pretty well. There are some cosmetic glitches with you couldn't not have noticed. Maybe there's also something wrong when acting on files outside the current directory.

As to the packaging question, I would really try to keep the Ivy integration code inside embark.el. This could actually be an _incentive_ for you to keep things cleanly separated. There are all sorts of hack that would be fine for an integration package but you wouldn't tolerate in embark.el, right? Perhaps the main downside of this approach is that you would depend on Ivy's willingness to fix things when it's their idiosyncrasies that hinder a clean integration.

(FWIW, Eglot is an example of package that deals well with soft dependencies. It has 25 lines of company-specific code, 3 lines of yasnippet-specific code, and 3 lines referring to `gfm-view-mode`. And then there are 30 lines to configure 22 language servers, plus 113 lines of hacks at the end for two nonconforming servers. This all looks incredibly reasonable to me.)

**Comment by oantolin** [comment]
Hey @astoff, good to hear from you here! Would you mind helping me identify the glitches with the Ivy integration code? Whether it is added to Embark, or to some dedicated `embark-ivy` package, or just put on the Embark wiki, it needs to be polished first. (My personal preference is, as you say, to include it in Embark, but I'm very much open debate, and @purcell makes good points.)

What problems did you notice? I'm pretty sure the `file` type does need special treatment. My guess is that the target *collector* is correct as is, but the the target *finder* is returning just the last path component and needs to return instead the full path.

What cosmetic glitches did you see?

**Comment by astoff** [comment]
Sure, I'll let you know as I come across any problems. The cosmetic glitch (really just one) happens after pressing `C-h` while on `embark-act`. The "Act" prompt slides to the end of the candidate list.

![image](https://user-images.githubusercontent.com/6500902/104074135-a0c23000-520f-11eb-8094-16ea81fb2e4e.png)

**Comment by oantolin** [comment]
That's crazy! And delightful!

**Comment by astoff** [comment]
Please wrap the Ivy setup code in `with-eval-after-load`! (Some would argue it's bad style to provide hooks which are non-nil by default. I don't know, perhaps defcustom is to blame for not handling this automagically. But not deferring the setting of hooks usually works, so this can be confusing.)

**Comment by oantolin** [comment]
Oh, that's right. Maybe I should split the variables in two? Like `embark-target-finders` and `embark-additional-target-finders`? I feel that some built-in list are like that but with a different naming convention. What was it?

**Comment by astoff** [comment]
Yeah, I'm sure there's stuff like that all over the place (in auctex, for instance; if the list is built-in this particular problem can't happen). I personally find this ugly, especially if one wants to change the default rather than just add to it. Appending the default value to the occasional user customization at load time, or even just giving a warning, would still seem less bad to me, but this is probably too unusual.

**Comment by oantolin** [comment]
By the way, I never properly figure this out: is the ivy integration buggy with respect to absolute vs relative paths?

**Comment by astoff** [comment]
Most of the time it captures the basename only (even if the file is not in the current directory). This is not the right thing, is it? I got the impression that some other random stuff happens sometimes, but I can't reproduce.

**Comment by astoff** [comment]
The variable `ivy--directory` holds the directory name during and after reading a file name. It also seems that it is always nil when reading something other than a file name.

**Comment by oantolin** [comment]
Thanks for looking into this, @astoff!

**Comment by oantolin** [comment]
> Strangely enough, while `(ivy-state-current ivy-last)` reflects the current Ivy session, all other fields of `ivy-last` seem to refer to the previous Ivy session. So you shouldn't use `ivy-state-directory` or `ivy-state-text` (but please check this claim).

And `ivy--old-cands` contains the current candidates. 🤷🏽

**Comment by oantolin** [comment]
Because of the discussion here, and since @minad already added out-of-the-box Selectrum support to Consult, I decided to add support in Embark for Selectrum da1613a and Ivy 988660f78b83394902d783370f740cda445d3187. I'll update the documentation once this hits Melpa.

**Comment by oantolin** [comment]
And since no-one seems interested in Helm support (to be honest, I'm pretty surprised there was interest in Ivy support)

**Comment by raxod502** [comment]
> maybe @raxod502 could provide more info on that, personally I prefer when the packages include setup code for the popular packages they typically interact with

I think there are compelling arguments for both sides, and it's fine to pick whichever seems more reasonable for a particular case. I have done it both ways in the past (e.g. `prescient.el` has separate packages, while `straight.el` is all-in-one).

What you all came to in this thread seems eminently reasonable.

**Comment by astoff** [comment]
At least until recently, I was getting a byte-compilation error when installing Consult without Selectrum installed, and that was because the Consult package itself is/was shipping consult-selectrum.el.

While an error should always be fixed, that struck me as a possibly good compromise: instead of creating a lot of extra integration packages, just ship some additional files in the main package, which the user is welcome to load if the integration features are desired.

**Comment by minad** [comment]
@astoff Did you observe warnings or errors?

**Comment by astoff** [comment]
```
Compiling file /.../.emacs.d/elpa/consult-20210117.47/consult-selectrum.el at Sun Jan 17 20:07:03 2021
consult-selectrum.el:25:1:Error: Cannot open load file: No such file or directory, selectrum
```

**Comment by oantolin** [comment]
If you are not going to `(require 'selectrum)` there is no real advantage in having this in a separate file, @minad. 😛

**Comment by minad** [comment]
Yes, I know. But I also don't want to see this inside my polished consult.el :see_no_evil:
