### ISSUE TITLE
Live-occur seems to be broken

### ISSUE THREAD

**Issue by minad** [oantolin/embark#60]
Does not work for me anymore on https://github.com/oantolin/embark/commit/9af30353e79cf19ddc6b95377e4461ca8d125f4d

**Comment by oantolin** [comment]
This is odd. As you know, I use live occur as my completion framework. It's definitely working here.

**Comment by minad** [comment]
Hmm, yes I know. I will investigate this a bit and do some bisection if necessary.

**Comment by oantolin** [comment]
What I usually do in cases like this is ... blame selectrum. 😆 Sorry.

**Comment by oantolin** [comment]
Ah, I think I can reproduce it. Let me investigate.

**Comment by oantolin** [comment]
I think I got it, it was a silly mistake. Please test.

Oh, and selectrum had nothing to do with it, so I apologize publicly for maligning it.

**Comment by minad** [comment]
Works :)

**Comment by oantolin** [comment]
That's a relief!

**Comment by minad** [comment]
Now that embark is on MELPA you will see a large influx of selectrum users ;)

**Comment by oantolin** [comment]
I might need to install and configure Selectrum if only for debugging. I don't think I can really get used to it for day to day stuff: it shows you so few candidates at once! I'm really used to the dense grid view by now. Using Selectrum or Icomplete-vertical feels like peering at the completion candidates through a keyhole.

**Comment by minad** [comment]
Haha, you can certainly see it like this. But I've been accustomed to ido before, there the keyhole is even smaller. The vertical view is a nice compromise. I have both selectrum and icomplete-vertical for testing consult and a simple toggle function.
