### ISSUE TITLE
M-. (xref-find-defintions)

### ISSUE THREAD

**Issue by sjLambda** [oantolin/embark#607]
Emacs default key chord M-. (xref-find-defintions) has been lost after loading embark. If I re-bind to the key-map, I get this error: 

`Command attempted to use minibuffer while in minibuffer`

Is there a way to restore or re-define the same key chord to the same function? 

Thanks for any help/pointers.

**Comment by oantolin** [comment]
Embark does not define any global key bindings of its own. If `M-.` is now bound to an Embark function it is because _you_ bound it to that function in your configuration. The solution is simple: change your mind! Look at your configuration for Embark and modify the key binding to your liking.

**Comment by minad** [comment]
I want to emphasize that `embark-dwim` is a generalization of `xref-find-definitions` and as such a worthy command bound to `M-.`.

**Comment by oantolin** [comment]
We're you able to fix this, @sjLambda?

**Comment by sjLambda** [comment]
Not yet. Apparently I have to bind the dwim command to a specific key map for embark to work like the default used to.On Feb 23, 2023, at 5:40 AM, Omar Antolín Camarena ***@***.***> wrote:﻿
We're you able to fix this, @sjLambda?

**Comment by oantolin** [comment]
This seems unusual to say the least. Could you post your embark configuration? I bet if I see it I can point you in the right direction.

**Comment by sjLambda** [comment]
Sorry for the long lapse here. Got distracted, now I'm back to my old machine trying to integrate embark. Any help is greatly appreciated. 

All I want is M-. to behave as before: open the source code, definition.

`(use-package embark :defer t
  :bind
  (("C-."          . embark-act)
   ("C-c RET"      . embark-dwim)
   ;; ("M-."       . xref-find-definitions) 
   ("M-."          . embark-dwim)
   ("C-h B"        . embark-bindings)
   ("C-h b"        . embark-bindings)
   ("C-h C-b"      . describe-bindings)
   ("C-M-<return>" . embark-dwim)
   :map minibuffer-local-completion-map
   ("C-c C-o"      . embark-export)
   ("M-s o"        . embark-export)
   ("C->"          . embark-become)
   ("C-*"          . embark-act-all)
   :map embark-file-map
   ("S"            . sudo-find-file)
   ("C-="          . diff)
   ("O"            . find-file-other-window)
   ("F"            . find-file-other-frame)
   :map embark-url-map
   ("B"            . eww))
  :hook
  (embark-collect-mode . consult-preview-at-point-mode)
  :init
  (add-to-list 'display-buffer-alist
               '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                 nil
                 (window-parameters (mode-line-format . none)))))`
