### ISSUE TITLE
Compat 29.1.4.0 supports natnum and key defcustom types

### ISSUE THREAD

**Issue by minad** [oantolin/embark#609]
Hi Omar, I added support for the natnum and key types yesterday. We've talked about the key type before, when we moved to the new key convention. You may want to change the types used in Embark.

**Comment by oantolin** [comment]
Ooh, natnum is courting controversy! Does it mean positive integers or non-negative integers?

**Comment by minad** [comment]
No controversy in Emacs since `natnump` has been around since forever.

**Comment by minad** [comment]
But you could lobby for the deprecation of `natnump` in favor of `wholenump` :D

**Comment by oantolin** [comment]
I didn't know about `natnump`! So it's non-negative integers, cool.

"Whole number" is even more ambiguous. Depending on who says it it can mean integer, positive integer or non-negative integer.

**Comment by minad** [comment]
For some reason `wholenump` is an alias for `natnump`. :shrug:

**Comment by minad** [comment]
But anyway, I opened this issue more because of the type `key`, since we talked about this before, when we replaced `key-sequence` with `string` which is much less specific.

**Comment by oantolin** [comment]
Yes, of course. Let me try the new custom widget first, but I'll very likely bump the compat requirement and switch to the key type.

**Comment by oantolin** [comment]
The key widget is pretty nice. You do type the string representation but (1) it is validated for you, and (2) using `C-q` to insert a special character inserts the correct string representation instead of the character!

**Comment by oantolin** [comment]
Done, thanks for letting me know!
