### ISSUE TITLE
`embark-copy-as-kill` on org src block copies extra indents

### ISSUE THREAD

**Issue by jumper047** [oantolin/embark#613]
[at least in my current setup] org_src blocks indented with two spaces when displayed inline in org file, and have no these bonus indentation when edited in separate buffer with `org-edit-special`. When I acted with `embark-copy-as-kill` on source block, it is copied with these indentation, while I expected it will be copied without it.
Is it desired behavior of the function? I mean maybe my use case differs from yours and it's actually not a bug:)

**Comment by oantolin** [comment]
Well, it copies the `#+begin_src` and `#+end_src` lines too, it would be weird to keep those lines and not the indentation, wouldn't it?

I take it you want just the inner source, without the `#+begin_src` and `#+end_src` lines? That's probably worth adding as a separate action.

**Comment by oantolin** [comment]
By tehe way, the reason it currently copies the whole thing, with indentation and `#+begin_src` and `#+end_src` lines is that that entire thing is the syntax of an Org source block.

**Comment by jumper047** [comment]
Sorry, I somehow missed the fact that source block copied with the decorators, so it's totally makes sense:). Though I still think that action to copy content of the source block (or even region of the source block) may be very useful.

**Comment by oantolin** [comment]
I agree it would be useful, I'll add it separately with a name like "copy inner block" or something like that.

**Comment by oantolin** [comment]
Done. I added an `embark-org-copy-block-contents` action bound to `c` to copy the block contents sans indentation. I also bound `org-babel-mark-block` to `SPC`, this marks just the block contents (of course, that region does include the indentation). While I was there, I also bound `TAB` to `org-indent-block`, which reindents the block, and `/` to `org-babel-demarcate-block` which will split the block at the current line into two blocks.

Also, I fixed a little problem with `embark-insert`, so now you can duplicate a block with `i` (before that inserted the duplicate right at point, which has not ever been what I want).

**Comment by jumper047** [comment]
Awesome, thank you!!
