### ISSUE TITLE
Embark-consult-goto-grep sometimes gets the path wrong

### ISSUE THREAD

**Issue by agzam** [oantolin/embark#616]
*I'm not sure if this is a legit bug just throwing it here for posterity and discussion*

Embark-collect's push-button action would randomly fail for me sometimes, and it took me a while to figure out what was happening. I would search for something in the project, then collect the data. In the Embark Collect buffer, pressing `RET` should take you to the location, right? Well, sometimes it wouldn't work. Turns out, for some reason `embark-consult-goto-grep` would conflate `default-directory` and `project-directory`.

I suspect this is a bug in Doom's `vertico` module.

#### To reproduce it:

- Open any project
- Open a file or directory nested deeply in the project's dir structure
- Search within a project as you'd normally do
- Collect the results (don't export - Embark Export is not broken)
- Try to jump to any location - in Embark Collect buffer press `RET`

#### Observed behavior:

It can't find the file.

#### Hacky fix:

I did the following (and it appears to be working):

```emacs-lisp
(defadvice! embark-consult-goto-grep-a (fn &rest args)
    "Embark Collect Buffer Fix."
    :before #'embark-consult-goto-grep
    ;; Sometimes, when the search is initiated from a nested dir, Embark Collect can't
    ;; find the file anymore. It looks for the file from the place of search origin,
    ;; instead of the project root
    (setq default-directory (projectile-project-root)))
```

*Sorry for the Doom macro syntax. As I said, I suspect it only affects users of Doom's vertico module*

**Comment by oantolin** [comment]
I can reproduce this without Doom. I'll look into it. It might be that I introduced a different bug while trying to fix #612.

**Comment by oantolin** [comment]
I had forgotten to set the default-directory in one case!

**Comment by oantolin** [comment]
Have you been able to check if that fixes the problem, @agzam?

**Comment by agzam** [comment]
I've tried a few different cases (without that advise-hack), and what previously failed now seems to be working. Thank you!
