### ISSUE TITLE
Installation Error: Error (use-package): embark/:catch: Symbol’s function definition is void: defvar-keymap

### ISSUE THREAD

**Issue by Sinthoras7** [oantolin/embark#618]
When I try to install embark, (via use-package and straight) I get an error message.

For installing I have the following code in my init.el:
`      (use-package embark
        :straight t)
      (use-package embark-consult
        :straight t)`

The Error message states:
"Error (use-package): embark/:catch: Symbol’s function definition is void: defvar-keymap Disable showing Disable logging
Error (use-package): embark-consult/:catch: Symbol’s function definition is void: defvar-keymap Disable showing Disable logging"

What's the problem?

**Comment by oantolin** [comment]
I'm not familiar with straight but it sound like it doesn't honor dependencies. Embark depends on Compat, which defines, among many other things, the defvar-keymap. If you installed using package.el it would automatically install Compat for you,maybe for straight you need to manually install dependencies?

**Comment by Sinthoras7** [comment]
Your suspicion was correct. I installed `compat` and afterwards embark was installed without a problem. Thank you!

**Comment by oantolin** [comment]
I'm a little surprised straight did not automatically install compat for you. If straight really forces you to manage dependencies manually, you may prefer to switch to the built-in package manager, package.el, which does automatically install dependencies.

**Comment by minad** [comment]
I wonder what is wrong with Straight. Why does it ignore dependencies?

**Comment by Sinthoras7** [comment]
For some strange reason I had the same issue, when I ported my configuration to another device, where embark needed to be installed again. The fix was to delete the folder where all my packages are and let it reinstall all of them.
