### ISSUE TITLE
[FR] Add file opened with `embark-open-externally` to recent files

### ISSUE THREAD

**Issue by gusbrs** [oantolin/embark#619]
This is a small suggestion / feature request. Embark offers the useful `embark-open-externally`, which would be even nicer if it would integrate with `recentf-mode` by adding the file with `recentf-add-file` when the mode is enabled.

**Comment by oantolin** [comment]
I don't think everybody would like this behavior. In particular I think many people *only* use `embark-open-externally` on files they never want to open in Emacs, always externally; and many of those people would also want their recent files list to be files they want to open inside Emacs.

So, maybe the best option is to just leave this matter to people's personal configuration.

The `embark-open-externally` command can be used directly or as an Embark action. If you want every single use of it to add to the recent files list you can use:

```elisp
(advice-add 'embark-open-externally :after 'recentf-add-file)
```

If you only want to add the recent file list when you use `embark-open-externally` as an Emabrk action, and not when you call it directly, you could use:

```elisp
(cl-defun embark-add-recent-file (&key target &allow-other-keys)
  (recentf-add-file target))

(push (alist-get 'embark-open-externally embark-post-action-hooks)
      'embark-add-recent-file)
```

**Comment by gusbrs** [comment]
> In particular I think many people _only_ use `embark-open-externally` on files they never want to open in Emacs, always externally; and many of those people would also want their recent files list to be files they want to open inside Emacs.

I think the relevant distinction is not "in Emacs" vs "externally", but rather opening "through Emacs" vs "through some other means". Personally, I use `embark-open-externally` for PDFs, which, as you say, I never want to open in Emacs (no DocView for me), but I do find it useful to have those files listed in `consult-buffer`, where I can call `embark-open-externally` on them more easily.

> I don't think everybody would like this behavior.

But, I do grant this might be debatable, and some people may not want it. So I understand your call. Thank you for considering though.




> So, maybe the best option is to just leave this matter to people's personal configuration.

That's fine too, I do have one such advice, but just thought it was a good idea to suggest. And thanks for the tips as well.

**Comment by minad** [comment]
I agree with @oantolin's reasoning. Creating your own action commands is also easy. As far as I know, even remapping should work correctly `embark-open-externally -> my-embark-open-externally-with-recentf`.

**Comment by oantolin** [comment]
By the way, @gusbrs, if you always want to open PDFs externally, you might want to look into [openwith](https://bitbucket.org/jpkotta/openwith), or maybe rolling your own "magic file handler" (which I believe is how openwith is implemented). You can read about magic file names [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Magic-File-Names.html).

**Comment by oantolin** [comment]
Oh, and finally, you may want to give pdf-tools a shot. I like it much better than DocView, and now Emacs + pdf-tools is my favorite PDF viewer.

**Comment by oantolin** [comment]
The best table of contents navigation for PDFs I've ever seen is pdf-tools + consult-imenu + orderless. You can move around so fast it makes non-Emacsers dizzy.

**Comment by gusbrs** [comment]
@oantolin 

> By the way, @gusbrs, if you always want to open PDFs externally, you might want to look into [openwith](https://bitbucket.org/jpkotta/openwith), or maybe rolling your own "magic file handler" (which I believe is how openwith is implemented). You can read about magic file names [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Magic-File-Names.html).

That's a good tip, thanks. But I've been through that, both `openwith` and trying to cook my own, trying to advise `find-file-noselect`. Truth is that it is "almost always". I do sometimes need to inspect an uncompressed PDF, for which Emacs is convenient, and using either of those alternatives makes it somewhat hard to do so. So I eventually stepped back (for the time being, at least) and use `W` in Dired and `C-. x` elsewhere. I might go back though, I'm not really happy with either approach in this case.

> Oh, and finally, you may want to give pdf-tools a shot. I like it much better than DocView, and now Emacs + pdf-tools is my favorite PDF viewer.

I've been a user of pdf-tools for a good number of years, but eventually gave up during the time the package was less cared for. I know it has a new maintainer now, but I haven't reactivated it. I know it is pretty good.

> The best table of contents navigation for PDFs I've ever seen is pdf-tools + consult-imenu + orderless. You can move around so fast it makes non-Emacsers dizzy.

That I haven't tried yet.  :-) At the time I had pdf-tools installed, I did not use consult yet. Sounds good!

Thanks for the several good suggestions!
