### ISSUE TITLE
Default action are broken for consult-line/consult-outline/...

### ISSUE THREAD

**Issue by minad** [oantolin/embark#62]
When doing consult-line, using either embark-act or embark-act-noexit and then pressing RET for the default action, I am observing multiple issues:

embark-act/embark-act-noexit on selectrum does not perform the jump but hangs due to how RET is handled:

* The action is not executed, but instead the minibuffer shows "Go to line: [full line candidate]"
* When pressing enter nothing happens
* When pressing down and selecting the full line candidate, the jump is performed

embark-act-noexit default action throws an error (happens also with icomplete):

* When executing the default action, I either get a commandp type error in embark-default-action or I am getting an error "recenter: recentering a window that does not display current buffer". This is the consult recentering. The issue is that the current window is the minibuffer-window, but this should not be the case when leaving completing-read, the buffer/selected window should be reset correctly. Maybe this has something to do with the reason window switching for actions which broke default actions?
* Update: Right now I am unable to reproduce the commandp error, I don't know what the issue was - maybe I had a wrong embark version. But the recenter problem is still there, if I set consult-after-jump-hook to nil (removing the recentering), everything works, but I still think this should be fixed since the default action is executed in the wrong window?

**Comment by oantolin** [comment]
I think this isn't an issue with `embark-default-action`, but with something those consult commands do. Instead of using `embark-default-action`, try using `consult-line` as the action, for example by running it with `M-x`. The same thing seems to happen.

**Comment by minad** [comment]
> I think this isn't an issue with embark-default-action, but with something those consult commands do. Instead of using embark-
default-action, try using consult-line as the action, for example by running it with M-x. The same thing seems to happen.

The first issue: I think this is just a quirk of how selectrum handles RET. This does not happen with icomplete.

The second issue:

I checked again and when I am invoking `M-x consult-line M-SPC M-x consult-line` (M-SPC is bound embark-act-noexit), the second consult-line is executed in Minibuf-1 window. My expectation is wrong here. Basically the idea of executing in the embark--target-buffer is not strong enough and the action should also change the selected window.
The question is if you want to change that in embark. Maybe it makes sense since when you execute normal commands via M-x as soon as the command executes it is executed in the context of the selected original window.

When printing the window and current-buffer in the beginning of consult-line `(message "%s %s" (current-buffer)  (selected-window)))` I see `consult.el #<window 4 on  *Minibuf-1*>` for the second execution of consult-line.

The error is then triggered by `recenter`, which expects `(current-buffer)=(window-buffer (selected-window))` and this does not hold necessarily.

**Comment by minad** [comment]
You can also try `M-x switch-to-buffer M-SPC M-x recenter` to see this triggered without consult.

**Comment by oantolin** [comment]
Ah, got it! I hadn't really understood the problem. Thank you very much for this extended explanation!

If you press RET in an Embark Occur buffer I already select a window containing the target buffer. I could do that for actions too, for consistency. Will experiment and report back.

**Comment by minad** [comment]
> If you press RET in an Embark Occur buffer I already select a window containing the target buffer.

Yes, Embark Occur works. I also tested this, should have mentioned it earlier.

**Comment by minad** [comment]
Right now I am investigating the next weird issue, but I thin this time Selectrum is the culprit...

**Comment by oantolin** [comment]
That commit should fix this, thanks again for explaining the problem to me. I'll close and you reopen if I missed something.

**Comment by minad** [comment]
The next weird issue is here #63. Sorry!

**Comment by minad** [comment]
> That commit should fix this, thanks again for explaining the problem to me. I'll close and you reopen if I missed something.

The fix for the recenter problem works! Thank you! The other RET issue - do you think this is more selectrum related or should I add an issue too as reminder?
