### ISSUE TITLE
Clean way to give argument to interactive action?

### ISSUE THREAD

**Issue by hrehfeld** [oantolin/embark#621]
Is there a clean way to use an around-hook to call an interactive command that doesn't prompt minibuffer but takes an arg?

This workarounds, but just ignores further hooks in `:run`:

``` elisp
    (cl-defun my-embark--target-as-arg (&rest rest &key run target  &allow-other-keys)
      (interactive)
      (save-excursion
        (funcall (plist-get rest :action) target)))
```

It doesn't seem possible looking at `embark--run-action-hooks`, right?

On the other hand, it doesn't really seem to make sense to put this hook somewhere else than directly around the action, so maybe it's just fine this way?

Anyways, I'm confused, I think this could at least be mentioned in the documentation.

My use case specifically is `org-web-tools`, where interactive commands look for things in the `kill-ring` if there's no arg. (yes, I could push to the kill-ring, I guess)

**Comment by oantolin** [comment]
You could define a non-interactive alias for the function you want to use as an action.

**Comment by minad** [comment]
My recommendation is to write a new interactive command which prompts via the minibuffer. From the Embark README:

> In general it is more flexible to write any new Embark actions as commands, that is, as interactive functions, because that way you can also run them directly, without Embark.

**Comment by oantolin** [comment]
Sure, that also works, @minad. I honestly don't see much difference in this case.

**Comment by oantolin** [comment]
Probably @minad's suggestion is the most straightforward way to achieve this.

**Comment by minad** [comment]
> Sure, that also works, @minad. I honestly don't see much difference in this case.

It is just embarkier. ;)
