### ISSUE TITLE
Targets for org-mode markup

### ISSUE THREAD

**Issue by jumper047** [oantolin/embark#623]
Is it possible to add targets like `=line of the code=` or `~some command~`. Those elements supposed to contain some shell command or code, and IMHO it will be useful to treat them according to their purpose, for add option to execute command. 

But I should mention that personally, I started that issue after I failed to select command inside that tag (I just wanted to copy it), so maybe this feature is completely out of scope of the Embark and I should try to add it into `expand-region` instead.

**Comment by minad** [comment]
On 4/24/23 12:38, jumper047 wrote:
> Is it possible to add targets like |=line of the code=| or |~some
> command~|. Those elements supposed to contain some shell command or
> code, and IMHO it will be useful to treat them according to their
> purpose, for add option to execute command.

This won't work in general since such code can be anything: identifiers,
Elisp, Shell, Python, ...

> But I should mention that personally, I started that issue after I
> failed to select command inside that tag (I just wanted to copy it), so
> maybe this feature is completely out of scope of the Embark and I should
> try to add it into |expand-region| instead.

In my setup Embark is already doing fine. It recognizes =foo= as
identifier and =(foo)= as identifier or Elisp expression.

Note that you can also add your own target finders and actions. You
could even enable them selectively per files via file-local variables.

**Comment by oantolin** [comment]
You can easily add new org targets in your own configuration as follows:

```elisp
(push 'verbatim embark-org--types) ; =this is verbatim=
(push 'code embark-org--types)     ; ~and this is code~
```

(If you look at the definition of `embark-org--types`, you'll see it is declared as a "constant", but Emacs Lisp will kindly let you modify it anyway!)

With this configuration you can at least run general actions on them like copying. The reason that they aren't enabled by default in `embark-org` is simply that aren't any non-generic actions one could easily use for them. You mentioned evaluation here:

> IMHO it will be useful to treat them according to their purpose, for add option to execute command.

But execute them how? How can you tell what language the code is written in? Org does have inline source code expression that look like `src_LANG[OPTIONS]{CODE}`, and for those we could add Embark targets with an action that evaluates the code, but for `~CODE~` I don't think it would be wise to play guess the language.

If in your personal files you only ever use `=CODE=` for, say, shell commands, then you could do something like:

```elisp
(push 'code embark-org--types)

(defvar-keymap embark-org-code-map
  :doc "Keymap for actions on Org =code= elements."
  :parent embark-general-map
  "RET" #'shell-command)

(add-to-list 'embark-keymap-alist
             '(embark-org-code embark-org-code-map)) 
```

**Comment by oantolin** [comment]
Ah, `shell-command` doesn't quite work there since the target includes the markup `~` characters, but you can easily write your own function that removes then and then calls the string as a shell-command.

**Comment by minad** [comment]
> ...but for ~CODE~ I don't think it would be wise to play guess the language.

I see two options: Either one defines a file-local variable which defines the language or one defines multiple actions for the code target (e.g. embark-execute-as-shell, embark-execute-as-python, and so on).

**Comment by minad** [comment]
Completely agree. For example I recently added `cape-elisp-block` to my Cape package, which completes Elisp code in inline and normal Org source blocks. It would be problematic to handle ~ and = blocks like this.

**Comment by oantolin** [comment]
I should probably enable these inline src blocks (I think that's what they're called) in embark-org. I think they have basically the same actions as the big source blocks: evaluate, edit in a separate buffer, delete the results.

**Comment by oantolin** [comment]
I've added support for inline source blocks, though it seems you really only have those three actions I mentioned. cac4476dbe207951501ca1071eecb767385b457b

**Comment by oantolin** [comment]
As for enabling support for `=verbatim=` and `~code~` markup, I think I'll just leave it to user's configurations, since we don't really have nice actions for them. I hope the code I posted above, solves your issue @jumper047. If not, feel free to let me know what more you need.

**Comment by jumper047** [comment]
Thank you for pointing on inline code blocks, I didn't know about them. Regarding code - this is exactly what I needed, thank you for help!
