### ISSUE TITLE
`query-replace` with `embark-act` jumps to next candidate

### ISSUE THREAD

**Issue by alternateved** [oantolin/embark#624]
Hello and thank you for an amazing package!

I was wondering if something changed with `embark-act` behavior and if it was an intended change. If I remember correctly, when using combination `M-x embark-act M-x query-replace` the behavior was to start replacing with the candidate on point (or region). Currently it jumps to next candidate to perform replacement. Is there a way to go back to previous behavior?

**Comment by oantolin** [comment]
The behavior is not supposed to have changed. I'll look into it.

**Comment by alternateved** [comment]
Amazing, thank you!
