### ISSUE TITLE
Slowdown in recursive setting

### ISSUE THREAD

**Issue by minad** [oantolin/embark#63]
1. When pressing `M-x xyz...` everything is fast in both icomplete and selectrum.
2. When pressing `M-x M-x M-x M-x xyz...` everything is fast in both icomplete and selectrum.
3. But when I am pressing the keys `M-x M-SPC M-x abc...`, the `M-x abc...` completion is really slow as if there is some interaction between the recursive completion sessions going on. In my setup `M-SPC` is bound to `embark-act-noexit`.

You will probably only observe this with selectrum since there the completion speed becomes more noticeable. But it is also noticeable when using icomplete with delay=0.

I tested without `marginalia-mode`, the annotators are not the issue here. I did some profiling but it wasn't obvious directly where the problem lies. Do you observe this too?

**Comment by oantolin** [comment]
It doesn't feel noticeably slow here, even with `(setq icomplete-compute-delay 0)`. I also can't imagine how there could be any interaction between the two completion sessions.

**Comment by minad** [comment]
I will try to reproduce this in emacs -Q and I will try to get a profile. It is really noticeable, but the effect is significantly stronger with selectrum, since there the completions are immediate.

I am not sure what icomplete is doing with delay=0. I think the execution is still deferred in the event loop and not immediately executed? That could make a difference.

**Comment by oantolin** [comment]
I think I can reproduce this now, with embark-live-occur. It seems to be worse if you start from `find-file`. Weird.

**Comment by oantolin** [comment]
It also happens if you act on the symbol at point. For example, if in an Emacs Lisp buffer you move to some variable name and the run `embark-act` and for the action enter `M-x describe-variable`. (By the way the recent change to select the target window, makes this very awkward: right after `M-x` you get moved back to the Emacs Lisp buffer you start from, and you have to switch to the minibuffer to type `describe-variable`. I'll try to fix that too.)

**Comment by minad** [comment]
I didn't have time yet to investigate this further. Yesterday I took some more profiles but I didn't see the problem in the profile.

**Comment by oantolin** [comment]
Please test now, @minad. I *think* that last commit takes care of it for default completion (including embark-live-occur) and for icomplete, but I'm not sure, and I don't know if helps selectrum at all.

**Comment by minad** [comment]
@oantolin Unfortunately the "fix" does not fix the slowdown for me, for neither icomplete nor selectrum.

**Comment by oantolin** [comment]
I'm going crazy: it doesn't fix it for me anymore either! What on earth did I do before?

**Comment by oantolin** [comment]
Huh, that fix does seem to work on my Chromebook, but not on my Windows laptop. I have different Emacs versions on them, but they are both fairly recent "Emacs 28.0.50".

**Comment by minad** [comment]
The windows fix doesn't count! It is not free software!

**Comment by oantolin** [comment]
This one is mysterious...

**Comment by oantolin** [comment]
Ah, the fix never worked on the the Chromebook: the slowdown simply does not happen there...

**Comment by minad** [comment]
When I tried to reproduce the issue #65 with emacs -Q, there the slowdown was very noticeable. But I am using 27.1

~~~ elisp
(load "~/emacs-pkg/embark/embark.el")
(load "~/emacs-pkg/consult/consult.el")
(icomplete-mode)
(setq enable-recursive-minibuffers t)
(setq completion-styles '(substring))
(define-key icomplete-minibuffer-map (kbd "M-SPC") #'embark-act-noexit)
~~~

**Comment by oantolin** [comment]
GitHub apparently autocloses if your commit message contains "fix #n". I only said I think this fixes the problem. Please test @minad, and reopen if it persists.

I think I was running (run-at-time 0 nil ...) in a tight loop, changing the 0 to 0.1 gives Emacs some breathing room.

**Comment by minad** [comment]
@oantolin This fixes it for me. Is this some kind of busy-wait loop? Is there no better way?

**Comment by minad** [comment]
Generally for such things I'd love to see a comment. I am myself rarely commenting things if they are self-explanatory, but in such cases where it cost a bit of time to figure it out, I think it would be very appropriate.

**Comment by oantolin** [comment]
You're right about adding a comment. I did that here: 4776162f2d1e7830f662175c3e511040af113bf2

I like this `(run-at-time 0 nil ...)` idiom to schedule things to happen at the next cycle of the Emacs event loop, but the freedom to use `M-x` that I defend so much causes a complication here: if you use `M-x` to specify the action, the embark action system would normally want to inject the target at the `M-x` prompt and then run cleanup immediately. Both injection and cleanup need to be postponed. if you use `M-x`. The injection is run through `minibuffer-setup-hook`, so it just declines to inject if it sees the `M-x` prompt and relies on that hook still being valid the next time a minibuffer is open.

It would be nice to run the cleanup right there in `embark--act-inject` or maybe in a `minibuffer-exit-hook`. But that wouldn't let you use commands that don't use the minibuffer as actions (the injection hook would stick around till the next minibuffer). So the cleanup is scheduled with `(run-at-time 0 nil ...)`, instead. Before this scheduling method I was attaching the cleanup function as `:after` advice on the action command (I get a chance to know what the command is right before in runs, in the exit function of `set-transient-map`), but that didn't run cleanup if you quit in the middle of the command.

I'll think about this whole mess some more, there's probably a better way to do it.

**Comment by oantolin** [comment]
There is a better way! I never should have let [this StackExchange answer](https://emacs.stackexchange.com/questions/55070/how-to-call-a-keymap) talk me into using `set-transient-map` and then going through extreme contorsions to arrange for cleanup to run after the action...

Oh well, live and learn. I'll rewrite everything to just use `read-key-sequence` and run actions under control of `embark-act`. Yes it is tedious to fully emulate the command loop, but I don't actually want all the command loop features for actions: they shouldn't be recorded in the general command history, for example. No elaborate cleanup will be necessary beyond `minibuffer-with-setup-hook`'s neatly self-destructing hooks.

I'll do the rewrite in a separate branch, test myself extensively and then merge when it's ready. Right now it looks like the code will be *much* more straightforward that way. After that change it will be easy to do things like toggle exit/noexit at the last minute, and setup exit/noexit defaults per action.

**Comment by minad** [comment]
Oh okay, while I originally wondered why you are using transient maps, I think they are not that bad in the current setting. I wonder if this read-key-sequence approach is a good idea. I tend to think it is not. Is it keymap based? The good thing is that the keymap based approach works so nicely with which-key for example. I would only consider doing this if it really gets much much simpler, otherwise I would prefer the current setting and I would only refactor the logic around the keep-alive handler etc.

Note that you can also easily replace set-transient-map with your own version. set-transient-map is a very simple function only pushing a override-terminal-local-map (or how this thing is called) and setting up a pre-command-hook! If set-transient-map is limiting you, I recommend instead to write your own version. I did this for my hydra implementation and it works really well. And it also takes the magic out of set-transient-map if you control all the hooks yourself.

**Comment by minad** [comment]
In my implementation of hydra it boils down to the following (https://github.com/minad/polyp/blob/master/polyp.el#L370):

Setup:

~~~ elisp
            (add-hook 'pre-command-hook (polyp--handler polyp--stack))
            (setq overriding-terminal-local-map ,name
                  polyp--active t)
~~~

Reset:

~~~ elisp
            (remove-hook 'pre-command-hook (polyp--handler polyp--stack))
            (setq overriding-terminal-local-map nil
                  polyp--active nil)
~~~

All my custom keep alive logic and so on lives within my custom command hook.

**Comment by oantolin** [comment]
If you want to see what I have in mind, check out this [mock up](https://github.com/oantolin/embark/blob/simplified-actions/plan.el) of `embark-act`. As you see, it would still use exactly the same keymaps as currently, and it does locally assign to `overriding-terminal-local-map`. I'll take a look at your `polyp.el`, but I don't anticipate any problems with the approach sketched in `mock-act`.

Why do you think `read-key-sequence` is a bad idea?

**Comment by oantolin** [comment]
The point of using `read-key-sequence` after setting up `overriding-terminal-local-map` is to control when and under what circumstances the action is run. All of nasty parts of the current action code have to do with the difficulty of scheduling cleanup at the correct time. If I run the action directly, there is no delicate scheduling problem.

**Comment by minad** [comment]
I guess, I cannot give you a good argument here - but to me read-key-sequence feels like a hack which somehow works against how things are usually done using keymaps. From what I've learned with hydra etc - there everything is done purely using transient maps and I think the setting is pretty similar to what we have here. In the hydra setting it is not sufficient to use set-transient-map since it is too restricted, but a hand-rolled version using pre-command-hook and overriding-terminal-local-map works well, as I mentioned before.

In Polyp I am using wrappers around all the commands, in order to perform operations before and after the actual operation - but this is something you want to avoid. But since you can do arbitrary rewriting of this-command in the pre-command-hook, you could rewrite it to some kind of dynamic wrapper which allows you to perform some cleanup directly after the command. I am unfortunately not deep enough into the embark code base to say something more qualified...

**Comment by oantolin** [comment]
Well, don't think of the action keymaps as really being keymaps in the same sense a minor mode's keymap is a real keymap: the embark action keymaps are more like menus. You wouldn't object to using `read-char` to read a character with a prompt like `"[c]opy, [d]elete, or [r]ename"`, right? You probably wouldn't say: "oh, don't use `read-char`, to prompt the user and then run the appropriate command inside this same function, instead what you should do is set up an `overriding-reminal-local-map` with the appropriate bindings for `c`, `d` and `r`, have your function end and then execute whatever cleanup is need afterwards in the commands you bind in the overriding keymap".

I'm pretty sure my approach will work well and be much simpler than dealing with this tricky inversion of control. I feel confident enough about this that I still plan on at least trying it. The worst that can happen is that it doesn't work out and I never merge the branch.

**Comment by oantolin** [comment]
I think I can be clearer about the difference between embark actions and hydras: it's that actions are all one-shot, while for hydras, some commands exit the hydra and some don't. For a hydra where every single key exits the hydra, which is essentially what `embark-act` is, a simple `read-key-sequence` is enough.

**Comment by minad** [comment]
Sure, go ahead. Maybe it is simpler in the end. The menu argument you are making here is reasonable, this is indeed different from the hydra like setting where you still want to potentially pass through some other keys, while keeping the hydra is alive. You can also achieve that with the read-key-sequence approach, I guess. But at some point you will have more logic in the loop and then the transient map turns out simpler again.

**Comment by minad** [comment]
@oantolin I guess we wrote done the same thought at the same time.
