### ISSUE TITLE
手动安装提示没有 compat

### ISSUE THREAD

**Issue by KMPrg** [oantolin/embark#631]
OS：win10
环境：msys2
Emacs version：27.2

init-embark.el 
code:
(require 'embark)
(require 'embark-consult)
(global-set-key (kbd "C-. k") 'embark-act) ; pick some comfortable binding
;; (global-set-key (kbd "C-. t") 'embark-dwim) ; good alternative: M-.(find a tag)
;; Optionally replace the key help with a completing-read interface
(setq prefix-help-command #'embark-prefix-help-command)

Warning (initialization): An error occurred while loading
File is missing: Cannot open load file, No such file or directory, compat

只能用包管理器安装吗？

**Comment by oantolin** [comment]
You need to install the compat library too. Usually package managers should take care of installing dependencies for you automatically, but if your package manager didn't do that, just install an up to date compat manually.

**Comment by oantolin** [comment]
Out of curiosity: are you using the straight package manager? It has been failing to update compat recently.
