### ISSUE TITLE
Add replace-string to embark-pre-action-hooks

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#634]
I added a Keymap Hierarchy to the wiki.  I made it by editing the output of `occur` from `embark.el`.  The last step in that process I wanted to delete all occurrances of "(defvar-keymap " from the buffer.  I marked the region and wondered if embark had a command for this, and not surprisingly it didn't.  I could delete the region with `backspace` but not act on all occurrances.

The way I settled on was to mark the string as region and copy it with `M-w` (or `C-. w`) and then use `replace-string`.  Then I wondered if I did `C-. M-x replace-string` would embark fill in the from string which it did; but with `transient-mark-mode` enabled, the replacement was just the original string, not the whole buffer.  I was going to write a custom command to make this work and then remembered and found `embark-pre-action-hooks` which sets up `query-replace-regexp` to work in my exact situation. Thanks!

So I think `replace-string` should be in `embark-pre-action-hooks` just like `query-replace-regexp`.  Also is there a better way for me to add this to alist then the following?  I use the package [visual-regexp](https://github.com/benma/visual-regexp.el/) so need to do this in my config anyway.  Perhaps the README could include an example of adding to `embark-pre-action-hooks`. 

```elisp
(add-to-list 'embark-pre-action-hooks
      '(replace-string embark--beginning-of-target embark--unmark-target))
(add-to-list 'embark-pre-action-hooks
      '(vr/replace embark--beginning-of-target embark--unmark-target))
(add-to-list 'embark-pre-action-hooks
      '(vr/query-replace embark--beginning-of-target embark--unmark-target))
```

**Comment by oantolin** [comment]
Yes, that's a perfectly good way to add hooks. 

And thanks for the suggestion, I will add a hook for `replace-string`. I personally use `query-replace` for this, but mostly because it has a key binding. If you like that `replace-string` does not  prompt for confirmation, you might want to give it a global key binding or a key binding in `embark-general-map`.

**Comment by hmelman** [comment]
Thanks.  I have long bound `replace-string` to `M-&` and have the [visual-regexp](https://github.com/benma/visual-regexp.el/) equivalents bound to `C-M-&` and `C-M-%`.

**Comment by oantolin** [comment]
I forgot to say, thanks for adding the keymap hierarchy to the wiki!
