### ISSUE TITLE
Question: is it possible to embark-collect or embark-export and live-preview results under-cursor in a single buffer?

### ISSUE THREAD

**Issue by davidhaley** [oantolin/embark#640]
Hello,

It looks like `embark-export` supports `C-c C-f` to preview results; however, it opens one buffer per file. I would like to open a single buffer and resuse it while previewing results. It would be nice if this worked with `embark-collect` as well.

Thank you.

**Comment by oantolin** [comment]
`embark-export` produces buffers in a variety of major modes. I think you are probably think of using it with something like `consult-grep` to get a grep-mode buffer or with `consult-line` to get an occur-mode buffer, is that right? Both grep-mode and occur-mode have `C-c C-f` bound to `next-error-follow-minor-mode`, a minor mode in which moving the cursor over a search result will display the corresponding location. This `next-error-follow-minor-mode` is built-in Emacs functionality and not provided by Embark.

**Comment by oantolin** [comment]
I have to say, I'm not entirely sure how you want `next-error-follow-minor-mode` to behave. For starters, it seems very natural to me to open different files in different buffers and I can't imagine you really want them all to overwrite the contents of a single buffer. Maybe you meant you want all these buffers displayed in the same window? But that is how it seems to behave by default in my limited testing.
