### ISSUE TITLE
Consult async search commands default to searching the entire project regardless of the directory being acted upon

### ISSUE THREAD

**Issue by ashlineldridge** [oantolin/embark#641]
The default value of `consult-project-function` results in project.el being used to determine the project root. If this variable is set, `consult-ripgrep` and its friends will use it rather than `default-directory` as mentioned [here](https://github.com/minad/consult/blob/c0f792740a0aca38c64eea711ab395a11f38f0d1/consult.el#L4788-L4796). Is this the intended behaviour? Because it means that when acting upon a file/dir and selecting `consult-ripgrep` the value of `default-directory` that is set by Embark is not used by default.

As a workaround, I've written the following function and bound it into `embark-consult-search-map` to replace `consult-ripgrep`:

```elisp
  (defun my/consult-ripgrep-default-directory (&optional dir initial)
    (let (consult-project-function)
      (consult-ripgrep dir initial))))
```

I noticed [this commit](https://github.com/oantolin/embark/commit/958d158f00919e17fcaedc08a811f4ee9cf0a059) ("DWIM behavior for consult-async commands"). Is the intention that users set `consult-project-function` to `nil`?

**Comment by oantolin** [comment]
No, that was not intended. I probably missed this issue because I must have tested only on directories not inside a project.

**Comment by oantolin** [comment]
Should be fixed now, thanks for reporting!

**Comment by ashlineldridge** [comment]
@oantolin The fix seems to only address `consult-grep` but not the other members of `embark-consult-async-search-map` such as `consult-ripgrep`.

**Comment by oantolin** [comment]
That is correct, @ashlineldridge. I didn't see any use of `consult-project-function` in their docstrings. And the docstring of `consult-project-function` only mentions `consult-grep` and `consult-buffer` as using it. I didn't check the consult source code to verify the information from the dosctrings. Do the other commands also use `consult-project-function` in an undocumented way? (It made sense to me that, for example, `consult-ripgrep` would not use `consult-project-function`, since ripgrep itself knows how to search git repos.)

**Comment by oantolin** [comment]
At least `consult-ripgrep` *does* use `consult-project-function`. Probably all the async search functions do.

**Comment by ashlineldridge** [comment]
@oantolin `consult-ripgrep` and `consult-git-grep` both reference `consult-grep` in their documentation ([here](https://github.com/minad/consult/blob/main/consult.el#L4885) and [here](https://github.com/minad/consult/blob/main/consult.el#L4853)) for the user to read the full documentation. And all 3 grepping functions delegate to `consult--grep` to do the actual work.

I was almost going to set `consult-project-function` to nil but noticed it is referenced quite a bit so erred on the side of leaving it with its default setting. But yes, I'm pretty sure all of the async search functions use `consult-project-function`.

**Comment by oantolin** [comment]
According to a quick experiment I just ran, of the async consult functions, namely,

- `consult-locate`,
- `consult-find`,
- `consult-git-grep`,
- `consult-ripgrep`, and
- `consult-grep`,

the only one that does *not* use `consult-project-function` is `consulte-locate` (which makes sense). I'll add the hook for the others.

**Comment by ashlineldridge** [comment]
Yes, that confirms what I'm also seeing. Thank you!

**Comment by ashlineldridge** [comment]
Out of interest, is there ever a use-case to leave `consult-project-function` non-nil if you're acting on a directory (and running a consult command)? Just wondering whether it could be done more generally.

**Comment by oantolin** [comment]
> is there ever a use-case to leave `consult-project-function` non-nil if you're acting on a directory

I mean, it's up to the user what acting on a directory or file means. Here I am agreeing with you that it should mean "any searches should run in the directory or the directory containing the file", but some else might prefer it to "any searches should run in the project containing the directory or file".

**Comment by ashlineldridge** [comment]
Sure, that makes sense.

**Comment by oantolin** [comment]
And yet a third person might prefer it to mean "when acting on a directory, any search should run in that directory; when acting on a file, any search should run in the *project* containing the file"! Maybe that's actually better?

**Comment by oantolin** [comment]
OK, so I added the same hook to all async search commands (including `consult-locate`, which doesn't need it 🤷🏽). For now the rule is "if the target has an associated directory as reported by `embark--associated-directory`, then set `consult-project-function` to nil". If someone complains in the future that, I don't know, they want that rule for directories, but not for files or buffers, which should instead use the project, we'll deal with that then,

**Comment by oantolin** [comment]
> if acting on a file resulted in the directory containing the file being searched that's totally fine too

That is indeed what happens now with these changes. I think that's fine since `consult-grep` and friends are really directory searching tools, not single-file searching tools.
