### ISSUE TITLE
How to not use embark in Python mode?

### ISSUE THREAD

**Issue by mlouielu** [oantolin/embark#642]
Hi all, I encounter a problem when using embark, I use Emacs in terminal for a long time but is a newbie in setting anything up.

I have use example setup from README quickstart section. But after setting it up, when I want to edit Python code,
e.g. TAB to indent the following code:

```python
def main():
<TAB>pass
```

It will shows `embark-act` buffer and said: `Act on identifier ‘pass’`, inside the minibuffer, the TAB is `embark-cycle` and I don't see any  command descriptions is something similar to `indent`.

How could I setup embark correctly in this situation, or did I miss anything? 

Thanks

**Comment by mlouielu** [comment]
I see TAB bind to embark-act via embark-bindings:

```
1/4    Command: TAB                                                                                                                                                          
TAB                                  embark-act                         Prompt the user for an action and perform it.                                                        
M-g TAB                              move-to-column                     Move point to column COLUMN in the current line.                                                     
C-x TAB                              indent-rigidly                     Indent all lines starting in the region.                                                             
C-x C-k TAB                          kmacro-insert-counter              Insert current value of ‘kmacro-counter’, then increment it by ARG.                                  
```

But the `embark.el` didn't have this binding, how should I remove it?

**Comment by oantolin** [comment]
Embark does not bind `embark-act` to any key. That binding must be in your personal configuration (or in some other package you have installed). You should figure out how you are binding it, and remove that binding. As you said, it is not in `embark.el`.

**Comment by oantolin** [comment]
Did you figure out how you were binding `embark-act` to `TAB`?

**Comment by mlouielu** [comment]
> Did you figure out how you were binding `embark-act` to `TAB`?

I tried several ways to debug this problem (`C-h k`, `C-h b`, `rg TAB`, rg `embark-act` ...etc), but have no luck where it comes up. Is hard for me to isolate this phantom binding with my configs, it only occurs when I enable embark. (I am not sure if I am correct, can Emacs setup a keybinding without the command exist? i.e. if I enable other package, can they bind global-set-key with `embark-act`?)

Currently my workaround is, `global-unset-key` the TAB then `global-set-key` the TAB again. It is not ideal but can defer this issue a little bit.

**Comment by oantolin** [comment]
Do you use Doom or another such configuration framework? Maybe that's what's binding `embark-act`. You could try grep ping for `embark-act` in your `.emacs.d` and in the files for your starter kit if you use one.

**Comment by mlouielu** [comment]
I think I find the problem. I find it by the follow test:

```bash
emacs -Q -nw
C-h k
C-i
```

It shows that `C-i` is bound to `TAB`.

And in my  embark setting, I bind `embark-ack` under `C-i`, that could be the reason I change the `TAB` binding to `embark-ack`. After I re-bind the key to another key-binding, then it will not change the `TAB` behavior.

I would like to suggest that in the README keybinding setup part could say more about this:
https://github.com/oantolin/embark/blob/c5ac899d87992c4206a9a01e6355369d088b9f75/README.org?plain=1#L386

I am not sure how this can be improve, but I can tell my experience: so after reading the above line, I change the `C-.` binding to `C-i` binding, at that moment I don't know `C-i` is bound to `TAB`, and Emacs didn't show any warning or message said that it has conflict or defined.

Thanks again @oantolin, I am very appreciate your time to help me out of this. Thanks!

**Comment by oantolin** [comment]
Oh! Know you've learned a bit of computing history/trivia. TAB and C-i are exactly the same character in ASCII!
