### ISSUE TITLE
eldoc error: (wrong-type-argument number-or-marker-p nil) When on org-list 

### ISSUE THREAD

**Issue by schrenker** [oantolin/embark#645]
Hello,

I have a problem specifically on linux, on WSL2, Ubuntu-22.04, where if point is on element of a list, link or checkbox item, I get an error, and also I cannot use any embark command (dwim, or act). I use the same config on WSL2 and on macos, and this occurs only on WSL2. I use emacs 29.

eldoc error: (wrong-type-argument number-or-marker-p nil) 

It works normally on regular text or org headings, and anywhere else outside of an org mode.
![image](https://github.com/oantolin/embark/assets/42305809/bed0f8f8-8c01-48f1-bc41-48a5b2f35941)
![image](https://github.com/oantolin/embark/assets/42305809/cd833577-3880-4985-949d-fa4aedfc916b)

I was able to nail down, that something embark--targets does is being broken. Below text and heading working, and list not working:
![image](https://github.com/oantolin/embark/assets/42305809/2ad80cdf-76bf-4c81-920c-c56355250b63)
![image](https://github.com/oantolin/embark/assets/42305809/6278e11c-2791-4193-ae70-dd97bde2388d)

![image](https://github.com/oantolin/embark/assets/42305809/ec872f1f-126d-4ad5-a435-3ee0c61344e5)

I tried to get some debugging information from that function, and I tried to understand something from it, but without success:
![image](https://github.com/oantolin/embark/assets/42305809/cb3b100f-4333-4663-bf19-4e3f905f5ee9)

My embark config can be found here https://github.com/schrenker/emacs.d/blob/master/init.el#L728 . I would appreciate the help with this issue.

**Comment by oantolin** [comment]
I haven't been able to reproduce this. Maybe that means that it is due to some change in Emacs 29 (I'm on 28.1). What version of Org are you running? (You can run `M-x org-version` to find out.)

**Comment by oantolin** [comment]
Does it also happen if starting from `emacs - Q` you only load Org and Embark? Having a minimal way to reproduce it from `emacs - Q` would be extremely helpful.

**Comment by schrenker** [comment]
I am sorry, turns out I was using bleeding edge org mode. With builtin org this doesn't happen. Thanks for your time, and sorry for confusion :)

**Comment by oantolin** [comment]
Ah, but that means I still may need to fix this soon. So I'll update my Org, and try to reproduce.
