### ISSUE TITLE
Make embark-act-all act like embark-act when there are no marks

### ISSUE THREAD

**Issue by walseb** [oantolin/embark#649]
Hello!

Is there a way to have `embark-act-all` act like `embark-act` when there are no marks/selections? Just as `dired-do-delete` for instance does in `dired`?

Currently, running `embark-act-all` without anything selected causes it to run the command on all entries. When you start to select entries, only those are acted on. With `dired-do-delete` on the other hand, if no entries are selected, only the entry under the cursor is acted on. Otherwise what's acted on is the same between the two.

If this is possible, I won't need to bind `embark-act` at all, and can do with just `embark-act-all` unless I want to for some reason ignore the marks I have made and only act on what's under the cursor.

Thoughts?

**Comment by oantolin** [comment]
I wouldn't want to change the definition of `embark-act-all`, but you can easily write a function that behaves as you describe:

```elisp
(defun embark-act-all-or-one ()
  "Act on the selection or, if empty, on the target or targets at point."
  (interactive)
  (if embark--selection (embark-act-all) (embark-act)))
```

**Comment by walseb** [comment]
That's perfect! Thank you so much!

**Comment by minad** [comment]
@oantolin Shall we change the behavior of `embark-act` to behave like `embark-act-all` if there are selections? This would make `embark-act` more dwimmy but likely more in line with the expectations of most users. Iirc I've been against such a change earlier, but maybe it is time to reconsider. ;)

**Comment by oantolin** [comment]
People like modal interfaces, don't they? That suggested change would mean that once you make a selection, you lose the ability to act on anything but that selection until the selection is gone! The selection becomes like a dialog box you need to dismiss before you can get back to normal Embark.

I'm not sure I agree with making this inflexible behavior the default. It's not just  a theoretical preference for freedom in my case, I do take advantage of that freedom. For example, a couple of times I've selected several defuns to move them together; while moving around looking for the defun I want I sometimes notice something else I need to fix and just do it along the way, and this can involve embark-act because I often use it to duplicate or delete an s-expression. I'd need to remember that I am forbidden from using embark-act until I finish with the selection!

**Comment by oantolin** [comment]
Another example I've come across: sometimes when attaching multiple files from some directory to an email I notice a file I want to delete. I want to build up a selection of those files and when I spot the errant file I can just delete it and then continue selecting files.

**Comment by oantolin** [comment]
> The problem is also that we cannot select again via embark-act if embark-act suddenly becomes embark-act-all.

Well at least this problem is somewhat reduced now that embark-select can be called directly to select the first target at point. But yeah, if embark-act acted on non-empty selections, you would only be able to extend the selection by targets that happen to be the first target at some point.

**Comment by oantolin** [comment]
As for rethinking designs, what if we unified single targets and selections of targets? This would also unify target finders and candidate collectors. We could have the selection (when non-empty) be the highest priority target, then all the current targets and have as lowest priority the "selection of all targets". Then embark-act could serve as both the current embark-act and as embark-act-all, you'd choose which behavior you want by target cycling.

That would also allow you to define multiple candidate collectors and choose which to export by cycling. Currently you cannot choose what to export, it's always the first candidate collector to return non-nil.

**Comment by minad** [comment]
Tbh this doesn't sound convenient and easy to understand if I would have to cycle between single target and multiple targets. Multiple candidate export is also quite costly, so cycling wouldn't work nicely. However it would be nice to support selecting among different collectors in embark-export/collect/act-all.

**Comment by oantolin** [comment]
> Tbh this doesn't sound convenient and easy to understand if I would have to cycle between single target and multiple targets.

I agree! I was just trying out an idea but I don't really like it either.

> However it would be nice to support selecting among different collectors in embark-export/collect/act-all.

Yeah, though I'm not really sure there are  many users for that ability. The only one I can remember off the top of my head is for buffer table of contents, picking between outline and imenu candidates.

**Comment by minad** [comment]
> Yeah, though I'm not really sure there are many users for that ability. The only one I can remember off the top of my head is for buffer table of contents, picking between outline and imenu candidates.

You are right. There are not many such scenarios and this hasn't been requested before. One could also distinguish different exporters, e.g., see #560. Not sure if it makes sense to offer an interactive feature to switch. For special use cases, users could define their own commands which adjust the candidate collectors and exporters as desired.

The overall design for act/act-all/select we have currently seems good as is. It is hard to make the design better without affecting the current usage of Embark. I like to only bind embark-act and embark-dwim and this should be enough.

If users prefer a slightly different UI they can define wrapper commands as you suggested in https://github.com/oantolin/embark/issues/649#issuecomment-1633364659. Embark provides the necessary building blocks. I find it important that we do not make the building blocks worse, which may happen if we make commands more dwimmy. Then the commands behave less predictably and are harder to compose.

**Comment by hmelman** [comment]
I haven't really played with embark-select but in the interest of exploring making it more similar to dired:

Make it easy to select-all.  Maybe that's a separate command or an arg to embark-select.  I think in dired the analogy would be dired-toggle-marks when nothing is marked.

Have an embark-act-dwim that behaves as your embark-act-all-or-one.  To make it very much like dired and handle your one off-action when there are selections, let it take a numeric argument and if it's 1, it acts on the current candidate, not the selection (really the next N candidates for arg N).   embark-act-dwim could subsume embark-act-all at the cost of having to select-all first (which is hopefully via just one key).

To really go all out (and I don't recommend this for embark), support dired flags, allowing multiple simultaneous sets of selections.

**Comment by hmelman** [comment]
> @hmelman `C-. A SPC` selects (or rather toggles) all. If this key sequence is too long you can define a kmacro and bind it to a key. :)

touché :) 

> While coherent behavior with Dired may be nice, I think the analogies break down quickly. I also like the Embark design actually more where the SPC key toggles instead of separate mark unmark keys.

I agree with both points, was just exploring the idea.  I think dired behavior is better suited to collection buffers than work in the minibuffer (I never understood the appeal of something like `helm-mini`). I was also misremembering, I was thinking that embark-act-all had a suggested top-level global-binding, which would be appealing to remove.

I do think the docstring for `embark-act-all` should be updated to explicitly describe it's behavior when there's a selection.

**Comment by oantolin** [comment]
> I do think the docstring for `embark-act-all` should be updated to explicitly describe it's behavior when there's a selection.

Good idea, @hmelman! Does this sound OK? 644fb1022a694ce8ce5367658b7ebc910d94edc9

**Comment by oantolin** [comment]
> I also like the Embark design actually more where the SPC key toggles instead of separate mark unmark keys.

I like it better too, @minad. I think that was your idea, I was going to imitate dired with its separate marking and unmarking commands.
