### ISSUE TITLE
consult-line + embark-occur -> nil error

### ISSUE THREAD

**Issue by minad** [oantolin/embark#65]
I also mentioned this before but then it has been gone for a while but now I am seeing the bug reproducible every time I press RET in the occur buffer. The error occurs in `embark-default-action` and `call-interactively`. 

~~~
Debugger entered--Lisp error: (wrong-type-argument commandp nil)
  call-interactively(nil)
  embark-default-action()
  embark-occur-choose(#<marker (moves after insertion) at 225 in *Embark Occur*>)
~~~

This only happens for the first call of `consult-line` and `embark-occur`!

**Comment by oantolin** [comment]
Another one I can't reproduce. 😢 I tried from my config and also from emacs -Q as follows:

Evaluate this in `*scratch*`:

```elisp

(load "~/my-elisp-packages/embark/embark.el")
(define-key minibuffer-local-completion-map (kbd "C-:") #'embark-act)
(setq completion-styles '(orderless))
(package-initialize) ; for consult autoloads (I'm using the MELPA version now)
```

Then I open a file with some text in it and run `M-x consult-line RET something C-: O` to get an occur buffer. Pressing `RET` works.

**Comment by oantolin** [comment]
I'd really appreciate a recipe to reproduce.

**Comment by minad** [comment]
Using emacs -Q is feeling as if my hands have been hacked off. Not such a good idea to rebind basic keys...

**Comment by minad** [comment]
@oantolin I have problems reproducing this, I will let you know when I manage to find a good recipe!

**Comment by oantolin** [comment]
Still unable to reproduce.

**Comment by minad** [comment]
@oantolin I will look at this again soon!

**Comment by minad** [comment]
I am not observing this error anymore
