### ISSUE TITLE
Change the prompt string in the completing-read-prompter from "Command: " to "Command on %s: "

### ISSUE THREAD

**Issue by doolio** [oantolin/embark#655]
I replace the key help with a completing-read interface as suggested in the README and this replaces `which-key` for me. This is really nice feature. Is it possible to change the prompt string in the completing-read-prompter from `"Command: "` to `"Command on %s: "`?

I believe this is what was _originally posted by @karthink in https://github.com/oantolin/embark/issues/186#issuecomment-887971027_.

Thanks for your time and this package.

**Comment by oantolin** [comment]
Mmh. We could do this, of course, but to me it would feel redundant with the indicators. For example in this screenshot I'm using the minimal indicator and it clearly shows right above the `Command:` prompt what I am acting on.
![image](https://github.com/oantolin/embark/assets/2635478/c9788b9e-e375-47a5-854d-4ddaa03169b8)

**Comment by doolio** [comment]
Oh yes, sorry for not being clear from the start.
