### ISSUE TITLE
embark-multitarget-actions not working

### ISSUE THREAD

**Issue by localauthor** [oantolin/embark#657]
Hello!

Starting with this commit 9a44418c349e41020cdc5ad1bd21e8c77a429062, when `embark-quit-after-action` is non-nil, `embark-act-all` bypasses the multitarget-action functionality, and therefore passes single arguments rather than a list.

Any thoughts on how to resolve this?

Thank you!

**Comment by oantolin** [comment]
Thanks for catching that! I made a logic error in that commit, which I believe is now fixed.
