### ISSUE TITLE
Binding non-actions to embark keymaps

### ISSUE THREAD

**Issue by minad** [oantolin/embark#66]
Trigger warning - I am about to ask for more type errors. 

Since I am using Embark as a context menu in the minibuffer I would like to bind both `marginalia-cycle-annotators` and `consult-preview-mode` there (this could also go into the marginalia or consult docs as examples!). But obviously these are type-errors. My question is if it somehow possible to avoid the consumption of embark--target. If it turns out that this is possible, this could also be used for embark-occur, embark-live-occur and embark-export since they all consume and ignore embark--target afaik. I asked this before, but I guess it somehow got lost in the discussions. Basically this is the thing which is missing to make the embark keymaps fully "general purpose" and easier to use.

PS: @oantolin Sorry for flooding you here with questions and issues. There is no hurry in answering those, but I think it is better to have things documented/reported somewhere instead of them getting lost.

**Comment by oantolin** [comment]
I think the requirement on `embark--target` being consumed was necessary for an old strategy for scheduling cleanup. It is possible that this is not necessary anymore, I'll investigate.

Don't worry about flooding the issue tracker, I agree that it's better to have things documented here.

**Comment by minad** [comment]
I should add, I tested `consult-preview-mode`, `marginalia-cycle-annotators` and `marginalia-mode` via `embark-act-noexit M-x` and they all seem to work nicely!

**Comment by minad** [comment]
If this works out from the side of embark, I will probably add `nil` to `marginalia-annotators` and then we have a configurable minibuffer via embark :)

**Comment by oantolin** [comment]
I think the new cleanup scheduling strategy really does take care of this and actions are no longer required to consume `embark--target`. Already `embark-live-occur` was not consuming the target and did work as an action. I'm removing the `(ignore (embark-target))` from `embark-occur` and `embark-export`.

**Comment by oantolin** [comment]
I'm closing this, but we can reopen if some edge case comes up.

**Comment by minad** [comment]
@oantolin Now that we have changed actions such that they are not invoked from the minibuffer, our `marginalia-cycle-annotators` is not working as nicely anymore :(

I have to fix this somehow, by jumping back to the minibuffer!

**Comment by oantolin** [comment]
Popping to embark--target-buffer is causing all sorts of headaches for me. Somehow `set-buffer` was fine, but actually selecting the window fixes the `consult-line` stuff but causes other problems.

**Comment by oantolin** [comment]
In the case of `marginalia-cycle-annotators` I think it would be reasonable to change it to say "if any minibuffer is active, change them locally there".

**Comment by minad** [comment]
> 
> Popping to embark--target-buffer is causing all sorts of headaches for me. Somehow set-buffer was fine, but actually selecting the window fixes the consult-line stuff but causes other problems.

What other things? It would be nice if we could keep it like this since I think it is the right thing to do. But if it turns out that is really not possible, I can also replace the consult `recenter` with a hack.

> In the case of marginalia-cycle-annotators I think it would be reasonable to change it to say "if any minibuffer is active, change them locally there".

Yes, working on that right now.

**Comment by minad** [comment]
See https://github.com/minad/marginalia/commit/5cf66a3349663a5de0983472e16da43aa9a07d0a. Works nicely when bound to "A" in embark-general-map. I will add this to the readme too!

**Comment by oantolin** [comment]
> Popping to embark--target-buffer is causing all sorts of headaches for me. Somehow `set-buffer` was fine, but actually selecting the window fixes the `consult-line` stuff but causes other problems.

No more headaches. The rewrite took care of all of this. 😄
