### ISSUE TITLE
GNU ELPA build of `embark-consult` includes file "embark-org.el" (which includes an outdated file)

### ISSUE THREAD

**Issue by alphapapa** [oantolin/embark#664]
Hi Omar,

I was happy to find this fix the other day: https://github.com/oantolin/embark/commit/3ffb27a833d326ccf7e375bb9d94ebf4dc37fa77  However, even after upgrading `embark` in my config, the problem persists.

After investigating, I find that the library `embark-org` is being loaded from the package `embark-consult`, which I have installed at v0.7 from GNU ELPA.  The [MELPA recipe](https://github.com/melpa/melpa/blob/master/recipes/embark-consult) only includes "embark-consult.el", but the GNU ELPA build includes "embark-org.el", and at a version that does not include that fix.

Thanks for your work.

**Comment by oantolin** [comment]
I'm afraid I don't know how to solve this. I only agreed to the GNU ELPA but have no idea how they actually get made.

**Comment by oantolin** [comment]
embark-org should be a part of the embark package, not of the embark-consult package.

**Comment by oantolin** [comment]
I should find out how to fix this but in the meantime, @alphapapa, I'd recommend you use MELPA for embark and embark-consult.

**Comment by minad** [comment]
I think the issue has already been fixed on ELPA-devel. Maybe I asked
one of the ELPA maintainers about it, I don't recall. It should be
sufficient to bump the versions of embark and embark-consult, such that
we also get updated versions on ELPA stable.

**Comment by minad** [comment]
See
https://git.savannah.gnu.org/cgit/emacs/elpa.git/commit/elpa-packages?id=0d9c026a16afee10529ea42a98218693e39a8c82

**Comment by oantolin** [comment]
Looking into it, I think [this file](https://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/elpa-packages) is what decides what each package contains, and indeed, it seems to be fixed already:

```
 (embark		:url "https://github.com/oantolin/embark"
  :doc "embark.texi"
  :ignored-files ("embark-consult.el" "avy-embark-collect.el"))
 (embark-consult	:url "https://github.com/oantolin/embark"
  :ignored-files ("embark.el" "embark.texi" "avy-embark-collect.el"
                  "embark-org.el"))
``

**Comment by oantolin** [comment]
Oh, @minad as usual beat me to the punch and even quoted the exact commit that fixed it.

**Comment by oantolin** [comment]
OK. Will bump versions, then.

**Comment by oantolin** [comment]
By the way, shouldn't I just remove `avy-embark-collect`? It's not in any package, except possibly by mistake, and I sincerely hope no-one is using it...

**Comment by minad** [comment]
On 9/19/23 20:55, Omar Antolín Camarena wrote:
> By the way, shouldn't I just remove |avy-embark-collect|? It's not in
> any package, except possibly by mistake, and I sincerely hope no-one is
> using it...

It is available on MELPA (~600 downloads), so it should stay here,
unless you want to deprecate it and stop maintaining it. I don't use it,
never have, so I wouldn't mind. But there seem to be a few users at least.

**Comment by oantolin** [comment]
> It is available on MELPA (~600 downloads)

I'm so clueless! 😄 I must have known this, because I must have submitted it, but honestly did not remember. Maybe I should at some point officially deprecate it in favor `link-hint`.

**Comment by minad** [comment]
On 9/19/23 21:04, Omar Antolín Camarena wrote:
>     It is available on MELPA (~600 downloads)
> 
> I'm so clueless! 😄 I must have known this, because I must have
> submitted it, but honestly did not remember. Maybe I should at some
> point officially deprecate it in favor |link-hint|.

Haha, indeed you did https://github.com/melpa/melpa/pull/7359. Regarding
link-hint, I remember there were some technical problems which prevented
you from going forward with the avy-embark-collect deprecation.

Do you still use avy-embark-collect? If not you could also move it to a
separate repository for preservation and ping the MELPA maintainers to
drop it from the archive. 600 downloads is not much.

I personally try to avoid packages which have fewer than maybe 5k or 10k
downloads, except if I am happy to hack on the package myself. But some
of my lesser known packages don't even reach these threshold yet.

**Comment by oantolin** [comment]
I don't remember what the problem with link-hint was. It is what I use now instead of avy-embark-collect.

**Comment by oantolin** [comment]
I hope the GNU ELPA fix + the version bump here takes care of this, so I'm closing.

**Comment by oantolin** [comment]
@minad: I remembered what my problem with link-hint was, noctuid/link-hint.el#219
