### ISSUE TITLE
Dired file name targets with spaces

### ISSUE THREAD

**Issue by minad** [oantolin/embark#669]
File names with spaces are not supported right now. One can use the `dired-filename` property instead of searching for space as follows:

~~~ elisp
(when-let ((file (dired-get-filename nil t))
           (beg (next-single-property-change (pos-bol) 'dired-filename nil (pos-eol)))
           (end (next-single-property-change beg 'dired-filename nil (pos-eol))))
  ...)
~~~

**Comment by minad** [comment]
There are also functions `dired-move-to-filename` and `dired-move-to-end-of-filename`. Maybe using these is more convenient?

**Comment by oantolin** [comment]
Oh, the target string is correct but the bounds (which are probably irrelevant for all sensible file actions) are not. Is that what you mean?

**Comment by minad** [comment]
Sorry, should have been more precise. Yes, only the bounds are incorrect.

**Comment by oantolin** [comment]
Looks like `(cons (point) (1+ (point)))` is a good formula for `image-dired-thumbnail-mode`.

**Comment by oantolin** [comment]
Mmh.  The bounds are off by one on the heading line of a dired buffer too (that goes through another code path since dired does not think that line contains a file).

**Comment by minad** [comment]
Many thanks!
