### ISSUE TITLE
Rename embark-target-completion-at-point to embark-target-completion-candidate

### ISSUE THREAD

**Issue by minad** [oantolin/embark#671]
Hi Omar,

this is only a minor issue, if at all, but the naming confused me a little bit when I looked for something in the Embark source. We have `embark-target-collect-candidate`, so `embark-target-completion-at-point` should probably be renamed accordingly for consistency? I would also avoid the specific suffix `*-completion-at-point`, since this suffix is kind of reserved for completion at point functions (Capfs).

**Comment by minad** [comment]
Maybe also `embark-target-top-minibuffer-completion` -> `embark-target-top-minibuffer-candidate`? The `embark-target-*-candidate` finders should probably also come first in the list of the target finders or is there a specific reason for the current order?

**Comment by oantolin** [comment]
I agree about renaming `embark-target-completion-at-point` and
`embark-target-top-minibuffer-completion`.

I don't know why `embark-target-text-heading-at-point` has higher priority than the candidate collectors, that's probably just an editing mistake and I'll move it down; but `embark-target-active-region` *is* supposed to have the highest priority, that's intentional.

**Comment by oantolin** [comment]
How about this renaming:

- `embark-target-completion-at-point` → `embark-target-completion-list-item`
- `embark-completions-buffer-candidates` → `embark-completion-list-candidates` (or maybe `embark-completion-list-items`?)
- keep `embark-target-top-minibuffer-completion` as is.

I will also make `embark-target-text-heading-at-point` lower priority.

**Comment by minad** [comment]
Hmm, I like the name "candidate" better than "completion". Completion is more about the process and the completed string, but not so much about the candidates. Note that many UIs don't actually complete (in the sense of shell/TAB completion), they rather allow you to select.

- embark-target-completion-at-point -> embark-target-completion-list-candidate
- embark-target-top-minibuffer-completion -> embark-target-top-minibuffer-candidate
- embark-completions-buffer-candidates -> embark-completion-list-candidates

**Comment by minad** [comment]
Thanks!

**Comment by oantolin** [comment]
No, thank you, it was a good suggestion. Specially avoiding the phrase completion-at-point.
