### ISSUE TITLE
Embark export reuses currently open Dired?

### ISSUE THREAD

**Issue by minad** [oantolin/embark#675]
Hi Omar,

I observed that `embark-export` seems to reuse the currently selected Dired buffer. Is this expected or intended? This seems to happen also in emacs -Q on 29.1.

**Comment by oantolin** [comment]
It is not intended, but I thought we had already fixed that.

**Comment by minad** [comment]
On 11/2/23 19:55, Omar Antolín Camarena wrote:
> It is not intended, but I thought we had already fixed that.

Doesn't look like it. I have the newest Embark from ELPA-devel and run 29.1.

**Comment by minad** [comment]
On 11/2/23 19:55, Omar Antolín Camarena wrote:
> It is not intended, but I thought we had already fixed that.

I've found #527, but this solves a different problem - preventing Embark
buffers from being reused by Dired. What we want here is to prevent
normal Dired buffers from being reused by Embark.

The culprit is dired-find-buffer-nocreate, called like this:

embark-export-dired
  -> dired-noselect
  -> dired-internal-noselect
  -> dired-find-buffer-nocreate

I've not found a dynamic variable which could be bound to prevent this
from happening, but we could cl-letf bind (symbol-function
'dired-find-buffer-nocreate) to '#ignore in the exporter. Not sure if
this has other problematic side effects.

**Comment by oantolin** [comment]
Yep, #527 was what I was remembering incorrectly.

**Comment by minad** [comment]
Another maybe cleaner possibility could be to create a new buffer and then turn on dired-mode. Would that work?

**Comment by oantolin** [comment]
> Another maybe cleaner possibility could be to create a new buffer and then turn on dired-mode. Would that work.or is there too much going on in Dired, such that this approach would get too complicated?

Well, my idea in using `dired-noselect` was that that way I wouldn't need to find out everything that dired does. :) But maybe it's worth looking into it and handcrafting the buffer, though I have to say that I don't feel your fix added much complexity.
