### ISSUE TITLE
Question: Step-by-step how to embark-export a set of filenames and run a single consult-grep over them

### ISSUE THREAD

**Issue by rswgnu** [oantolin/embark#677]
Hi:

I use consult and have installed both embark and embark-consult.

I have read the embark README.org but can't follow the terse instructions there about using consult-grep with embark.

I want to export or collect a list of filenames, e.g. from find-file with vertico enabled, and then feed them to a single run of consult-grep.  Can you explain how to do this.  I just don't get how to take a captured list of items and apply them as multiple arguments to a single shell command essentially, though explaining it for consult-grep should be sufficient.

Thank you.

**Comment by oantolin** [comment]
You can't do this without writing some supplementary code, unfortunately. I don't think the consult-grep.command provides an easy way to specify a list of file names to search. The closest is that with a prefix argument, consult-grep prompts for a single starting directory.

**Comment by minad** [comment]
Iirc consult-grep can take a list of directories/files as argument and @rswgnu contributed that feature to Consult.

**Comment by rswgnu** [comment]
So even more generally, I want to understand how to feed a collection of items to either a Lisp command or a shell command, as that would be my prime use case of Embark.  Thanks.-- BobOn Nov 8, 2023, at 5:25 AM, Daniel Mendler ***@***.***> wrote:﻿
Iirc consult-grep can take a list of directories/files as argument and @rswgnu contributed that feature to Consult.

**Comment by oantolin** [comment]
Oh, I didn't remember @rswgnu contributed the multiple file case to `consult-grep`. I said earlier some code would need to be written, and this means the vast majority already has been written! Now you just need:

```elisp
(cl-pushnew 'consult-grep embark-multitarget-actions)
```

Now whenever you have multiple files targets available for embark to collect, you can use `embark-act-all` (notice the `-all`!) to run `consult-grep`. From within `embark-act`, `embark-act-all` is bound to `A` and `consult-grep` to `C g`, so if you bind `embark-act` to `C-.`, say, then you can run the multifile version of `consult-grep` with `C-. A C g`.

For example, from `find-file`, if the files matching the current input are exactly the ones you want, then directly use `C-. A C g`. Or if you want a few of those files, navigate to them, mark them with `embark-select` (`C-. SPC`) first, then do `C-. A C g`. If you want a more permanent list of the currently matching files, you can `embark-export` (`C-. E`) to get a dired buffer listing them and there you can use `C-. A C g` (or, mark some with dired's marking functions and then `C-. A C g` will only use the marked ones).

Note that without the `A` for `embark-act-all`, using `consult-grep` on a file has a slightly different meaning (which is also useful): it runs `consult-grep` not on the file, but on the entire directory containing the file; this also works on buffer targets, running `consult-grep` in the `default-directory` of the buffer.

**Comment by oantolin** [comment]
I think I should just add `consult-grep` to `embark-multitarget-actions` by default in embark-consult. I'll think through the interaction with the other configuration we have for `consult-grep`, before I do that, though.

**Comment by minad** [comment]
> I think I should just add consult-grep to embark-multitarget-actions by default in embark-consult. I'll think through the interaction with the other configuration we have for consult-grep, before I do that, though.

No, the default operation is to search for symbols at point, and not to search through files, isn't it?

**Comment by oantolin** [comment]
For file and buffer targets the default is to search the associated directory, for everything else it is to search for the text of the target. I think. I'll check carefully before I make any changes.

**Comment by oantolin** [comment]
OK, so the current embark hooks for `consult-grep` do the following when you use `consult-grep` as an action:

- For targets of type file, buffer, bookmark and Emacs Lisp library, run `consult-grep` with no initial input, ignoring projects, and in the "associated directory" which is what you'd expect except maybe for files: it is the containing directory unless the file *is* a directory in which case it is the file itself.

- For all other target types run `consult-grep` with the target text as initial input, and if the target was an active region, unmark it.

**Comment by rswgnu** [comment]
Perfect, thank you.  I hope this info makes it into the doc somewhere.On Nov 8, 2023, at 2:07 PM, Daniel Mendler ***@***.***> wrote:﻿

I think I should just add consult-grep to embark-multitarget-actions by default in embark-consult. I'll think through the interaction with the other configuration we have for consult-grep, before I do that, though.

No, the default operation is to search for symbols at point, and not to search through files, isn't it?

**Comment by oantolin** [comment]
I'm revamping the configuration for consult search commands, which is a little hard to understand currently since it involves the interaction between a few functions, a tiny bit of consult internals, and it doesn't take advantage of `consult-*grep`'s arguments.

Would it be confusing to keep the current meaning for a single (non-directory) file, that is, to search the containing directory and at the same time have the meaning for a list of files to be to search exactly those files? Specifically, would it be confusing that using a file and a list of a single file have different meanings?

**Comment by oantolin** [comment]
Also, I have a question for @minad: this ability to pass either a single directory or a list of files and directories only applies to the `consult-*grep` family, and not to `consult-find` or `consult-fd`, right?

**Comment by minad** [comment]
On 11/9/23 18:11, Omar Antolín Camarena wrote:
> Also, I have a question for @minad <https://github.com/minad>: this
> ability to pass either a single directory or a list of files and
> directories only applies to the |consult-*grep| family, and not to
> |consult-find| or |consult-fd|, right?

I think it also applies to consult-find.

**Comment by minad** [comment]
On 11/9/23 18:08, Omar Antolín Camarena wrote:
> Would it be confusing to keep the current meaning for a single
> (non-directory) file, that is, to search the containing directory and at
> the same time have the meaning for a list of files to be to search
> exactly those files? Specifically, would it be confusing that using a
> file and a list of a single file have different meanings?

Yes, I think this is confusing. I would prefer if acting on files always
searches only the given files. We should have a separate actions to
search the parent directory, or use some other means to achieve this.

**Comment by rswgnu** [comment]
Yes, I agree with Daniel.  If you want to search onecor more directories, collect them up.  If you send one or more files, the search should use them. On Nov 9, 2023, at 7:44 PM, Daniel Mendler ***@***.***> wrote:﻿
On 11/9/23 18:08, Omar Antolín Camarena wrote:
> Would it be confusing to keep the current meaning for a single
> (non-directory) file, that is, to search the containing directory and at
> the same time have the meaning for a list of files to be to search
> exactly those files? Specifically, would it be confusing that using a
> file and a list of a single file have different meanings?

Yes, I think this is confusing. I would prefer if acting on files always
searches only the given files. We should have a separate actions to
search the parent directory, or use some other means to achieve this.

**Comment by oantolin** [comment]
I guess that then when using consult-grep as an action on buffers, we should search `(or (buffer-file-name) default-directory)`.

**Comment by oantolin** [comment]
Done! The behavior should be pretty intuitive now. Please test and please let me know if the change in the manual is clear enough.

**Comment by oantolin** [comment]
First problem found with the new code I forgot @minad's advice: "Do not use bookmark-location since it does not return nil, but a string if the location is missing". I'll fix that when I'm back at the computer.

**Comment by rswgnu** [comment]
Could you point us to the change or include the text here.  We have hyperlinks for such things :-)-- BobOn Dec 6, 2023, at 4:29 PM, Omar Antolín Camarena ***@***.***> wrote:﻿
Done! The behavior should be pretty intuitive now. Please test and please let me know if the change in the manual is clear enough.

**Comment by oantolin** [comment]
Sure, it's this commit: 9551724
