### ISSUE TITLE
Make the embark--keymap available in some variable?

### ISSUE THREAD

**Issue by minad** [oantolin/embark#68]
Now I feel bad for asking this, since you removed all variables so nicely - can you make the current embark-keymap available again for the indicators. Alternatively (and probably better, but breaking the current indicator function), pass the keymap as argument to the indicator? I need this to show the keymap via which-key-show-keymap via the indicator function.

**Comment by minad** [comment]
This shows the keymap but breaks embark, the actions don't work anymore :(

~~~ elisp
  (setq embark-action-indicator
        (lambda ()
          (which-key--show-keymap "embark" (embark--action-keymap)
                                  nil nil nil))
        embark-become-indicator embark-action-indicator)
~~~

**Comment by minad** [comment]
Maybe @clemera knows how to fix this, since I think the original which-key config was due to him? @clemera, are you already using the new Embark version after the large refactoring?

**Comment by clemera** [comment]
No, I did not update it for my daily use but I just tried and can confirm my which-key prompter is broken. Hopefully we can have something like it back?

**Comment by minad** [comment]
@clemera It seems to work after I added 'no-paging!

**Comment by minad** [comment]
Unfortunately now, C-g is broken, but I guess this is expected since @oantolin removed the C-g ignore binding?

**Comment by oantolin** [comment]
Glad you guys figures this out before I even got here. 😄 

I'm a little surprised at the problem with `C-g`. How exactly did the which-key indicator break without `C-g`?

**Comment by minad** [comment]
Well, I expect the menu to open and then pressing C-g, I only want to close the menu, but not execute the full action. I am also using `embark-act-noexit`, so maybe `C-g` is broken for `embark-act-noexit` and should not really exit?

**Comment by oantolin** [comment]
Ah, `C-g` is indeed broken, for both `embark-act` and `embark-act-noexit`. 😆 Sorry, about that. I guess I'll restore the keybinding in `embark-general-map`. I got confused and thought some other change handled the `C-g`.

**Comment by oantolin** [comment]
Oh, that's not enough if I want `C-g` to cancel the exiting of `embark-act-noexit`. I'll handle this in the keymap-prompter.

**Comment by oantolin** [comment]
OK, I fixed the `C-g` problem and added support for `C-u` as well. (But not for digit-argument, which needs a little more work). 76072b9e6a44601969b179739b57f05cf4165291

**Comment by oantolin** [comment]
Your `embark-become-indicator` shouldn't work. 😉 

I can call the indicator function with the keymap, I'd prefer that to storing the keymap in a variable.

**Comment by minad** [comment]
> I can call the indicator function with the keymap, I'd prefer that to storing the keymap in a variable.

That would be great!

**Comment by oantolin** [comment]
Done! 457091c0159a32c02dda0f477e47d39aa69dc691

**Comment by oantolin** [comment]
Ah, the docstrings for embark-action-indicator and embark-become-indicator should mention the possible returns values of the function, as `embark--show-indicator`'s docstring explains. I'll do that later, and am writing this here so I won't forget.

**Comment by minad** [comment]
From my side this can be closed then!

**Comment by oantolin** [comment]
Excellent, I'll close it after updating those docstrings. I think I'll remove the possibility to return an overlay to be deleted: might as well return a lambda that does the deletion. Could you please update the wiki where it explains how to setup which-key?

**Comment by minad** [comment]
I will update the wiki - but my recommendation would rather be to have the most important configuration basics ready in the README, similar to how we have it in Marginalia and Consult. I consider which-key to be an essential - therefore I would like to see that there. Even if you are not using it, we can keep that info updated. Otherwise it will get out of sync too easily - at least if it is in the README and broken, it will be reported much earlier.

**Comment by minad** [comment]
For reference, it is this simple now:

~~~ elisp
  (setq embark-action-indicator
        (lambda (map) (which-key--show-keymap "Embark" map nil nil 'no-paging)
          #'which-key--hide-popup-ignore-command)
        embark-become-indicator embark-action-indicator))
~~~

**Comment by oantolin** [comment]
The become indicator that I said was broken was the one that called `(embark--action-keymap)`, since that is not how you get the become keymap! But the indicator function you just posted should work for both actions and becoming.

**Comment by oantolin** [comment]
I agree on including this in the readme. I'll do that tonight.
