### ISSUE TITLE
Disambiguate functions and variables in Elisp

### ISSUE THREAD

**Issue by minad** [oantolin/embark#680]
If there exists a function and variable in Elisp with the same name, they are not disambiguated automatically by Embark. Consider the following docstring:

~~~ elisp
"In docstrings the convention is to write the variable `jinx-languages'
or the function `jinx-languages', while checkdoc will warn if plain
`jinx-languages` is mentioned."
~~~

It would be nice to perform an automatic disambiguation in this case if possible. Do you think it makes sense to add this or is this another [waste of time](https://github.com/oantolin/orderless/pull/152#issuecomment-1805956701)? Maybe this is too much of an edge case. :wink:

**Comment by oantolin** [comment]
I think Embark will currently find both target types at each occurrence. Are you suggesting returning only one type depending on context, or just changing the priority so that the type mentioned in the surrounding text comes first?

**Comment by minad** [comment]
I think if the context uniquely specifies the type, only that type should be returned.

**Comment by minad** [comment]
We could take the bounds in `embark-target-identifier-at-point` and look
back for "variable `" or "function `" if the mode is Elisp and the
position is inside a string. If the current point is inside a string can
be determined with `(nth 3 (syntax-ppss))`, which is non-nil then. Then
the respective type should be prioritized.

**Comment by oantolin** [comment]
Sure, but maybe it would be worth it to list more contexts that disambiguate type: `let` means it's the variable, `symbol-function` and `#'` mean it's the function, etc.

**Comment by minad** [comment]
Indeed. This would be nice.

**Comment by minad** [comment]
Trying to detect the context everywhere is a lot of work, and all of this only to disambiguate. Reusing a name for variables and functions is not that common, so it doesn't seem worth to do this.
