### ISSUE TITLE
embark-act breaks on SourceHut URLs

### ISSUE THREAD

**Issue by jgarte** [oantolin/embark#684]
`embark-act` didn't select all of the following URL:

https://git.sr.ht/~whereiseveryone/confetti

WDYT

Screenshot of the failure:

![image](https://github.com/oantolin/embark/assets/47760695/26113d7b-7bdf-467f-a016-1f0f94d8aea0)

**Comment by oantolin** [comment]
I cannot reproduce this problem, for me embark does select the entire URL, even in `scheme-mode.` Also, in your screenshot you don't seem to running `embark-act`, but `isearch-forward-symbol` or something like that. Please add a recipe to reproduce the problem starting from `emacs -Q`, and then reopen this issue.
