### ISSUE TITLE
Compilation warnings with emacs-30

### ISSUE THREAD

**Issue by CaptainBloodz** [oantolin/embark#689]
`>>> Compiling source in /var/tmp/portage/app-emacs/embark-20231130.1735/work/embark-20231130.1735 ...
 * Generating autoload file for GNU Emacs ...
Package autoload is deprecated
  SCRAPE   .
  INFO     Scraping files for embark-autoloads.el... 
  INFO     Scraping files for embark-autoloads.el...done                                                                            [ ok ]
 * Compiling GNU Emacs Elisp files ...
Checking /var/tmp/portage/app-emacs/embark-20231130.1735/work/embark-20231130.1735/...
Compiling /var/tmp/portage/app-emacs/embark-20231130.1735/work/embark-20231130.1735/embark-autoloads.el...

In toplevel form:
embark-autoloads.el:1:1: Warning: file has no ‘lexical-binding’ directive on its first line
Compiling /var/tmp/portage/app-emacs/embark-20231130.1735/work/embark-20231130.1735/embark-org.el...
Compiling /var/tmp/portage/app-emacs/embark-20231130.1735/work/embark-20231130.1735/embark.el...

In embark-define-thingatpt-target:
embark.el:871:2: Warning: docstring has wrong usage of unescaped single quotes (use \=' or different quoting such as `...')
Done (Total of 2 files compiled, 1 skipped)                                                                                         [ ok ]
>>> Source compiled.`

Maybe some of these warnings can be addressed?

**Comment by oantolin** [comment]
Sure, but I'd need some documentation of changes in Emacs. For example, both files have `lexical-binding: t` in the first line, so either the format for that changed or the message you got is a bug in Emacs 30. If the format did indeed change, I'd need to know to *what* it changed and then to see if there is a way to support both emacs 30 and <30.

**Comment by CaptainBloodz** [comment]
Thks 4 ur quick reply.

As a emacs noob I'd rather rely on your expertise.
Will investigate for packages not having that lexical-binding issue reported...

**Comment by oantolin** [comment]
So you're saying that the message "Warning: file has no ‘lexical-binding’ directive on its first line" is a bug in the Emacs 30 byte compiler, @minad?

**Comment by CaptainBloodz** [comment]
My bad,
As it seems embark-autoloads.el is internally generated by package manager here.
Closing now.

**Comment by CaptainBloodz** [comment]
You helped me to understand better about my NX environment.
Nice!
