### ISSUE TITLE
How to run action on region without sending "bounds" as first arg?

### ISSUE THREAD

**Issue by unhammer** [oantolin/embark#692]
I'm using https://gist.github.com/unhammer/f4a26e7de42cd9600ef9f7318ad0caab to mark org-mode columns and run rectangle-replace within the column. The replacement function needs the the target to be marked, so I added around-action-hooks embark--mark-target, but that means I have to add an unused first argument to the cua-replace-in-rectangle call. Is there  a simpler way?

(Or perhaps has someone solved the whole "mark org-table column" problem already?)

**Comment by oantolin** [comment]
I'm not sure I fully understand your problem, but Ivd remove the unused argument from the function definition and also add embark--ignore-target to embark-injection-target-hooks for your function.

**Comment by oantolin** [comment]
Let me know if that doesn't solve your problem.
