### ISSUE TITLE
How to disable embark confirmation for a specific action?

### ISSUE THREAD

**Issue by IceAsteroid** [oantolin/embark#694]
Hi, good day!

Here I found that the readme page was quite overwhelming to read. After half of a day, I still could't figure out how to disable the confirmation for a certain action pre-defined by embark, such as kill-buffer.

How can I do that?

**Comment by oantolin** [comment]
You can use:

```elisp
(setf (alist-get 'kill-buffer embark-pre-action-hooks)
      (delq 'embark--confirm
            (alist-get 'kill-buffer embark-pre-action-hooks)))
```

In this particular case, since the only pre-action hook for `kill-buffer` in the default configuration is `embark--confirm`, you could also do:

```
(setf (alist-get 'kill-buffer embark-pre-action-hooks) nil)
```
