### ISSUE TITLE
org-open-at-point-global does not work on links with multiline descriptions

### ISSUE THREAD

**Issue by oantolin** [oantolin/embark#696]
As I feared, maybe Embark should use `org-open-at-point` when in Org buffers and `org-open-at-point-global` only in non-org buffers.

**Comment by minad** [comment]
Maybe report this as a bug first? I think org-open-at-point-global should behave as well as org-open-at-point in Org buffers or just fall back to that?

**Comment by oantolin** [comment]
I [reported the bug](https://lists.gnu.org/archive/html/emacs-orgmode/2024-01/msg00412.html) and suggested your fix.

**Comment by oantolin** [comment]
And in the meantime I'm using this workaround:

```elisp
  (defun when-in-org-do-as-the-organs-do (fn)
    (if (derived-mode-p 'org-mode) (org-open-at-point) (funcall fn)))
  (advice-add 'org-open-at-point-global :around #'when-in-org-do-as-the-organs-do)
```

**Comment by oantolin** [comment]
@yantar92 quickly fixed the bug now checking the entire paragraph! I think once a version of org with the fix is released, I'll update the embark org-link target finder to check the org version and, if it's new enough, use the new criterion.
