### ISSUE TITLE
*Embark Actions* buffer pops up despite setting embark-promp to embark-completing-read-prompter

### ISSUE THREAD

**Issue by doolio** [oantolin/embark#699]
My configuration is as follows:

```emacs-lisp
(use-package embark
  :bind (("C-." . embark-act)
         ("C-;" . embark-dwim)
         ("C-h B" . embark-bindings)) ; Alternative for `describe-bindings'.
  ;; Replace the key help with a completing-read interface.
  :init (setq prefix-help-command #'embark-prefix-help-command)
  :config
  (setq embark-prompter 'embark-completing-read-prompter)
  ;; Hide the mode line of the Embark live/completions buffers.
  (add-to-list 'display-buffer-alist
               '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                 nil
                 (window-parameters (mode-line-format . none)))))
```

I've tried setting it within the `:init` block as well but I still observed the popup in addition to the completing read suggestions in the minibuffer.

![image](https://github.com/oantolin/embark/assets/13859009/ca68fa0d-42d9-4121-b88d-4171dec19f59)

**Comment by oantolin** [comment]
If you wish to remove the `*Embark Actions*` buffer, remove or replace the `embark-mixed-indicator` or `embark-verbose-indicator` from the variable `embark-indicators`. I suggest replacing either of those with `embark-minimal-indicator`, you could add

```elisp
  :custom
  (embark-indicators '(embark-minimal-indicator
                       embark-highlight-indicator
                       embark-isearch-highlight-indicator))
```

to your `use-package` form.

**Comment by doolio** [comment]
Thanks. That did the trick. Reading the README again it suggests the `embark-minimal-indicator` is on by default. This was not the case for me. I had 

```emacs-lisp
(embark--vertico-indicator embark-mixed-indicator embark-highlight-indicator embark-isearch-highlight-indicator)`
```

which was changed (I guess by the `vertico` package) from the following original value:

```emacs-lisp
(embark-mixed-indicator embark-highlight-indicator embark-isearch-highlight-indicator)
 ```

**Comment by oantolin** [comment]
Oh, you're right: the minimal indicator *is* on by default! The point is to remove the mixed indicator which is also on by default.

**Comment by oantolin** [comment]
Oh, I'll fix the readme.
