### ISSUE TITLE
A question on using external libraries

### ISSUE THREAD

**Issue by a13** [oantolin/embark#7]
What is the policy for using external libraries which are not included in Emacs?

I see several approaches:

- denied, let the user decide what to bind. In this case, I think it's worth to add some examples to README

- use something like 
```
(when (require 'feature-name nil t)
  '("x" . feature-name-magic-command))
```
- make compatibility packages `embark-feature-name` with explicit dependencies

**Comment by oantolin** [comment]
Maybe we can start out with just snippets in the README or the GitHub project wiki. And discuss making a package if there ever feels like there is enough material.

When it does, I think a single package would be OK (like counsel). It shouldn't depend on the external packages that contain the functions it binds, just using `declare-function` is enough.

**Comment by a13** [comment]
> It shouldn't depend on the external packages that contain the functions it binds, just using declare-function is enough.

what if the package is not installed?

**Comment by oantolin** [comment]
I was suggesting making the binding anyway and let the user get an error message if the package is not installed. I believe this is what counsel does.

**Comment by a13** [comment]
An example of what I'd like to see as an action:

https://github.com/nflath/sudo-edit/blob/master/sudo-edit.el#L206 

Generating a sudo file name can be a relatively complex task (`counsel-find-file-as-root` uses simpler logic, which covers less cases)

**Comment by a13** [comment]
```org
| keymap          | action              | package   | char? |
|-----------------+---------------------+-----------+-------|
| embark-file-map | sudo-edit-find-file | sudo-edit | s     |
| embark-file-map | magit-status        | magit     | g/m   |
| embark-file-map | vlf                 | vlf       | l/v   |
```

**Comment by oantolin** [comment]
Those are good examples. Care to add them to the [examples page](https://github.com/oantolin/embark/wiki/Additional-Configuration) on the project wiki?

By the way, I think most magit users probably bind `magit-status` to a key, commonly `C-x g`. That means the savings in binding it in an embark action keymap aren't large: if you bind `embark-act` to `M-o`, say, then it's `M-o C-x g` vs `M-o g`. (I'm not saying it's not worth it, just pointing out that you don't need special bindings to make an action convenient to use in embark, you only need them to make it _even more convenient_!)

**Comment by a13** [comment]
> By the way, I think most magit users probably bind magit-status to a key, commonly C-x g

magit-status is bound to the current repo, so if you want to jump to another (while opening a file or smth like that) - it would be useful

> Care to add them to the examples page on the project wiki?

yep

**Comment by oantolin** [comment]
Thanks for adding to the examples page!

> magit-status is bound to the current repo, so if you want to jump to another (while opening a file or smth like that) - it would be useful

Oh, I see what you mean! Something extra needs to be done to get the repo of the completion candidate instead of the current repo.

But binding `magit-status` to `g` in `embark-file-map` doesn't do what you want. In fact if, say, your global binding for `magit-status` is `C-x g` and you bind `embark-act` to `M-o`, then from the minibuffer `M-o g` and `M-o C-x g` are exactly equivalent. Neither one of them will actually use the completion candidate, and both will give you the current repo instead.

If you call `magit-status` with `C-u` then it does prompt you. So you can use `M-o C-u C-x g`, or, with your `g` binding, `M-o C-u g`. But you still need the `C-u`. Of course you can make a custom command that uses the embark target to find a containing repo and bind that to `g` instead:

```elisp
(defun embark-magit-status ()
  "Run `magit-status` on repo containing the embark target."
  (interactive)
  (magit-status (locate-dominating-file (embark-target) ".git")))
```

**Comment by a13** [comment]
> But binding magit-status to g in embark-file-map doesn't do what you want. 

worked for me:

`C-x C-f`, navigate to a file/dir from another git repo, `M-o`, `g`, `RET` - does exactly what I want

**Comment by a13** [comment]
I got it, I haven't try it with files, just directories. You are right.

**Comment by oantolin** [comment]
> worked for me: 
> `C-x C-f`, navigate to a dir from another git repo, `M-o`, `g`, `RET` - does exactly what I want

That's odd, for me that behaves as follows, assuming the target is a directory:

1. If I start in a directory that is not a repo, it works: magit-status prompts for a repo, the target gets inserted and `RET` open the magit status buffer for the target.

2. However, if I start in a directory that **is** a repo, then `M-o g` will *not* prompt, and the magit status buffer for the initial directory pops up (not for the embark target directory!).

Maybe you only teste case 1?

I think even with directories you'd still want a custom function for this, or, keep `magit-status` but use `C-u` with it.

**Comment by oantolin** [comment]
Since we have a plan (for now the wiki, maybe later a package), I'm closing this issue.
