### ISSUE TITLE
Zebra highlighting should not hardcode color values

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#70]
Embark's zebra highlighting includes hardcoded color values.  My background is `#eeeeec` so I couldn't perceive the light background highlight choice of `#efefef` and it took a while to figure out if zebra striping was in fact working.

Instead of hard coded values, perhaps embark could compute the stripe highlight using the background color and one of the functions in `color.el` like `color-lighten-hsl` or `color-gradient`.  It would still have to know about light or dark backgrounds and to be very robust would need to recompute each time when needed because backgrounds change (I use a function a to rotate between 8 background colors when bringing up new frames) but the computation should be fast.

**Comment by oantolin** [comment]
I think the standard thing actually is to pick some hard coded value, but to put it in a defface, so that users can easily customize it (or to install some theme that customizes it). That's the approach I took here. I'll look into what other packages do, but I think this probably a sensible choice.

(By the way, zebra mode doesn't hard code one value but two: one for light backgrounds and one for dark backgrounds. This too I believe is standard.)

**Comment by hmelman** [comment]
Yes, I had read the embark code and customized the face.  

While it's true many packages do hardcode values I think it's a weakness of emacs.  For many faces that are some semantic thing there isn't much of an option other than perhaps inheriting from a similar builtin face but emacs doesn't have enough of those.  But in this case where the goal is to be slightly different from the background, I think it's the perfect situation to avoid hardcoding a value, and having the code be able to just work™ without needing any support from a theme.

**Comment by minad** [comment]
@oantolin what you did here is certainly right. I wouldn't like an auto computation and inheriting is no option for backgrounds. I did the same for my small goggles package and @protesilaos helped to make the background colors nicer :)

**Comment by oantolin** [comment]
@protesilaos helped pick these colors too. :)

**Comment by oantolin** [comment]
I'm sorry, I'm going to close this issue. I don't want to introduce some complicated calculation to pick the colors, when it's pretty easy for users or theme writers to customize the colors. I think your situation, where you use 8 different background colors, must be pretty unusual. I bet most people use at most one light background and one dark ground, so they can probably just pick a zebra color once and be done with it.
