### ISSUE TITLE
`embark-insert` includes text properties, such as `read-only`

### ISSUE THREAD

**Issue by jochu** [oantolin/embark#705]
When using `embark-insert`, it includes all text properties from the source text. This can be problematic for some specific properties, such as `read-only`.

`yank` has a set of rules that are used to remove/handle properties from yanked text. What do you think of applying these rules to text that is being inserted by `embark-insert`?

---

Using yank rules could be done by replacing the call to `insert` with `insert-for-yank` in the `embark-insert` function. The rules this applies include `yank-excluded-properties` (remove some properties), `yank-handled-properties` (modify some properties), and `yank-transform-functions` (modify the string).

The property handling rules sound desirable to me. The transform one is new (emacs 29.1), and I don't know what the use cases are. I'm guessing they're fine, but, if we think they will become an issue, we can call `(remove-yank-excluded-properties start (point))` after the insert instead.

**Comment by minad** [comment]
I think `embark-insert` should strip all text properties before
inserting a candidate. `embark-insert` was probably a simple command
reading from the minibuffer before, where text properties would have
been stripped naturally. At some point the command was changed to a
function taking a list of strings and the text property removal got lost
on the way.

**Comment by oantolin** [comment]
I agree with @minad, embark-insert should just strip all text properties to match it's old behavior (which was courtesy of completing-read).

**Comment by minad** [comment]
The only two commands affected by this problem should be `embark-insert` and `embark-copy-as-kill`.

**Comment by oantolin** [comment]
Maybe copy-as-kill should keep the text properties? It's a version of `kill-ring-save` which does keep them (and lets `insert-for-yank` deal with that).

**Comment by minad** [comment]
> I haven't done it for embark-copy-as-kill because I'm not convinced that function should do it too, but will think about it and am open to arguments.

Okay, I see your point. There are certainly scenarios where one wants to keep the properties. I think that completion candidate properties can be considered mostly internal, so by stripping them, we would avoid any such leakage.

**Comment by oantolin** [comment]
I agree with the point about completion candidate properties being mostly "internal", I'd be happy stripping those properties. But what about text properties in targets from regular buffers? I can't remember if the target finders already a strip those or not, probably not.
