### ISSUE TITLE
Using `xdg-open` on a  note

### ISSUE THREAD

**Issue by iago-pssjd** [oantolin/embark#714]
Is it possible to use `xdg-open` on a note after `M-x consult-notes` through `embark`? I am trying:
1. M-x consult-notes
2. Select note of interest
3. C-.
4. M-&
5. xdg-open
As in 'Run a shell command on a minibuffer candidate file without losing your session' (https://karthinks.com/software/fifteen-ways-to-use-embark/)
Not success because it is applied to something it is not the file name.

or
4. E (embark-export)
5. Select note of interest again and
6. M-x embark-select
7. a (embark-act)
8. ! (like in dired-mode to apply shell commands)
but `! is unefined`

Related: 
- https://github.com/oantolin/embark/issues/700#issue-2118096785
- (equivalent question on another mode) https://github.com/jrblevin/deft/issues/119

**Comment by oantolin** [comment]
I'm sorry, but I'm not familiar with consult-notes. I'm guessing its completion candidates are not files, if the procedure you described doesn't work. You might be able to write an embark candidate transformer that converts the candidates to files but doing so will probably require some knowledge of how consult-notes is implemented.

**Comment by iago-pssjd** [comment]
Thanks for the answer!

**Comment by hmelman** [comment]
It's a nice package based on some code I put in the consult wiki.  I still run my version and this is how I support embark:

```elisp
(defun hrm-notes-grep (cand)
  "Run consult-ripgrep in directory of notes file CAND."
  (interactive "fNote: ")
  (consult-ripgrep (file-name-directory cand)))

(defvar-keymap hrm-notes-map
  :doc "Keymap for Embark notes actions."
  :parent embark-file-map
  "g" #'hrm-notes-grep)

(with-eval-after-load 'embark
  (add-to-list 'embark-keymap-alist `(,hrm-notes-category hrm-notes-map))
  ;; make embark-export use dired for notes
  (setf (alist-get hrm-notes-category embark-exporters-alist) #'embark-export-dired))
```

It's the last few lines you need to tell embark about the notes category, you'll want to change `hrm-notes-category` to `consult-notes-category`.  Note that the keymap sets the `embark-file-map` to be the parent.

**Comment by oantolin** [comment]
Thanks, @hmelman!

**Comment by iago-pssjd** [comment]
Thanks for the help @hmelman 

If I include that code in my `.init` I switch `hrm-notes-category` with `consult-notes-category` and I open emacs I get `Symbol's value as variable is void: embark-file-map`.

**Comment by oantolin** [comment]
Right, because Embark hasn't been loaded yet. You should move the code that uses embark-file-map into the`(with-eval-after-load 'embark ...)` form.

**Comment by iago-pssjd** [comment]
Thanks @oantolin too. Previous issue solved. Now, @hmelman , if I try
1. M-x consult-notes
2. Select note of interest
3. C-.
It appears an option which is
x     embark-open-externally             Open file or URL using system's default applitacion
I try it then:
4. x
But I get
```
embark PCH: (wrong-type-argument window-valid-p #<window 25>
```

**Comment by oantolin** [comment]
Try reproducing that problem starting from `emacs -Q` and loading only embark, consult-notes and the above configuration. If the problem occurs then, maybe you can give me instructions to reproduce it and I might be able to install consult-notes and investigate.
