### ISSUE TITLE
New release 1.1?

### ISSUE THREAD

**Issue by minad** [oantolin/embark#717]
Hello Omar,

could you please tag a new release 1.1, such that we get https://github.com/oantolin/embark/commit/d8ae99c116cccb7e69c24f83cdd4e6e038d28e43? This commit is needed by Consult, such that I can also release a new version. I am not sure about the other changes, i.e., if a new Embark release is already justified, but it seems there are also a number of bug fixes and the alternative exporter. Thanks!

**Comment by minad** [comment]
Thanks!

**Comment by oantolin** [comment]
No problem!

**Comment by nicolas-graves** [comment]
@oantolin Could you also tag the repository accordingly? Thanks!

**Comment by oantolin** [comment]
Done, @nicolas-graves.

**Comment by nicolas-graves** [comment]
Thanks! That was for updating on Guix, which relies on the repository tag. Have a nice day!

**Comment by astoff** [comment]
Maybe time is due for version 1.2? :-)
