### ISSUE TITLE
Errors with `embark-org` modifying lexically-bound `embark-target-finders`

### ISSUE THREAD

**Issue by hpfr** [oantolin/embark#726]
If a user defines a function in their config that calls `embark-act` with a lexically bound `embark-target-finders`, loading of `embark-org` can fail.

For example, this function from the wiki (using a finder from the wiki):
```emacs-lisp
(defun embark-act-on-buffer-file (&optional arg)
  (interactive "P")
  (let ((embark-target-finders '(embark-target-this-buffer-file)))
    (embark-act arg)))
```

In `emacs -Q`, I mocked up a scenario where a user opens an Org file and then calls their custom function calling `embark-act` (for the first time, causing embark to load) with lexically bound `embark-target-finders`:

```emacs-lisp
(require 'org)
(defvar embark-target-finders)
(let ((embark-target-finders '(foo)))
  (require 'embark))
```

which results in:

```
Debugger entered--Lisp error: (wrong-type-argument consp nil)
  byte-code("\301\10>\211\1A\302\1>\203\20\0\211\202\23\0\302\1B\262\1\241\266\2\303\304\305\"\207" [embark-target-finders embark-target-active-region embark-org-target-link autoload org-attach-dir "org-attach"] 5)
  require(embark-org)
  #f(compiled-function () #<bytecode 0x19809208cd0a>)()
  eval-after-load(org #f(compiled-function () #<bytecode 0x19809208cd0a>))
  byte-code("\300\301!\210\302\303\304\"\210\302\305\306\"\207" [provide embark eval-after-load consult #f(compiled-function () #<bytecode 0x14852325549e118b>) org #f(compiled-function () #<bytecode 0x19809208cd0a>)] 3)
  require(embark)
  (let ((embark-target-finders '(embark-target-this-file))) (require 'embark))
  (progn (let ((embark-target-finders '(embark-target-this-file))) (require 'embark)))
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  command-execute(eval-last-sexp)
```

I was able to see where the failure during loading occurred by evaluating fboundp on some of the defun names to see where it stopped. `embark-org-target-link` was bound, but `embark-org--refine-link-type` was not. So the issue here was with

https://github.com/oantolin/embark/blob/9c166c4b96a0b1e85401bcc6fb95ce021e7b5013/embark-org.el#L260-L261

which makes sense, because I let-bound `embark-target-finders` so the `memq` returns `nil`. A previous addition to `embark-target-finders` in `embark-org` uses `if-let` which avoids this:

https://github.com/oantolin/embark/blob/9c166c4b96a0b1e85401bcc6fb95ce021e7b5013/embark-org.el#L122-L125

I’m not sure if there’s a way `embark-org` can add finders more robustly. If you use `if-let` each time, it won’t error out, but you still end up without the `embark-org` target finders since they just get added to the lexically bound value.

I added `(require 'embark)` preceding the let-binding of `embark-target-finders` in the function in my config so that the mutations to `embark-target-finders` during loading happen correctly. I figured I would open an issue in case anyone better at Elisp had ideas. If not, maybe we can just update the wiki functions to `(require 'embark)` to be safe.

Even if that’s the plan, I think all the mutations evaluated at load time (I see various other `add-to-list` calls for other functionality) could be moved into an `embark-org-setup` function that could be autoloaded and called instead of `(require 'embark-org)`. Doesn’t solve the lexical binding during loading issue, but I think it would make the package more readable in general.

**Comment by minad** [comment]
> I added (require 'embark) preceding the let-binding of embark-target-finders in the function in my config so that the mutations to embark-target-finders during loading happen correctly.

Yes, that's the way to go.
