### ISSUE TITLE
Would got Error running timer: (buffer-read-only #<buffer *Embark Export Grep*>) when Embark Export Grep already exists.

### ISSUE THREAD

**Issue by jixiuf** [oantolin/embark#73]
Would got `Error running timer: (buffer-read-only #<buffer *Embark Export Grep*>)` when  *Embark Export Grep* already exists.

**Comment by oantolin** [comment]
What would you prefer happen? That the same buffer gets reused, or that a new `*Embark Export Grep*<2>` buffer be created?

**Comment by oantolin** [comment]
I implemented the fix where a new buffer is created each time you export. I think this is more flexible because you can keep the old buffers around if you still need them. But maybe there is a good case to be made for recycling buffers. Let me know what you think.
