### ISSUE TITLE
Functionality: Filter minibuffer results before collecting them

### ISSUE THREAD

**Issue by mattiasdrp** [oantolin/embark#738]
Hey, 

Thanks for this awesome package!

I have the following issue:
- I use consult-ripgrep to find lines in a big project containing a specific word
- Out of all these lines, most of them are noise because they contain a specific word that I'm not interested in
- I can't (or at least I didn't find how) create a regex that would do something like "search for word1 butt excludes word2 as rg doesn't accept look-ahead and look-behind
- I tried changing the embark-collect function to filter the minibuffer but for the life of me I couldn't find where the minibuffer content was collected in this simple function (am I blind?!)
- So I was wondering if there was a way to filter results before collecting them with embark-collect

**Comment by oantolin** [comment]
With its default configuration consult-ripgrep interprets a minibuffer input of the form `#part1#part2` as follows: it uses `part1` to construct the pattern it sends to `rg` and then filters the results inside Emacs using `part2` with your current completion style. If you use the orderless completion styles, you can use `part2` to exclude a word with a pattern like `!word`. Once you have only the matches you want, you can call embark-collect.

**Comment by oantolin** [comment]
I don't think you did try my suggested solution. In the linked discussion I see you are using the basic and substring completion styles, which do not support filtering out. What I suggested was that ou install the orderless completion style.

**Comment by mattiasdrp** [comment]
Ok so the reason why it didn't work in my setup is that I had these lines in my lsp-mode config:

```
   (defun minad/orderless-dispatch-prefixes-first (_pattern index _total)
     (and (eq index 0) 'orderless-prefixes))

   (add-hook 'orderless-style-dispatchers #'minad/orderless-dispatch-prefixes-first)
```

I don't remember exactly what they did but commenting them brought back the behaviour of orderless for string filtering. I tried to find in the different wikis (consult, corfu, vertico) if I could find these lines but there have been either removed or they're in a different place.

**Comment by oantolin** [comment]
That configuration makes it so that the first  (0th) space-separated component of the minibuffer input is only considered to match using the prefixes matching style.

**Comment by mattiasdrp** [comment]
Yep, that's what I thought. Thanks for the explanation and sorry again for the noise :'(
