### ISSUE TITLE
Category minor-mode uses symbol map

### ISSUE THREAD

**Issue by minad** [oantolin/embark#75]
The minor mode category can contain lighter strings as candidates (both consult-minor-mode-menu and describe-minor-mode). There should he some step to translate from a lighter to a symbol first before a symbol action is applied. Marginalia has special treatment for the minor-mode category.

**Comment by oantolin** [comment]
Oh, thanks for reporting, I had no idea! I tried the consult command briefly and thought all the candidates were minor mode names.

**Comment by minad** [comment]
Yes, you also told me, but I had forgotten this too. It occurred to me again when I saw #74. There are two reasons for the minor-mode category:

* Allows more informative annotations
* Has both lighters and symbols

**Comment by oantolin** [comment]
What can you do with the lighters? The symbol actions do work on the minor mode names.

Ah, maybe this another transformation I should do? For the category `minor-mode`, I could check if the target is the name of a function, and if it is not, go through `minor-mode-alist` comparing with all the lighters, and replace the target with the matching minor-mode.

**Comment by minad** [comment]
Yes, see marginalia!

**Comment by oantolin** [comment]
Oh, there is a `lookup-minor-mode-from-indicator`! Excellent.

**Comment by minad** [comment]
I should add - see also https://github.com/minad/marginalia/blob/a78a4b38aba3cc80cc138aa6cd6982d7a7e32be0/marginalia.el#L629

**Comment by oantolin** [comment]
Oh, boy. Embark occur could keep those lighters around after their buffer is gone, let alone the window!

**Comment by oantolin** [comment]
Are your sure about the window? I tried `(lookup-minor-mode-from-indicator "ARev")` in a help buffer and in a brand new fundamental mode buffer and it said `auto-revert-mode` both times, even though those buffers where not in `auto-revert-mode` (but some other buffer is).

**Comment by minad** [comment]
@oantolin maybe you find a better way to do the lookup. I don't know how this works internally and where the lighter status is kept. The problem in my case was flycheck, which modifies it's lighter on the fly. So the lighters are not constant strings.

Another alternative you may consider - just filter out the lighters. The corresponding mode names are still in the list. But maybe that would be unexpected for an occur buffer?

**Comment by oantolin** [comment]
> But maybe that would be unexpected for an occur buffer?

Yes, totally unexpected, but even worse, what is embark-act in the minibuffer from describe-minor-mode supposed to do? It seems rude for it to refuse to work.

I think I'll just use `lookup-minor-mode-from-indicator` and hope for the best. It'll work in many more cases than it does now, maybe not flycheck, but still more cases.

**Comment by minad** [comment]
> Yes, totally unexpected, but even worse, what is embark-act in the minibuffer from describe-minor-mode supposed to do? It seems rude for it to refuse to work.

I think in that case the window is still alive :) only the occur buffer is really problematic. But I think it is okay if this particular feature is not 100% reliable. I think the lighters in the minor mode lists are not the best idea.

**Comment by oantolin** [comment]
Not 100% reliable it is then! ;) Closed.
