### ISSUE TITLE
Suggested README updates

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#76]
Suggested README updates

Typo: `embark-heymap-help` should be `embark-keymap-help`

Typo: `embark-prompt-style` should be `embark-prompter` and I think the value for choosing completion should be `embark-completing-read-prompter` not `completion`

The `embark-export` description should mention the new grep mode handling

Currently `embark-act-noexit` is just mentioned in passing and- `embark-live-occur` is briefly mentioned.  I think they both need better explanations of what they do, and an example of when you'd want to use them over their variants.  Also `embark-become` is currently not described

Since these aren't configured for the user, I think a single section listing all the autoload commands that a user might want to bind (globally or in the minibuffer) or would help them get started.  But I'm not sure where that would best fit in the current outline structure.

I think the README should have a table listing all the builtin categories embark knows about and the name of the associated keymap (and perhaps other info).  Otherwise the keymap names aren't discoverable without reading the source. Something like this:

| Category | Keymap |
| ---- | ---- |
| Region | embark-region-map|
| File | embark-file-map |
| Buffer | embark-buffer-map |
| Symbol | embark-symbol-map |
| Package | embark-package-map |
| URL | embark-url-map |
| Bookmark | embark-bookmark-map |
| Unicode Name | embark-unicode-name-map |

Now that the suggested `which-key` configuration is in the README it can be removed from the Additional Configuration wiki page.

**Comment by oantolin** [comment]
> Suggested README updates
> 
> Typo: `embark-heymap-help` should be `embark-keymap-help`
> 
> Typo: `embark-prompt-style` should be `embark-prompter` and I think the value for choosing completion should be `embark-completing-read-prompter` not `completion`
> 
> The `embark-export` description should mention the new grep mode handling

Thanks! I'll do all of these.

> Currently `embark-act-noexit` is just mentioned in passing and- `embark-live-occur` is briefly mentioned. I think they both need better explanations of what they do, and an example of when you'd want to use them over their variants. Also `embark-become` is currently not described

Good point, I'll add something about these.

> Since these aren't configured for the user, I think a single section listing all the autoload commands that a user might want to bind (globally or in the minibuffer) or would help them get started. But I'm not sure where that would best fit in the current outline structure.

I did do that! The only command that needs a binding is `embark-act`! From there you can comfortably run become, occur, live-occur and export.

> I think the README should have a table listing all the builtin categories embark knows about and the name of the associated keymap (and perhaps other info).

I guess I could do that, sure.

>  Otherwise the keymap names aren't discoverable without reading the source.

That's what customize is for!

> Now that the suggested `which-key` configuration is in the README it can be removed from the Additional Configuration wiki page.

I left for people that remember it there and want to look it up again, but I can also remove it. I don't care either way.

**Comment by hmelman** [comment]
Thanks.

I do understand that all that's *needed* is binding `embark-act` and that's great for Getting Started.  But after that, I wanted to try some more things and found figuring out all that embark could do was difficult.  I could be misunderstanding the other commands marked autoloaded but I meant to collect everything you might want to bind in one place.  So yeah, live-occur wouldn't need to be included, but I think -noexit and perhaps -become would?

Correct me if I'm wrong but I don't see the category keymaps in customize and wouldn't expect to.  You modify them with elisp and so collecting the names in one place would be convenient, and also it would document all the supported categories.

I agree the which-key config is useful in the README.  Having it in two places means they could get out of sync if they change.  Maybe the wiki points to the new README section?

**Comment by oantolin** [comment]
> Thanks.

No thank you, this issue is very useful!

> I do understand that all that's _needed_ is binding `embark-act` and that's great for Getting Started. But after that, I wanted to try some more things and found figuring out all that embark could do was difficult. I could be misunderstanding the other commands marked autoloaded but I meant to collect everything you might want to bind in one place. So yeah, live-occur wouldn't need to be included, but I think -noexit and perhaps -become would?

Mmh, `embark-act-noexit` should probably be mentioned in the quick start, but I think that to be less intrusive, I won't recommend people bind anything other that `embark-act` and/or `embark-act-noexit`. I personally always run `embark-become` from inside `embark-act` and I think that works just fine, there really is no need for a direct keybinding. Or do you think I should recommend a binding for `embark-become`?

> Correct me if I'm wrong but I don't see the category keymaps in customize and wouldn't expect to. You modify them with elisp and so collecting the names in one place would be convenient, and also it would document all the supported categories.

`M-x customize-group embark` includes `embark-keymap-alist` and this shows you  all the keymap names. `M-x customize-variable RET embark-keymap-alist RET` would work too, of course.

But maybe people aren't used to exploring customization? It might be worth it to list the table you mentioned in the README even if it is trivially accesible through custom.

> I agree the which-key config is useful in the README. Having it in two places means they could get out of sync if they change. Maybe the wiki points to the new README section?

Ah, good idea!

**Comment by hmelman** [comment]
I honestly don't yet know what embark-become does so it's hard for me to comment on it (I think I understand the rest).  The sense I got from reading the whole README was that the main entry point is embark-act and that the Getting Started section was about doing just that, a quick start.  After playing with embark a little for a week or so I tried to explore more.  

I found the rest of the README a little unstructured for presenting the rest of the capabilities.  I'm not sure I can suggest a better one now, but it presents a bunch of new concepts (targets, categories, actions, occur) and hints at a few more things and I think I wanted a stronger reading path?  The ideas of the table and listing the autoloads you might want to bind, were my (perhaps misguided) attempts to get an exhaustive list of embarks capabilities without having to read all the source.

Take that input as one person's reactions.  I'll try to think more about it and come up with a more concrete suggestion.  The info presented currently is good, I think I just needed a little more handholding to convince myself I was absorbing it all and fully understanding embark.

**Comment by oantolin** [comment]
The README has just grown organically over time, it is pretty unstructured. I'll think about how to organize it. Thanks a lot for the suggestions.

**Comment by hmelman** [comment]
No problem.  Thanks a lot for embark!

One question.  Do you use embark on regions much? Working on regions jumped out at me quickly as something very interesting, but thinking a little more about it does it add much?  If I had a region marked and wanted to lowercase it, I'd just hit M-l and it would do it, having to get to it via embark is just a little longer?  I like the idea of a having a place collecting all the region commands (I've done that myself several times in various forms), but I think now many emacs commands have gotten the ability to work on the region if active and so collecting them isn't that useful?  Am I missing something?

**Comment by oantolin** [comment]
I don't think you are missing anything: the region actions don't really add anything over just running the commands directly. (Well, in your lowercasing example, I bet you rebound `M-l` to `downcase-dwim` instead of the default `downcase-word`, but i get your point.)

The only region actions I actually use are the ones that don't have default keybindings: `eval-region`, `rot13-region`, `whitespace-cleanup-region`, `transpose-regions`, and `org-table-convert-region`.

Oh, I also use `apply-macro-to-region-lines` as a region action because the default keybinding, `C-x C-k r` is fairy awkward. Since I added this one to `embark-region-map` I use it *much* more.

**Comment by oantolin** [comment]
Plus, there is some small value to having a list of these region commands, I do very occasionally use `embark-keymap-help` to browse that list.

**Comment by hmelman** [comment]
Makes sense.  The only one of those I use is eval-region and I've long bound it to `C-c r`.  I usually just apply macros by line, I'll have to think about incorporating `apply-macro-to-region-lines` into my repertoire.

I'm on a mac and use Alfred (and Quicksilver before) as a system launcher, so I have commands defined in that which send the selection of any app (including emacs' region) to other things, like a websearch or to other apps.  I generally edit anything non-trivial in an emacs buffer so sending text to other apps is helpful.  I use magit's transient package and have a bunch of region commands on `s-r` and I might replace that with embark.

**Comment by oantolin** [comment]
> The `embark-export` description should mention the new grep mode handling

I think this might just take too long to explain. There are no default commands that prompt you for a grep result. I'd have to say something like, "if you are on Emacs master and you configure xref to prompt you for locations in the minibuffer, or if you use the consult-{grep,git-grep,ripgrep} commands ...", but explaining how you configure xref.

**Comment by oantolin** [comment]
> I think the README should have a table listing all the builtin categories embark knows about and the name of the associated keymap (and perhaps other info).

Mmh. I already link to the wiki with the list of default actions. I think maybe instead of the full table, I'll just enumerate the main categories and point people to `embark-keymap-alist` and the wiki.

**Comment by hmelman** [comment]
> I think this might just take too long to explain. There are no default commands that prompt you for a grep result. I'd have to say something like, "if you are on Emacs master and you configure xref to prompt you for locations in the minibuffer, or if you use the consult-{grep,git-grep,ripgrep} commands ...", but explaining how you configure xref.

Ah, I was wondering why it wasn't doing much for me on Emacs 27. :)

**Comment by oantolin** [comment]
> Ah, I was wondering why it wasn't doing much for me on Emacs 27. :)

I decided to bite the bullet and explain this properly.

**Comment by oantolin** [comment]
OK, so I've updated the README. I didn't follow all your suggestions completely, but the idea is that the Overview section now does contain a fairly complete overview of what Embark offers, except that instead of listing all of the dozens of actions it points you to the wiki (as it already did, that's not part of what I updated). Please take a look and let me know if you think that more or less covers it or if you think I need to add things to the overview.

**Comment by hmelman** [comment]
Great. I took a quick skim and it does look improved.  I'll read it in more depth in a bit.  I did notice a couple of typos, so I suggest keeping this issue open and I'll update with what I find.

**Comment by oantolin** [comment]
Sure, let's keep this open. I'll also proofread again in a little while.

**Comment by hmelman** [comment]
Are categories and types the same thing?  If so, using one consistently would help.  Or at least explain at first usage that they are synonyms. 

When introducnig occur and export, I would say "Embark provides three commands to work on candidate sets:" and list `embark-live-occur` as another bullet.  Like the other two it has a binding in `embark-general-map`.

Search for "But in case you are ever in a situation were you don’t already"  and change the "were" to "where"

Everything else looked good.

**Comment by oantolin** [comment]
> Are categories and types the same thing?

`category` is the term used by the completion metadata. Embark's classification for targets uses the category metadatum for the minibuffer by default, in almost all cases (but see `embark-transformer-alist`, which is allowed to replace the category with another symbol). Of course targets that do not come from the minibuffer do not have category metadata. I think I've been using "category" specifically for the minibuffer completion metadatum and "type" more generally for the classification Embark uses, but I'm not 100% sure I'm consistent about this.

Maybe it makes sense to always say category, since that is what the type most often is.

> When introducnig occur and export, I would say "Embark provides three commands to work on candidate sets:" and list embark-live-occur as another bullet. Like the other two it has a binding in embark-general-map.

OK, good idea.

> Search for "But in case you are ever in a situation were you don’t already" and change the "were" to "where"

Will do.

Thanks again!

**Comment by oantolin** [comment]
> Maybe it makes sense to always say category, since that is what the type most often is.

No, I think I'd rather reserve category for the minibuffer completion metadata, specially since in the `virtual-buffer` case, by default, the Embark type is not equal to the category.

**Comment by oantolin** [comment]
I decided to explain the category/type distinction in the above commit.

**Comment by hmelman** [comment]
> I decided to explain the category/type distinction in the above commit.

Looks great.

**Comment by oantolin** [comment]
Thanks. Should we close this issue now?

**Comment by hmelman** [comment]
Sure.
