### ISSUE TITLE
README: the return value of an invocation of defun is undefined

### ISSUE THREAD

**Issue by leungbk** [oantolin/embark#81]
In the README and in various wikis, I've seen recommendations of using a `defun` invocation as an actual return value:

``` elisp
     (add-hook 'embark-target-finders
               (defun current-candidate+category ()
                 (when selectrum-active-p
                   (cons (selectrum--get-meta 'category)
                         (selectrum-get-current-candidate)))))

     (add-hook 'embark-candidate-collectors
               (defun current-candidates+category ()
                 (when selectrum-active-p
                   (cons (selectrum--get-meta 'category)
                         (selectrum-get-current-candidates
                          ;; Pass relative file names for dired.
                          minibuffer-completing-file-name)))))
```

But the documentation for `defun` mentions that its return value is undefined:

> The definition is (lambda ARGLIST [DOCSTRING] BODY...). See also the function interactive. DECL is a declaration, optional, of the form (declare DECLS...) where DECLS is a list of elements of the form (PROP . VALUES).  These are interpreted according to defun-declarations-alist. **The return value is undefined.**

For this reason, I think it might be a good idea to edit the relevant parts of the README to something like

``` elisp
  (defun current-candidate+category ()
    (when selectrum-active-p
      (cons (selectrum--get-meta 'category)
	    (selectrum-get-current-candidate))))

  (add-hook 'embark-target-finders #'current-candidate+category)
```

**Comment by oantolin** [comment]
Oh, thanks for pointing this out. I've fixed it in the Embark readme and the Selectrum wiki.

**Comment by minad** [comment]
Tbh I find this very weird. I don't think any change in the bytecode compiler or elisp interpreter which breaks the symbol return value will make it into master 😬

**Comment by oantolin** [comment]
I agree @minad, but using a return value that's documented as unspecified after one is made aware of the documentation seems sketchy.

**Comment by minad** [comment]
Yes I am aware of this, I am just wondering if some should try to change the upstream documentation instead ;)
