### ISSUE TITLE
generate texi files from org

### ISSUE THREAD

**Issue by minad** [oantolin/embark#82]
See consult README.org for the necessary attributes. It seems to work well. Melpa converts this to an info file when the package is being built.

**Comment by minad** [comment]
Yes, I wonder if there is some conditional for info/html. The consult readme also needs much more tweaking. But it is a first step. You might also add this to your other projects if you haven't done that already?

**Comment by oantolin** [comment]
> You might also add this to your other projects

Just did that. 😄

**Comment by oantolin** [comment]
I can't seem to get the Embark readme to export to texinfo that Melpa likes. I already managed to fix the problems with orderless and icomplete-vertical and Melpa installed passable info manuals for them, but there's still something wrong with the Embark manual. I'll keep trying. It's a slow process, because I don't know what Melpa wants exactly, the info manuals look fine on my machine, but sometimes I find out 3 or 4 hours later that they don't show up after updating the Melpa package. 🤷

**Comment by oantolin** [comment]
At any rate, I'll recommend a little trick: put stuff you don't want in the info manual in drawers and configure drawers to not export. The drawer contents are still visible on GitHub. I did that for the melpa bades, for example. Alternatively, but `:noexport:` on the headline of an entire section you don't want in the info manual (the `:noexport:` tag does not show up on GitHub). I did this for the screenshot sections.

**Comment by oantolin** [comment]
Oh, another tip: don't use colons in headings, texinfo get's superconfused.

**Comment by minad** [comment]
Thanks for the drawer tip! I missed that! I already added the :noexport: tag to the screenshot section.

**Comment by oantolin** [comment]
It's `#+OPTIONS: d:nil` to keep the drawersfrom exporting.

**Comment by oantolin** [comment]
Maybe you need to `C-c C-c` on the `#+OPTIONS` line for it to take effect? I'm not sure, but I did just check my `embark.texi` and the drawers are not there.

**Comment by minad** [comment]
@oantolin It works now! I didn't have the OPTIONS line before, that's all.

**Comment by oantolin** [comment]
Man, I still cannot get the Embark manual to appear. I wonder what Melpa doesn't like about `embark.texi`... `makeinfo` reports no errors, and the manual looks good on my computer. The manuals for orderless and icomplete-vertical do install correctly... 🤷
