### ISSUE TITLE
Using text properties of embark target

### ISSUE THREAD

**Issue by tpeacock19** [oantolin/embark#83]
The recent updates to Embark have removed embark--target and I'm unable to figure out a way to replace this in my workflow. Currently, I have a function that provides org headlines with marker information as text properties. Previously, I was able to use a function like the below to provide an action for Embark

```elisp
(defun embark-insert-org-id-link ()
  "Embark action to insert org-link from headline nav menu."
  (interactive)
  (let* ((entry (embark-target))
         (id (format "id:%s" (get-text-property 0 'ID entry)))
         (head (org-link-display-format (get-text-property 0 'raw-value entry))))
    (funcall #'org-insert-link nil id head)
    (evil-insert nil)))
```
However, I cannot seem to find a way to have an action act on the currently selected target in the minibuffer (including it's text properties).

**Comment by oantolin** [comment]
Oh, I never thought someone would want to use the text properties of the target! I don't think every completion UI is careful to preserve them, so this sounds brittle (but maybe it works). Have you tried this?

```elisp
(defun embark-insert-org-id-link (entry)
  "Embark action to insert org-link from headline nav menu."
  (interactive "sLink: ")
  (let* ((id (format "id:%s" (get-text-property 0 'ID entry)))
         (head (org-link-display-format (get-text-property 0 'raw-value entry))))
    (funcall #'org-insert-link nil id head)
    (evil-insert nil)))
```

When I insert the target I don't strip the properties, so this probably works. (Maybe. Let me know.)

**Comment by oantolin** [comment]
Honestly, I don't think conveying this information through text properties is the best solution. You could instead associate the headlines with their ID in a hashtable or alist instead.

**Comment by tpeacock19** [comment]
it gives me an error

```elisp
Error running timer: (wrong-number-of-arguments ((t) (entry) "Embark action to insert org-link from headline nav menu." (interactive) (let* ((buff (current-buffer)) (marker (get-text-property 0 'org-hd-marker entry))) (org-goto-marker-or-bmk marker))) 0)
```

The function and config i'm using is below

```
(defun baal-org-ql--candidates (&optional arg archive)
  "Collect headlines in all selected org files.
ARG controls whether to search current buffer, open org buffers, and
org-agenda-files.  Search headlines in ARCHIVE when non-nil."
  (let* ((buf-name (buffer-file-name))
         (base (buffer-base-buffer))
         (-compare-fn #'file-equal-p)
         (b (pcase arg
              ('3 (org-files-list))
              ('(4) (-uniq
                     (append (org-agenda-files)
                             (when (derived-mode-p 'org-mode)
                               (list (or buf-name
                                         (buffer-file-name base)))))))
              (_ (or buf-name
                     base)))))
    (->> (org-ql-select b
           (if archive
               '(tags "ARCHIVE")
             ;; entries & files tagged with noql are not searched. TODO
             ;; look into restricting search for only headlines with
             ;; custom ids. (may be faster but obviously not as inclusive).
             '(not (tags "noql" "ARCHIVE")))
           :action 'element-with-markers
           ;; When searching current-buffer sort headlines by default
           ;; buffer-order. Otherwise, sort by random order.
           :sort (when arg '(random)))
         (--map (org-ql-view--format-element it)))))

(defun baal-org-ql-insert-link (&optional arg id)
  "Go to the location of a custom ID, selected interactively.
ARG passed to `baal:org-global-custom-ids'."
  (interactive "P")
  (unless (derived-mode-p 'org-mode)
    (user-error "Not an Org buffer: %s" (buffer-name)))
  (let* ((prescient-sort-length-enable nil)
         (cands (unless id (baal-org-ql--candidates arg)))
         (entry (unless id (selectrum-read "[LINK] Headline: " cands :require-match t)))
         (title (org-link-display-format
                 (if id (org-with-point-at
                            (org-id-find id t)
                          (org-get-heading t t t))
                   (get-text-property 0 'raw-value entry))))
         (id (or id (get-text-property 0 'ID entry))))
    (org-insert-link nil (format "id:%s" id) title)
    (evil-insert 1)))

(embark-define-keymap embark-org-id-map
  "Keymap for Embark org id actions."
  :parent embark-general-map
  ("i" embark-insert-org-id-link)
  ("t" embark-insert-org-edna)
  ("RET" embark-goto-org-id))

(cl-pushnew '(org-id . embark-org-id-map) embark-keymap-alist)
(--map (cl-pushnew `(,it . org-id) marginalia-command-categories)  '(baal-org-ql-insert-link baal-org-ql-insert-edna baal-org-ql-goto-heading baal-org-ql-goto-backlink))

**Comment by tpeacock19** [comment]
I initially used an alist but after looking through how org-ql manages to recreate agenda views, I started to leverage text properties

**Comment by oantolin** [comment]
> ```emacs-lisp
> Error running timer: (wrong-number-of-arguments ((t) (entry) "Embark action to insert org-link from headline nav menu." (interactive) (let* ((buff (current-buffer)) (marker (get-text-property 0 'org-hd-marker entry))) (org-goto-marker-or-bmk marker))) 0)
> ```

The error message looks a little suspicious: why does it say `(interactive)` instead of `(interactive "sHeadline: ")` or something like that? Did you update the `interactive` spec in the function definition to prompt for `entry`?

**Comment by tpeacock19** [comment]
oh sorry, i think that may have been an older version of the function. Actually what happens is that the function you wrote is called with an empty entry, so i get a wrong type argument error.

**Comment by tpeacock19** [comment]
It may be a result of another issue I notice, I'm unable to get embark to act on any target that is highlighted, only the top most completion.

**Comment by oantolin** [comment]
Ah! Are you using Selectrum? If so, you need to update your configuration, [see the updated Selectrum wiki](https://github.com/raxod502/selectrum/wiki/Additional-Configuration#minibuffer-actions-with-embark).

I'm sorry for all the changes lately, but I promise that each one really is an improvement, and also that the churn won't last much longer.

**Comment by tpeacock19** [comment]
Hm, thank you for the note, I had missed that. It seems to fix the highlighted candidate issue I was experiencing. However, now the actions don't show up for functions I create myself. Though, I imagine this has to do with Marginalia's command categories.

**Comment by oantolin** [comment]
I don't think my initial suggestion works anyway, the candidate doesn't seem to actually have the text properties, they seem to get lost somewhere along the way.

**Comment by oantolin** [comment]
I don't like using text properties for this. Two strings are considered equal if they match ignoring text properties. It would be weird for two equal strings to be treated differently by the actions. I recommend storing the information externally, as you said you were doing before with alists.

As for the other problems you are having with Embark and Marginalia, I'd be happy to help if you gave me more details.

**Comment by minad** [comment]
I would also advise against text properties. I had only bad experiences with them in the context of completing-read. And I am also not a big fan of using them to attach arbitrary data structures to text (the compile buffer is doing that). But maybe it is a common Emacs thing in major modes, I am not that familiar with that.

**Comment by oantolin** [comment]
I think it's a lot safer for text stored in a buffer you control, like what the compile buffer does. In that case it is attached to specific text the user is expected to move to and run a command on. It's basically like buttons. On the other hand, using it with completing-read is a recipe for disaster: the user is typing part or all of the text you want the property attached to, it's just to easy to make a new equal string without the properties.

**Comment by minad** [comment]
Yes, in the context of completing-read it is a no go. I don't understand how ivy/helm are getting along using this. I've heard that they use properties to mark candidates.

**Comment by tpeacock19** [comment]
Thanks you both for your advice, I ended up going back to an alist. However, I think it may be useful to include a snippet I found in embark.el, in the wiki. For some reason, Marginalia's command-categories was not working for a custom function, This allowed me to specify the metadata category much easier.

```elisp
(defun baal--org-ql-completion-table (category candidates)
  (lambda (string pred action)
    (if (eq action 'metadata)
        `(metadata (category . ,category))
      (complete-with-action action candidates string pred))))
```

**Comment by minad** [comment]
> For some reason, Marginalia's command-categories was not working for a custom function, This allowed me to specify the metadata category much easier.

If you manage to reproduce this, please create an issue on the marginalia issue tracker!

> This allowed me to specify the metadata category much easier.

Yes, if you have your own completion table, you should specify the category there. This is better than using Marginalia. Marginalia is more meant to attach a category to completing-reads where you don't control the source, e.g., Emacs builtins.

Note that you can also use `consult--read` if you want to have a slightly more handy API. It is private API for now and as such may change, but in the end it is just a wrapper around a normal completing-read.

**Comment by oantolin** [comment]
Hi @tpeacock19, have you managed to update your configuration now? Is there anything I might help you with still?

**Comment by tpeacock19** [comment]
Hello - sorry i should have responded. I did update my config to leverage alists instead of text properties. I'll go ahead and close this now.
