### ISSUE TITLE
Refine virtual buffer type for nonexistent buffers strips leading char

### ISSUE THREAD

**Issue by jakanakaevangeli** [oantolin/embark#84]
To create a new buffer, one can type its name in `M-x consult-buffer` and press
enter. If consult sees that it doesn't equal one of the candidates, it falls
back to treating it as a buffer.

Now when trying to create it in a new window with embark, there are two
problems:
- Embark falls back to the type `'general` so it doesn't offer the `o` binding
  for opening in a new window. Perhaps it would be more sensible to fall back
  to the type `'buffer` to make it more uniform with consult.
- Embark also incorrectly strips the leading character with the call to
  substring.

**Comment by minad** [comment]
@oantolin Yes, we should only strip special characters >= #x100000.

**Comment by oantolin** [comment]
Ha! Thanks for reporting this. It should be fixed now, please let me know if I missed anything.

**Comment by oantolin** [comment]
> Yes, we should only strip special characters >= #x100000.

I decided only characters in the range from `#x100000` to `(+ #x100000 ?z)` will be consider prefix characters for `virtual-buffer` targets. I didn't want to limit to just the ones you currently use, @minad, but figure you probably won't have more 26 total types of virtual buffers.
