### ISSUE TITLE
Two outdated doc strings

### ISSUE THREAD

**Issue by protesilaos** [oantolin/embark#86]
Hello Omar!  Just to note that the following reference is out-of-date as of commit `4dde0d5`.

```
If you are using `embark-completing-read' as your
`completing-read-function' you might want to set
`embark-occur-minibuffer-completion' to t.
```

Found in `embark-occur-minibuffer-completion` and `embark-occur-choose`.

**Comment by oantolin** [comment]
Ha! Thank you! Will fix.
