### ISSUE TITLE
embark-become not working

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#89]
I am unsuccessful at getting `embark-become` to work.

I'm using selectrum, prescient, consult and embark on Mitsuharu Yamamoto's macport of Emacs 27 on MacOS 10.15.7.

I'm trying to start with `consult-buffer` and switch to `find-file`.  I'm doing:

1. `C-x b` to invoke `consult-buffer`
2. typing an input ("major") that matches no buffer but is a substring match for file in `default-directory`
3. `s-/` to invoke `embark-act`
4. `B` to invoke `embark-become`
5. `C-x C-f` which is bound to `find-file`

Now what happens is odd, I see a macOS-native dialog box titled "Find file:" which I don't ever see.  Its directory is correct and the file name input is blank.  This happens whether recursive minibuffers are t or nil.  If I invoke `find-file` via `M-x` or `C-x C-f` it prompts me in the emacs minibuffer but I do see this native dialog if I invoke it from the menu (emacs on mac has a native mac menu bar which I rarely use).

This is what `view-lossage` shows

		 C-x b			;; consult-buffer
		 m			;; self-insert-command
		 a			;; self-insert-command
		 j			;; self-insert-command
		 o			;; self-insert-command
		 r			;; self-insert-command
		 s-/			;; embark-act
		 B C-x C-f C-h		;; which-key-C-h-dispatch
		 l			;; help-go-back

The same thing happens if I change step 5. to use `M-x find-file`.

I'm under the impression that for step 5 I should be able to just type `f` to use `embark-become-file+buffer-map` but when I do that I see in the prompt "[Not an action]" and nothing else seems to happen.

I stepped through `embark-become` in the debugger.  It did seem that `become` was `find-file` but I got a little lost in the debugger with the `run-at-time` call.  If I do `eval-expression` via `M-:` and enter `(command-execute 'find-file)` I get prompted in the minibuffer as expected.

I tried chaning `embark-become` to call `minibuffer-with-setup-hook` without the `run-at-time` wrapper and I got prompted in the minibuffer for Find File: with "major" as input (all good), but if I hit return, the file was opened in a new buffer, but not switched to.

Any hints of where I should go from here?

**Comment by hmelman** [comment]
Progress.  If I set `use-file-dialog` to `nil` (the default it `t`), the above seems to work as expected.  This variable is defined in C code and is described in the Emacs manual so I think it's part of Emacs and not something added by the macport.  I can set it, but I don't know if `embark-become` should handle it by let binding it.

**Comment by oantolin** [comment]
Yes, `embark-become` should be setting that. This is the same bug as in #39, but I shortsightedly only fixed it for `embark-act(-noexit)`, instead of thinking of all the places it could happen.

**Comment by hmelman** [comment]
So it works if I do step 5 as above, using `C-x C-f`.  Using just `f` doesn't work, am I misunderstanding that it should via `embark-become-file+buffer-map`? Do I have to do something to invoke or configure that?

**Comment by oantolin** [comment]
> I'm under the impression that for step 5 I should be able to just type `f` to use `embark-become-file+buffer-map` but when I do that I see in the prompt "[Not an action]" and nothing else seems to happen.

This seems troubling and potentially a separate problem.

**Comment by oantolin** [comment]
> So it works if I do step 5 as above, using `C-x C-f`. Using just `f` doesn't work, am I misunderstanding that it should via `embark-become-file+buffer-map`? Do I have to do something to invoke or configure that?

Ah, I missed initially you rebind `C-x b` to `consult-buffer`!

The way `embark-become` decides which keymaps to activate is as follows: it scans the keymaps in `embark-become-keymaps` for the command you are running, and activates those keymaps which contain it. So in your case, it looks for `consult-buffer`, doesn't find it, and therefore doesn't offer you any keymaps at all. You can still use `C-x C-f` as you noticed.

You should probably just bind `consult-buffer` to some key in `embark-become-file+buffer-map`. If you don't use `switch-to-buffer` at all anymore, just bind `consult-buffer` to `b`, for example.

**Comment by oantolin** [comment]
Does that make sense? The idea is that each keymap listed in `embark-become-keymaps` is a clique of commands you are like to want to able to easily switch among using `embark-become`.

**Comment by oantolin** [comment]
You know, maybe a tiny `embark-consult` package consisting solely of keybindings for consult commands in embark keymaps might be sensible... Thoughts @minad?

**Comment by hmelman** [comment]
> The way `embark-become` decides which keymaps to activate is as follows: it scans the keymaps in `embark-become-keymaps` for the command you are running, and activates those keymaps which contain it.

This was not clear to me.  I think you spell out this scanning more clearly in the last paragraph of the embark-become section of the README.

**Comment by oantolin** [comment]
> I just thought they were a normal keymap and looked up the key and ran the command.

Well, they are normal keymaps. The only non-normal thing about them is which one is chosen to be activated.

**Comment by minad** [comment]
@oantolin 

> You know, maybe a tiny embark-consult package consisting solely of keybindings for consult commands in embark keymaps might be sensible... Thoughts @minad? I guess it depends on how many of them would be bound. I haven't even done that in my personal config yet.

I would probably refrain from doing that for now. Maybe we should rather implement some small default configuration based on use-package that people could include/copy into their init. This has been discussed/mentioned quite often before. So I think this would be important for onboarding. If it turns out that we have a lot of gluing functionality we could still extracting parts of it to a separate package!

**Comment by hmelman** [comment]
> Well, they are normal keymaps. The only non-normal thing about them is which one is chosen to be activated.

Yes, that's what I meant, that they aren't used normally.

**Comment by oantolin** [comment]
> I would probably refrain from doing that for now. Maybe we should rather implement some small default configuration based on use-package that people could include/copy into their init. This has been discussed/mentioned quite often before. So I think this would be important for onboarding. If it turns out that we have a lot of gluing functionality we could still extracting parts of it to a separate package!

Agreed.

**Comment by oantolin** [comment]
> Yes, that's what I meant, that they aren't used normally.

Right, gotcha. Do you have any suggestion on how to make the explanation clearer? It currently says:

> But for even more convenience, embark-become offers shorter key bindings for commands you are likely to want the current command to become. The way this works is that there is a variable embark-become-keymaps containing a list of names of keymaps. When you use embark-become it activates those keymaps in that list which contain the current command. For example, the default value of embark-become-keymaps contains a keymap embark-become-file+buffer-map with bindings for several commands related to files and buffers, in particular, it binds switch-to-buffer to b and find-file to f. So when I accidentally try to switch to a buffer for a file I haven’t opened yet, I can type C-S-a B f to switch to find-file.

Is the problem that "When you use embark-become it activates those keymaps in that list which contain the current command." goes by too fast?

**Comment by oantolin** [comment]
How about this instead?

> But for even more convenience, `embark-become` offers shorter key bindings for commands you are likely to want the current command to become. The way this works is that there is a variable `embark-become-keymaps` containing a list of names of keymaps. When you use `embark-become` it scans those keymaps looking for the current command, and then activates all keymaps that contain it. For example, the default value of `embark-become-keymaps` contains a keymap `embark-become-file+buffer-map` with bindings for several commands related to files and buffers, in particular, it binds `switch-to-buffer` to `b` and `find-file` to `f`. So when I accidentally try to switch to a buffer for a file I haven't opened yet, `embark-become` sees that the only keymap in the list containing a binding for the command I ran (namely `switch-to-buffer`) is `embark-become-file+buffer-map`, so it activates that keymap. The end result is that I can type `C-S-a B f` to switch to `find-file`.

**Comment by hmelman** [comment]
FWIW I just made this:

    (embark-define-keymap embark-become-consult-map
      "Embark become keymap for consult files and buffer commands."
      ("f" find-file)
      ("p" project-find-file)
      ("r" consult-recent-file)
      ("b" consult-buffer)
      ("l" consult-locate)
      ("x" consult-file-externally)
      ("L" find-library))
    (add-to-list 'embark-become-keymaps 'embark-become-consult-map)

It also wasn't clear to me I had to the `add-to-list` myself, I had guessed the `embark-define-keymap` would do that, but of course it doesn't.  Maybe an `embark-become-define-keymap` macro could?

**Comment by oantolin** [comment]
> FWIW I just made this: [...]

Nice.

> It also wasn't clear to me I had to the `add-to-list` myself, I had guessed the `embark-define-keymap` would do that, but of course it doesn't. Maybe an `embark-become-define-keymap` macro could?

I'd rather not add such a macro. In fact maybe the best thing is to rename `embark-define-keymap` to `embark--define-keymap` and remove mentions of it from the readme. Defining keymaps is a problem that many packages solve and I want each person to use their favorite solution, not to think that for Embark they need to use Embark's keymap facilities.

**Comment by hmelman** [comment]
> How about this instead?

That's better.  I made a pass at improving it more.  What do you think of this?

> But for even more convenience, `embark-become` offers shorter key bindings for commands you are likely to want the current command to become. When you use `embark-become` it looks for the current command in all keymaps named in the list `embark-become-keymaps` and then activates all keymaps that contain it. For example, the default value of `embark-become-keymaps` contains a keymap `embark-become-file+buffer-map` with bindings for several commands related to files and buffers, in particular, it binds `switch-to-buffer` to `b` and `find-file` to `f`. So when I accidentally try to switch to a buffer for a file I haven't opened yet, `embark-become` finds that the command I ran, `switch-to-buffer`, is in the keymap `embark-become-file+buffer-map`, so it activates that keymap (and any others that also contain a binding for `switch-to-buffer`). The end result is that I can type `C-S-a B f` to switch to `find-file`.

**Comment by oantolin** [comment]
I like it. I'll use that, thanks!

**Comment by hmelman** [comment]
> I'd rather not add such a macro. In fact maybe the best thing is to rename `embark-define-keymap` to `embark--define-keymap` and remove mentions of it from the readme. Defining keymaps is a problem that many packages solve and I want each person to use their favorite solution, not to think that for Embark they need to use Embark's keymap facilities.

I think this would be fine.  I was a bit confused as to what an `embark-define-keymap` did over a standard mechanism.  I think I had read in the README that it was just convenience, but without going back and checking, I assumed that convenience was adding it to `embark-become-keymaps`.  So it was my fault, but it also was a little misleading.

**Comment by hmelman** [comment]
What order are the keymaps scanned and activated?  It should be well defined and there should be something in the README explaining it.  If I want my keymaps bindings to override others (so that `b` does `consult-buffer` and not `switch-to-buffer`) do I want to add my keymap to the beginning or end of `embark-become-keymaps`?

**Comment by oantolin** [comment]
They are activated in the order they are listed, so to override put maps at the beginning.
