### ISSUE TITLE
Question about optional arguments for commands

### ISSUE THREAD

**Issue by protesilaos** [oantolin/embark#90]
Hello Omar!  I am writing some commands to expand my `embark-act` toolkit.  However, I am a bit puzzled by the following behaviour.

```elisp
;; This returns nil when I call `embark-act' over the function's name
(defun test-command-embark-act (&optional target)
  (interactive)
  (message "The target is: %s" target))

(define-key embark-symbol-map (kbd "T") #'test-command-embark-act)
```

```elisp
;; While this returns the symbol
(defun test-command-embark-act (target)
  (interactive
   (list (read-string "What is the target? ")))
  (message "The target is: %s" target))
  
(define-key embark-symbol-map (kbd "T") #'test-command-embark-act)
```

Is this intended behaviour or am I doing something wrong?  Would it be possible for the target to be interpreted as a command's optional argument?  Or shall I use the method that currently works?

Thanks again for Embark!  I have a lot to do with it.

**Comment by oantolin** [comment]
It is intended behavior, I'm afraid. There is only one mechanism `embark-act` uses to pass the target to a command: injecting it at the first minibuffer prompt. If your command does read from the minibuffer you do not get access to the target.

Is there a case where you would really like the target as an argument that is not read from the minibuffer? We can discuss ways to restructure that or, possibly, for a very compelling case, add a second way to access the target (probably bringing back the embark--target variable, but now let-bound).

**Comment by protesilaos** [comment]
> It is intended behavior, I'm afraid. [...] Is there a case where you would really like the target as an argument that is not read from the minibuffer?

I am fine with this and will work with it.  Just wanted to be sure that I am not doing something wrong.  Thanks!
