### ISSUE TITLE
embark-become shows no actions after successful "becoming" sequence

### ISSUE THREAD

**Issue by protesilaos** [oantolin/embark#93]
Hello Omar!

I have been trying out `embark-become` and noticed a behaviour that I wanted to bring to your attention.  When I do, say, `find-file`, `embark-become`, `b` I successfully go to `switch-to-buffer`.  The opposite direction works as well.  But if I retry `embark-become` after finalising that sequence, I cannot execute any action except `C-h`.

So this:

`find-file`, `embark-become`, `b`, `switch-to-buffer`, `embark-become` STOP.

Can you reproduce this or is it due to some misconfiguration on my part?

**Comment by oantolin** [comment]
Happens here too, will investigate.

**Comment by oantolin** [comment]
I wish all bugs were as easy to diagnose and fix. 😄

**Comment by protesilaos** [comment]
Thanks!

**Comment by oantolin** [comment]
GitHub auto-closes an issue if you say `(fix #93)` or something similar, but of course, if I didn't really fix the bug, please comment here about it.

I think you may be the first person to ever run embark-become twice in a row. 😆

**Comment by protesilaos** [comment]
> if I didn't really fix the bug, please comment here about it.

All good here!

> I think you may be the first person to ever run embark-become twice in a row

The sacrifices I make!  Haha!
