### ISSUE TITLE
There is still no info manual when installing from Melpa

### ISSUE THREAD

**Issue by oantolin** [oantolin/embark#96]
I have no idea what I'm doing wrong. The info manuals for icomplete-vertical and orderless do get installed from Melpa. 🤷

**Comment by oantolin** [comment]
I guess I should try checking in the info manual itself instead of the texinfo source.

**Comment by minad** [comment]
Maybe the melpa maintainers have a build log? I wonder about the tradeoffs of supplying info vs texinfo. I think texinfo is more high-level or useful as a source format. But since everything is generated from org maybe there is no point?

**Comment by oantolin** [comment]
> Maybe the melpa maintainers have a build log?

I'm an idiot: I could clone melpa and build it here to see what actually happens, couldn't I? Now that I think about it, I seem to remember @protesilaos even suggested this.

**Comment by minad** [comment]
Is the info export working for you locally? Or is there something suspicious?

**Comment by oantolin** [comment]
It seems fine locally. I first used Emacs's commands to do the export, but then read that the external makeinfo program has better error reporting, so I installed it and exported again, and it also looked fine.

**Comment by protesilaos** [comment]
Just to note that you can clone melpa and do `make recipes/embark` or open the recipe and `C-c C-c`, which will compile the package and ask you to install it.

**Comment by protesilaos** [comment]
> I think texinfo is more high-level or useful as a source format. But since everything is generated from org maybe there is no point?

I think Org derives the texi and then compiles it to Info.  Try it by just creating an Info export to see that a texi file is built as well.

(did not check the source code though)

**Comment by protesilaos** [comment]
Omar, the fault is with your recipe:

```elisp
(embark :repo "oantolin/embark"
        :fetcher github
        :files ("embark.el"))
```

**Comment by oantolin** [comment]
Oh, that's right @protesilaos! I wanted to exclude `avy-occur-embark` from the package, but instead i'm really saying use *only* `embark.el`. Thank you!

**Comment by protesilaos** [comment]
You are welcome! Now you need to open a new PR.

**Comment by minad** [comment]
I only got this right because @purcell wrote the recipe for me :laughing:

**Comment by oantolin** [comment]
Done! Thanks again, @protesilaos. melpa/melpa#7352

**Comment by protesilaos** [comment]
Very well!
