### ISSUE TITLE
Minibuffer timeout with embark-act at point

### ISSUE THREAD

**Issue by tpeacock19** [oantolin/embark#97]
Hello,

It seems by design that the when executing embark-act outside the minibuffer, the  value for `minibuffer-message-timeout` as nil. However, if you are using the `embark-completing-read-prompter` it will not show the options until you begin typing. It may be just a preference, but I believe setting an actual timeout when using this prompter would provide a better workflow.

**Comment by oantolin** [comment]
I see what you mean: for the completing read prompter, the timeout is a better experience. And for the keymap prompter, having no timeout is much better, because once the message disappears there's no indication that you are in embark-act.

I'll make the change once I figure out the best place for it.

**Comment by oantolin** [comment]
Hi @tpeacock19! Instead of adding a timeout, I made the prompt shown by `embark-completing-read-prompter` display what you are acting on. I think this is even nicer that a timeout.

**Comment by oantolin** [comment]
I also think `embark-completing-read-prompter` probably should not show you the keybindings, since you cannot use them there and you cannot type them to complete an action either, what do you think?

**Comment by oantolin** [comment]
I did something even better than removing the keybindings: I made them useful! Now if you are using the completing-read prompter and you type `@` followed by one of the keybindings for actions, it will insert the action command at the prompt. f80a917e8de6ba400a37cc3b99628da510e2db85

**Comment by tpeacock19** [comment]
These changes are great. Displaying the target in the prompt is very useful. Thank you.

**Comment by oantolin** [comment]
I'm glad you like the changes!
